### ISSUE TITLE
SHOW TABLES does not work for hidden tpch, tpcds schemas

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#1005]
`tpch."sf3000.0"` definitely exists:
```
presto> select * from tpch."sf3000.0".nation limit 1;
 nationkey |  name   | regionkey |                       comment
-----------+---------+-----------+-----------------------------------------------------
         0 | ALGERIA |         0 |  haggle. carefully final deposits detect slyly agai
(1 row)
```

but one cannot see tables in that schema:
```
presto> show tables from tpch."sf3000.0";
Query 20190615_143150_00028_gwaqu failed: line 1:1: Schema 'sf3000.0' does not exist
io.prestosql.sql.analyzer.SemanticException: line 1:1: Schema 'sf3000.0' does not exist
	at io.prestosql.sql.rewrite.ShowQueriesRewrite$Visitor.visitShowTables(ShowQueriesRewrite.java:192)
	at io.prestosql.sql.rewrite.ShowQueriesRewrite$Visitor.visitShowTables(ShowQueriesRewrite.java:150)
	at io.prestosql.sql.tree.ShowTables.accept(ShowTables.java:72)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.rewrite.ShowQueriesRewrite.rewrite(ShowQueriesRewrite.java:147)
	at io.prestosql.sql.rewrite.StatementRewrite.rewrite(StatementRewrite.java:53)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:73)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:68)
```

**Comment by Praveen2112** [comment]
@findepi Can I take up this issue ?
