### ISSUE TITLE
PrestoBenchmarkDriver::run with scheduledExecutor hang

### ISSUE THREAD

**Issue by l0yu** [prestosql/presto#1050]
Hi, I tried to schedule benchmark driver periodically with scheduledExecutor, but seems like the thread just hang

```
scheduledExecutor = Executors.newSingleThreadScheduledExector(...)
scheduledExecutor.schedule(() -> {
        log.info("starting ...");
        benchmarkDriver.run(args);
        log.info("Done"); // this line never printout
        // schedule one more time, etc ....
}, 0, TimeUnits.SECONDS)
```
https://github.com/prestosql/presto/blob/master/presto-benchmark-driver/src/main/java/io/prestosql/benchmark/driver/PrestoBenchmarkDriver.java#L56

I turn ou ` --debug ` option, from console only see
```
io.airlift.log.logging Logging to stderr
```
I took thread dump found that scheduled thread always in waiting (parking) stage

If I run with main thread (with no scheduledExecutor), everything is fine ... Any suggestion ?

**Comment by dain** [comment]
We haven't really used this benchmark package in 4 years, and instead use https://github.com/prestosql/benchto

If you can post the stack trace, I might be able to figure out what is going on.

**Comment by l0yu** [comment]
@dain 
I see why, when use jackson dependency in benchmark based project, should **remove** <scope>provided</scope>
Change to, and works
```
<dependency>
     <groupId>com.fasterxml.jackson.core</groupId>
     <artifactId>jackson-annotations</artifactId>
     <version>${jackson.version}</version>
     <!--<scope>provided</scope>-->
   </dependency>
```
previously, I did not see error log since config at warn level, the issue is
```
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper
    at io.airlift.json.JsonCodec.<clinit>(JsonCodec.java:39)
    at io.prestosql.benchmark.driver.Suite.readSuites(Suite.java:119)
    at io.prestosql.benchmark.driver.PrestoBenchmarkDriver.run(PrestoBenchmarkDriver.java:70)
    at com.salesforce.presto.benchmark.benchmark.BenchmarkMetricsDriver.runBenchmark(BenchmarkMetricsDriver.java:19)
    at com.salesforce.presto.benchmark.BenchmarkRunner.runBenchmark(BenchmarkRunner.java:48)
    at com.salesforce.presto.benchmark.BenchmarkRunner.start(BenchmarkRunner.java:57)
    at com.salesforce.presto.benchmark.BenchmarkRunner.main(BenchmarkRunner.java:73)
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper
    ... 7 more
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ObjectMapper
    at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```
And that thread just hang silently ...

**Comment by l0yu** [comment]
@dain 
where to find definition for **process cpu time** and **query cpu time** in presto
https://github.com/prestosql/presto/blob/master/presto-benchmark-driver/src/main/java/io/prestosql/benchmark/driver/BenchmarkQueryRunner.java#L267
cpu time is how long query processed by cpu, a virtual clock ?

**Comment by dain** [comment]
> where to find definition for **process cpu time** and **query cpu time** in presto
> https://github.com/prestosql/presto/blob/master/presto-benchmark-driver/src/main/java/io/prestosql/benchmark/driver/BenchmarkQueryRunner.java#L267
> cpu time is how long query processed by cpu, a virtual clock ?

That line of code is:
```
URI addressUri = uriBuilderFrom(server).replacePath("/v1/jmx/mbean/java.lang:type=OperatingSystem/ProcessCpuTime").build();
```
This is reading the cpu time counter for the entire Java process on that worker.  This value comes from the operating system and is the sum total of all time the process spent scheduled on a CPU core.

The query cpu time is the time reported by the query itself.  Presto tracks this by calculating the delta CPU time of a thread assigned to work on a query.  The process CPU is larger than the query cpu time, because the full process with include overheads like GC.
