### ISSUE TITLE
Failed to access CSV table after adding a column on Hive

### ISSUE THREAD

**Issue by ebyhr** [prestosql/presto#1057]
If we add a column to csv table on Hive, we can't access the table from Presto anymore. I could access the table if I add a column on Presto.

Steps to reproduce
```
-- Hive 
CREATE TABLE test_csv (
 col1 string COMMENT 'from deserializer'
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
STORED AS INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
;

-- Presto
show create table hive.default.test_csv;
             Create Table
--------------------------------------
 CREATE TABLE hive.default.test_csv (
    col1 varchar
 )
```

```
-- Hive
alter table test_csv add columns (col2 string);

-- Presto
show create table hive.default.test_csv;

Query 20190628_070110_00004_akvwa failed: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Error: type expected at the position 0 of '<derived from deserializer>' but '<' is found.
com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Error: type expected at the position 0 of '<derived from deserializer>' but '<' is found.
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
	at io.prestosql.plugin.hive.metastore.CachingHiveMetastore.get(CachingHiveMetastore.java:218)
	at io.prestosql.plugin.hive.metastore.CachingHiveMetastore.getTable(CachingHiveMetastore.java:263)
	at io.prestosql.plugin.hive.metastore.SemiTransactionalHiveMetastore.getTable(SemiTransactionalHiveMetastore.java:152)
	at io.prestosql.plugin.hive.HiveMetadata.getViews(HiveMetadata.java:1580)
	at io.prestosql.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.getViews(ClassLoaderSafeConnectorMetadata.java:424)
	at io.prestosql.metadata.MetadataManager.getView(MetadataManager.java:928)
	at io.prestosql.sql.rewrite.ShowQueriesRewrite$Visitor.visitShowCreate(ShowQueriesRewrite.java:421)
	at io.prestosql.sql.rewrite.ShowQueriesRewrite$Visitor.visitShowCreate(ShowQueriesRewrite.java:150)
	at io.prestosql.sql.tree.ShowCreate.accept(ShowCreate.java:67)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.rewrite.ShowQueriesRewrite.rewrite(ShowQueriesRewrite.java:147)
	at io.prestosql.sql.rewrite.StatementRewrite.rewrite(StatementRewrite.java:53)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:73)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:68)
	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:184)
	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:92)
	at io.prestosql.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:706)
	at io.prestosql.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:118)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Error: type expected at the position 0 of '<derived from deserializer>' but '<' is found.
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
	at io.prestosql.plugin.hive.metastore.CachingHiveMetastore.get(CachingHiveMetastore.java:218)
	at io.prestosql.plugin.hive.metastore.CachingHiveMetastore.getTable(CachingHiveMetastore.java:263)
	at io.prestosql.plugin.hive.metastore.CachingHiveMetastore.loadTable(CachingHiveMetastore.java:274)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)
	at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:188)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	... 28 more
Caused by: java.lang.IllegalArgumentException: Error: type expected at the position 0 of '<derived from deserializer>' but '<' is found.
	at org.apache.hadoop.hive.serde2.typeinfo.TypeInfoUtils$TypeInfoParser.expect(TypeInfoUtils.java:401)
	at org.apache.hadoop.hive.serde2.typeinfo.TypeInfoUtils$TypeInfoParser.expect(TypeInfoUtils.java:384)
	at org.apache.hadoop.hive.serde2.typeinfo.TypeInfoUtils$TypeInfoParser.parseType(TypeInfoUtils.java:445)
	at org.apache.hadoop.hive.serde2.typeinfo.TypeInfoUtils$TypeInfoParser.parseTypeInfos(TypeInfoUtils.java:358)
	at org.apache.hadoop.hive.serde2.typeinfo.TypeInfoUtils.getTypeInfoFromTypeString(TypeInfoUtils.java:865)
	at io.prestosql.plugin.hive.HiveType.valueOf(HiveType.java:182)
	at io.prestosql.plugin.hive.metastore.thrift.ThriftMetastoreUtil.fromMetastoreApiFieldSchema(ThriftMetastoreUtil.java:677)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.prestosql.plugin.hive.metastore.thrift.ThriftMetastoreUtil.fromMetastoreApiTable(ThriftMetastoreUtil.java:432)
	at io.prestosql.plugin.hive.metastore.thrift.ThriftMetastoreUtil.fromMetastoreApiTable(ThriftMetastoreUtil.java:415)
	at io.prestosql.plugin.hive.metastore.thrift.BridgingHiveMetastore.lambda$getTable$0(BridgingHiveMetastore.java:86)
	at java.util.Optional.map(Optional.java:215)
	at io.prestosql.plugin.hive.metastore.thrift.BridgingHiveMetastore.getTable(BridgingHiveMetastore.java:82)
	at io.prestosql.plugin.hive.metastore.CachingHiveMetastore.loadTable(CachingHiveMetastore.java:274)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)
	at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:188)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	... 41 more
```

Hive metastore
```
mysql> select * from COLUMNS_V2 where cd_id = 12 order by integer_idx;
+-------+-------------------+-------------+-----------------------------+-------------+
| CD_ID | COMMENT           | COLUMN_NAME | TYPE_NAME                   | INTEGER_IDX |
+-------+-------------------+-------------+-----------------------------+-------------+
|    12 | from deserializer | col1        | <derived from deserializer> |           0 |
|    12 | NULL              | col2        | string                      |           1 |
+-------+-------------------+-------------+-----------------------------+-------------+
```

**Comment by findepi** [comment]
We need to check if it's a CSV table in  https://github.com/prestosql/presto/blob/48e73d9b90537e84e411ec934ad9d3511d60b861/presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/BridgingHiveMetastore.java#L83

cc @kokosing

**Comment by deepcodejam** [comment]
@findepi Is it available for pickup? If yes, may I work on this?

**Comment by ebyhr** [comment]
I confirmed with https://github.com/prestosql/presto/pull/920 and it seems the PR resolves this issue.

**Comment by findepi** [comment]
@deepcodejam thanks for asking! @ebyhr you're right. This is going to be fixed by #920.

**Comment by gustavoatt** [comment]
We are seeing this same issue with Presto 339 due a column having been added a column to the CSV table through hive:

```sql
show create table csv_table;
                       Create Table
----------------------------------------------------------
 CREATE TABLE csv_table (
    ds varchar
 )
 WITH (
    csv_quote = '"',
    csv_separator = ',',
    format = 'CSV',
    partitioned_by = ARRAY['ds']
 )
```

We are not able to read any data from this table within Presto though:

```sql
presto:default> SELECT count(*)
             -> FROM csv_table
             -> WHERE ds = '2020-09-10';
Query 20200922_173544_00072_s8afw failed: java.lang.IllegalArgumentException: Error: type expected at the position 0 of '<derived from deserializer>' but '<' is found.
io.prestosql.spi.PrestoException: java.lang.IllegalArgumentException: Error: type expected at the position 0 of '<derived from deserializer>' but '<' is found.
        at io.prestosql.plugin.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:238)
        at io.prestosql.plugin.hive.util.ResumableTasks$1.run(ResumableTasks.java:38)
        at io.prestosql.$gen.Presto_____20200922_015237_2.run(Unknown Source)
        at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Error: type expected at the position 0 of '<derived from deserializer>' but '<' is found.
        at com.google.common.cache.LocalCache.loadAll(LocalCache.java:4068)
        at com.google.common.cache.LocalCache.getAll(LocalCache.java:4021)
        at com.google.common.cache.LocalCache$LocalLoadingCache.getAll(LocalCache.java:4972)
        at io.prestosql.plugin.hive.metastore.cache.CachingHiveMetastore.getAll(CachingHiveMetastore.java:259)
        at io.prestosql.plugin.hive.metastore.cache.CachingHiveMetastore.getPartitionsByNames(CachingHiveMetastore.java:685)
        at io.prestosql.plugin.hive.HiveMetastoreClosure.lambda$getPartitionsByNames$4(HiveMetastoreClosure.java:213)
        at java.base/java.util.Optional.map(Optional.java:265)
        at io.prestosql.plugin.hive.HiveMetastoreClosure.getPartitionsByNames(HiveMetastoreClosure.java:213)
        at io.prestosql.plugin.hive.metastore.SemiTransactionalHiveMetastore.getPartitionsByNames(SemiTransactionalHiveMetastore.java:695)
        at io.prestosql.plugin.hive.HiveSplitManager.lambda$getPartitionMetadata$2(HiveSplitManager.java:310)
        at com.google.common.collect.Iterators$6.transform(Iterators.java:783)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
        at com.google.common.collect.Iterators$ConcatenatedIterator.hasNext(Iterators.java:1333)
        at io.prestosql.plugin.hive.ConcurrentLazyQueue.poll(ConcurrentLazyQueue.java:37)
        at io.prestosql.plugin.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:298)
        at io.prestosql.plugin.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:231)
        ... 6 more
```

While reading in Hive is working as expected.

The PR linked to this issue seems like it resolved the issue, but wondering if I'm missing something on my end or if this is a different issue. Would appreciate any help you can provide 🙏

**Comment by kokosing** [comment]
What Hive version are you using? Can you please share the DDL of that table from Hive, so we could try to reproduce it?

**Comment by gustavoatt** [comment]
@kokosing I'm using Hive 2.3.4. Here is a set of commands to reproduce the error:

```sql
-- Hive: Create table
CREATE TABLE gustavo_test_csv (
	col string
)
PARTITIONED BY (ds string)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
  'quoteChar'='\'',
  'separatorChar'=',')
STORED AS INPUTFORMAT
  'org.apache.hadoop.mapred.TextInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat';

-- Insert data into it
SET hive.exec.dynamic.partition.mode=nonstrict;
INSERT OVERWRITE TABLE gustavo_test_csv PARTITION(ds)
VALUES 
	('a', '2020-09-16'),
	('b', '2020-09-16');

-- Reading data works both in Presto & Hive.
SELECT *
FROM gustavo_test_csv;

-- Add a column in Hive
ALTER TABLE gustavo_test_csv ADD COLUMNS (extra_col string);

-- Insert more data into it.
INSERT OVERWRITE TABLE gustavo_test_csv PARTITION(ds)
VALUES 
	('a', 'extra_col', '2020-09-16'),
	('b', 'extra_col', '2020-09-16');

-- This select now only works in Hive, but in Presto it gives the stacktrace from the previous command
SELECT ds, col, extra_col
FROM gustavo_test_csv;
```

Basically the issue appears after we add a column to a Hive CSV table and insert data into it. Once that happens we are not able to read data from Presto anymore.
