### ISSUE TITLE
Predicate pushdown may result in query failure

### ISSUE THREAD

**Issue by mbasmanova** [prestosql/presto#1080]
Projection `IF (o.orderstatus = 'P', t.x[3], NULL) as y` combined with `o.orderstatus = 'P' AND y IS NOT NULL` filter on top of a join causes pushdown of `x[3] IS NOT NULL` predicate into `t`. This may trigger `Array subscript out of bounds` error if `t` has records where `x` has fewer than 3 elements. In case these records don't survive the join, the overall query should pass, but it fails.

To reproduce:

```sql
CREATE TABLE memory.default.test AS 
SELECT
    l.linenumber,
    o.orderkey,
    o.orderstatus,
    IF (o.orderstatus = 'P', ARRAY[1, 2, 4], ARRAY[1]) AS x
FROM tpch.tiny.lineitem l, tpch.tiny.orders o
WHERE l.orderkey = o.orderkey;

SELECT *
FROM (
    SELECT
        o.orderstatus,
        IF (o.orderstatus = 'P', x[3], NULL) AS y
    FROM memory.default.test t, tpch.tiny.orders o
    WHERE t.orderkey = o.orderkey
)
WHERE orderstatus = 'P' AND y IS NOT NULL;
```

The stacktrace:

```
Query 20190703_200851_00003_qhsg6 failed: Array subscript out of bounds
io.prestosql.spi.PrestoException: Array subscript out of bounds
	at io.prestosql.operator.scalar.ArraySubscriptOperator.checkIndex(ArraySubscriptOperator.java:166)
	at io.prestosql.operator.scalar.ArraySubscriptOperator.longSubscript(ArraySubscriptOperator.java:95)
	at io.prestosql.$gen.PageFilter_20190703_200851_9.filter(Unknown Source)
	at io.prestosql.$gen.PageFilter_20190703_200851_9.filter(Unknown Source)
	at io.prestosql.operator.project.DictionaryAwarePageFilter.filter(DictionaryAwarePageFilter.java:83)
	at io.prestosql.operator.project.PageProcessor.createWorkProcessor(PageProcessor.java:115)
	at io.prestosql.operator.ScanFilterAndProjectOperator$SplitToPages.lambda$processPageSource$1(ScanFilterAndProjectOperator.java:254)
	at io.prestosql.operator.WorkProcessorUtils.lambda$flatMap$4(WorkProcessorUtils.java:246)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:320)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:307)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:307)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
	at io.prestosql.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:278)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:320)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:307)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
	at io.prestosql.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:133)
	at io.prestosql.operator.Driver.processInternal(Driver.java:379)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_null__testversion____20190703_200826_1.run(Unknown Source)
```

`PredicatePushDown.Rewriter#processInnerJoin` already makes sure not to push down non-deterministic predicates. It may need to block pushdown of predicates that may generate an error or wrap these in `try`.

Dup of https://github.com/prestodb/presto/issues/13009

**Comment by martint** [comment]
Thanks for reporting this @mbasmanova. I know what the underlying issue is -- I'm working on a fix.

**Comment by mbasmanova** [comment]
@martint Martin, thanks for looking into this. I'm curious what the fix is. Would you share some details? @kaikalur also looked into this and shared some ideas in https://github.com/prestodb/presto/issues/13009#issuecomment-520875381 I'm wondering if you have a similar idea or something else.

**Comment by mbasmanova** [comment]
@martint *ping*

**Comment by martint** [comment]
I can't reproduce this anymore. Please reopen if you come up with another test case that reproduces it.
