### ISSUE TITLE
build failed on tag:308    Dependency problems found

### ISSUE THREAD

**Issue by groobyming** [prestosql/presto#1096]
Hi, everyone.
I think There are some error on dependency configuration in pom.xml on tag: 308.
How to build successfully? Thanks.

Error as follows：
[INFO] presto-root ........................................ SUCCESS [  4.097 s]
[INFO] presto-spi ......................................... SUCCESS [ 17.269 s]
[INFO] presto-plugin-toolkit .............................. SUCCESS [  4.150 s]
[INFO] presto-client ...................................... SUCCESS [  3.079 s]
[INFO] presto-parser ...................................... SUCCESS [  8.531 s]
[INFO] presto-geospatial-toolkit .......................... SUCCESS [  2.404 s]
[INFO] presto-array ....................................... SUCCESS [  2.488 s]
[INFO] presto-matching .................................... SUCCESS [  1.622 s]
[INFO] presto-memory-context .............................. FAILURE [  1.203 s]
[INFO] presto-tpch ........................................ SKIPPED
[INFO] presto-main ........................................ SKIPPED
[INFO] presto-resource-group-managers ..................... SKIPPED
[INFO] presto-tests ....................................... SKIPPED
[INFO] presto-atop ........................................ SKIPPED
[INFO] presto-jmx ......................................... SKIPPED
[INFO] presto-record-decoder .............................. SKIPPED
[INFO] presto-kafka ....................................... SKIPPED
[INFO] presto-redis ....................................... SKIPPED
[INFO] presto-accumulo .................................... SKIPPED
[INFO] presto-cassandra ................................... SKIPPED
[INFO] presto-blackhole ................................... SKIPPED
[INFO] presto-memory ...................................... SKIPPED
[INFO] presto-orc ......................................... SKIPPED
[INFO] presto-benchmark ................................... SKIPPED
[INFO] presto-parquet ..................................... SKIPPED
[INFO] presto-rcfile ...................................... SKIPPED
[INFO] presto-hive ........................................ SKIPPED
[INFO] presto-hive-hadoop2 ................................ SKIPPED
[INFO] presto-teradata-functions .......................... SKIPPED
[INFO] presto-example-http ................................ SKIPPED
[INFO] presto-local-file .................................. SKIPPED
[INFO] presto-tpcds ....................................... SKIPPED
[INFO] presto-raptor-legacy ............................... SKIPPED
[INFO] presto-base-jdbc ................................... SKIPPED
[INFO] presto-mysql ....................................... SKIPPED
[INFO] presto-postgresql .................................. SKIPPED
[INFO] presto-redshift .................................... SKIPPED
[INFO] presto-testing-docker .............................. SKIPPED
[INFO] presto-sqlserver ................................... SKIPPED
[INFO] presto-mongodb ..................................... SKIPPED
[INFO] presto-ml .......................................... SKIPPED
[INFO] presto-geospatial .................................. SKIPPED
[INFO] presto-jdbc ........................................ SKIPPED
[INFO] presto-cli ......................................... SKIPPED
[INFO] presto-product-tests ............................... SKIPPED
[INFO] presto-benchmark-driver ............................ SKIPPED
[INFO] presto-elasticsearch ............................... SKIPPED
[INFO] presto-password-authenticators ..................... SKIPPED
[INFO] presto-thrift-api .................................. SKIPPED
[INFO] presto-thrift-testing-server ....................... SKIPPED
[INFO] presto-thrift ...................................... SKIPPED
[INFO] presto-kudu ........................................ SKIPPED
[INFO] presto-session-property-managers ................... SKIPPED
[INFO] presto-server ...................................... SKIPPED
[INFO] presto-server-rpm .................................. SKIPPED
[INFO] presto-docs ........................................ SKIPPED
[INFO] presto-verifier .................................... SKIPPED
[INFO] presto-testing-server-launcher ..................... SKIPPED
[INFO] presto-benchto-benchmarks .......................... SKIPPED
[INFO] presto-proxy ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 46.425 s
[INFO] Finished at: 2019-07-08T19:31:59+08:00
[INFO] Final Memory: 256M/1575M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:analyze-only (default) on project presto-memory-context: Dependency problems found -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:analyze-only (default) on project presto-memory-context: Dependency problems found
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
        at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
        at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:50)
Caused by: org.apache.maven.plugin.MojoExecutionException: Dependency problems found
        at org.apache.maven.plugins.dependency.analyze.AbstractAnalyzeMojo.execute(AbstractAnalyzeMojo.java:253)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 27 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :presto-memory-context

**Comment by groobyming** [comment]
It is a problem with proxy configuretion

**Comment by findepi** [comment]
@groobyming thanks for updating the issue, happy to hear the problem is resolved now

**Comment by milanperera** [comment]
In case someone ended up here again for a different reason; I got the same when I built it while skipping tests.

**Comment by bhaskara1017** [comment]
I am facing issue, how to fix it?

**Comment by findepi** [comment]
@bhaskara1017 please reach out on `#dev` on [our slack](https://trino.io/slack.html), describing the error you're getting.
