### ISSUE TITLE
 presto-docs: Failed to run the report: Sphinx report generation failed

### ISSUE THREAD

**Issue by groobyming** [prestosql/presto#1097]
Hi,guys
   I am trying to  make the build of presto(tag 308), but failed 
 Below is the build log

[ERROR] Failed to execute goal io.airlift.maven.plugins:sphinx-maven-plugin:2.1:generate (default) on project presto-docs: Failed to run the report: Sphinx report generation failed -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.airlift.maven.plugins:sphinx-maven-plugin:2.1:generate (default) on project presto-docs: Failed to run the report
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:50)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to run the report
	at io.airlift.maven.sphinx.SphinxMojo.execute(SphinxMojo.java:237)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 27 more
Caused by: org.apache.maven.reporting.MavenReportException: Sphinx report generation failed
	at io.airlift.maven.sphinx.SphinxMojo.runForkedSphinx(SphinxMojo.java:428)
	at io.airlift.maven.sphinx.SphinxMojo.executeReport(SphinxMojo.java:250)
	at io.airlift.maven.sphinx.SphinxMojo.execute(SphinxMojo.java:234)
	... 29 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :presto-docs

**Comment by kokosing** [comment]
Can you please go into a `presto-docs` directory and run `make clean html`? That should show more detailed error message.

**Comment by groobyming** [comment]
@kokosing  Thanks, and  I will try it

**Comment by findepi** [comment]
@groobyming did you succeed to build docs?
I am closing this, but you can still comment here.
Or we can talk on the [Presto Slack](https://prestosql.io/slack.html).

**Comment by xkwangcn** [comment]
Hello, @groobyming @findepi ,  I met the same error, did you find a solution?
After I run `pip2 install sphinx`,  run `make clean html` can succeed, but the presto-docs build still failed. Could you give me some advice about the problem?
Thank you very much

**Comment by findepi** [comment]
@xkwangcn can you please ask on #troubleshooting on [our slack](https://prestosql.io/slack.html)?

**Comment by xkwangcn** [comment]
@findepi thanks for your reply, I created a slack account, but it seems that I can't join in `prestosql.slack.com` workspace, and can't find the channel `#troubleshooting`. Could you invite me to join them? my slack account email is `wangxinkecn@gmail.com`, username is `xinke wang`. 
Could you give me the steps how to join? and after joined succeed, could I ask my question in the channel troubleshooting?
Thank you very much.

**Comment by electrum** [comment]
This link should work: https://join.slack.com/t/prestosql/shared_invite/enQtNTMyNzU2NzQ1NzQ4LWUyMjY4NTA0NWU0ZDlkMjM4Y2JhODdiZWZiZWQ2NDNhZDVhOGY5ZTk4NDY0OGIzOTE2YzI3YjhlMmUyNDJiNGM

**Comment by electrum** [comment]
You can find that Slack invite link using the “sign up” link here: https://prestosql.io/slack.html

**Comment by xkwangcn** [comment]
success, thanks everyone～ @electrum @findepi
