### ISSUE TITLE
REST API returns status 200 with corrupted geometry

### ISSUE THREAD

**Issue by MichaelChirico** [prestosql/presto#1138]
```
with ex(lon, lat) as (values 
    (100.118409, 6.427002), (100.118409, 6.427002), (100.118409, 6.405029), 
    (100.140381, 6.427002), (100.129395, 6.405029), (100.140381, 6.421509),
    (100.129395, 6.421509), (100.129395, 6.421509), (100.140381, 6.421509),
    (100.129395, 6.405029), (100.140381, 6.427002), (100.118409, 6.405029), 
    (100.118409, 6.427002), (100.118409, 6.427002)
  )
  select
    st_polygon(concat(concat('POLYGON ((', array_join(array_agg(concat(concat(CAST(lon AS varchar), ' '), CAST(lat AS varchar))), ', ')), '))'))
  from ex
```

Errors reproducibly with:

```
com.fasterxml.jackson.databind.JsonMappingException: corrupted geometry (through reference chain: io.prestosql.client.QueryResults["data"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:353)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:727)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1396)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:913)
	at io.airlift.jaxrs.JsonMapper.writeTo(JsonMapper.java:233)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:266)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:251)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:109)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:85)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1135)
	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:662)
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:395)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:385)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$3.run(ServerRuntime.java:884)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:916)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:872)
	at io.airlift.http.server.AsyncResponseHandler$1.onSuccess(AsyncResponseHandler.java:102)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1058)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.esri.core.geometry.GeometryException: corrupted geometry
	at com.esri.core.geometry.OperatorExportToWktLocal.exportPolygonToWkt(OperatorExportToWktLocal.java:111)
	at com.esri.core.geometry.OperatorExportToWktLocal.exportToWkt(OperatorExportToWktLocal.java:47)
	at com.esri.core.geometry.OperatorExportToWktLocal.execute(OperatorExportToWktLocal.java:31)
	at com.esri.core.geometry.GeometryEngine.geometryToWkt(GeometryEngine.java:274)
	at com.esri.core.geometry.ogc.OGCPolygon.asText(OGCPolygon.java:65)
	at io.prestosql.plugin.geospatial.GeometryType.getObjectValue(GeometryType.java:86)
	at io.prestosql.server.protocol.RowIterable$RowIterator.computeNext(RowIterable.java:77)
	at io.prestosql.server.protocol.RowIterable$RowIterator.computeNext(RowIterable.java:50)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at com.google.common.collect.Iterators$ConcatenatedIterator.hasNext(Iterators.java:1323)
	at com.google.common.collect.Iterators$1.hasNext(Iterators.java:136)
	at com.fasterxml.jackson.databind.ser.std.IterableSerializer.serializeContents(IterableSerializer.java:83)
	at com.fasterxml.jackson.databind.ser.std.IterableSerializer.serialize(IterableSerializer.java:74)
	at com.fasterxml.jackson.databind.ser.std.IterableSerializer.serialize(IterableSerializer.java:12)
	at com.fasterxml.jackson.databind.ser.std.StdDelegatingSerializer.serialize(StdDelegatingSerializer.java:168)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	... 32 more
```

However, this doesn't come out on the REST API with any error message or status:

(using R package `httr` to query):

```
library(httr)

q = "
with ex(lon, lat) as (values 
  (100.118409, 6.427002), (100.118409, 6.427002), (100.118409, 6.405029), 
  (100.140381, 6.427002), (100.129395, 6.405029), (100.140381, 6.421509),
  (100.129395, 6.421509), (100.129395, 6.421509), (100.140381, 6.421509),
  (100.129395, 6.405029), (100.140381, 6.427002), (100.118409, 6.405029), 
  (100.118409, 6.427002), (100.118409, 6.427002)
)
select
  st_polygon(concat(concat('POLYGON ((', array_join(array_agg(concat(concat(CAST(lon AS varchar), ' '), CAST(lat AS varchar))), ', ')), '))'))
from ex
"

post_obj = POST(REST_URL, AUTH_HEADERS, body = q)
if (post_obj$status != 200) stop("STATUS ERROR")
recContent = content(post_obj)
while(TRUE) {
  if (!is.null(recContent$error)) {
   stop("CONTENT ERROR: ", recContent$error)
  }
  if (is.null(recContent$nextUri)) break
  get_obj = GET(recContent$nextUri, AUTH_HEADERS)
  if (get_obj$status != 200) stop("STATUS ERROR")
  recContent = tryCatch(content(get_obj), error = function(e) cat(rawToChar(get_obj$content)))
}
```

^ Forgive the R code. But this will consistently give back a `content` object consisting only of the `fasterxml` error (i.e. not valid JSON, hence `content(get_obj)` will fail), and also always return `status=200`.

It seems to me either

 1. This should return some sort of valid JSON object with an `error` key containing the `fasterxml` message, or
 2. Return with `status = xxx` non-200

`1` would be more informative as I would expect `status` reserved for HTTP errors (which this is not)

**Comment by electrum** [comment]
Thanks for the report. I confirmed the behavior using `GeoQueryRunner` and updated the stack trace.

Here's a simplified version of the original query:
```sql
SELECT st_polygon('POLYGON ((100.118409 6.427002, 100.118409 6.427002, 100.118409 6.405029, 100.140381 6.427002, 100.129395 6.405029, 100.140381 6.421509, 100.129395 6.421509, 100.129395 6.421509, 100.140381 6.421509, 100.129395 6.405029, 100.140381 6.427002, 100.118409 6.405029, 100.118409 6.427002, 100.118409 6.427002))')
```

This Java code is effectively this:
```java
String input = "POLYGON ((100.118409 6.427002, 100.118409 6.427002, 100.118409 6.405029, 100.140381 6.427002, 100.129395 6.405029, 100.140381 6.421509, 100.129395 6.421509, 100.129395 6.421509, 100.140381 6.421509, 100.129395 6.405029, 100.140381 6.427002, 100.118409 6.405029, 100.118409 6.427002, 100.118409 6.427002))";
OGCGeometry geometry = OGCGeometry.fromText(input);
geometry.setSpatialReference(null);
String text = geometry.asText();
```

I think the correct fix is to force validation at creation time. This could be done in `GeoFunctions.geometryFromText()` by calling `asBinary()` (which performs the same validation but should be faster).

**Comment by electrum** [comment]
A quick benchmark shows that adding `asBinary()` has a minimal (if any) cost on construction:
```
Benchmark                    Mode  Cnt       Score       Error  Units
BenchmarkGeometry.baseline  thrpt    5  340577.937 ± 40011.138  ops/s
BenchmarkGeometry.asBinary  thrpt    5  318781.618 ± 11644.430  ops/s
BenchmarkGeometry.asText    thrpt    5   72350.517 ±  1656.082  ops/s
```

**Comment by MichaelChirico** [comment]
Thanks @electrum. Seems you've already prototyped a fix so I'll leave it up to you & watch for a PR. Cheers!

**Comment by electrum** [comment]
I did not actually write fix, which would be adding the call, exception handling (to translate to a proper Presto error), and tests. Would you like to do that?

**Comment by yen-von** [comment]
`OGCGeometry` allows user to create corrupted geometry.
Also, Presto provides [`ST_IsValid`](https://prestosql.io/docs/current/functions/geospatial.html#ST_IsValid) function to check the correctness of a geometry.  
So returning `200` should be expected behavior and I don't think we need to force validation at creation time. It will just break many other test cases.  

However, the response body is wrong due to `OGCGeometry.asText()` throwing a exception  and there's no error handling in [`GeometryType.getObjectValue()L86`](https://github.com/prestosql/presto/blob/master/presto-geospatial/src/main/java/io/prestosql/plugin/geospatial/GeometryType.java#L86)

I'm new to Presto. Not sure what kind of Exception thrown in `getObjectValue` will be properly handled.  
I have a quick fix that just catch it and return **`"Corrupted [type of that geometry]"`**


Test: `'POLYGON ((0 0, 1 0))'`(corrupted polygon with only two vertices)
```
presto> select st_isvalid(ST_GeometryFromText('POLYGON ((0 0, 1 0))'));
 _col0 
-------
 false 
(1 row)

presto> select ST_GeometryFromText('POLYGON ((0 0, 1 0))');
Query is gone (server restarted?)


========= after code change =========


presto> select ST_GeometryFromText('POLYGON ((0 0, 1 0))');
       _col0       
-------------------
 Corrupted Polygon 
(1 row)

```

**Comment by wendigo** [comment]
@electrum what is desired behaviour here? Using asBinary() as a validation method is not valid because ```POINT EMPTY``` is valid representation in WKT (Well-Known Text format) but invalid in WKB (Well-Known Binary format) (it throws).

If ST_GeometryFromText() will throw eagerly then I won't be able to do: ```select st_isvalid(ST_GeometryFromText('POLYGON ((0 0, 1 0))'));``` because query will fail eagerly. 

The problem is that ```https://github.com/prestosql/presto/blob/master/presto-geospatial/src/main/java/io/prestosql/plugin/geospatial/GeometryType.java#L86``` throws an exception that could not be serialized as JSON (that's why client sees query failure). I don't know how I can fail a query in a proper way here.

**Comment by wendigo** [comment]
I've checked how postgis works:

```
STATEMENT:  SELECT ST_GeomFromText('POLYGON ((0 0, 1 0))')
ERROR:  geometry requires more points
HINT:  "POLYGON ((0 0, 1 0))" <-- parse error at position 24 within geometry
```

```
STATEMENT:  SELECT st_isvalid(ST_GeomFromText('POLYGON ((0 0, 1 0))'))
ERROR:  geometry requires more points
HINT:  "POLYGON ((0 0, 1 0))" <-- parse error at position 24 within geometry
```

```
SELECT ST_GeomFromText('POLYGON EMPTY');
010300000000000000
```

```
SELECT ST_GeomFromText('POINT (1.0 0.0)');
0101000000000000000000F03F0000000000000000
```

**Comment by wendigo** [comment]
https://github.com/prestodb/presto/issues/12289

**Comment by martint** [comment]
As an aside, `ST_isValid` is *not* meant to validate whether the WKT or WKB is well-formed. That's the job of `ST_GeometryFromText` and `ST_GeomFromBinary`. `ST_IsValid` is responsible for performing logical validations (e.g., both coordinates of a point must be null or both non-null, etc).
