### ISSUE TITLE
Distinct operation on UUID fails when values are equal

### ISSUE THREAD

**Issue by guyco33** [prestosql/presto#1170]
```
select distinct u 
from (values (uuid'be0b0518-35a1-4d10-b7f1-1b61355fa741'),
             (uuid'be0b0518-35a1-4d10-b7f1-1b61355fa741')
) as t(u)
```

Results with:
```
java.lang.UnsupportedOperationException: io.prestosql.spi.block.Int128ArrayBlockBuilder
	at io.prestosql.spi.block.Block.compareTo(Block.java:146)
	at io.prestosql.type.UuidOperators$UuidDistinctFromOperator.isDistinctFrom(UuidOperators.java:202)
	at io.prestosql.$gen.PagesHashStrategy_20190724_092919_3.positionNotDistinctFromRow(Unknown Source)
	at io.prestosql.operator.MultiChannelGroupByHash.positionNotDistinctFromCurrentRow(MultiChannelGroupByHash.java:442)
	at io.prestosql.operator.MultiChannelGroupByHash.putIfAbsent(MultiChannelGroupByHash.java:286)
	at io.prestosql.operator.MultiChannelGroupByHash.putIfAbsent(MultiChannelGroupByHash.java:276)
	at io.prestosql.operator.MultiChannelGroupByHash.access$200(MultiChannelGroupByHash.java:54)
	at io.prestosql.operator.MultiChannelGroupByHash$AddNonDictionaryPageWork.process(MultiChannelGroupByHash.java:592)
	at io.prestosql.operator.HashAggregationOperator.addInput(HashAggregationOperator.java:421)
	at io.prestosql.operator.Driver.processInternal(Driver.java:384)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_316____20190724_092808_1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by findepi** [comment]
@stewartpark would you like to contribute a fix for this?

**Comment by guyco33** [comment]
@findepi I will fix it

**Comment by stewartpark** [comment]
I'd love to contribute if @guyco33 hasn't started the work! I have a fix that fixed this problem on our production. I can clean up and add test cases and make a PR.

**Comment by martint** [comment]
Fixed in version 318.

**Comment by Praveen2112** [comment]
I guess we can close it.
