### ISSUE TITLE
Bad error message for DISTINCT on non-aggregation function

### ISSUE THREAD

**Issue by electrum** [prestosql/presto#1204]
This is failing with a `VerifyException` rather than a proper analysis error.

```
presto> SELECT lower(DISTINCT id) FROM (VALUES ('foo')) AS t (id);
Query 20190729_060454_00001_d9dzy failed: window does not support distinct

com.google.common.base.VerifyException: window does not support distinct
	at com.google.common.base.Verify.verify(Verify.java:124)
	at io.prestosql.sql.planner.ExpressionInterpreter$Visitor.visitFunctionCall(ExpressionInterpreter.java:934)
	at io.prestosql.sql.tree.FunctionCall.accept(FunctionCall.java:110)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.planner.ExpressionInterpreter.optimize(ExpressionInterpreter.java:287)
	at io.prestosql.sql.planner.iterative.rule.SimplifyExpressions.rewrite(SimplifyExpressions.java:54)
	at io.prestosql.sql.planner.iterative.rule.SimplifyExpressions.lambda$createRewrite$0(SimplifyExpressions.java:79)
	at io.prestosql.sql.planner.iterative.rule.ExpressionRewriteRuleSet$ProjectExpressionRewrite.lambda$apply$0(ExpressionRewriteRuleSet.java:125)
	at io.prestosql.sql.planner.plan.Assignments.lambda$rewrite$1(Assignments.java:108)
```

Based on the original report from @yuokada, 9f78af6fec9441532a9a19a0d235e322455588c9 seems to have added validation for this, and previously the bogus keyword was silently ignored.

**Comment by alexjo2144** [comment]
Would the fix for this just be to switch to use something like:
`throw new PrestoException(NOT_SUPPORTED, ...);`
Or is there another exception type for these kinds of errors?

**Comment by findepi** [comment]
@alexjo2144 i'm not 100% sure yet. let's do this err code for now. 
i think the right place is https://github.com/prestosql/presto/blob/8e242e803dd97f3b471f9852d3bd8afe2e6c7763/presto-main/src/main/java/io/prestosql/sql/analyzer/ExpressionAnalyzer.java#L849 
+ some tests

**Comment by j4ckofalltrades** [comment]
@findepi Is it okay if I pick this up?

**Comment by findepi** [comment]
@j4ckofalltrades thanks!

**Comment by j4ckofalltrades** [comment]
This can be closed.

**Comment by findepi** [comment]
Fixed in https://github.com/prestosql/presto/pull/5418

thanks @j4ckofalltrades !
