### ISSUE TITLE
Explicit bindings are required and io.prestosql.plugin.jdbc.ConnectionFactory is not explicitly bound

### ISSUE THREAD

**Issue by prashant-jain** [prestosql/presto#1208]
Hi, I am setting up prestosql-316 to query on oracle.
After adding presto-oracle plugin (https://github.com/tweea/presto-oracle). I am unable to run the presto server. kindly help to resolve this error.

Performed steps:
cp -r plugin/mysql plugin/oracle
rm plugin/oracle/mysql-connector*
rm plugin/oracle/presto-mysql*
mv /home/Downloads/presto-oracle*.jar plugin/oracle

Launcher log:
2019-07-29T14:48:53.330+0700    INFO    main    Bootstrap       oracle.use-fetch-size-with-long-column    null        null
2019-07-29T14:48:53.452+0700    ERROR   main    io.prestosql.server.PrestoServer        Unable to create injector, see the following errors:
1) Explicit bindings are required and io.prestosql.plugin.jdbc.ConnectionFactory is not explicitly bound.
while locating io.prestosql.plugin.jdbc.ConnectionFactory
  for the 1st parameter of io.prestosql.plugin.jdbc.JdbcModule.createConnectionFactoryWithStats(JdbcModule.java:72)
at io.prestosql.plugin.jdbc.JdbcModule.createConnectionFactoryWithStats(JdbcModule.java:72)
1 error
com.google.inject.CreationException: Unable to create injector, see the following errors:
1) Explicit bindings are required and io.prestosql.plugin.jdbc.ConnectionFactory is not explicitly bound.
while locating io.prestosql.plugin.jdbc.ConnectionFactory
  for the 1st parameter of io.prestosql.plugin.jdbc.JdbcModule.createConnectionFactoryWithStats(JdbcModule.java:72)
at io.prestosql.plugin.jdbc.JdbcModule.createConnectionFactoryWithStats(JdbcModule.java:72)
1 error
      at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
      at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
      at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
      at com.google.inject.Guice.createInjector(Guice.java:87)
      at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:240)
      at io.prestosql.plugin.jdbc.JdbcConnectorFactory.create(JdbcConnectorFactory.java:79)
      at io.prestosql.connector.ConnectorManager.createConnector(ConnectorManager.java:328)
      at io.prestosql.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:198)
      at io.prestosql.connector.ConnectorManager.createConnection(ConnectorManager.java:190)
      at io.prestosql.connector.ConnectorManager.createConnection(ConnectorManager.java:176)
      at io.prestosql.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:88)
      at io.prestosql.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
      at io.prestosql.server.PrestoServer.run(PrestoServer.java:127)
      at io.prestosql.server.PrestoServer.main(PrestoServer.java:70)
2019-07-29T14:48:53.454+0700    INFO    Thread-99       io.airlift.bootstrap.LifeCycleManager   Life cycle stopping...

**Comment by findepi** [comment]
@prashant-jain we can only support plugins that are part of Presto code base. 
Clearly, the https://github.com/tweea/presto-oracle plugin needs to be updated to work with Presto 316, so I recommend you create an issue in that repository.
From my understanding of the stacktrace, you should be able to use this plugin with Presto 315.

I'm closing this issue as answered.
Let's continue on Slack where you asked this question as well (https://prestosql.slack.com/archives/CGB0QHWSW/p1564391862133600).
