### ISSUE TITLE
Insert overwrite for unpartitioned table fails when using Glue as metastore

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#1243]
Steps to reproduce - run `TestHiveGlueMetastore#testInsertOverwriteUnpartitioned`

```
io.prestosql.spi.PrestoException: listTablePrivileges is not supported by Glue
    at io.prestosql.plugin.hive.metastore.glue.GlueHiveMetastore.listTablePrivileges(GlueHiveMetastore.java:887)
    at io.prestosql.plugin.hive.metastore.CachingHiveMetastore.loadTablePrivileges(CachingHiveMetastore.java:743)
    at io.prestosql.plugin.hive.metastore.CachingHiveMetastore.lambda$new$0(CachingHiveMetastore.java:189)
    at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)
    at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:188)
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
    at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
    at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
    at io.prestosql.plugin.hive.metastore.CachingHiveMetastore.get(CachingHiveMetastore.java:218)
    at io.prestosql.plugin.hive.metastore.CachingHiveMetastore.listTablePrivileges(CachingHiveMetastore.java:738)
    at io.prestosql.plugin.hive.metastore.SemiTransactionalHiveMetastore.listTablePrivileges(SemiTransactionalHiveMetastore.java:835)
    at io.prestosql.plugin.hive.HiveMetadata.finishInsert(HiveMetadata.java:1410)
    at io.prestosql.plugin.hive.AbstractTestHive.insertData(AbstractTestHive.java:3752)
    at io.prestosql.plugin.hive.AbstractTestHive.doInsertOverwriteUnpartitioned(AbstractTestHive.java:3238)
    at io.prestosql.plugin.hive.AbstractTestHive.testInsertOverwriteUnpartitioned(AbstractTestHive.java:2371)
...
    at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
    at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
```

**Comment by findepi** [comment]
cc @electrum @xumingming

**Comment by sopel39** [comment]
It might be that entire section:
```
                    // get privileges from existing table
                    PrincipalPrivileges principalPrivileges = fromHivePrivilegeInfos(metastore.listTablePrivileges(handle.getSchemaName(), handle.getTableName(), null));

                    // first drop it
                    metastore.dropTable(session, handle.getSchemaName(), handle.getTableName());

                    // create the table with the new location
                    metastore.createTable(session, table, principalPrivileges, Optional.of(partitionUpdate.getWritePath()), false, partitionStatistics);
```
needs a dedicated Metastore method, e.g. `changeTableLocation`
