### ISSUE TITLE
Flaky TestSystemConnector.testQueryDuringAnalisysIsCaptured

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#1339]
```
[ERROR] Tests run: 2013, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2,602.93 s <<< FAILURE! - in TestSuite
[ERROR] testQueryDuringAnalisysIsCaptured(io.prestosql.connector.system.TestSystemConnector)  Time elapsed: 0.823 s  <<< FAILURE!
java.lang.AssertionError: 
For query: 
 SELECT state FROM system.runtime.queries WHERE query LIKE '%test_query_id_2%' AND query NOT LIKE '%system.runtime.queries%'
not equal
Actual rows (up to 100 of 1 extra rows shown, 1 rows in total):
    [RUNNING]
Expected rows (up to 100 of 1 missing rows shown, 1 rows in total):
    [FINISHED]

	at org.testng.Assert.fail(Assert.java:94)
	at io.prestosql.tests.QueryAssertions.assertEqualsIgnoreOrder(QueryAssertions.java:223)
	at io.prestosql.tests.QueryAssertions.assertQuery(QueryAssertions.java:203)
	at io.prestosql.tests.QueryAssertions.assertQuery(QueryAssertions.java:106)
	at io.prestosql.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:137)
	at io.prestosql.connector.system.TestSystemConnector.testQueryDuringAnalisysIsCaptured(TestSystemConnector.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sopel39** [comment]
Should it be closed?
