### ISSUE TITLE
Presto insert results in malformed ORC file. 

### ISSUE THREAD

**Issue by 360d-io-labs** [prestosql/presto#1450]
Presto version: 318
Hive version: 1.2.1

hive configuration:
hive.orc.bloom-filters.enable=true
hive.max-partitions-per-writers=365

I will try to summarize the issue as best as I can but unfortunately I'm not able to copy some data to illustrate the issue.

I have a set of parquet file partitioned by date containing about 50 millions records per day with about 800 columns. I have absolutely no issue to query this external table (through hive) with Presto.

I'm now trying to create a new table with Presto that take the original parquet file and keep the partition but that add buckets and a bloom filter. This is an internal hive table and here is the end of the create table in hive:

>  PARTITIONED BY (
  `logdate` string)
CLUSTERED BY (
  `id`) INTO 60 buckets
STORED AS ORC
TBLPROPERTIES 
  ("orc.compress"="SNAPPY", 
  "orc.create.index"="true", "orc.bloom.filter.columns"="events",
  "orc.bloom.filter.fpp"="0.05",
  "orc.stripe.size"="268435456",
  "orc.row.index.stride"="10000");

I then inserted data from my original table (parquet files) with Presto and this doesn't result in any error:

> INSERT INTO xxxx_prod_log_orc SELECT * FROM xxxx_prod_log_parquet WHERE logdate=('2019-01-01');

The orc file are created, however if now I try to do a Select * with a predicate on that table I will get this:

> Query 20190830_135233_00701_phxb4 failed: Malformed ORC file. Seek past end of stream [hdfs://mycluster/apps/hive/warehouse/g.db/xxxx_prod_log_orc/logdate=2019-08-20/000006_0_20190829_122657_00067_phxb4]
io.prestosql.spi.PrestoException: Malformed ORC file. Seek past end of stream [hdfs://mycluster/apps/hive/warehouse/g.db/xxxx_prod_log_orc/logdate=2019-08-20/000006_0_20190829_122657_00067_phxb4]
        at io.prestosql.plugin.hive.orc.OrcPageSource$OrcBlockLoader.load(OrcPageSource.java:235)
        at io.prestosql.plugin.hive.orc.OrcPageSource$OrcBlockLoader.load(OrcPageSource.java:209)
        at io.prestosql.spi.block.LazyBlock.assureLoaded(LazyBlock.java:277)
        at io.prestosql.spi.block.LazyBlock.getLoadedBlock(LazyBlock.java:268)
        at io.prestosql.operator.PageUtils.lambda$recordMaterializedBytes$0(PageUtils.java:42)
        at io.prestosql.spi.block.LazyBlock.assureLoaded(LazyBlock.java:277)
        at io.prestosql.spi.block.LazyBlock.getLoadedBlock(LazyBlock.java:268)
        at io.prestosql.operator.project.DictionaryAwarePageProjection$DictionaryAwarePageProjectionWork.setupDictionaryBlockProjection(DictionaryAwarePageProjection.java:211)
        at io.prestosql.operator.project.DictionaryAwarePageProjection$DictionaryAwarePageProjectionWork.lambda$getResult$0(DictionaryAwarePageProjection.java:197)
        at io.prestosql.spi.block.LazyBlock.assureLoaded(LazyBlock.java:277)
        at io.prestosql.spi.block.LazyBlock.getLoadedBlock(LazyBlock.java:268)
        at io.prestosql.operator.project.PageProcessor$ProjectSelectedPositions.processBatch(PageProcessor.java:341)
        at io.prestosql.operator.project.PageProcessor$ProjectSelectedPositions.process(PageProcessor.java:204)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
        at io.prestosql.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:278)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:320)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:307)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
        at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
        at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
        at io.prestosql.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:278)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:320)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:307)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
        at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
        at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
        at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
        at io.prestosql.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
        at io.prestosql.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:148)
        at io.prestosql.operator.Driver.processInternal(Driver.java:379)
        at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
        at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
        at io.prestosql.operator.Driver.processFor(Driver.java:276)
        at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
        at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
        at io.prestosql.$gen.Presto_318____20190829_120913_1.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.prestosql.orc.OrcCorruptionException: Malformed ORC file. Seek past end of stream [hdfs://mycluster/apps/hive/warehouse/g.db/xxxx_prod_log_orc/logdate=2019-08-20/000006_0_20190829_122657_00067_phxb4]
        at io.prestosql.orc.stream.CompressedOrcChunkLoader.seekToCheckpoint(CompressedOrcChunkLoader.java:95)
        at io.prestosql.orc.stream.OrcInputStream.seekToCheckpoint(OrcInputStream.java:175)
        at io.prestosql.orc.stream.ByteArrayInputStream.seekToCheckpoint(ByteArrayInputStream.java:50)
        at io.prestosql.orc.stream.ByteArrayInputStream.seekToCheckpoint(ByteArrayInputStream.java:22)
        at io.prestosql.orc.stream.CheckpointInputStreamSource.openStream(CheckpointInputStreamSource.java:57)
        at io.prestosql.orc.reader.SliceDirectStreamReader.openRowGroup(SliceDirectStreamReader.java:243)
        at io.prestosql.orc.reader.SliceDirectStreamReader.readBlock(SliceDirectStreamReader.java:104)
        at io.prestosql.orc.reader.SliceStreamReader.readBlock(SliceStreamReader.java:77)
        at io.prestosql.orc.OrcRecordReader.readBlock(OrcRecordReader.java:410)
        at io.prestosql.plugin.hive.orc.OrcPageSource$OrcBlockLoader.load(OrcPageSource.java:231)
        ... 44 more

If I do a select columns1,columns2 with the same predicate the query will succeed.

I was thinking that maybe some of the data in the original parquet file were creating the issue, so I created the same exact table but then inserted the data with hive/Tez (that process is also going fine without any error). When the data are inserted with hive/tez I can query them from Presto without any error, and of course I get the same number of lines with both method.

Thanks for everything!

**Comment by findepi** [comment]
@360d-io-labs thanks for reporting the issue.
Can I ask you to try to narrow down the issue a bit?
- the offending file is `xxxx_prod_log_orc/logdate=2019-08-20/000006_0_20190829_122657_00067_phxb4`. If you populate your ORC table with just this single partition, does the issue persist?
- if you disable bloom filters, does the issue persist?
- if you omit 400 of your 800 columns when creating the ORC table, does the issue persist? What if you create the table with only the other 400 columns?
- does it happen only when the table is bucketed?

cc @dain

**Comment by electrum** [comment]
Can you also try setting these session properties:
```java
SET SESSION hive.orc_optimized_writer_validate = true;
SET SESSION hive.orc_optimized_writer_validate_percentage = 100;
SET SESSION hive.orc_optimized_writer_validate_mode = 'BOTH';
```
This won't fix the problem, of course, but might provide additional hints on what is wrong.

**Comment by 360d-io-labs** [comment]
Spent some time to try to nail the issue.

The issue as described by the ORC validation is:

> Malformed ORC file. Write validation failed: Invalid row count 

I did the following steps:
* I removed the bloom filter and all the other ORC properties -> issue still occurring
* I removed the bucketing .> issue still occuring
* I changed the compression algo from snappy to lz4, -> issue still occurring
* I started to create a new table adding the columns by small batches. Results were ok until I reached around 185 columns then the same error occurred again. (at that time the only orc properties left was lz4 compression and no bucketing)
* I thought that the problem may be caused by the data in the last 25 columns I added. Created a news table with just these 25 columns and the ORC validation was ok.

Hope that helps!

**Comment by findepi** [comment]
@360d-io-labs thanks for this investigation and narrowing down the scope!

> Results were ok until I reached around 185 columns then the same error occurred again.

How big was the resulting file at that time? (you may need to disable writer validation to retain the file)

**Comment by dain** [comment]
Can you post the writer validation stack trace?
Do you have test code that can reproduce the problem?  I can normally fix this pretty fast once I have a reproduction... either a bad file or code to produce the bad file.

**Comment by findepi** [comment]
@360d-io-labs any update on this?
