### ISSUE TITLE
Product test suite-3 is very flaky

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#1468]
`PRODUCT_TESTS_SUITE=suite-3` is very flaky.

**Comment by findepi** [comment]
Relates #683

**Comment by Praveen2112** [comment]
PrestoCliTests are also failing

**Comment by Praveen2112** [comment]
PrestoCliTests are also failing

**Comment by kokosing** [comment]
> PrestoCliTests are also failing

Can you please point stack track or/and link to the log file?

**Comment by ebyhr** [comment]
Maybe this one? https://api.travis-ci.com/v3/job/256645666/log.txt
```
2019-11-14 22:47:20 INFO: FAILURE     /    io.prestosql.tests.cli.TestPrestoCli.shouldHandleTransaction (Groups: cli) took 3.0 seconds
2019-11-14 22:47:20 SEVERE: Failure cause:
java.lang.AssertionError: 
Expecting:
 <[]>
to contain:
 <["USE"]>
but could not find:
 <["USE"]>

	at io.prestosql.tests.cli.TestPrestoCli.shouldHandleTransaction(TestPrestoCli.java:245)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

**Comment by Praveen2112** [comment]
It varies, sometimes it throws exception like `No process ran for last 10mins`

**Comment by kokosing** [comment]
```
2019-11-21 05:49:48 INFO: [33 of 57] sql_tests.testcases.join.explicit_inner_implicit_same_tables (Groups: join)


No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

The build has been terminated
```
