### ISSUE TITLE
Presto fails to read MySQL view containing UNION ALL: No database selected

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#1583]
This is reproducible with MySQL 5.7 (the version used in product tests).

In MySQL
```
CREATE TABLE t(a bigint);
INSERT INTO t VALUES (42), (53);

CREATE OR REPLACE VIEW v AS 
    SELECT * FROM (
        SELECT a FROM t
        UNION ALL SELECT (a + 2) AS a FROM t
    ) x
;
```

In Presto
```
presto:test> SELECT * FROM t;
 a
----
 42
```

```
presto:test> SELECT * FROM v;

Query 20190925_121556_00004_zkmby failed: No database selected
io.prestosql.spi.PrestoException: No database selected
	at io.prestosql.plugin.jdbc.JdbcRecordCursor.handleSqlException(JdbcRecordCursor.java:251)
	at io.prestosql.plugin.jdbc.JdbcRecordCursor.<init>(JdbcRecordCursor.java:102)
	at io.prestosql.plugin.jdbc.JdbcRecordSet.cursor(JdbcRecordSet.java:63)
	at io.prestosql.spi.connector.RecordPageSource.<init>(RecordPageSource.java:39)
	at io.prestosql.split.RecordPageSourceProvider.createPageSource(RecordPageSourceProvider.java:43)
	at io.prestosql.split.PageSourceManager.createPageSource(PageSourceManager.java:56)
	at io.prestosql.operator.TableScanOperator.getOutput(TableScanOperator.java:277)
```

**Comment by findepi** [comment]
The SQL being sent to MySQL is:
```
SELECT `a` FROM `test`.`v`;
```

It doesn't work from mysql CLI either:
```
$ docker exec -it common_mysql_1 mysql -u swarm -pswarm

Server version: 5.7.27 MySQL Community Server (GPL)

mysql> SELECT `a` FROM `test`.`v`;
ERROR 1046 (3D000): No database selected
```

**Comment by vihag** [comment]
MySQL 8 on AWS RDS works in for this scenario. I tried with MySQL 8.0.20
