### ISSUE TITLE
Query fails on Internal error since 319

### ISSUE THREAD

**Issue by guyco33** [prestosql/presto#1586]
Since version 319 the following query fails with Internal error:
```
WITH
  a AS (SELECT id FROM (VALUES (1)) AS t(id)),
  b AS (SELECT id FROM (VALUES (1)) AS t(id)),
  c AS (SELECT id FROM (VALUES ('1')) AS t(id)),
  d as (SELECT id FROM (VALUES (1)) AS t(id))
SELECT a.id
FROM a
LEFT JOIN b ON a.id = b.id
JOIN c ON a.id = CAST(c.id AS bigint)
JOIN d ON d.id = a.id
```
 
Full stack trace is:
```java.lang.NullPointerException: undefined
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:877)
	at com.google.common.collect.ImmutableList$Builder.add(ImmutableList.java:788)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.prestosql.sql.planner.iterative.rule.EliminateCrossJoins.getJoinOrder(EliminateCrossJoins.java:145)
	at io.prestosql.sql.planner.iterative.rule.EliminateCrossJoins.apply(EliminateCrossJoins.java:79)
	at io.prestosql.sql.planner.iterative.rule.EliminateCrossJoins.apply(EliminateCrossJoins.java:52)
	at io.prestosql.sql.planner.iterative.IterativeOptimizer.transform(IterativeOptimizer.java:165)
	at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreNode(IterativeOptimizer.java:140)
	at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:105)
	at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:190)
	at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:107)
	at io.prestosql.sql.planner.iterative.IterativeOptimizer.optimize(IterativeOptimizer.java:96)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:169)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:158)
	at io.prestosql.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:393)
	at io.prestosql.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:381)
	at io.prestosql.execution.SqlQueryExecution.start(SqlQueryExecution.java:333)
	at io.prestosql.$gen.Presto_319_gade21ce____20190924_124331_1.run(Unknown Source)
	at io.prestosql.execution.SqlQueryManager.createQuery(SqlQueryManager.java:239)
	at io.prestosql.dispatcher.LocalDispatchQuery.lambda$startExecution$4(LocalDispatchQuery.java:107)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The query works without the join on `c` or the join on `d` (skips `EliminateCrossJoins.getJoinOrder` since  `joinGraph.size() < 3`)
It also works when changing `LEFT JOIN` to `INNER JOIN`

**Comment by martint** [comment]
This is probably related to #1390
