### ISSUE TITLE
Presto fails to read MySQL view containing a function which cannot be executed by Presto's user

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#1597]
Repro steps below are for product test env
```
./presto-product-tests/conf/docker/singlenode-mysql/compose.sh up

docker exec -it common_mysql_1 mysql -u root -ptest -D test
```

In MySQL define

```sql
mysql>
CREATE TABLE t(a bigint);
INSERT INTO t VALUES (42), (53);

DELIMITER //
CREATE FUNCTION foo(param BIGINT) RETURNS int DETERMINISTIC
BEGIN
    DECLARE result int;
    SET result = (SELECT DISTINCT true FROM t WHERE t.a = param);
    RETURN result;
END//

DELIMITER ;

CREATE OR REPLACE VIEW v AS SELECT a FROM t WHERE foo(a) = 1;
```

```sql
mysql>
CREATE USER 'bob'@'%' IDENTIFIED BY 'bob';
GRANT SELECT ON test.* TO 'bob'@'%' ;
GRANT USAGE ON *.* TO 'bob'@'%';
FLUSH PRIVILEGES;
```

Now, configure Presto mysql connector using `bob` user.

```
presto>
presto:test> SHOW TABLES;
 Table
-------
 t
 v
```
```
presto:test> SELECT * FROM v;
Query 20190927_130330_00003_h536e failed: Table 'test.v' not found
io.prestosql.spi.connector.TableNotFoundException: Table 'test.v' not found
	at io.prestosql.plugin.jdbc.BaseJdbcClient.getColumns(BaseJdbcClient.java:260)
...
	at io.prestosql.plugin.jdbc.JdbcMetadata.getTableMetadata(JdbcMetadata.java:149)
	at io.prestosql.metadata.MetadataManager.getTableMetadata(MetadataManager.java:450)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:894)
```

**Comment by findepi** [comment]
If we remove `connectionProperties.setProperty("useInformationSchema", "true");` from mysql connection properties, we will get
```
presto:test> SELECT * FROM v;
...
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: execute command denied to user 'bob'@'%' for routine 'test.foo'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2439)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1365)
	at com.mysql.jdbc.DatabaseMetaData$2.forEach(DatabaseMetaData.java:2442)
	at com.mysql.jdbc.DatabaseMetaData$2.forEach(DatabaseMetaData.java:2340)
	at com.mysql.jdbc.IterateBlock.doForAll(IterateBlock.java:50)
	at com.mysql.jdbc.DatabaseMetaData.getColumns(DatabaseMetaData.java:2338)
	at io.prestosql.plugin.jdbc.BaseJdbcClient.getColumns(BaseJdbcClient.java:272)
	at io.prestosql.plugin.jdbc.BaseJdbcClient.getColumns(BaseJdbcClient.java:240)
	... 41 more
```

**Comment by findepi** [comment]
Obviously, having `useInformationSchema=false` connection property yields some actionable error message.
However, we cannot make it the default. We set `useInformationSchema=true` for a good reason: 10aad75bd35edf8b97996a79e31b0c65ec1b876c.

I am closing this, as I don't plan to change this. 
If this turns out to be a common problem, we can think about a workaround.
