### ISSUE TITLE
PrestoResultSet sometimes fails with IndexOutOfBoundsException after translating column name to column index

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#1732]
From https://github.com/prestosql/presto/pull/1716's Travis log:
```
[ERROR] Tests run: 110, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 61.816 s <<< FAILURE! - in TestSuite
[ERROR] testExtraCredentials(io.prestosql.jdbc.TestJdbcConnection)  Time elapsed: 0.319 s  <<< FAILURE!
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at java.util.Collections$UnmodifiableList.get(Collections.java:1311)
	at io.prestosql.jdbc.PrestoResultSet.column(PrestoResultSet.java:1695)
	at io.prestosql.jdbc.PrestoResultSet.getString(PrestoResultSet.java:369)
	at io.prestosql.jdbc.TestJdbcConnection.listExtraCredentials(TestJdbcConnection.java:298)
	at io.prestosql.jdbc.TestJdbcConnection.testExtraCredentials(TestJdbcConnection.java:247)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by findepi** [comment]
This doesn't look like test's problem. More like JDBC's.

**Comment by kasiafi** [comment]
Here's another one from https://github.com/prestosql/presto/pull/1017
```
[ERROR] Tests run: 110, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 92.072 s <<< FAILURE! - in TestSuite
[ERROR] testGetTables(io.prestosql.jdbc.TestPrestoDriver)  Time elapsed: 0.004 s  <<< FAILURE!
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at java.util.Collections$UnmodifiableList.get(Collections.java:1311)
	at io.prestosql.jdbc.PrestoResultSet.column(PrestoResultSet.java:1674)
	at io.prestosql.jdbc.PrestoResultSet.getObject(PrestoResultSet.java:532)
	at io.prestosql.jdbc.TestPrestoDriver.readRows(TestPrestoDriver.java:1703)
	at io.prestosql.jdbc.TestPrestoDriver.testGetTables(TestPrestoDriver.java:682)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
