### ISSUE TITLE
CLI version >= 321 failed to get result from old cluster

### ISSUE THREAD

**Issue by ebyhr** [prestosql/presto#1805]
This issue happens on below version. The query succeeded on server, but cli shows following exception. While we can avoid it by using the same version between cli and server, some people who manage multiple clusters with different versions may face this issue. 

CLI: 321 ~ upstream
Server: 320

```
$ ./presto-cli-321-executable.jar --debug
presto> show catalogs;

Query 20191019_053126_00000_myj35, QUEUED, 0 nodes, 0 splits
http://localhost:8000/ui/query.html?20191019_053126_00000_myj35
java.lang.RuntimeException: Error fetching next at http://localhost:8000/v1/statement/executing/20191019_053126_00000_myj35/xb782924dd999414da4d2f9b7d9dcfa34/0 returned an invalid response: JsonResponse{statusCode=200, statusMessage=OK, headers={content-type=[application/json], date=[Sat, 19 Oct 2019 05:31:28 GMT], vary=[Accept-Encoding, User-Agent], x-content-type-options=[nosniff]}, hasValue=false} [Error: {"id":"20191019_053126_00000_myj35","infoUri":"http://localhost:8000/ui/query.html?20191019_053126_00000_myj35","partialCancelUri":"http://localhost:8000/v1/statement/partialCancel/20191019_053126_00000_myj35/0/xb782924dd999414da4d2f9b7d9dcfa34","nextUri":"http://localhost:8000/v1/statement/executing/20191019_053126_00000_myj35/xb782924dd999414da4d2f9b7d9dcfa34/1","columns":[{"name":"Catalog","type":"varchar(9)","typeSignature":{"rawType":"varchar","typeArguments":[],"literalArguments":[],"arguments":[{"kind":"LONG_LITERAL","value":9}]}}],"data":[["cassandra"],["hive"],["system"],["tpch"]],"stats":{"state":"RUNNING","queued":false,"scheduled":true,"nodes":1,"totalSplits":19,"queuedSplits":18,"runningSplits":0,"completedSplits":1,"cpuTimeMillis":8,"wallTimeMillis":9,"queuedTimeMillis":15,"elapsedTimeMillis":1186,"processedRows":0,"processedBytes":0,"peakMemoryBytes":0,"spilledBytes":0,"rootStage":{"stageId":"0","state":"RUNNING","done":false,"nodes":1,"totalSplits":1,"queuedSplits":1,"runningSplits":0,"completedSplits":0,"cpuTimeMillis":0,"wallTimeMillis":0,"processedRows":0,"processedBytes":0,"subStages":[{"stageId":"1","state":"FINISHED","done":true,"nodes":1,"totalSplits":17,"queuedSplits":17,"runningSplits":0,"completedSplits":0,"cpuTimeMillis":0,"wallTimeMillis":0,"processedRows":0,"processedBytes":0,"subStages":[{"stageId":"2","state":"FINISHED","done":true,"nodes":1,"totalSplits":1,"queuedSplits":0,"runningSplits":0,"completedSplits":1,"cpuTimeMillis":8,"wallTimeMillis":9,"processedRows":4,"processedBytes":0,"subStages":[]}]}]},"progressPercentage":5.2631578947368425},"warnings":[]}
]
	at io.prestosql.client.StatementClientV1.requestFailedException(StatementClientV1.java:463)
	at io.prestosql.client.StatementClientV1.advance(StatementClientV1.java:402)
	at io.prestosql.cli.StatusPrinter.printInitialStatusUpdates(StatusPrinter.java:133)
	at io.prestosql.cli.Query.renderQueryOutput(Query.java:155)
	at io.prestosql.cli.Query.renderOutput(Query.java:140)
	at io.prestosql.cli.Console.process(Console.java:331)
	at io.prestosql.cli.Console.runConsole(Console.java:257)
	at io.prestosql.cli.Console.run(Console.java:156)
	at io.prestosql.cli.Presto.main(Presto.java:31)
Caused by: java.lang.IllegalArgumentException: Unable to create class io.prestosql.client.QueryResults from JSON response:
[{"id":"20191019_053126_00000_myj35","infoUri":"http://localhost:8000/ui/query.html?20191019_053126_00000_myj35","partialCancelUri":"http://localhost:8000/v1/statement/partialCancel/20191019_053126_00000_myj35/0/xb782924dd999414da4d2f9b7d9dcfa34","nextUri":"http://localhost:8000/v1/statement/executing/20191019_053126_00000_myj35/xb782924dd999414da4d2f9b7d9dcfa34/1","columns":[{"name":"Catalog","type":"varchar(9)","typeSignature":{"rawType":"varchar","typeArguments":[],"literalArguments":[],"arguments":[{"kind":"LONG_LITERAL","value":9}]}}],"data":[["cassandra"],["hive"],["system"],["tpch"]],"stats":{"state":"RUNNING","queued":false,"scheduled":true,"nodes":1,"totalSplits":19,"queuedSplits":18,"runningSplits":0,"completedSplits":1,"cpuTimeMillis":8,"wallTimeMillis":9,"queuedTimeMillis":15,"elapsedTimeMillis":1186,"processedRows":0,"processedBytes":0,"peakMemoryBytes":0,"spilledBytes":0,"rootStage":{"stageId":"0","state":"RUNNING","done":false,"nodes":1,"totalSplits":1,"queuedSplits":1,"runningSplits":0,"completedSplits":0,"cpuTimeMillis":0,"wallTimeMillis":0,"processedRows":0,"processedBytes":0,"subStages":[{"stageId":"1","state":"FINISHED","done":true,"nodes":1,"totalSplits":17,"queuedSplits":17,"runningSplits":0,"completedSplits":0,"cpuTimeMillis":0,"wallTimeMillis":0,"processedRows":0,"processedBytes":0,"subStages":[{"stageId":"2","state":"FINISHED","done":true,"nodes":1,"totalSplits":1,"queuedSplits":0,"runningSplits":0,"completedSplits":1,"cpuTimeMillis":8,"wallTimeMillis":9,"processedRows":4,"processedBytes":0,"subStages":[]}]}]},"progressPercentage":5.2631578947368425},"warnings":[]}
]
	at io.prestosql.client.JsonResponse.<init>(JsonResponse.java:70)
	at io.prestosql.client.JsonResponse.execute(JsonResponse.java:144)
	at io.prestosql.client.StatementClientV1.advance(StatementClientV1.java:388)
	... 7 more
Caused by: java.lang.IllegalArgumentException: Invalid JSON string for [simple type, class io.prestosql.client.QueryResults]
	at io.airlift.json.JsonCodec.fromJson(JsonCodec.java:137)
	at io.prestosql.client.JsonResponse.<init>(JsonResponse.java:67)
	... 9 more
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `io.prestosql.client.ClientTypeSignatureParameter$ParameterKind` from String "LONG_LITERAL": value not one of declared Enum instance names: [NAMED_TYPE, TYPE, VARIABLE, LONG]
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: io.prestosql.client.QueryResults["columns"]->java.util.ArrayList[0]->io.prestosql.client.Column["typeSignature"]->io.prestosql.client.ClientTypeSignature["arguments"]->java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1549)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:911)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:255)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:179)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3984)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2276)
	at io.prestosql.client.ClientTypeSignatureParameter$ClientTypeSignatureParameterDeserializer.deserialize(ClientTypeSignatureParameter.java:142)
	at io.prestosql.client.ClientTypeSignatureParameter$ClientTypeSignatureParameterDeserializer.deserialize(ClientTypeSignatureParameter.java:132)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1611)
Query is gone (server restarted?)
```

**Comment by electrum** [comment]
Sorry, this was my fault. Already fixed in https://github.com/prestosql/presto/pull/1785
