### ISSUE TITLE
Iceberg error while creating s3 table

### ISSUE THREAD

**Issue by guyco33** [prestosql/presto#1858]
iceberg.properties
`connector.name=iceberg`
`hive.metastore=file`
`hive.metastore.catalog.dir=s3a://bucket-name/iceberg`

Sql commands:
`create schema iceberg.try;`
`create table iceberg.try.test123 as (with t(x,y) as (values (1,2)) select * from t);`

Error:
```
io.prestosql.spi.PrestoException: Could not create permissions directory
	at io.prestosql.plugin.hive.metastore.file.FileHiveMetastore.setTablePrivileges(FileHiveMetastore.java:1036)
	at io.prestosql.plugin.hive.metastore.file.FileHiveMetastore.createTable(FileHiveMetastore.java:284)
	at io.prestosql.plugin.hive.metastore.cache.CachingHiveMetastore.createTable(CachingHiveMetastore.java:457)
	at io.prestosql.plugin.hive.metastore.cache.CachingHiveMetastore.createTable(CachingHiveMetastore.java:457)
	at io.prestosql.plugin.iceberg.HiveTableOperations.commit(HiveTableOperations.java:225)
	at org.apache.iceberg.BaseTransaction.commitTransaction(BaseTransaction.java:200)
	at io.prestosql.plugin.iceberg.IcebergMetadata.finishInsert(IcebergMetadata.java:380)
	at io.prestosql.plugin.iceberg.IcebergMetadata.finishCreateTable(IcebergMetadata.java:314)
	at io.prestosql.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.finishCreateTable(ClassLoaderSafeConnectorMetadata.java:362)
	at io.prestosql.metadata.MetadataManager.finishCreateTable(MetadataManager.java:766)
	at io.prestosql.sql.planner.LocalExecutionPlanner.lambda$createTableFinisher$3(LocalExecutionPlanner.java:2769)
	at io.prestosql.operator.TableFinishOperator.getOutput(TableFinishOperator.java:297)
	at io.prestosql.operator.Driver.processInternal(Driver.java:379)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_320_1_gb6c724c____20191024_105731_1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by findepi** [comment]
Fixed by https://github.com/prestosql/presto/pull/1664
