### ISSUE TITLE
prestodb won't start because "Unable to create injector"

### ISSUE THREAD

**Issue by damianobarbati** [prestosql/presto#1995]
I can't start a prestodb instance for testing.

It complains with the following:
```
2019-11-09T18:57:27.892Z	ERROR	main	com.facebook.presto.server.PrestoServer	Unable to create injector, see the following errors:
presto_1  |
1) Explicit bindings are required and com.facebook.presto.plugin.mysql.MySqlConfig is not explicitly bound.
  while locating com.facebook.presto.plugin.mysql.MySqlConfig
    for the 3rd parameter of com.facebook.presto.plugin.mysql.MySqlClient.<init>(MySqlClient.java:68)
  at com.facebook.presto.plugin.mysql.MySqlClientModule.setup(MySqlClientModule.java:35)
presto_1  |
2) An exception was caught and reported. Message: Database (catalog) must not be specified in JDBC URL for MySQL connector
  at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
presto_1  |
2 errors
com.google.inject.CreationException: Unable to create injector, see the following errors:
presto_1  |
1) Explicit bindings are required and com.facebook.presto.plugin.mysql.MySqlConfig is not explicitly bound.
  while locating com.facebook.presto.plugin.mysql.MySqlConfig
    for the 3rd parameter of com.facebook.presto.plugin.mysql.MySqlClient.<init>(MySqlClient.java:68)
  at com.facebook.presto.plugin.mysql.MySqlClientModule.setup(MySqlClientModule.java:35)
presto_1  |
2) An exception was caught and reported. Message: Database (catalog) must not be specified in JDBC URL for MySQL connector
  at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
presto_1  |
2 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:240)
	at com.facebook.presto.plugin.jdbc.JdbcConnectorFactory.create(JdbcConnectorFactory.java:71)
	at com.facebook.presto.connector.ConnectorManager.createConnector(ConnectorManager.java:358)
	at com.facebook.presto.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:217)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:209)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:195)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:96)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:74)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:132)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:74)
Caused by: java.lang.IllegalArgumentException: Database (catalog) must not be specified in JDBC URL for MySQL connector
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:135)
	at com.facebook.presto.plugin.mysql.MySqlClientModule.ensureCatalogIsEmpty(MySqlClientModule.java:46)
	at com.facebook.presto.plugin.mysql.MySqlClientModule.setup(MySqlClientModule.java:36)
	at io.airlift.configuration.AbstractConfigurationAwareModule.configure(AbstractConfigurationAwareModule.java:43)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
	at com.google.inject.spi.Elements.getElements(Elements.java:103)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	... 11 more
```

Concerns arise because:
1) `Explicit bindings are required and com.facebook.presto.plugin.mysql.MySqlConfig is not explicitly bound.` but I can't find anything about "binding connectors" on prestodb docs: maybe missing java libs?

2)  `Database (catalog) must not be specified in JDBC URL for MySQL connector` but in the docs I see the same format I'm using for the mysql connector which is jdbc https://github.com/damianobarbati/docker-prestodb/blob/master/etc/catalog/mysql.properties

**How to reproduce?**

Repro here: https://github.com/damianobarbati/docker-prestodb

Run with:
```
wget https://repo1.maven.org/maven2/com/facebook/presto/presto-server/0.228/presto-server-0.228.tar.gz
docker-compose up --build --force-recreate --remove-orphans
```

**Comment by dain** [comment]
The root issue is `Database (catalog) must not be specified in JDBC URL for MySQL connector`.  I believe this is because the JDBC URL in the `mysql.properties` file ends with [`/test`](https://github.com/damianobarbati/docker-prestodb/blob/master/etc/catalog/mysql.properties#L2).  Looking at the [docs](https://prestosql.io/docs/current/connector/mysql.html#configuration), the URL should just have the host and port, so in your case would be `connection-url=jdbc:mysql://127.0.0.1:3306`.

Also, I would upgrade to a more recent version of Presto like 324, https://prestosql.io/download.html, as you are missing out on a number of new features.

**Comment by damianobarbati** [comment]
@dain thanks, it was that: I removed the db name from the connection string (and updated to 324)

**Comment by Gvrreddy91** [comment]
I have installed presto-345

I am able to do bin/launcher start and run, but when i am checking in server.logs below error am getting.

ERROR : com.facebook.presto.server.prestoserver unable to create injector see the following errors
Error in custom provider java.lang.NullPointerException
Error injecting constructor, java.io.UncheckedIOException : Failed to bind to /0.0.0.0:8080
Caused by : java.io.UncheckedIOException : Failed to bind to /0.0.0.0:8080

I am unable to generate http-request.log.
I want to connect mysql and postgresql through Presto.

**Comment by findepi** [comment]
@Gvrreddy91  Presto 3xx releases are maintained at https://github.com/prestosql/presto.
Also, there is the `#troubleshooting` channel on Presto Community Slack (https://prestosql.io/slack.html)
