### ISSUE TITLE
Connect failed to ElasticSearch when ElasticSearch enable the Authenticate

### ISSUE THREAD

**Issue by ellieshen** [prestosql/presto#2127]
I got the “401 Unauthorized” error when presto connect to elasticsearch when our elasticsearch cluster enabled the authentication, can presto support to pass-through account and credential to elasticsearch when submitting queries? Attached presto log file and elasticsearch config file.

Presto:325
elasticsearch:6.7.2
==============================
elk.properties:
```
connector.name=elasticsearch
elasticsearch.host=esnode.webex.com
elasticsearch.port=9200
elasticsearch.default-schema-name=default
elasticsearch.tls.enabled=true
elasticsearch.tls.verify-hostnames=false
elasticsearch.tls.truststore-path=etc/elasticsearch/es_xpack.crt
```
==============================
Presto logs:
```
2019-11-28T00:58:13.343Z        INFO    main    Bootstrap       elasticsearch.security                 ----        ----
2019-11-28T00:58:13.343Z        INFO    main    Bootstrap       elasticsearch.tls.enabled              false       true
2019-11-28T00:58:13.343Z        INFO    main    Bootstrap       elasticsearch.tls.truststore-path      ----        etc/elasticsearch/es_xpack.crt
2019-11-28T00:58:13.343Z        INFO    main    Bootstrap       elasticsearch.tls.truststore-password  [REDACTED]  [REDACTED]
2019-11-28T00:58:13.343Z        INFO    main    Bootstrap       elasticsearch.tls.verify-hostnames     true        false
2019-11-28T00:58:13.484Z        ERROR   main    io.prestosql.elasticsearch.client.ElasticsearchClient   Error refreshing nodes
io.prestosql.spi.PrestoException: method [GET], host [https://esnode.webex.com:9200], URI [/_nodes/http], status line [HTTP/1.1 401 Unauthorized]
{"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication token for REST request [/_nodes/http]","header":{"WWW-Authenticate":["Bearer realm=\"security\"","Basic realm=\"security\" charset=\"UTF-8\""]}}],"type":"security_exception","reason":"missing authentication token for REST request [/_nodes/http]","header":{"WWW-Authenticate":["Bearer realm=\"security\"","Basic realm=\"security\" charset=\"UTF-8\""]}},"status":401}
        at io.prestosql.elasticsearch.client.ElasticsearchClient.doRequest(ElasticsearchClient.java:560)
        at io.prestosql.elasticsearch.client.ElasticsearchClient.fetchNodes(ElasticsearchClient.java:332)
        at io.prestosql.elasticsearch.client.ElasticsearchClient.refreshNodes(ElasticsearchClient.java:153)
        at io.prestosql.elasticsearch.client.ElasticsearchClient.initialize(ElasticsearchClient.java:135)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.airlift.bootstrap.LifeCycleManager.startInstance(LifeCycleManager.java:240)
        at io.airlift.bootstrap.LifeCycleManager.addInstance(LifeCycleManager.java:211)
        at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:62)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
        at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
        at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
        at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
        at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
        at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
        at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:245)
                at io.prestosql.connector.ConnectorManager.createCatalog(ConnectorManager.java:203)
        at io.prestosql.connector.ConnectorManager.createCatalog(ConnectorManager.java:195)
        at io.prestosql.connector.ConnectorManager.createCatalog(ConnectorManager.java:181)
        at io.prestosql.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:88)
        at io.prestosql.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
        at io.prestosql.server.PrestoServer.run(PrestoServer.java:130)
        at io.prestosql.$gen.Presto_325____20191128_005800_1.run(Unknown Source)
        at io.prestosql.server.PrestoServer.main(PrestoServer.java:73)
Caused by: org.elasticsearch.client.ResponseException: method [GET], host [https://esnode.webex.com:9200], URI [/_nodes/http], status line [HTTP/1.1 401 Unauthorized]
{"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication token for REST request [/_nodes/http]","header":{"WWW-Authenticate":["Bearer realm=\"security\"","Basic realm=\"security\" charset=\"UTF-8\""]}}],"type":"security_exception","reason":"missing authentication token for REST request [/_nodes/http]","header":{"WWW-Authenticate":["Bearer realm=\"security\"","Basic realm=\"security\" charset=\"UTF-8\""]}},"status":401}
        at org.elasticsearch.client.RestClient$1.completed(RestClient.java:355)
        at org.elasticsearch.client.RestClient$1.completed(RestClient.java:344)
        at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
        at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
        at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:121)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
        at java.lang.Thread.run(Thread.java:748)
[configuration.txt](https://github.com/prestosql/presto/files/3899963/configuration.txt)
[presto-to-es-log.txt](https://github.com/prestosql/presto/files/3899964/presto-to-es-log.txt)


```

**Comment by ebyhr** [comment]
Going to close this issue since #4165 was merged.

**Comment by hqisog** [comment]
hi, this issue was solved?

**Comment by hqisog** [comment]
@ebyhr
