### ISSUE TITLE
TestTablePartitioningInsertInto.selectFromPartitionedNation is flaky

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#2278]
Example failure

```
CI / product-tests (config-cdh5, suite-1)
```

```
2019-12-15T00:29:51.9135598Z 2019-12-15 06:14:51 INFO: FAILURE     /    io.prestosql.tests.hive.TestTablePartitioningInsertInto.selectFromPartitionedNation (Groups: smoke) took 3.8 seconds
2019-12-15T00:29:51.9145260Z 2019-12-15 06:14:51 SEVERE: Failure cause:
2019-12-15T00:29:51.9145400Z java.lang.AssertionError: 
2019-12-15T00:29:51.9145486Z Expecting:
2019-12-15T00:29:51.9145583Z  <0L>
2019-12-15T00:29:51.9145681Z to be equal to:
2019-12-15T00:29:51.9145991Z  <10L>
2019-12-15T00:29:51.9146083Z but was not.
2019-12-15T00:29:51.9146209Z 	at io.prestosql.tests.hive.TestTablePartitioningInsertInto.testQuerySplitsNumber(TestTablePartitioningInsertInto.java:84)
2019-12-15T00:29:51.9146464Z 	at io.prestosql.tests.hive.TestTablePartitioningInsertInto.selectFromPartitionedNation(TestTablePartitioningInsertInto.java:61)
2019-12-15T00:29:51.9146594Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2019-12-15T00:29:51.9146694Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2019-12-15T00:29:51.9146824Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2019-12-15T00:29:51.9146946Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2019-12-15T00:29:51.9147066Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2019-12-15T00:29:51.9147188Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2019-12-15T00:29:51.9147287Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2019-12-15T00:29:51.9147404Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2019-12-15T00:29:51.9147530Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2019-12-15T00:29:51.9147655Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2019-12-15T00:29:51.9147758Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2019-12-15T00:29:51.9147884Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2019-12-15T00:29:51.9147999Z 	at java.lang.Thread.run(Thread.java:748)
2019-12-15T00:29:51.9148054Z 
```

**Comment by findepi** [comment]
Sometimes the "expected" is different too:
```
2019-12-15T08:41:08.2171393Z 2019-12-15 14:26:08 INFO: FAILURE     /    io.prestosql.tests.hive.TestTablePartitioningInsertInto.selectFromPartitionedNation (Groups: smoke) took 4.5 seconds
2019-12-15T08:41:08.2182871Z 2019-12-15 14:26:08 SEVERE: Failure cause:
2019-12-15T08:41:08.2183054Z java.lang.AssertionError: 
2019-12-15T08:41:08.2183163Z Expecting:
2019-12-15T08:41:08.2189426Z  <0L>
2019-12-15T08:41:08.2189756Z to be equal to:
2019-12-15T08:41:08.2191256Z  <15L>
2019-12-15T08:41:08.2191367Z but was not.
2019-12-15T08:41:08.2191494Z 	at io.prestosql.tests.hive.TestTablePartitioningInsertInto.testQuerySplitsNumber(TestTablePartitioningInsertInto.java:84)
2019-12-15T08:41:08.2191667Z 	at io.prestosql.tests.hive.TestTablePartitioningInsertInto.selectFromPartitionedNation(TestTablePartitioningInsertInto.java:63)
...
```

**Comment by findepi** [comment]
https://github.com/prestosql/presto/pull/2368/checks?check_run_id=369865028

**Comment by findepi** [comment]
failed on master -- https://github.com/prestosql/presto/runs/370121222

**Comment by findepi** [comment]
https://github.com/prestosql/presto/pull/2373/checks?check_run_id=371458065
