### ISSUE TITLE
Flaky tests due to major GC stop the world

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#2279]

**Comment by findepi** [comment]
```
CI / product-tests (config-empty, suite-1)
```

```
2019-12-15T13:30:49.6073217Z 2019-12-15 19:15:49 INFO: [411 of 437] sql_tests.testcases.window_functions.rangeUnbounded (Groups: window)
2019-12-15T13:30:59.6699767Z 2019-12-15 19:15:59 INFO: FAILURE     /    sql_tests.testcases.window_functions.rangeUnbounded (Groups: window) took 10.0 seconds
2019-12-15T13:30:59.6846661Z 2019-12-15 19:15:59 SEVERE: Failure cause:
2019-12-15T13:30:59.6852964Z io.prestosql.tempto.query.QueryExecutionException: java.sql.SQLException: Error executing query
2019-12-15T13:30:59.6853247Z 	at io.prestosql.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:115)
2019-12-15T13:30:59.6867373Z 	at io.prestosql.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:83)
2019-12-15T13:30:59.6872390Z 	at io.prestosql.tempto.internal.convention.sql.SqlQueryConventionBasedTest.runTestQuery(SqlQueryConventionBasedTest.java:118)
2019-12-15T13:30:59.6872564Z 	at io.prestosql.tempto.internal.convention.sql.SqlQueryConventionBasedTest.test(SqlQueryConventionBasedTest.java:101)
2019-12-15T13:30:59.6878535Z 	at io.prestosql.tempto.internal.convention.ConventionBasedTestProxyGenerator$ConventionBasedTestProxy.test(ConventionBasedTestProxyGenerator.java:121)
2019-12-15T13:30:59.6882016Z 	at io.prestosql.tempto.window_functions.rangeUnbounded(Unknown Source)
2019-12-15T13:30:59.6886016Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2019-12-15T13:30:59.6889340Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2019-12-15T13:30:59.6893796Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2019-12-15T13:30:59.6894156Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2019-12-15T13:30:59.6901258Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2019-12-15T13:30:59.6910618Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2019-12-15T13:30:59.6912279Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2019-12-15T13:30:59.6912414Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2019-12-15T13:30:59.6923177Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2019-12-15T13:30:59.6932902Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2019-12-15T13:30:59.6938270Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2019-12-15T13:30:59.6941026Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2019-12-15T13:30:59.6941301Z 	at java.lang.Thread.run(Thread.java:748)
2019-12-15T13:30:59.6946023Z Caused by: java.sql.SQLException: Error executing query
2019-12-15T13:30:59.6951775Z 	at io.prestosql.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:274)
2019-12-15T13:30:59.6956996Z 	at io.prestosql.jdbc.PrestoStatement.execute(PrestoStatement.java:227)
2019-12-15T13:30:59.6957120Z 	at io.prestosql.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:123)
2019-12-15T13:30:59.6961496Z 	at io.prestosql.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:108)
2019-12-15T13:30:59.6965688Z 	... 18 more
2019-12-15T13:30:59.6971762Z Caused by: java.io.UncheckedIOException: java.net.SocketTimeoutException: timeout
2019-12-15T13:30:59.6971919Z 	at io.prestosql.jdbc.$internal.client.JsonResponse.execute(JsonResponse.java:154)
2019-12-15T13:30:59.6979556Z 	at io.prestosql.jdbc.$internal.client.StatementClientV1.<init>(StatementClientV1.java:132)
2019-12-15T13:30:59.6981716Z 	at io.prestosql.jdbc.$internal.client.StatementClientFactory.newStatementClient(StatementClientFactory.java:24)
2019-12-15T13:30:59.6989301Z 	at io.prestosql.jdbc.QueryExecutor.startQuery(QueryExecutor.java:46)
2019-12-15T13:30:59.7152243Z 	at io.prestosql.jdbc.PrestoConnection.startQuery(PrestoConnection.java:699)
2019-12-15T13:30:59.7152432Z 	at io.prestosql.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:239)
2019-12-15T13:30:59.7155844Z 	... 21 more
2019-12-15T13:30:59.7162177Z Caused by: java.net.SocketTimeoutException: timeout
2019-12-15T13:30:59.7166711Z 	at io.prestosql.jdbc.$internal.okio.Okio$4.newTimeoutException(Okio.java:230)
2019-12-15T13:30:59.7166833Z 	at io.prestosql.jdbc.$internal.okio.AsyncTimeout.exit(AsyncTimeout.java:285)
2019-12-15T13:30:59.7170923Z 	at io.prestosql.jdbc.$internal.okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
2019-12-15T13:30:59.7173590Z 	at io.prestosql.jdbc.$internal.okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
2019-12-15T13:30:59.7176899Z 	at io.prestosql.jdbc.$internal.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
2019-12-15T13:30:59.7182919Z 	at io.prestosql.jdbc.$internal.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
2019-12-15T13:30:59.7183131Z 	at io.prestosql.jdbc.$internal.okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:187)
2019-12-15T13:30:59.7187558Z 	at io.prestosql.jdbc.$internal.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
2019-12-15T13:30:59.7189161Z 	at io.prestosql.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-12-15T13:30:59.7193657Z 	at io.prestosql.jdbc.$internal.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
2019-12-15T13:30:59.7193875Z 	at io.prestosql.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-12-15T13:30:59.7194019Z 	at io.prestosql.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-12-15T13:30:59.7195318Z 	at io.prestosql.jdbc.$internal.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
2019-12-15T13:30:59.7195561Z 	at io.prestosql.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-12-15T13:30:59.7196841Z 	at io.prestosql.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-12-15T13:30:59.7197005Z 	at io.prestosql.jdbc.$internal.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
2019-12-15T13:30:59.7197122Z 	at io.prestosql.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-12-15T13:30:59.7197283Z 	at io.prestosql.jdbc.$internal.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
2019-12-15T13:30:59.7197450Z 	at io.prestosql.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-12-15T13:30:59.7201992Z 	at io.prestosql.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-12-15T13:30:59.7202199Z 	at io.prestosql.jdbc.$internal.client.OkHttpUtil.lambda$userAgent$0(OkHttpUtil.java:65)
2019-12-15T13:30:59.7202328Z 	at io.prestosql.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-12-15T13:30:59.7202497Z 	at io.prestosql.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-12-15T13:30:59.7202670Z 	at io.prestosql.jdbc.$internal.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
2019-12-15T13:30:59.7203904Z 	at io.prestosql.jdbc.$internal.okhttp3.RealCall.execute(RealCall.java:77)
2019-12-15T13:30:59.7204091Z 	at io.prestosql.jdbc.$internal.client.JsonResponse.execute(JsonResponse.java:131)
2019-12-15T13:30:59.7204201Z 	... 26 more
2019-12-15T13:30:59.7205162Z Caused by: java.net.SocketTimeoutException
2019-12-15T13:30:59.7205329Z 	at sun.nio.ch.SocketAdaptor$SocketInputStream.read(SocketAdaptor.java:211)
2019-12-15T13:30:59.7209380Z 	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
2019-12-15T13:30:59.7209510Z 	at io.prestosql.jdbc.$internal.okio.Okio$2.read(Okio.java:139)
2019-12-15T13:30:59.7209969Z 	at io.prestosql.jdbc.$internal.okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
2019-12-15T13:30:59.7215268Z 	... 49 more
2019-12-15T13:30:59.7215322Z 
2019-12-15T13:30:59.9941720Z 2019-12-15 19:15:59 INFO: [412 of 437] sql_tests.testcases.window_functions.rankFunctionsImplicitExplicitFrame (Groups: window)
2019-12-15T13:31:00.0714737Z presto-master_1       | 2019-12-15T19:16:00.037+0545	ERROR	Announcer-0	io.airlift.discovery.client.Announcer	Expected service announcement after 8000.00ms, but announcement was delayed 15.02s
2019-12-15T13:31:00.0782307Z presto-master_1       | 2019-12-15T19:16:00.077+0545	INFO	Service Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 660881ms, stopped 10406ms: 921.25MB -> 879.40MB
2019-12-15T13:31:00.2488765Z 2019-12-15 19:16:00 INFO: SUCCESS
```

**Comment by sopel39** [comment]
Could it be leak?

**Comment by electrum** [comment]
This collection didn't free very much:
```
Major GC: application 660881ms, stopped 10406ms: 921.25MB -> 879.40MB

**Comment by sopel39** [comment]
Looking at the query:
```
select orderkey, discount,
dense_rank() over (order by discount),
rank() over (order by discount range between unbounded preceding and current row)
from tpch.tiny.lineitem where partkey = 272
```
it limits the input data, but maybe not enough.
BTW: why Presto only has 1GB of heap in these tests?

**Comment by kokosing** [comment]
> BTW: why Presto only has 1GB of heap in these tests?

It was designed to run travis where we had to split RAM into several docker components. Maybe we could raise the bar now for Presto.

**Comment by findepi** [comment]
https://github.com/prestosql/presto/pull/2373/checks?check_run_id=369927537

**Comment by findepi** [comment]
Hopefully obsolete.
