### ISSUE TITLE
Spurious startup failure due to JMX agent automatic port allocation

### ISSUE THREAD

**Issue by kokosing** [prestosql/presto#2386]
https://github.com/prestosql/presto/pull/2372/checks?check_run_id=368884462

https://pipelines.actions.githubusercontent.com/sJrKZtZsjYLeyqPixYxcTJp8fX9YNlwyJbmEGSC0oymXVDSpbK/_apis/pipelines/1/runs/1344/signedlogcontent/29?urlExpires=2020-01-02T09%3A32%3A52.2707900Z&urlSigningMethod=HMACV1&urlSignature=FYc0YjWhoKkCRYK057fX1ZYJ8%2B3OosefNSk5dYSmxEk%3D

```
parallelism for committing or aborting a transaction
2019-12-31T10:26:33.7040836Z presto-worker-2_1     | 2019-12-31T16:11:33.703+0545	INFO	main	org.eclipse.jetty.util.ssl.SslContextFactory	x509=X509@217235f5(docker.cluster,h=[],w=[docker.cluster]) for SslContextFactory@4b41587d[provider=null,keyStore=file:///docker/presto-product-tests/conf/presto/etc/docker.cluster.jks,trustStore=null]
2019-12-31T10:26:34.3297345Z presto-worker-1_1     | 2019-12-31T16:11:34.328+0545	INFO	main	org.eclipse.jetty.util.ssl.SslContextFactory	x509=X509@217235f5(docker.cluster,h=[],w=[docker.cluster]) for SslContextFactory@4b41587d[provider=null,keyStore=file:///docker/presto-product-tests/conf/presto/etc/docker.cluster.jks,trustStore=null]
2019-12-31T10:26:35.1911021Z presto-worker-2_1     | 2019-12-31T16:11:35.190+0545	INFO	Attach Listener	stderr	Error: Exception thrown by the agent 
2019-12-31T10:26:35.2019089Z presto-worker-2_1     | 2019-12-31T16:11:35.201+0545	INFO	Attach Listener	stderr	: java.rmi.server.ExportException: Port already in use: 38343; nested exception is: 
2019-12-31T10:26:35.2019740Z presto-worker-2_1     | 	java.net.BindException: Address already in use (Bind failed)
2019-12-31T10:26:35.2039419Z presto-worker-2_1     | 2019-12-31T16:11:35.203+0545	INFO	Attach Listener	stderr	jdk.internal.agent.AgentConfigurationError: java.rmi.server.ExportException: Port already in use: 38343; nested exception is: 
2019-12-31T10:26:35.2039982Z presto-worker-2_1     | 	java.net.BindException: Address already in use (Bind failed)
2019-12-31T10:26:35.2047187Z presto-worker-2_1     | 2019-12-31T16:11:35.204+0545	INFO	Attach Listener	stderr		at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap.startRemoteConnectorServer(ConnectorBootstrap.java:491)
2019-12-31T10:26:35.2054357Z presto-worker-2_1     | 2019-12-31T16:11:35.204+0545	INFO	Attach Listener	stderr		at jdk.management.agent/jdk.internal.agent.Agent.startRemoteManagementAgent(Agent.java:388)
2019-12-31T10:26:35.2096639Z presto-worker-2_1     | 2019-12-31T16:11:35.208+0545	INFO	Attach Listener	stderr	Caused by: java.rmi.server.ExportException: Port already in use: 38343; nested exception is: 
2019-12-31T10:26:35.2097588Z presto-worker-2_1     | 	java.net.BindException: Address already in use (Bind failed)
2019-12-31T10:26:35.2106308Z presto-worker-2_1     | 2019-12-31T16:11:35.210+0545	INFO	Attach Listener	stderr		at java.rmi/sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:335)
2019-12-31T10:26:35.2110568Z presto-worker-2_1     | 2019-12-31T16:11:35.210+0545	INFO	Attach Listener	stderr		at java.rmi/sun.rmi.transport.tcp.TCPTransport.exportObject(TCPTransport.java:243)
2019-12-31T10:26:35.2117460Z presto-worker-2_1     | 2019-12-31T16:11:35.211+0545	INFO	Attach Listener	stderr		at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.exportObject(TCPEndpoint.java:411)
2019-12-31T10:26:35.2130931Z presto-worker-2_1     | 2019-12-31T16:11:35.212+0545	INFO	Attach Listener	stderr		at java.rmi/sun.rmi.transport.LiveRef.exportObject(LiveRef.java:147)
2019-12-31T10:26:35.2173026Z presto-worker-2_1     | 2019-12-31T16:11:35.216+0545	INFO	Attach Listener	stderr		at java.rmi/sun.rmi.server.UnicastServerRef.exportObject(UnicastServerRef.java:234)
2019-12-31T10:26:35.2177130Z presto-worker-2_1     | 2019-12-31T16:11:35.217+0545	INFO	Attach Listener	stderr		at java.rmi/sun.rmi.registry.RegistryImpl.setup(RegistryImpl.java:220)
2019-12-31T10:26:35.2181170Z presto-worker-2_1     | 2019-12-31T16:11:35.217+0545	INFO	Attach Listener	stderr		at java.rmi/sun.rmi.registry.RegistryImpl.<init>(RegistryImpl.java:180)
2019-12-31T10:26:35.2196881Z presto-worker-2_1     | 2019-12-31T16:11:35.219+0545	INFO	Attach Listener	stderr		at jdk.management.agent/sun.management.jmxremote.SingleEntryRegistry.<init>(SingleEntryRegistry.java:49)
2019-12-31T10:26:35.2253015Z presto-worker-2_1     | 2019-12-31T16:11:35.224+0545	INFO	Attach Listener	stderr		at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap.exportMBeanServer(ConnectorBootstrap.java:836)
2019-12-31T10:26:35.2257174Z presto-worker-2_1     | 2019-12-31T16:11:35.225+0545	INFO	Attach Listener	stderr		at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap.startRemoteConnectorServer(ConnectorBootstrap.java:479)
2019-12-31T10:26:35.2274709Z presto-worker-2_1     | 2019-12-31T16:11:35.227+0545	INFO	Attach Listener	stderr		... 1 more
2019-12-31T10:26:35.2279790Z presto-worker-2_1     | 2019-12-31T16:11:35.227+0545	INFO	Attach Listener	stderr	Caused by: java.net.BindException: Address already in use (Bind failed)
2019-12-31T10:26:35.2289018Z presto-worker-2_1     | 2019-12-31T16:11:35.228+0545	INFO	Attach Listener	stderr		at java.base/java.net.PlainSocketImpl.socketBind(Native Method)
2019-12-31T10:26:35.2293432Z presto-worker-2_1     | 2019-12-31T16:11:35.228+0545	INFO	Attach Listener	stderr		at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:436)
2019-12-31T10:26:35.2297284Z presto-worker-2_1     | 2019-12-31T16:11:35.229+0545	INFO	Attach Listener	stderr		at java.base/java.net.ServerSocket.bind(ServerSocket.java:395)
2019-12-31T10:26:35.2334436Z presto-worker-2_1     | 2019-12-31T16:11:35.232+0545	INFO	Attach Listener	stderr		at java.base/java.net.ServerSocket.<init>(ServerSocket.java:257)
2019-12-31T10:26:35.2341208Z presto-worker-2_1     | 2019-12-31T16:11:35.233+0545	INFO	Attach Listener	stderr		at java.base/java.net.ServerSocket.<init>(ServerSocket.java:149)
2019-12-31T10:26:35.2345358Z presto-worker-2_1     | 2019-12-31T16:11:35.233+0545	INFO	Attach Listener	stderr		at java.rmi/sun.rmi.transport.tcp.TCPDirectSocketFactory.createServerSocket(TCPDirectSocketFactory.java:45)
2019-12-31T10:26:35.2349503Z presto-worker-2_1     | 2019-12-31T16:11:35.234+0545	INFO	Attach Listener	stderr		at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newServerSocket(TCPEndpoint.java:666)
2019-12-31T10:26:35.2353500Z presto-worker-2_1     | 2019-12-31T16:11:35.234+0545	INFO	Attach Listener	stderr		at java.rmi/sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:324)
2019-12-31T10:26:35.2357450Z presto-worker-2_1     | 2019-12-31T16:11:35.235+0545	INFO	Attach Listener	stderr		... 10 more
2019-12-31T10:26:35.3343411Z presto-worker-2_1     | 2019-12-31T16:11:35.333+0545	INFO	main	io.airlift.jmx.JmxAgent	JMX agent started and listening on presto-worker-2:44013
2019-12-31T10:26:35.4200349Z presto-worker-2_1     | 2019-12-31T16:11:35.401+0545	ERROR	main	io.prestosql.server.PrestoServer	Unable to create injector, see the following errors:
2019-12-31T10:26:35.4201448Z presto-worker-2_1     | 
2019-12-31T10:26:35.4202735Z presto-worker-2_1     | 1) Error injecting constructor, com.sun.tools.attach.AttachOperationFailedException: java.lang.RuntimeException: jdk.internal.agent.AgentConfigurationError: java.rmi.server.ExportException: Port already in use: 38343; nested exception is: 	java.net.BindException: Address already in use (Bind failed)
2019-12-31T10:26:35.4203617Z presto-worker-2_1     |   at io.airlift.jmx.JmxAgent9.<init>(JmxAgent9.java:47)
2019-12-31T10:26:35.4204410Z presto-worker-2_1     |   at io.airlift.jmx.JmxModule.configure(JmxModule.java:55)
2019-12-31T10:26:35.4206154Z presto-worker-2_1     |   while locating io.airlift.jmx.JmxAgent9
2019-12-31T10:26:35.4206890Z presto-worker-2_1     |   while locating io.airlift.jmx.JmxAgent
2019-12-31T10:26:35.4207599Z presto-worker-2_1     |     for the 1st parameter of io.airlift.jmx.JmxModule$JmxAnnouncementProvider.setJmxAgent(JmxModule.java:68)
2019-12-31T10:26:35.4208462Z presto-worker-2_1     |   while locating io.airlift.jmx.JmxModule$JmxAnnouncementProvider
2019-12-31T10:26:35.4209494Z presto-worker-2_1     |   while locating io.airlift.discovery.client.ServiceAnnouncement annotated with @com.google.inject.internal.Element(setName=,uniqueId=132, type=MULTIBINDER, keyType=)
2019-12-31T10:26:35.4210190Z presto-worker-2_1     |   while locating java.util.Set<io.airlift.discovery.client.ServiceAnnouncement>
2019-12-31T10:26:35.4210827Z presto-worker-2_1     |     for the 2nd parameter of io.airlift.discovery.client.Announcer.<init>(Announcer.java:68)
2019-12-31T10:26:35.4212254Z presto-worker-2_1     |   at io.airlift.discovery.client.DiscoveryModule.configure(DiscoveryModule.java:64)
2019-12-31T10:26:35.4212926Z presto-worker-2_1     |   while locating io.airlift.discovery.client.Announcer
2019-12-31T10:26:35.4213612Z presto-worker-2_1     |     for the 2nd parameter of io.airlift.discovery.client.DiscoveryModule.createMergingServiceSelectorFactory(DiscoveryModule.java:122)
2019-12-31T10:26:35.4214376Z presto-worker-2_1     |   at io.airlift.discovery.client.DiscoveryModule.createMergingServiceSelectorFactory(DiscoveryModule.java:122)
2019-12-31T10:26:35.4215030Z presto-worker-2_1     |   while locating io.airlift.discovery.client.MergingServiceSelectorFactory
2019-12-31T10:26:35.4215906Z presto-worker-2_1     |   at io.airlift.discovery.client.DiscoveryModule.configure(DiscoveryModule.java:73)
2019-12-31T10:26:35.4216611Z presto-worker-2_1     |   while locating io.airlift.discovery.client.ServiceSelectorFactory
2019-12-31T10:26:35.4217634Z presto-worker-2_1     |     for the 1st parameter of io.airlift.discovery.client.ServiceSelectorProvider.setServiceSelectorFactory(ServiceSelectorProvider.java:50)
2019-12-31T10:26:35.4218447Z presto-worker-2_1     |   at io.airlift.event.client.HttpEventModule.configure(HttpEventModule.java:43)
2019-12-31T10:26:35.4219209Z presto-worker-2_1     | 
2019-12-31T10:26:35.4219741Z presto-worker-2_1     | 1 error
2019-12-31T10:26:35.4220348Z presto-worker-2_1     | com.google.inject.CreationException: Unable to create injector, see the following errors:
2019-12-31T10:26:35.4220896Z presto-worker-2_1     | 
2019-12-31T10:26:35.4221976Z presto-worker-2_1     | 1) Error injecting constructor, com.sun.tools.attach.AttachOperationFailedException: java.lang.RuntimeException: jdk.internal.agent.AgentConfigurationError: java.rmi.server.ExportException: Port already in use: 38343; nested exception is: 	java.net.BindException: Address already in use (Bind failed)
2019-12-31T10:26:35.4222616Z presto-worker-2_1     |   at io.airlift.jmx.JmxAgent9.<init>(JmxAgent9.java:47)
2019-12-31T10:26:35.4223196Z presto-worker-2_1     |   at io.airlift.jmx.JmxModule.configure(JmxModule.java:55)
2019-12-31T10:26:35.4223779Z presto-worker-2_1     |   while locating io.airlift.jmx.JmxAgent9
2019-12-31T10:26:35.4224345Z presto-worker-2_1     |   while locating io.airlift.jmx.JmxAgent
2019-12-31T10:26:35.4224980Z presto-worker-2_1     |     for the 1st parameter of io.airlift.jmx.JmxModule$JmxAnnouncementProvider.setJmxAgent(JmxModule.java:68)
2019-12-31T10:26:35.4225710Z presto-worker-2_1     |   while locating io.airlift.jmx.JmxModule$JmxAnnouncementProvider
2019-12-31T10:26:35.4226484Z presto-worker-2_1     |   while locating io.airlift.discovery.client.ServiceAnnouncement annotated with @com.google.inject.internal.Element(setName=,uniqueId=132, type=MULTIBINDER, keyType=)
2019-12-31T10:26:35.4227124Z presto-worker-2_1     |   while locating java.util.Set<io.airlift.discovery.client.ServiceAnnouncement>
2019-12-31T10:26:35.4227758Z presto-worker-2_1     |     for the 2nd parameter of io.airlift.discovery.client.Announcer.<init>(Announcer.java:68)
2019-12-31T10:26:35.4228386Z presto-worker-2_1     |   at io.airlift.discovery.client.DiscoveryModule.configure(DiscoveryModule.java:64)
2019-12-31T10:26:35.4229121Z presto-worker-2_1     |   while locating io.airlift.discovery.client.Announcer
2019-12-31T10:26:35.4229805Z presto-worker-2_1     |     for the 2nd parameter of io.airlift.discovery.client.DiscoveryModule.createMergingServiceSelectorFactory(DiscoveryModule.java:122)
2019-12-31T10:26:35.4230500Z presto-worker-2_1     |   at io.airlift.discovery.client.DiscoveryModule.createMergingServiceSelectorFactory(DiscoveryModule.java:122)
2019-12-31T10:26:35.4231139Z presto-worker-2_1     |   while locating io.airlift.discovery.client.MergingServiceSelectorFactory
2019-12-31T10:26:35.4231762Z presto-worker-2_1     |   at io.airlift.discovery.client.DiscoveryModule.configure(DiscoveryModule.java:73)
2019-12-31T10:26:35.4232368Z presto-worker-2_1     |   while locating io.airlift.discovery.client.ServiceSelectorFactory
2019-12-31T10:26:35.4233055Z presto-worker-2_1     |     for the 1st parameter of io.airlift.discovery.client.ServiceSelectorProvider.setServiceSelectorFactory(ServiceSelectorProvider.java:50)
2019-12-31T10:26:35.4234009Z presto-worker-2_1     |   at io.airlift.event.client.HttpEventModule.configure(HttpEventModule.java:43)
2019-12-31T10:26:35.4240433Z presto-worker-2_1     | 
2019-12-31T10:26:35.4241048Z presto-worker-2_1     | 1 error
2019-12-31T10:26:35.4241699Z presto-worker-2_1     | 	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
2019-12-31T10:26:35.4242380Z presto-worker-2_1     | 	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:178)
2019-12-31T10:26:35.4243009Z presto-worker-2_1     | 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
2019-12-31T10:26:35.4243618Z presto-worker-2_1     | 	at com.google.inject.Guice.createInjector(Guice.java:87)
2019-12-31T10:26:35.4245526Z presto-worker-2_1     | 	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:245)
2019-12-31T10:26:35.4245943Z presto-worker-2_1     | 	at io.prestosql.server.PrestoServer.run(PrestoServer.java:122)
2019-12-31T10:26:35.4246395Z presto-worker-2_1     | 	at io.prestosql.$gen.Presto_327_53_g3c62c26____20201231_102613_1.run(Unknown Source)
2019-12-31T10:26:35.4247029Z presto-worker-2_1     | 	at io.prestosql.server.PrestoServer.main(PrestoServer.java:72)
2019-12-31T10:26:35.4248208Z presto-worker-2_1     | Caused by: com.sun.tools.attach.AttachOperationFailedException: java.lang.RuntimeException: jdk.internal.agent.AgentConfigurationError: java.rmi.server.ExportException: Port already in use: 38343; nested exception is: 	java.net.BindException: Address already in use (Bind failed)
2019-12-31T10:26:35.4249097Z presto-worker-2_1     | 	at jdk.attach/sun.tools.attach.VirtualMachineImpl.execute(VirtualMachineImpl.java:224)
2019-12-31T10:26:35.4249612Z presto-worker-2_1     | 	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.executeCommand(HotSpotVirtualMachine.java:309)
2019-12-31T10:26:35.4250062Z presto-worker-2_1     | 	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.executeJCmd(HotSpotVirtualMachine.java:291)
2019-12-31T10:26:35.4250531Z presto-worker-2_1     | 	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.startManagementAgent(HotSpotVirtualMachine.java:237)
2019-12-31T10:26:35.4250950Z presto-worker-2_1     | 	at io.airlift.jmx.JmxAgent9.startJmxAgent(JmxAgent9.java:116)
2019-12-31T10:26:35.4251484Z presto-worker-2_1     | 	at io.airlift.jmx.JmxAgent9.<init>(JmxAgent9.java:88)
2019-12-31T10:26:35.4251967Z presto-worker-2_1     | 	at io.airlift.jmx.JmxAgent9$$FastClassByGuice$$52a284ef.newInstance(<generated>)
2019-12-31T10:26:35.4252433Z presto-worker-2_1     | 	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
2019-12-31T10:26:35.4252881Z presto-worker-2_1     | 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
2019-12-31T10:26:35.4253323Z presto-worker-2_1     | 	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
2019-12-31T10:26:35.4253762Z presto-worker-2_1     | 	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
2019-12-31T10:26:35.4254240Z presto-worker-2_1     | 	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
2019-12-31T10:26:35.4254663Z presto-worker-2_1     | 	at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
2019-12-31T10:26:35.4255148Z presto-worker-2_1     | 	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
2019-12-31T10:26:35.4255622Z presto-worker-2_1     | 	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
2019-12-31T10:26:35.4256070Z presto-worker-2_1     | 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
2019-12-31T10:26:35.4256519Z presto-worker-2_1     | 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
2019-12-31T10:26:35.4256976Z presto-worker-2_1     | 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
2019-12-31T10:26:35.4257391Z presto-worker-2_1     | 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
2019-12-31T10:26:35.4257858Z presto-worker-2_1     | 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
2019-12-31T10:26:35.4258287Z presto-worker-2_1     | 	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
2019-12-31T10:26:35.4258728Z presto-worker-2_1     | 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
2019-12-31T10:26:35.4259174Z presto-worker-2_1     | 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
2019-12-31T10:26:35.4259595Z presto-worker-2_1     | 	at com.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:82)
2019-12-31T10:26:35.4260039Z presto-worker-2_1     | 	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:147)
2019-12-31T10:26:35.4260480Z presto-worker-2_1     | 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:124)
2019-12-31T10:26:35.4260925Z presto-worker-2_1     | 	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
2019-12-31T10:26:35.4261501Z presto-worker-2_1     | 	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
2019-12-31T10:26:35.4261961Z presto-worker-2_1     | 	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
2019-12-31T10:26:35.4262393Z presto-worker-2_1     | 	at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
2019-12-31T10:26:35.4262867Z presto-worker-2_1     | 	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
2019-12-31T10:26:35.4263335Z presto-worker-2_1     | 	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
2019-12-31T10:26:35.4263870Z presto-worker-2_1     | 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
2019-12-31T10:26:35.4264343Z presto-worker-2_1     | 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
2019-12-31T10:26:35.4264787Z presto-worker-2_1     | 	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:60)
2019-12-31T10:26:35.4265234Z presto-worker-2_1     | 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
2019-12-31T10:26:35.4265695Z presto-worker-2_1     | 	at com.google.inject.internal.RealMultibinder$RealMultibinderProvider.doProvision(RealMultibinder.java:198)
2019-12-31T10:26:35.4266533Z presto-worker-2_1     | 	at com.google.inject.internal.RealMultibinder$RealMultibinderProvider.doProvision(RealMultibinder.java:151)
2019-12-31T10:26:35.4266995Z presto-worker-2_1     | 	at com.google.inject.internal.InternalProviderInstanceBindingImpl$Factory$1.call(InternalProviderInstanceBindingImpl.java:120)
2019-12-31T10:26:35.4267463Z presto-worker-2_1     | 	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
2019-12-31T10:26:35.4267878Z presto-worker-2_1     | 	at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
2019-12-31T10:26:35.4268323Z presto-worker-2_1     | 	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
2019-12-31T10:26:35.4268769Z presto-worker-2_1     | 	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
2019-12-31T10:26:35.4269222Z presto-worker-2_1     | 	at com.google.inject.internal.InternalProviderInstanceBindingImpl$Factory.get(InternalProviderInstanceBindingImpl.java:115)
2019-12-31T10:26:35.4269632Z presto-worker-2_1     | 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
2019-12-31T10:26:35.4270059Z presto-worker-2_1     | 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
2019-12-31T10:26:35.4270477Z presto-worker-2_1     | 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
2019-12-31T10:26:35.4270890Z presto-worker-2_1     | 	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
2019-12-31T10:26:35.4271300Z presto-worker-2_1     | 	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
2019-12-31T10:26:35.4271734Z presto-worker-2_1     | 	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
2019-12-31T10:26:35.4272139Z presto-worker-2_1     | 	at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
2019-12-31T10:26:35.4272582Z presto-worker-2_1     | 	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
2019-12-31T10:26:35.4273023Z presto-worker-2_1     | 	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
2019-12-31T10:26:35.4274179Z presto-worker-2_1     | 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
2019-12-31T10:26:35.4276545Z presto-worker-2_1     | 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
2019-12-31T10:26:35.4276985Z presto-worker-2_1     | 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
2019-12-31T10:26:35.4277396Z presto-worker-2_1     | 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
2019-12-31T10:26:35.4277832Z presto-worker-2_1     | 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
2019-12-31T10:26:35.4278255Z presto-worker-2_1     | 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
2019-12-31T10:26:35.4278819Z presto-worker-2_1     | 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
2019-12-31T10:26:35.4279264Z presto-worker-2_1     | 	at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:173)
2019-12-31T10:26:35.4279735Z presto-worker-2_1     | 	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
2019-12-31T10:26:35.4280218Z presto-worker-2_1     | 	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.access$300(InternalProviderInstanceBindingImpl.java:139)
2019-12-31T10:26:35.4280691Z presto-worker-2_1     | 	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory$1.call(InternalProviderInstanceBindingImpl.java:169)
2019-12-31T10:26:35.4281155Z presto-worker-2_1     | 	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
2019-12-31T10:26:35.4281566Z presto-worker-2_1     | 	at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
2019-12-31T10:26:35.4282021Z presto-worker-2_1     | 	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
2019-12-31T10:26:35.4282447Z presto-worker-2_1     | 	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
2019-12-31T10:26:35.4282908Z presto-worker-2_1     | 	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:164)
2019-12-31T10:26:35.4283351Z presto-worker-2_1     | 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
2019-12-31T10:26:35.4283756Z presto-worker-2_1     | 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
2019-12-31T10:26:35.4284201Z presto-worker-2_1     | 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
2019-12-31T10:26:35.4284583Z presto-worker-2_1     | 	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
2019-12-31T10:26:35.4285016Z presto-worker-2_1     | 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
2019-12-31T10:26:35.4285422Z presto-worker-2_1     | 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
2019-12-31T10:26:35.4285853Z presto-worker-2_1     | 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
2019-12-31T10:26:35.4286272Z presto-worker-2_1     | 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
2019-12-31T10:26:35.4286672Z presto-worker-2_1     | 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
2019-12-31T10:26:35.4287091Z presto-worker-2_1     | 	at com.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:82)
2019-12-31T10:26:35.4287649Z presto-worker-2_1     | 	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:147)
2019-12-31T10:26:35.4329582Z presto-worker-2_1     | 	at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:101)
2019-12-31T10:26:35.4330074Z presto-worker-2_1     | 	at com.google.inject.internal.Initializer$InjectableReference.get(Initializer.java:245)
2019-12-31T10:26:35.4330499Z presto-worker-2_1     | 	at com.google.inject.internal.Initializer.injectAll(Initializer.java:140)
2019-12-31T10:26:35.4330962Z presto-worker-2_1     | 	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:176)
2019-12-31T10:26:35.4331324Z presto-worker-2_1     | 	... 6 more
2019-12-31T10:26:35.4331650Z presto-worker-2_1     | 
2019-12-31T10:26:35.4331974Z presto-worker-2_1     | 
2019-12-31T10:26:35.6227767Z presto-worker-1_1     | 2019-12-31T16:11:35.621+0545	INFO	main	io.airlift.jmx.JmxAgent	JMX agent started and listening on presto-worker-1:36457
2019-12-31T10:26:36.7638427Z presto-worker-1_1     | 2019-12-31T16:11:36.762+0545	INFO	main	org.eclipse.jetty.util.ssl.SslContextFactory	x509=X509@55296b50(docker.cluster,h=[],w=[docker.cluster]) for SslContextFactory@60591e1b[provider=null,keyStore=file:///docker/presto-product-tests/conf/presto/etc/docker.cluster.jks,trustStore=null]
2019-12-31T10:26:36.8221225Z presto-master_1       | 2019-12-31T16:11:36.821+0545	INFO	main	org.eclipse.jetty.util.ssl.SslContextFactory	x509=X509@39449465(docker.cluster,h=[],w=[docker.cluster]) for SslContextFactory@6e3dd5ce[provider=null,keyStore=file:///docker/presto-product-tests/conf/presto/etc/docker.cluster.jks,trustStore=null]
2019-12-31T10:26:37.0948507Z presto-worker-1_1     | 2019-12-31T16:11:37.093+0545	INFO	main	org.eclipse.jetty.util.ssl.SslContextFactory	x509=X509@27e199ce(docker.cluster,h=[],w=[docker.cluster]) for SslContextFactory@1c3b6963[provider=null,keyStore=file:///docker/presto-product-tests/conf/presto/etc/docker.cluster.jks,trustStore=null]
2019-12-31T10:26:39.9086992Z common_presto-worker-2_1 exited with code 1
2
```

**Comment by kokosing** [comment]
Maybe there is a race and port was allocated by something else.

**Comment by findepi** [comment]
We should try to remove:
https://github.com/airlift/airlift/blob/e739d06ae27a6de059a0b5c56b06ba8c69ae712e/jmx/src/main/java/io/airlift/jmx/NetUtils.java#L26-L37

it's proven to be racy.

**Comment by s2lomon** [comment]
It seems like another case of same issue: https://github.com/prestosql/presto/pull/3166/checks?check_run_id=528368553

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/601171986

cc @martint

**Comment by findepi** [comment]
It looks a bit like Java 11 or JmxAgent9 are more prone. Or GitHub Action's environment. We use same JmxAgent-ish approach since _ever_, yet I don't think I already got very familiar with them, and they are happening not very rarely this year.
