### ISSUE TITLE
Enhance serdeexception log to pin point exact failure

### ISSUE THREAD

**Issue by meghapthakkar** [prestosql/presto#2460]
Example where this log would be useful:

Query:
select *
from hive.information_schema.columns c
where c.table_schema != 'information_schema' 
LIMIT 100

Failure message (due to corrupt schema):

2019-04-12T18:27:04.334Z ERROR   SplitRunner-184-797948  com.facebook.presto.execution.executor.TaskExecutor Error processing Split 20190412_182551_18118_2rvw8.1.0-0 InformationSchemaSplit{tableHandle=hive:information_schema:columns, filters={}, addresses=[10.79.5.177:8081]} (start = 6.76413448971468E8, wall = 73014 ms, cpu = 0 ms, wait = 0 ms, calls = 1)
java.lang.RuntimeException: error initializing deserializer: org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe
    at com.facebook.presto.hive.HiveUtil.initializeDeserializer(HiveUtil.java:421)
    at com.facebook.presto.hive.HiveUtil.getDeserializer(HiveUtil.java:378)
    at com.facebook.presto.hive.HiveUtil.getTableObjectInspector(HiveUtil.java:340)
    at com.facebook.presto.hive.HiveUtil.getTableStructFields(HiveUtil.java:357)

With 1000s of tables in metastore it is difficult to pinpoint the exact table where failure is happening. A log line showing exact schema name for failure is useful.

**Comment by findepi** [comment]
> With 1000s of tables in metastore it is difficult to pinpoint the exact table where failure is happening. 

I totally agree

> A log line showing exact schema name for failure is useful.

thanks for self-assigning the issue!
before you start work, can you just double check with Presto 327 that we still don't provide actionable error message?
There was also some PR to avoid failures  during certain `information_schema` queries, so this may also help (or not) in your case.
