### ISSUE TITLE
Add sybase connector

### ISSUE THREAD

**Issue by tooptoop4** [prestosql/presto#2481]

**Comment by academy-codex** [comment]
I'll take this up. Have already implemented it.

**Comment by academy-codex** [comment]
> I'll take this up. Have already implemented it.

@findepi Can you assign this to me ?

**Comment by tooptoop4** [comment]
@academy-codex what driver do you use? I first tried jconn4.jar but hit "JZ0SB: Parameter index out of range: 1" error, reading online I saw getSchema is not implemented in JConn - 
io.prestosql.spi.PrestoException: JZ0SB: Parameter index out of range: 1.
	at io.prestosql.plugin.jdbc.BaseJdbcClient.listSchemas(BaseJdbcClient.java:191)
	at io.prestosql.plugin.jdbc.BaseJdbcClient.getSchemaNames(BaseJdbcClient.java:168)
	at io.prestosql.plugin.jdbc.jmx.StatisticsAwareJdbcClient.lambda$getSchemaNames$1(StatisticsAwareJdbcClient.java:81)
	at io.prestosql.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
	at io.prestosql.plugin.jdbc.jmx.StatisticsAwareJdbcClient.getSchemaNames(StatisticsAwareJdbcClient.java:81)
	at io.prestosql.plugin.jdbc.ForwardingJdbcClient.getSchemaNames(ForwardingJdbcClient.java:63)
	at io.prestosql.plugin.jdbc.ForwardingJdbcClient.getSchemaNames(ForwardingJdbcClient.java:63)
	at io.prestosql.plugin.jdbc.JdbcMetadata.listSchemaNames(JdbcMetadata.java:75)
	at io.prestosql.metadata.MetadataManager.listSchemaNames(MetadataManager.java:291)
	at io.prestosql.metadata.MetadataListing.listSchemas(MetadataListing.java:58)
	at io.prestosql.connector.informationschema.InformationSchemaPageSource.addSchemataRecords(InformationSchemaPageSource.java:300)
	at io.prestosql.connector.informationschema.InformationSchemaPageSource.buildPages(InformationSchemaPageSource.java:214)
	at io.prestosql.connector.informationschema.InformationSchemaPageSource.getNextPage(InformationSchemaPageSource.java:171)
	at io.prestosql.operator.TableScanOperator.getOutput(TableScanOperator.java:287)
	at io.prestosql.operator.Driver.processInternal(Driver.java:379)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_327_21_gae536e0_dirty____20200129_230107_2.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: JZ0SB: Parameter index out of range: 1.
	at com.sybase.jdbc4.jdbc.ErrorMessage.raiseError(Unknown Source)
	at com.sybase.jdbc4.jdbc.ParamManager.int(Unknown Source)
	at com.sybase.jdbc4.jdbc.ParamManager.doSetParam(Unknown Source)
	at com.sybase.jdbc4.jdbc.ParamManager.setParam(Unknown Source)
	at com.sybase.jdbc4.jdbc.SybPreparedStatement.a(Unknown Source)
	at com.sybase.jdbc4.jdbc.SybPreparedStatement.a(Unknown Source)
	at com.sybase.jdbc4.jdbc.SybPreparedStatement.setString(Unknown Source)
	at com.sybase.jdbc4.jdbc.SybDatabaseMetaData.a(Unknown Source)
	at com.sybase.jdbc4.jdbc.SybDatabaseMetaData.getSchemas(Unknown Source)
	at io.prestosql.plugin.jdbc.BaseJdbcClient.listSchemas(BaseJdbcClient.java:179)
	... 24 more

then I tried jtds-1.3.1.jar and hit below error
java.lang.AbstractMethodError: undefined
	at net.sourceforge.jtds.jdbc.JtdsDatabaseMetaData.getSchemas(JtdsDatabaseMetaData.java:3587)
	at io.prestosql.plugin.jdbc.BaseJdbcClient.listSchemas(BaseJdbcClient.java:179)
	at io.prestosql.plugin.jdbc.BaseJdbcClient.getSchemaNames(BaseJdbcClient.java:168)
	at io.prestosql.plugin.jdbc.jmx.StatisticsAwareJdbcClient.lambda$getSchemaNames$1(StatisticsAwareJdbcClient.java:81)
	at io.prestosql.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
	at io.prestosql.plugin.jdbc.jmx.StatisticsAwareJdbcClient.getSchemaNames(StatisticsAwareJdbcClient.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.prestosql.plugin.base.util.LoggingInvocationHandler.handleInvocation(LoggingInvocationHandler.java:60)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:86)
	at com.sun.proxy.$Proxy186.getSchemaNames(Unknown Source)
	at io.prestosql.plugin.jdbc.ForwardingJdbcClient.getSchemaNames(ForwardingJdbcClient.java:63)
	at io.prestosql.plugin.jdbc.ForwardingJdbcClient.getSchemaNames(ForwardingJdbcClient.java:63)
	at io.prestosql.plugin.jdbc.JdbcMetadata.listSchemaNames(JdbcMetadata.java:75)
	at io.prestosql.metadata.MetadataManager.listSchemaNames(MetadataManager.java:291)
	at io.prestosql.metadata.MetadataListing.listSchemas(MetadataListing.java:58)
	at io.prestosql.connector.informationschema.InformationSchemaPageSource.addSchemataRecords(InformationSchemaPageSource.java:300)
	at io.prestosql.connector.informationschema.InformationSchemaPageSource.buildPages(InformationSchemaPageSource.java:214)
	at io.prestosql.connector.informationschema.InformationSchemaPageSource.getNextPage(InformationSchemaPageSource.java:171)
	at io.prestosql.operator.TableScanOperator.getOutput(TableScanOperator.java:287)
	at io.prestosql.operator.Driver.processInternal(Driver.java:379)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_327_21_gae536e0_dirty____20200131_015521_2.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
From reading https://stackoverflow.com/questions/41231750/abstractmethoderror-with-jtds-jdbc-driver-on-tomcat-8 I thought connectionProperties.setProperty("validationQuery", "select 1"); would solve but not sure where to inject it.

other downside of jtds is it does not support Sybase IQ

**Comment by tooptoop4** [comment]
@academy-codex gentle ping

**Comment by academy-codex** [comment]
Hey @tooptoop4. I am using sajdbc.  See my fork today.

**Comment by tooptoop4** [comment]
where is that fork @academy-codex ?

**Comment by academy-codex** [comment]
@tooptoop4 You can see the PR I have made.

**Comment by kkond** [comment]
any update on this issue?

**Comment by codekaust** [comment]
Any updates on this issue @academy-codex @tooptoop4 ?
This connector will be of great help.

**Comment by tooptoop4** [comment]
https://github.com/prestosql/presto/pull/3105 is better than this

**Comment by andrii29** [comment]
For those who want to query Sybase from Trino, **tds_fdw** can be used as a workaround: https://github.com/tds-fdw/tds_fdw

**Dockerfile**
```
FROM postgres:17

RUN apt-get update && apt-get install -y \
    freetds-dev \
    freetds-common \
    freetds-bin \
    build-essential \
    libsybdb5 \
    git \
    curl \
    postgresql-server-dev-17 \
    && rm -rf "/var/lib/apt/lists/*"

RUN git clone https://github.com/tds-fdw/tds_fdw.git /tmp/tds_fdw \
    && cd /tmp/tds_fdw \
    && git checkout v2.0.5 \
    && make USE_PGXS=1 && make USE_PGXS=1 install \
    && rm -rf /tmp/tds_fdw

RUN mkdir -p /etc/freetds/
COPY locales.conf /etc/freetds/locales.conf

EXPOSE 5432
```

**locales.conf**  (adjust if your date format differs from the example)
```
[default]
        date format = %b %e %Y %I:%M:%S.%z%p
```

Build the image and verify connectivity:
```
docker build -t tds-fwd .
docker run --rm -it tds-fwd bash 
# Try connecting via the CLI
tsql -H
tsql -H CHANGEME_HOST -p CHANGEME_PORT -U CHANGEME_USER -P CHANGEME_PASSWORD -D CHANGEME_DB

SELECT DB_NAME();

GO

SELECT TOP 10 * FROM CHANGEME_TABLE;

GO

```
Once the connection is successful and you can run queries against the database, start PostgreSQL:
```
docker run -d --name tds-fwd -e POSTGRES_USER=fwd -e POSTGRES_PASSWORD=fwd -e POSTGRES_DB=fwd -e PGDATA=/var/lib/postgresql/data  -v ./data:/var/lib/postgresql/data -p 5432:5432 tds-fwd

docker exec -it tds-fwd psql -U fwd

CREATE EXTENSION IF NOT EXISTS tds_fdw;

CREATE SERVER sybase_server
FOREIGN DATA WRAPPER tds_fdw
OPTIONS (
    servername 'CHANGEME_SERVER',   -- Replace with your host
    port '2645',             -- Replace with the Sybase port
    database 'dev',          -- Sybase database
    tds_version '5.0',       -- Adjust depending on your Sybase version; we tried multiple values until we found one that worked with our server
    msg_handler 'notice',
    use_remote_estimate '0'   -- Disable remote estimates (they made queries very slow in our environment)
);

CREATE USER MAPPING FOR fwd
SERVER sybase_server
OPTIONS (
    username 'CHANGEME_USER',
    password 'CHANGEME_PASSWORD'
);

-- Column definitions must match the schema of the remote Sybase table
CREATE FOREIGN TABLE public.test (
    id bigint NOT NULL
)
SERVER sybase_server
OPTIONS (
    table_name 'Test'  -- Sybase table (can include schema if required, e.g. schema.table)
);

SELECT * FROM test LIMIT 10;
```
Now configure a Trino catalog using the PostgreSQL connector.
**sybase.properties**
```
connector.name=postgresql
connection-url=jdbc:postgresql://${ENV:TDS_FWD_HOST}:5432/${ENV:TDS_FWD_DATABASE}
connection-user=${ENV:TDS_FWD_USER}
connection-password=${ENV:TDS_FWD_PASSWORD}
case-insensitive-name-matching=true
```
Try selecting data from the table created above. If everything works, you can make additional tables available to Trino using:
```
USE sybase.public;

SHOW TABLES;

SELECT * from test;

CALL sybase.system.execute(query =>
    'CREATE FOREIGN TABLE public.test2 (
        id bigint NOT NULL
    )
    SERVER sybase_server
    OPTIONS (
        table_name ''Test''
    )'
);
```
To remove a table:
```
CALL sybase.system.execute(query => 'DROP FOREIGN TABLE public.test2');
```
