### ISSUE TITLE
Fix flaky ryuk docker container used in tests

### ISSUE THREAD

**Issue by kokosing** [prestosql/presto#2598]
https://pipelines.actions.githubusercontent.com/sJrKZtZsjYLeyqPixYxcTJp8fX9YNlwyJbmEGSC0oymXVDSpbK/_apis/pipelines/1/runs/3112/signedlogcontent/15?urlExpires=2020-01-23T16%3A35%3A17.4598166Z&urlSigningMethod=HMACV1&urlSignature=aM4nXPvDclM%2Fy%2Bccl0wrqzIXme0efQX9znEwC6VfiNs%3D
```
2020-01-21T18:08:07.7437590Z + presto-product-tests-launcher/target/presto-product-tests-launcher-329-SNAPSHOT-executable.jar test run --environment singlenode-hive-impersonation -- -g storage_formats,hdfs_impersonation
2020-01-21T18:08:08.2245946Z 2020-01-21T18:08:08.221Z	INFO	main	io.airlift.log.Logging	Logging to stderr
2020-01-21T18:08:08.2257117Z 2020-01-21T18:08:08.225Z	INFO	main	Bootstrap	Loading configuration
2020-01-21T18:08:08.4997517Z 2020-01-21T18:08:08.499Z	INFO	main	Bootstrap	Initializing logging
2020-01-21T18:08:08.7160277Z 2020-01-21T18:08:08.715Z	INFO	main	Bootstrap	PROPERTY  DEFAULT  RUNTIME  DESCRIPTION
2020-01-21T18:08:08.8938423Z 2020-01-21T18:08:08.893Z	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle starting...
2020-01-21T18:08:08.8945762Z 2020-01-21T18:08:08.894Z	INFO	main	io.airlift.bootstrap.LifeCycleManager	Life cycle startup complete. System ready.
2020-01-21T18:08:08.8994563Z 2020-01-21T18:08:08.899Z	INFO	main	io.prestosql.tests.product.launcher.cli.TestRun	Pruning old environment(s)
2020-01-21T18:08:08.9001073Z 2020-01-21T18:08:08.899Z	INFO	main	io.prestosql.tests.product.launcher.env.Environments	Shutting down previous containers
2020-01-21T18:08:09.5734902Z 2020-01-21T18:08:09.571Z	INFO	main	org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy	Found docker client settings from environment
2020-01-21T18:08:09.5735889Z 2020-01-21T18:08:09.573Z	INFO	main	org.testcontainers.dockerclient.DockerClientProviderStrategy	Found Docker environment with Environment variables, system properties and defaults. Resolved dockerHost=unix:///var/run/docker.sock
2020-01-21T18:08:09.7611077Z 2020-01-21T18:08:09.760Z	INFO	main	org.testcontainers.DockerClientFactory	Docker host IP address is localhost
2020-01-21T18:08:09.7845887Z 2020-01-21T18:08:09.784Z	INFO	main	org.testcontainers.DockerClientFactory	Connected to docker: 
2020-01-21T18:08:09.7846088Z   Server Version: 3.0.8
2020-01-21T18:08:09.7846184Z   API Version: 1.40
2020-01-21T18:08:09.7846258Z   Operating System: Ubuntu 18.04.3 LTS
2020-01-21T18:08:09.7846353Z   Total Memory: 6945 MB
2020-01-21T18:08:09.8134493Z 2020-01-21T18:08:09.813Z	WARN	main	org.testcontainers.utility.RegistryAuthLocator	Failure when attempting to lookup auth config (dockerImageName: quay.io/testcontainers/ryuk:0.2.3, configFile: /home/runner/.docker/config.json. Falling back to docker-java default behaviour. Exception message: /home/runner/.docker/config.json (No such file or directory)
2020-01-21T18:08:24.9519108Z 2020-01-21T18:08:24.949Z	ERROR	tc-okhttp-stream-2065718717	com.github.dockerjava.core.async.ResultCallbackTemplate	Error during callback
2020-01-21T18:08:24.9519759Z com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"Get https://quay.io/v2/testcontainers/ryuk/manifests/0.2.3: Get https://quay.io/v2/auth?scope=repository%3Atestcontainers%2Fryuk%3Apull&service=quay.io: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"}
2020-01-21T18:08:24.9520466Z 
2020-01-21T18:08:24.9521265Z 	at org.testcontainers.dockerclient.transport.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:285)
2020-01-21T18:08:24.9521793Z 	at org.testcontainers.dockerclient.transport.okhttp.OkHttpInvocationBuilder.lambda$executeAndStream$3(OkHttpInvocationBuilder.java:301)
2020-01-21T18:08:24.9522053Z 	at java.lang.Thread.run(Thread.java:748)
2020-01-21T18:08:24.9522214Z 
2020-01-21T18:08:24.9522558Z 
2020-01-21T18:08:24.9560616Z 2020-01-21T18:08:24.952Z	INFO	main	io.prestosql.tests.product.launcher.cli.TestRun	Done, cleaning up
2020-01-21T18:08:24.9561263Z 2020-01-21T18:08:24.952Z	INFO	main	io.prestosql.tests.product.launcher.env.Environments	Shutting down previous containers
2020-01-21T18:08:24.9978943Z 2020-01-21T18:08:24.997Z	ERROR	main	io.prestosql.tests.product.launcher.cli.TestRun	Failure: com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"Get https://quay.io/v2/testcontainers/ryuk/manifests/0.2.3: Get https://quay.io/v2/auth?scope=repository%3Atestcontainers%2Fryuk%3Apull&service=quay.io: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"}
2020-01-21T18:08:24.9979724Z 
2020-01-21T18:08:24.9980942Z 2020-01-21T18:08:24.997Z	ERROR	main	Bootstrap	Uncaught exception in thread main
2020-01-21T18:08:24.9981431Z com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"Get https://quay.io/v2/testcontainers/ryuk/manifests/0.2.3: Get https://quay.io/v2/auth?scope=repository%3Atestcontainers%2Fryuk%3Apull&service=quay.io: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"}
2020-01-21T18:08:24.9982115Z 
2020-01-21T18:08:24.9982425Z 	at org.testcontainers.dockerclient.transport.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:285)
2020-01-21T18:08:24.9982752Z 	at org.testcontainers.dockerclient.transport.okhttp.OkHttpInvocationBuilder.lambda$executeAndStream$3(OkHttpInvocationBuilder.java:301)
2020-01-21T18:08:24.9983054Z 	at java.lang.Thread.run(Thread.java:748)
2020-01-21T18:08:24.9983272Z 
2020-01-21T18:08:24.9983508Z 
2020-01-21T18:08:25.0261120Z + suite_exit_code=1
```

**Comment by findepi** [comment]
@kokosing please create an issue in testcontainers too

@bsideup is it possible to override & pull the image from docker hub?
(we already depend on docker hub, so if it's down, we won't run anyway)

**Comment by bsideup** [comment]
@findepi sure, see https://www.testcontainers.org/features/configuration/#customizing-ryuk-resource-reaper ( `ryuk.container.image` )

although I am surprised that it was that unstable for you. Does it happen regularly?

**Comment by findepi** [comment]
@bsideup thanks for quick feedback! Do you also provide "official" images on docker hub?

no, it doesn't happen regularly.

**Comment by bsideup** [comment]
@findepi we don't since the name was taken by a random guy who refused to give it :(

**Comment by findepi** [comment]
https://github.com/prestosql/presto/pull/3787

-- we are making a copy of the image; would be nice to have a copy that you maintain on Docker Hub
or you can redirect users to use our copy :)

**Comment by findepi** [comment]
https://github.com/prestosql/presto/pull/3787

-- we are making a copy of the image; @bsideup  would be nice to have a copy that you maintain on Docker Hub
or you can redirect users to use our copy :)

**Comment by bsideup** [comment]
@findepi we're working on it :)

**Comment by tovbinm** [comment]
So the solution is to maintain a separate image on dockerhub? Who own's the Ryuk? Can the move to there?

**Comment by bsideup** [comment]
It is Testcontainers' sub-project:
http://github.com/testcontainers/moby-ryuk

Yes, the image will eventually (ETA: this week) be moved to Docker Hub.

**Comment by tovbinm** [comment]
thank you @bsideup

**Comment by findepi** [comment]
> Yes, the image will eventually (ETA: this week) be moved to Docker Hub.

@bsideup thanks! let me know when the release is out so we can remove the override

**Comment by findepi** [comment]
> let me know when the release is out so we can remove the override

i created https://github.com/prestosql/presto/issues/3816 as a followup
