### ISSUE TITLE
Why does 'order by' need more memory than entire dataset size? 

### ISSUE THREAD

**Issue by tooptoop4** [prestosql/presto#2600]
Update: issue affects prestosql 328 version too: Query exceeded per-node user memory limit of 26GB [Allocated: 26.00GB, Delta: 53.54MB, Top Consumers: {OrderByOperator=20.97GB, MergeSortedPages=5.02GB, GenericSpiller=620kB}]

Originally raised as https://github.com/prestodb/presto/issues/13846

Got below error after running 'select * from hive.redact order by time_stamp desc'
Data is hudi parquet (hive - STORED AS INPUTFORMAT 'com.uber.hoodie.hadoop.HoodieInputFormat' ) on s3.

But entire dataset is only 3.5GB (85 columns wide), why does OrderByOperator need > 26GB ??
```
Query 20200124_104025_00000_6hc6x failed: Query exceeded per-node user memory limit of 18GB [Allocated: 18.00GB, Delta: 49.11MB, Top Consumers: {OrderByOperator=13.32GB, MergeSortedPages=4.68GB, GenericSpiller=640kB}]
io.prestosql.ExceededMemoryLimitException: Query exceeded per-node user memory limit of 18GB [Allocated: 18.00GB, Delta: 49.11MB, Top Consumers: {OrderByOperator=13.32GB, MergeSortedPages=4.68GB, GenericSpiller=640kB}]
        at io.prestosql.ExceededMemoryLimitException.exceededLocalUserMemoryLimit(ExceededMemoryLimitException.java:40)
        at io.prestosql.memory.QueryContext.enforceUserMemoryLimit(QueryContext.java:332)
        at io.prestosql.memory.QueryContext.updateUserMemory(QueryContext.java:137)
        at io.prestosql.memory.QueryContext$QueryMemoryReservationHandler.reserveMemory(QueryContext.java:313)
        at io.prestosql.memory.context.RootAggregatedMemoryContext.updateBytes(RootAggregatedMemoryContext.java:37)
        at io.prestosql.memory.context.ChildAggregatedMemoryContext.updateBytes(ChildAggregatedMemoryContext.java:38)
        at io.prestosql.memory.context.ChildAggregatedMemoryContext.updateBytes(ChildAggregatedMemoryContext.java:38)
        at io.prestosql.memory.context.ChildAggregatedMemoryContext.updateBytes(ChildAggregatedMemoryContext.java:38)
        at io.prestosql.memory.context.ChildAggregatedMemoryContext.updateBytes(ChildAggregatedMemoryContext.java:38)
        at io.prestosql.memory.context.SimpleLocalMemoryContext.setBytes(SimpleLocalMemoryContext.java:66)
        at io.prestosql.operator.OperatorContext$InternalLocalMemoryContext.setBytes(OperatorContext.java:662)
        at io.prestosql.util.MergeSortedPages.lambda$pageWithPositions$4(MergeSortedPages.java:148)
        at io.prestosql.operator.WorkProcessorUtils.lambda$flatMap$4(WorkProcessorUtils.java:245)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.prestosql.operator.WorkProcessorUtils$2.process(WorkProcessorUtils.java:125)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
        at io.prestosql.operator.WorkProcessorUtils.access$000(WorkProcessorUtils.java:37)
        at io.prestosql.operator.WorkProcessorUtils$YieldingProcess.process(WorkProcessorUtils.java:181)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.prestosql.operator.WorkProcessorUtils$YieldingIterator.computeNext(WorkProcessorUtils.java:80)
        at io.prestosql.operator.WorkProcessorUtils$YieldingIterator.computeNext(WorkProcessorUtils.java:66)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
        at io.prestosql.operator.OrderByOperator.getOutput(OrderByOperator.java:272)
        at io.prestosql.operator.Driver.processInternal(Driver.java:379)
        at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
        at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
        at io.prestosql.operator.Driver.processFor(Driver.java:276)
        at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
        at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
        at io.prestosql.$gen.Presto_328__0_220____20200124_104010_2.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

[{"queryId":"20200124_104025_00000_6hc6x","session":{"queryId":"20200124_104025_00000_6hc6x","transactionId":"46a13db6-f5c8-40f6-8502-c8456037888d","clientTransactionSupport":true,"user":"x","source":"presto-cli","path":{},"timeZoneKey":0,"locale":"en_US","remoteUserAddress":"127.0.0.1","userAgent":"StatementClientV1/0.220","clientTags":[],"clientCapabilities":["PATH"],"resourceEstimates":{},"startTime":1579862425894,"systemProperties":{},"catalogProperties":{},"unprocessedCatalogProperties":{},"roles":{},"preparedStatements":{}},"resourceGroupId":["global"],"state":"FAILED","memoryPool":"general","scheduled":true,"self":"http://xx:4033/v1/query/20200124_104025_00000_6hc6x","query":"select * from redact order by time_stamp desc","queryStats":{"createTime":"2020-01-24T10:40:26.077Z","endTime":"2020-01-24T10:41:45.990Z","queuedTime":"10.79ms","elapsedTime":"1.33m","executionTime":"1.32m","totalDrivers":47,"queuedDrivers":0,"runningDrivers":1,"completedDrivers":37,"rawInputDataSize":"796.67MB","rawInputPositions":11624437,"cumulativeUserMemory":6.180398658869E12,"userMemoryReservation":"18GB","totalMemoryReservation":"30.73GB","peakUserMemoryReservation":"18.00GB","peakTotalMemoryReservation":"32.36GB","totalCpuTime":"2.67m","totalScheduledTime":"3.48m","fullyBlocked":true,"blockedReasons":[],"progressPercentage":78.72340425531915},"errorType":"INSUFFICIENT_RESOURCES","errorCode":{"code":131079,"name":"EXCEEDED_LOCAL_MEMORY_LIMIT","type":"INSUFFICIENT_RESOURCES"}}]

"queryStats" : {
    "createTime" : "2020-01-24T10:40:26.077Z",
    "executionStartTime" : "2020-01-24T10:40:26.993Z",
    "lastHeartbeat" : "2020-01-24T10:41:46.012Z",
    "endTime" : "2020-01-24T10:41:45.990Z",
    "elapsedTime" : "1.33m",
    "queuedTime" : "10.79ms",
    "resourceWaitingTime" : "904.60ms",
    "dispatchingTime" : "1.29ms",
    "executionTime" : "1.32m",
    "analysisTime" : "907.60ms",
    "planningTime" : "573.78ms",
    "finishingTime" : "0.00ns",
    "totalTasks" : 3,
    "runningTasks" : 0,
    "completedTasks" : 3,
    "totalDrivers" : 47,
    "queuedDrivers" : 0,
    "runningDrivers" : 1,
    "blockedDrivers" : 9,
    "completedDrivers" : 37,
    "cumulativeUserMemory" : 6.180398658869E12,
    "userMemoryReservation" : "18GB",
    "revocableMemoryReservation" : "12.73GB",
    "totalMemoryReservation" : "30.73GB",
    "peakUserMemoryReservation" : "18.00GB",
    "peakRevocableMemoryReservation" : "32.07GB",
    "peakTotalMemoryReservation" : "32.36GB",
    "peakTaskUserMemory" : "18.00GB",
    "peakTaskRevocableMemory" : "32.07GB",
    "peakTaskTotalMemory" : "32.10GB",
    "scheduled" : true,
    "totalScheduledTime" : "3.48m",
    "totalCpuTime" : "2.67m",
    "totalBlockedTime" : "11.09m",
    "fullyBlocked" : true,
    "blockedReasons" : [ ],
    "physicalInputDataSize" : "796.67MB",
    "physicalInputPositions" : 11624437,
    "internalNetworkInputDataSize" : "8.09GB",
    "internalNetworkInputPositions" : 11624437,
    "rawInputDataSize" : "796.67MB",
    "rawInputPositions" : 11624437,
    "processedInputDataSize" : "9.16GB",
    "processedInputPositions" : 11624437,
    "outputDataSize" : "0B",
    "outputPositions" : 0,
    "physicalWrittenDataSize" : "0B",
    "stageGcStatistics" : [ {
      "stageId" : 0,
      "tasks" : 1,
      "fullGcTasks" : 0,
      "minFullGcSec" : 0,
      "maxFullGcSec" : 0,
      "totalFullGcSec" : 0,
      "averageFullGcSec" : 0
    }, {
      "stageId" : 1,
      "tasks" : 1,
      "fullGcTasks" : 0,
      "minFullGcSec" : 0,
      "maxFullGcSec" : 0,
      "totalFullGcSec" : 0,
      "averageFullGcSec" : 0
    }, {
      "stageId" : 2,
      "tasks" : 1,
      "fullGcTasks" : 0,
      "minFullGcSec" : 0,
      "maxFullGcSec" : 0,
      "totalFullGcSec" : 0,
      "averageFullGcSec" : 0
    } ]

EXPLAIN ANALYZE VERBOSE output:
```
Fragment 1 [ROUND_ROBIN]
CPU: 59.84s, Scheduled: 1.04m, Input: 4650726 rows (3.17GB); per task: avg.: 4650726.00 std.dev.: 0.00, Output: 4650726 rows (3.17GB)
Output layout: [redact_cols]
Output partitioning: SINGLE []
Stage Execution Strategy: UNGROUPED_EXECUTION
- LocalMerge[date_parse DESC_NULLS_LAST] => [redact_colsredact_cols]
CPU: 29.64s (18.67%), Scheduled: 31.61s (22.04%), Output: 4650726 rows (3.17GB)
Input avg.: 290670.38 rows, Input std.dev.: 162.59%
- PartialSort[date_parse DESC_NULLS_LAST] => [redact_colsredact_cols]
CPU: 28.11s (17.71%), Scheduled: 28.62s (19.95%), Output: 4650726 rows (3.17GB)
Input avg.: 290670.38 rows, Input std.dev.: 162.59%
- RemoteSource[2] => [redact_colsredact_cols]
CPU: 1.61s (1.01%), Scheduled: 1.76s (1.23%), Output: 4650726 rows (3.17GB)
Input avg.: 290670.38 rows, Input std.dev.: 162.59%

Fragment 2 [SOURCE]
CPU: 1.40m, Scheduled: 1.56m, Input: 4650726 rows (3.66GB); per task: avg.: 4650726.00 std.dev.: 0.00, Output: 4650726 rows (3.17GB)
Output layout: [redact_cols]
Output partitioning: ROUND_ROBIN []
Stage Execution Strategy: UNGROUPED_EXECUTION
- ScanProject[table = TableHandle{redact_cols]
CPU: 1.40m (53.00%), Scheduled: 1.61m (67.42%), Output: 4650726 rows (3.17GB)
Input avg.: 221463.14 rows, Input std.dev.: 190.76%
date_parse := "date_parse"(NULLIF("time_stamp", 'unknown'), '%Y-%m-%d %H:%i:%s.%f')
date_parse_9 := "date_parse"(NULLIF("dateorigin", 'unknown'), '%Y-%m-%d %H:%i:%s.%f')
date_parse_13 := "date_parse"(NULLIF("datedestination", 'unknown'), '%Y-%m-%d %H:%i:%s.%f')
date_parse_18 := "date_parse"(NULLIF("forecastedeta", 'unknown'), '%Y-%m-%d %H:%i:%s.%f')
date_parse_27 := "date_parse"(NULLIF("etaorigin", 'unknown'), '%Y-%m-%d %H:%i:%s.%f')
date_parse_28 := "date_parse"(NULLIF("startorigin", 'unknown'), '%Y-%m-%d %H:%i:%s.%f')
date_parse_29 := "date_parse"(NULLIF("endorigin", 'unknown'), '%Y-%m-%d %H:%i:%s.%f')
date_parse_34 := "date_parse"(NULLIF("startdestination", 'unknown'), '%Y-%m-%d %H:%i:%s.%f')
date_parse_81 := "date_parse"(NULLIF("forecastedorigineta", 'unknown'), '%Y-%m-%d %H:%i:%s.%f')
LAYOUT: redact_cols
unknown:string:-1:PARTITION_KEY
:: [[unknown]]
Input: 4650726 rows (3.66GB), Filtered: 0.00%
```

**Comment by sopel39** [comment]
Related to: https://github.com/prestosql/presto/issues/2610

**Comment by tooptoop4** [comment]
When setting pages-index.eager-compaction-enabled=true the query works:

some stats - 
    "peakRevocableMemoryReservation" : "9.22GB",
    "peakTotalMemoryReservation" : "9.46GB",
    "peakTaskUserMemory" : "9.32GB",
    "peakTaskRevocableMemory" : "9.22GB",
    "peakTaskTotalMemory" : "9.35GB",
    "physicalInputDataSize" : "796.67MB",
    "internalNetworkInputDataSize" : "16.31GB",
    "rawInputDataSize" : "796.67MB",
    "processedInputDataSize" : "9.16GB",
    "outputDataSize" : "9.29GB",
    "physicalWrittenDataSize" : "0B",
      "physicalInputDataSize" : "0B",
      "internalNetworkInputDataSize" : "8.22GB",
      "rawInputDataSize" : "8.22GB",
      "inputDataSize" : "9.29GB",
      "outputDataSize" : "9.29GB",
      "physicalWrittenDataSize" : "0B",
      "spilledDataSize" : "0B"
      "physicalInputDataSize" : "0B",
      "internalNetworkInputDataSize" : "0B",
      "rawInputDataSize" : "0B",
      "inputDataSize" : "9.29GB",
      "outputDataSize" : "9.29GB",
      "physicalWrittenDataSize" : "0B",
      "spilledDataSize" : "0B"
      "physicalInputDataSize" : "0B",
      "internalNetworkInputDataSize" : "8.09GB",
      "rawInputDataSize" : "8.09GB",
      "inputDataSize" : "9.16GB",
      "outputDataSize" : "9.16GB",
      "physicalWrittenDataSize" : "0B",

**Comment by sopel39** [comment]
Fixed via: https://github.com/prestosql/presto/pull/2612

**Comment by fs-rd-anish-dey** [comment]
Even I am facing the same issue on presto 0.227.
how to set pages-index.eager-compaction-enabled=true?
