### ISSUE TITLE
Query fails on NoSuchElementException since 329

### ISSUE THREAD

**Issue by guyco33** [prestosql/presto#2652]
On version `329`:

```
WITH t AS (SELECT * FROM (VALUES (1)) as _(a))
SELECT * FROM t 
WHERE a IS NULL OR a!=1 OR a=1
```
**fails**

```
WITH t AS (SELECT * FROM (VALUES (1)) as _(a))
SELECT * FROM t 
WHERE a IS NULL OR a!=1 OR a=2
```
**succeed**

On version `328` both works

stack trace is:
```
java.util.NoSuchElementException: undefined
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:721)
	at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:747)
	at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042)
	at com.google.common.collect.Iterators.getOnlyElement(Iterators.java:302)
	at com.google.common.collect.Iterables.getOnlyElement(Iterables.java:254)
	at io.prestosql.sql.planner.DomainTranslator$Visitor.visitLogicalBinaryExpression(DomainTranslator.java:408)
	at io.prestosql.sql.planner.DomainTranslator$Visitor.visitLogicalBinaryExpression(DomainTranslator.java:304)
	at io.prestosql.sql.tree.LogicalBinaryExpression.accept(LogicalBinaryExpression.java:88)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.planner.DomainTranslator.fromPredicate(DomainTranslator.java:301)
	at io.prestosql.sql.planner.optimizations.WindowFilterPushDown$Rewriter.visitFilter(WindowFilterPushDown.java:159)
	at io.prestosql.sql.planner.optimizations.WindowFilterPushDown$Rewriter.visitFilter(WindowFilterPushDown.java:83)
	at io.prestosql.sql.planner.plan.FilterNode.accept(FilterNode.java:72)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Collections$2.tryAdvance(Collections.java:4717)
	at java.util.Collections$2.forEachRemaining(Collections.java:4725)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:38)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:22)
	at io.prestosql.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
	at io.prestosql.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:32)
	at io.prestosql.sql.planner.optimizations.WindowFilterPushDown.optimize(WindowFilterPushDown.java:80)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:194)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:183)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:178)
	at io.prestosql.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:393)
	at io.prestosql.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:381)
	at io.prestosql.execution.SqlQueryExecution.start(SqlQueryExecution.java:336)
	at io.prestosql.$gen.Presto_329____20200128_102828_2.run(Unknown Source)
	at io.prestosql.execution.SqlQueryManager.createQuery(SqlQueryManager.java:240)
	at io.prestosql.dispatcher.LocalDispatchQuery.lambda$startExecution$4(LocalDispatchQuery.java:107)
	at io.prestosql.$gen.Presto_329____20200128_102828_2.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Praveen2112** [comment]
I think it is handled in #2656. So closing it. Please feel free to re-open it if it didn't work
