### ISSUE TITLE
Allow disabling referral following in LDAP authenticator

### ISSUE THREAD

**Issue by 360d-io-labs** [prestosql/presto#2667]
Hi all,

PS: I have been writing this issue while debugging and I think that I found the main problem after a while. This not really an issue (except for having a flag to control referral), but it can useful for other people encountering the same king of problem.

We were just trying to update to 329 with our AD configuration that has been ok for the last couple of years, but it seems that a breaking change (By the way it would be great if all breaking change in the configuration were highlighted in the changelog)was introduced.

We were using a simple LDAP membership check with anonymous/direct user binding to our internal Active Directory:
Here is the working config in 328
```
password-authenticator.name=ldap
ldap.url=ldaps://qq.q.grp:636/
ldap.user-bind-pattern=${USER}@qq.q.grp
ldap.user-base-dn=DC=qq,DC=q,DC=grp
ldap.group-auth-pattern=(|(memberOf=CN=users,OU=Data,OU=Applications,OU=Administrative,DC=qq,DC=q,DC=grp)(memberOf=CN=hadministrators,OU=Data,OU=Applications,OU=Administrative,DC=qq,DC=q,DC=grp))```

However since 329 this configuration triggers this part of the code:
```if (!userDistinguishedName.equals(search.next().getNameInNamespace())) {
                    String message = format("Multiple group membership results for user [%s] with different distinguished names", user);
```

Which seems ok based on the new behavior.

So I tried to change it to this based on the documentation (which tested ok against the AD)
```
ldap.group-auth-pattern=(&(sAMAccountName=${USER})(memberOf=CN=administrators,OU=Data,OU=Applications,OU=Administrative,DC=qq,DC=q,DC=grp))
```
Which should be parsed ok by the replaceUser function, and will only return one entry.

However I then get this exception:

```
Caused by java.lang.RuntimeException: Authentication error at io.prestosql.plugin.password.ldap.LdapAuthenticator.authenticateWithUserBind(LdapAuthenticator.java:141)
 at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)

 at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
        at io.prestosql.plugin.password.ldap.LdapAuthenticator.createAuthenticatedPrincipal(LdapAuthenticator.java:114)
        at io.prestosql.server.security.PasswordAuthenticator.authenticate(PasswordAuthenticator.java:65)
        at io.prestosql.server.security.AuthenticationFilter.doFilter(AuthenticationFilter.java:102)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
        at io.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:63)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
        at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:51)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:722)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1307)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:494)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
```

However if I remove the ldap.group-auth-pattern config, I can get authentified. So the problem reside in the behavior with a filter. 

After being able to reset everything on debug mode (was still with the com.facebook flag). I'm seeing this in the log:
`
Password validation successful for user DN [aga@qq.q.grp]
io.prestosql.plugin.password.ldap.LdapAuthenticator     Authentication failed for user [aga], null
`
So great I'm authenticated but it failed. And then I see that in the log:
```
Caused by: javax.naming.CommunicationException: simple bind failed: DomainDnsZones.qq.q.grp:636 [Root exception is javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative DNS name matching DomainDnsZones.qq.q.grp found.]
```

Ok so it seems that now in 329 somehow the LDAP library is following referral which is currently causing an issue with our internal setup (SSL certificate issue in our case, but it was also a DNS issue). 

Would it be possible to have a flag to not follow referral (the previous behavior) ?

By the way in our case we were able to temporary make it work with this flag:
-Dcom.sun.jndi.ldap.object.disableEndpointIdentification=true

**Comment by tooptoop4** [comment]
yea, https://github.com/prestosql/presto/blob/329/presto-password-authenticators/src/main/java/io/prestosql/plugin/password/ldap/LdapAuthenticator.java#L260 should not be hardcoded

**Comment by findepi** [comment]
@360d-io-labs can you please provide more information about why following referrals breaks in your environment?
Ignoring referrals isn't correct, out of the box behavior. Following them seems to conform to the design of the LDAP API.
I would like to better understand under what circumstances this is not the right thing to do.

**Comment by 360d-io-labs** [comment]
This is mainly a DNS issue, when you are not using the AD as you DNS server. You may have side effect when there is a change in the AD forest and you don't reflect this in your local configuration for the referral domain. In most case (when you have one domain), referral doesn't bring any additional information in the authentication process and can be safely disabled.

This problem is well known, for instance here is the same problem for Jira/Jenkins (Jira has a flag for that):
https://jira.atlassian.com/browse/CWD-4310
https://confluence.atlassian.com/jirakb/active-directory-users-fail-to-logon-intermittently-945118456.html
https://issues.jenkins-ci.org/browse/JENKINS-4895

So anyway I won't argue about what should be the default behavior but "follow" seems to be ok, however having it as a configuration parameter may really help with some AD/LDAP setup.

**Comment by findepi** [comment]
@360d-io-labs thanks for the explanation.
So this is not a bug in the code, but you're saying we should be more flexible to cater for misconfigured setups that exists too often in real world. 
I think it's OK to add a boolean flag for this (perhaps `ldap.follow-referrals`).

**Comment by 360d-io-labs** [comment]
Yes exactly you get my point, it will be easier for people encountering this kind of issue rather than having to recompile the whole code to change the value :)

**Comment by tooptoop4** [comment]
should be 3 options (ignore, follow, throw): https://docs.oracle.com/javase/jndi/tutorial/ldap/referral/jndi.html

**Comment by findepi** [comment]
@tooptoop4 i am aware there are 3 options in LDAP code.
This doesn't mean there is a sense to expose them all in Presto.

Actually, i think the flag should be `ldap.ignore-referrals`, so we would either `follow` or `ignore`.
I don't see a value in exposing `throw` to users, do you?
