### ISSUE TITLE
ArithmeticException: integer overflow error for certain Parquet files over 2 GB

### ISSUE THREAD

**Issue by fanglu-wish** [prestosql/presto#2730]
https://github.com/prestosql/presto/blob/d8e8cc768a13355d146e7db14d084caa84409653/presto-parquet/src/main/java/io/prestosql/parquet/DiskRange.java#L68

Got this Exception
```
io.prestosql.spi.PrestoException: Error opening Hive split s3://xxxx/xxxx/000235_0 (offset=0, length=6678975885): integer overflow
	at io.prestosql.plugin.hive.parquet.ParquetPageSourceFactory.createParquetPageSource(ParquetPageSourceFactory.java:251)
	at io.prestosql.plugin.hive.parquet.ParquetPageSourceFactory.createPageSource(ParquetPageSourceFactory.java:129)
	at io.prestosql.plugin.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:188)
	at io.prestosql.plugin.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:108)
	at io.prestosql.plugin.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:91)
	at io.prestosql.plugin.base.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:49)
	at io.prestosql.split.PageSourceManager.createPageSource(PageSourceManager.java:63)
	at io.prestosql.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:240)
	at io.prestosql.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:172)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:148)
	at io.prestosql.operator.Driver.processInternal(Driver.java:379)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_329____20200203_235109_2.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArithmeticException: integer overflow
	at java.lang.Math.toIntExact(Math.java:1011)
	at io.prestosql.parquet.DiskRange.span(DiskRange.java:68)
	at io.prestosql.plugin.hive.parquet.HdfsParquetDataSource.mergeAdjacentDiskRanges(HdfsParquetDataSource.java:244)
	at io.prestosql.plugin.hive.parquet.HdfsParquetDataSource.readSmallDiskRanges(HdfsParquetDataSource.java:170)
	at io.prestosql.plugin.hive.parquet.HdfsParquetDataSource.planRead(HdfsParquetDataSource.java:158)
	at io.prestosql.parquet.reader.ParquetReader.<init>(ParquetReader.java:122)
	at io.prestosql.plugin.hive.parquet.ParquetPageSourceFactory.createParquetPageSource(ParquetPageSourceFactory.java:208)
```

Seems if a parquet file is larger than 2GB, `DiskRange.span` will throw `Interger Overflow`.

How about use toLongExact instead of toIntExact?

**Comment by findepi** [comment]
Changing `DiskRange.length` to long doesn't seem correct, because

1. it will blow at https://github.com/prestosql/presto/blob/6da8d85df9a9534465f545de4a970f7892465b55/presto-hive/src/main/java/io/prestosql/plugin/hive/parquet/HdfsParquetDataSource.java#L282
2. we probably don't want to operate on such large chunk pieces anyway

i think the right approach is to add a condition so that this code does not create such large ranges.
Per 2. above, the 2gb integer limit is not the right one.

**Comment by fanglu-wish** [comment]
Hi,

Thank you for your reply!!! 

`Add a condition` is a better solution.

Put more context here:
Got this issue while running the query `select _arguments from requests_v2 where dt='2020-01-10' and regexp_like(_arguments, '^.*"filterId\\\\\\":\\\\\\"(.*)\\\\\\".*$') limit 10;`

`requests_v2` is a hive table. We added the following `CLUSTERED BY ( _tid)  INTO 1024 BUCKETS` while creating the table.

To confirm whether this issue caused by hive bucket, created another table `requests` without hive bucket.  Reran the same query, and succeeded.

Seems hive bucket may cause the issue.

Best,
Fang

**Comment by tooptoop4** [comment]
Potentially broken by https://github.com/prestosql/presto/pull/1925 from 325 release onwards

**Comment by davigust** [comment]
I'm still getting this error in 341. Has there been a regression?

```
io.prestosql.spi.PrestoException: Error opening Hive split abfs://xxxxxxxx@xxxxxxxx.dfs.core.windows.net/xxxxxxxx/day=2020-10-19/20201019_010801727_suez-859f9f6b9-85zw7 (offset=0, length=67108864): integer overflow
	at io.prestosql.plugin.hive.parquet.ParquetPageSourceFactory.createPageSource(ParquetPageSourceFactory.java:247)
	at io.prestosql.plugin.hive.parquet.ParquetPageSourceFactory.createPageSource(ParquetPageSourceFactory.java:134)
	at io.prestosql.plugin.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:171)
	at io.prestosql.plugin.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:101)
	at io.prestosql.spi.connector.ConnectorPageSourceProvider.createPageSource(ConnectorPageSourceProvider.java:68)
	at io.prestosql.plugin.base.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:66)
	at io.prestosql.split.PageSourceManager.createPageSource(PageSourceManager.java:64)
	at io.prestosql.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:254)
	at io.prestosql.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:182)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:149)
	at io.prestosql.operator.Driver.processInternal(Driver.java:379)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_341____20201027_161202_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by martint** [comment]
@davigust, that seems like a different problem. It's failing in this line, which would indicate the file has a column chunk within a row group that's larger than 2GB. The original problem was when a *file* was larger than 2GB.

```java
DiskRange range = new DiskRange(chunkMetadata.getStartingPos(), toIntExact(chunkMetadata.getTotalSize()));
```

Can you file a separate issue so we can track it and diagnose it further?
