### ISSUE TITLE
Presto throws Exception when accessing transaction table created from Hive

### ISSUE THREAD

**Issue by AbhishekNew** [prestosql/presto#2789]
Created transaction table from Hive( Hive Version 2.3.6 )
```
CREATE TABLE employee (id int, name string, salary int) STORED AS ORC TBLPROPERTIES ('transactional' = 'true');
CREATE TABLE college(clg_id int,clg_name string,clg_loc string) clustered by (clg_id) into 5 buckets stored as orc TBLPROPERTIES('transactional'='true');
INSERT INTO table college values(1,'nec','nlr'),(2,'vit','vlr'),(3,'srm','chen'),(4,'lpu','del'),(5,'stanford','uk'),(6,'JNTUA','atp'),(7,'cambridge','us');
from Hive>
hive> select * from college;
OK
5       stanford        uk
6       JNTUA   atp
1       nec     nlr
7       cambridge       us
2       vit     vlr
3       srm     chen
4       lpu     del
```

But when accessing table from Presto CLI throws Security Exception
```
presto:default> select * from college;
Query 20200211_043159_00001_etp8f failed: For security reasons, the config key metastore.txn.timeout cannot be accessed
Stack Trace
io.prestosql.spi.PrestoException: For security reasons, the config key metastore.txn.timeout cannot be accessed
	at io.prestosql.plugin.hive.metastore.thrift.ThriftHiveMetastore.getConfigValue(ThriftHiveMetastore.java:1618)
	at io.prestosql.plugin.hive.metastore.thrift.BridgingHiveMetastore.getConfigValue(BridgingHiveMetastore.java:400)
	at io.prestosql.plugin.hive.metastore.cache.CachingHiveMetastore.loadConfigValue(CachingHiveMetastore.java:828)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)
	at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:188)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
	at io.prestosql.plugin.hive.metastore.cache.CachingHiveMetastore.get(CachingHiveMetastore.java:240)
	at io.prestosql.plugin.hive.metastore.cache.CachingHiveMetastore.getConfigValue(CachingHiveMetastore.java:823)
	at io.prestosql.plugin.hive.HiveMetastoreClosure.getConfigValue(HiveMetastoreClosure.java:274)
	at io.prestosql.plugin.hive.metastore.SemiTransactionalHiveMetastore.getServerExpectedHeartbeatIntervalMillis(SemiTransactionalHiveMetastore.java:1013)
	at java.util.Optional.orElseGet(Optional.java:267)
	at io.prestosql.plugin.hive.metastore.SemiTransactionalHiveMetastore.lambda$beginQuery$32(SemiTransactionalHiveMetastore.java:996)
	at io.prestosql.plugin.hive.metastore.SemiTransactionalHiveMetastore.getValidWriteIds(SemiTransactionalHiveMetastore.java:1030)
	at io.prestosql.plugin.hive.HiveSplitManager.getSplits(HiveSplitManager.java:222)
	at io.prestosql.spi.connector.classloader.ClassLoaderSafeConnectorSplitManager.getSplits(ClassLoaderSafeConnectorSplitManager.java:50)
	at io.prestosql.split.SplitManager.getSplits(SplitManager.java:86)
	at io.prestosql.sql.planner.DistributedExecutionPlanner$Visitor.visitScanAndFilter(DistributedExecutionPlanner.java:190)
	at io.prestosql.sql.planner.DistributedExecutionPlanner$Visitor.visitTableScan(DistributedExecutionPlanner.java:173)
	at io.prestosql.sql.planner.DistributedExecutionPlanner$Visitor.visitTableScan(DistributedExecutionPlanner.java:150)
	at io.prestosql.sql.planner.plan.TableScanNode.accept(TableScanNode.java:131)
	at io.prestosql.sql.planner.DistributedExecutionPlanner.doPlan(DistributedExecutionPlanner.java:120)
	at io.prestosql.sql.planner.DistributedExecutionPlanner.doPlan(DistributedExecutionPlanner.java:125)
	at io.prestosql.sql.planner.DistributedExecutionPlanner.plan(DistributedExecutionPlanner.java:97)
	at io.prestosql.execution.SqlQueryExecution.planDistribution(SqlQueryExecution.java:431)
	at io.prestosql.execution.SqlQueryExecution.start(SqlQueryExecution.java:337)
	at io.prestosql.$gen.Presto_327____20200210_142917_2.run(Unknown Source)
	at io.prestosql.execution.SqlQueryManager.createQuery(SqlQueryManager.java:240)
	at io.prestosql.dispatcher.LocalDispatchQuery.lambda$startExecution$4(LocalDispatchQuery.java:107)
	at io.prestosql.$gen.Presto_327____20200210_142917_2.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hive.metastore.api.ConfigValSecurityException: For security reasons, the config key metastore.txn.timeout cannot be accessed
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$get_config_value_result$get_config_value_resultStandardScheme.read(ThriftHiveMetastore.java)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$get_config_value_result$get_config_value_resultStandardScheme.read(ThriftHiveMetastore.java)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$get_config_value_result.read(ThriftHiveMetastore.java)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:86)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_get_config_value(ThriftHiveMetastore.java:3502)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.get_config_value(ThriftHiveMetastore.java:3488)
	at io.prestosql.plugin.hive.metastore.thrift.ThriftHiveMetastoreClient.get_config_value(ThriftHiveMetastoreClient.java:486)
	at io.prestosql.plugin.hive.metastore.thrift.ThriftHiveMetastore.lambda$getConfigValue$69(ThriftHiveMetastore.java:1613)
	at io.prestosql.plugin.hive.util.RetryDriver.run(RetryDriver.java:130)
	at io.prestosql.plugin.hive.metastore.thrift.ThriftHiveMetastore.getConfigValue(ThriftHiveMetastore.java:1611)
	... 38 more
	Suppressed: org.apache.hadoop.hive.metastore.api.ConfigValSecurityException: For security reasons, the config key metastore.txn.timeout cannot be accessed
		... 48 more
	Suppressed: org.apache.hadoop.hive.metastore.api.ConfigValSecurityException: For security reasons, the config key metastore.txn.timeout cannot be accessed
		... 48 more
	Suppressed: org.apache.hadoop.hive.metastore.api.ConfigValSecurityException: For security reasons, the config key metastore.txn.timeout cannot be accessed
		... 48 more
	Suppressed: org.apache.hadoop.hive.metastore.api.ConfigValSecurityException: For security reasons, the config key metastore.txn.timeout cannot be accessed
		... 48 more
	Suppressed: org.apache.hadoop.hive.metastore.api.ConfigValSecurityException: For security reasons, the config key metastore.txn.timeout cannot be accessed
		... 48 more
	Suppressed: org.apache.hadoop.hive.metastore.api.ConfigValSecurityException: For security reasons, the config key metastore.txn.timeout cannot be accessed
		... 48 more
	Suppressed: org.apache.hadoop.hive.metastore.api.ConfigValSecurityException: For security reasons, the config key metastore.txn.timeout cannot be accessed
		... 48 more
	Suppressed: org.apache.hadoop.hive.metastore.api.ConfigValSecurityException: For security reasons, the config key metastore.txn.timeout cannot be accessed
		... 48 more
	Suppressed: org.apache.hadoop.hive.metastore.api.ConfigValSecurityException: For security reasons, the config key metastore.txn.timeout cannot be accessed
		... 48 more
```

**Comment by findepi** [comment]
@AbhishekNew the error reporting when accessing ACID in Hive 2.x is fixed in https://github.com/prestosql/presto/pull/2791 & https://github.com/prestosql/presto/issues/2790

However, this doesn't mean Hive ORC ACID tables are supported with Hive 2. They are not and this is tracked by https://github.com/prestosql/presto/issues/2937.
Please follow that issue. Or upgrade to Hive 3.
