### ISSUE TITLE
Flaky test TestThrottledAsyncQueue

### ISSUE THREAD

**Issue by electrum** [prestosql/presto#2797]
```
[ERROR] testThrottleEmptyQueue(io.prestosql.plugin.hive.util.TestThrottledAsyncQueue)  Time elapsed: 1.31 s  <<< FAILURE!
java.lang.AssertionError: lists don't have the same size expected [2] but found [1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:556)
	at org.testng.Assert.assertEquals(Assert.java:533)
	at io.prestosql.plugin.hive.util.TestThrottledAsyncQueue.testThrottleEmptyQueue(TestThrottledAsyncQueue.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by electrum** [comment]
https://github.com/prestosql/presto/runs/438981825

**Comment by electrum** [comment]
https://github.com/prestosql/presto/runs/439605631

**Comment by electrum** [comment]
https://github.com/prestosql/presto/runs/439773668

**Comment by findepi** [comment]
One of the problems of this test is that the class uses Guava `RateLimiter` which doesn't allow stubbing time (https://github.com/google/guava/issues/1774)
Sadly, Guava maintainers were not responsive in https://github.com/google/guava/pull/3759.

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/497446247

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/509609926

**Comment by ebyhr** [comment]
https://github.com/prestosql/presto/runs/536802100

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/543043052

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/806856308

**Comment by findepi** [comment]
cc @BenoitHanotte

**Comment by BenoitHanotte** [comment]
Hi @findepi, thanks for pinging me, I hadn't seen the issue.

I had a quick look at it, it seems that the "issue" is this logic:
```
        else if (!isFinished()) {
            // the queue is empty but not finished, wait before we can query a batch
            throttleFuture = getNotEmptySignal();
        }

        return Futures.transformAsync(
                throttleFuture,
                any -> {
                    int size = maxBatchSize(maxSize);
                    if (size > 0) {
                        rateLimiter.acquire(size);
                    }
                    return super.borrowBatchAsync(size, function);
                },
                executor);
    }
```
in the test, we try to get a batch of size 2 but the queue is empty so we wait for the not-empty signal (getNotEmptySignal). Once that signal is sent (the future is completed), then we ask again for a batch of `maxBatchSize(maxSize)`, which is `min(queue size, 2)`. Is this the conclusion you reached as well?

I guess a simple fix for this test is to ask for a batch of size 1 instead of 2 as it only aims at validating that we don't return an empty batch if the queue is empty but not finished.

**Comment by findepi** [comment]
@BenoitHanotte thanks for the analysis!

It's possible because we populate the queue in separate calls:
```
        assertTrue(queue.offer(3).isDone());
        assertTrue(queue.offer(4).isDone());
```

so the caller can get 3 alone or 3 and 4 together, right?

Asking for 1 sounds fine to me.

**Comment by BenoitHanotte** [comment]
Yes that's my understanding of the problem :) I'll tackle that on Monday if that's ok with you

**Comment by BenoitHanotte** [comment]
I pushed https://github.com/prestosql/presto/pull/4259 to fix the issue by using a batch of size 1 as discussed above.

**Comment by BenoitHanotte** [comment]
@findepi thank's for merging the review!
@electrum can we close this issue now, or do you want to wait for a few days to make sure the build will not fail again?
