### ISSUE TITLE
Document node.id requirements (allowed pattern)

### ISSUE THREAD

**Issue by AbhishekNew** [prestosql/presto#2800]
User given node.id =xx.yy.zz.ww in node.properties
restarted presto server
throws Exception
```
1 error
com.google.inject.CreationException: Unable to create injector, see the following errors:
1) Error: Invalid configuration property node.id: is malformed (for class io.airlift.node.NodeConfig.nodeId)
1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:245)
        at io.prestosql.server.PrestoServer.run(PrestoServer.java:122)
        at io.prestosql.$gen.Presto_327____20200211_065518_1.run(Unknown Source)
        at io.prestosql.server.PrestoServer.main(PrestoServer.java:72)
```

Suggested:
Document should be updated saying 
only following regex pattern allowed?  [A-Za-z0-9][_A-Za-z0-9-]*
Section:
https://prestosql.io/docs/current/installation/deployment.html -- In Node Properties Section

**Comment by AbhishekNew** [comment]
Please handle for node.environment too in doc. I see in code it follows the below pattern
    
     ENV_REGEXP = "[a-z0-9][_a-z0-9]*";

**Comment by mosabua** [comment]
Sounds good. Will update tomorrow

**Comment by mosabua** [comment]
@AbhishekNew PR is updated for environment as well
