### ISSUE TITLE
Fkaly test TestWorkProcessor.testFlatTransform

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#2897]
```
2020-02-21T14:12:35.4461302Z [ERROR] Tests run: 6103, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 886.716 s <<< FAILURE! - in TestSuite
2020-02-21T14:12:35.4462083Z [ERROR] testFlatTransform(io.prestosql.operator.TestWorkProcessor)  Time elapsed: 5.734 s  <<< FAILURE!
2020-02-21T14:12:35.4466543Z org.testng.internal.thread.ThreadTimeoutException: Method io.prestosql.operator.TestWorkProcessor.testFlatTransform() didn't finish within the time-out 5000
```

**Comment by findepi** [comment]
It's not only `testFlatTransform` method:

```
2020-02-21T13:46:04.1285016Z [ERROR] Tests run: 6103, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 842.859 s <<< FAILURE! - in TestSuite
2020-02-21T13:46:04.1288587Z [ERROR] testCreateFrom(io.prestosql.operator.TestWorkProcessor)  Time elapsed: 5.094 s  <<< FAILURE!
2020-02-21T13:46:04.1293138Z org.testng.internal.thread.ThreadTimeoutException: Method io.prestosql.operator.TestWorkProcessor.testCreateFrom() didn't finish within the time-out 5000
2020-02-21T13:46:04.1295817Z 	at sun.reflect.ReflectionFactory.newMethodAccessor(ReflectionFactory.java:171)
2020-02-21T13:46:04.1298091Z 	at java.lang.reflect.Method.acquireMethodAccessor(Method.java:564)
2020-02-21T13:46:04.1300437Z 	at java.lang.reflect.Method.invoke(Method.java:496)
2020-02-21T13:46:04.1303430Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-02-21T13:46:04.1306305Z 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
2020-02-21T13:46:04.1308871Z 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
2020-02-21T13:46:04.1311552Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020-02-21T13:46:04.1313947Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-02-21T13:46:04.1316483Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-02-21T13:46:04.1319283Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-02-21T13:46:04.1321370Z 	at java.lang.Thread.run(Thread.java:748)
```

https://github.com/prestosql/presto/runs/460223494
