### ISSUE TITLE
Flaky test TestSqlStageExecution.testFinalStageInfo

### ISSUE THREAD

**Issue by kokosing** [prestosql/presto#2929]
```
2020-02-24T11:39:47.2362664Z [ERROR] Tests run: 6108, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 815.606 s <<< FAILURE! - in TestSuite
2020-02-24T11:39:47.2368533Z [ERROR] testFinalStageInfo(io.prestosql.execution.TestSqlStageExecution)  Time elapsed: 0.053 s  <<< FAILURE!
2020-02-24T11:39:47.2372162Z java.lang.OutOfMemoryError: unable to create new native thread
2020-02-24T11:39:47.2374616Z 	at java.lang.Thread.start0(Native Method)
2020-02-24T11:39:47.2377278Z 	at java.lang.Thread.start(Thread.java:717)
2020-02-24T11:39:47.2382219Z 	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
2020-02-24T11:39:47.2386758Z 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1378)
2020-02-24T11:39:47.2391259Z 	at io.prestosql.execution.StateMachine.safeExecute(StateMachine.java:320)
2020-02-24T11:39:47.2396244Z 	at io.prestosql.execution.StateMachine.fireStateChanged(StateMachine.java:224)
2020-02-24T11:39:47.2400427Z 	at io.prestosql.execution.StateMachine.compareAndSet(StateMachine.java:214)
2020-02-24T11:39:47.2404451Z 	at io.prestosql.execution.StateMachine.setIf(StateMachine.java:171)
2020-02-24T11:39:47.2409638Z 	at io.prestosql.execution.TaskStateMachine.transitionToDoneState(TaskStateMachine.java:116)
2020-02-24T11:39:47.2415352Z 	at io.prestosql.execution.TaskStateMachine.abort(TaskStateMachine.java:102)
2020-02-24T11:39:47.2421208Z 	at io.prestosql.execution.MockRemoteTaskFactory$MockRemoteTask.abort(MockRemoteTaskFactory.java:405)
2020-02-24T11:39:47.2476542Z 	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:407)
2020-02-24T11:39:47.2542001Z 	at io.prestosql.execution.SqlStageExecution.abort(SqlStageExecution.java:253)
2020-02-24T11:39:47.2549107Z 	at io.prestosql.execution.TestSqlStageExecution.testFinalStageInfoInternal(TestSqlStageExecution.java:146)
2020-02-24T11:39:47.2564383Z 	at io.prestosql.execution.TestSqlStageExecution.testFinalStageInfo(TestSqlStageExecution.java:92)
2020-02-24T11:39:47.2568758Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-02-24T11:39:47.2574263Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-02-24T11:39:47.2580199Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-02-24T11:39:47.2586603Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2020-02-24T11:39:47.2592673Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-02-24T11:39:47.2597538Z 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
2020-02-24T11:39:47.2602476Z 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
2020-02-24T11:39:47.2607072Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020-02-24T11:39:47.2610873Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-02-24T11:39:47.2616423Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-02-24T11:39:47.2621798Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-02-24T11:39:47.2625327Z 	at java.lang.Thread.run(Thread.java:748)
2020-02-24T11:39:47.2626445Z 
2020-02-24T11:39:47.7187344Z [INFO] 
2020-02-24T11:39:47.7225699Z [INFO] Results:
2020-02-24T11:39:47.7226348Z [INFO] 
2020-02-24T11:39:47.7226650Z [ERROR] Failures: 
2020-02-24T11:39:47.7227601Z [ERROR]   TestSqlStageExecution.testFinalStageInfo:92->testFinalStageInfoInternal:146 Â» OutOfMemory
2020-02-24T11:39:47.7227926Z [INFO] 
2020-02-24T11:39:47.7228216Z [ERROR] Tests run: 6108, Failures: 1, Errors: 0, Skipped: 0
```

Happened at: https://github.com/prestosql/presto/pull/2881/checks?check_run_id=464482082

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/1454109647

**Comment by findepi** [comment]
@dain is this code here
https://github.com/prestosql/presto/blob/b39435cc72647e56e1ba03bbdd3a02521cf4c63a/presto-main/src/test/java/io/prestosql/execution/TestSqlStageExecution.java#L128-L137
trying to create a million of threads?
I guess  it's not, that would be too many, but what is the actual limit?

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/1459828200

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/1470645283

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/1510066934 

@dain did you have a chance to look into https://github.com/prestosql/presto/issues/2929#issuecomment-734344611 ?
