### ISSUE TITLE
Grouping expression not recognized when CAST uses different type name case

### ISSUE THREAD

**Issue by Svti** [prestosql/presto#2960]
```select 
--CAST(DATE_FORMAT(createAt,'%Y%m%d%H') AS bigint) hour ,     -- is ok 
CAST(DATE_FORMAT(createAt, '%Y%m%d%H') AS BIGINT) hour,     -- error !

appid,c
from mysql.tables
WHERE pt = 'app'
GROUP BY
CAST(DATE_FORMAT(createAt, '%Y%m%d%H') AS bigint),
appid,c
```

**Error running query: line 2:1: 'CAST(DATE_FORMAT(createAt, '%Y%m%d%H') AS BIGINT)' must be an aggregate expression or appear in GROUP BY clause**

presto version:330

**Comment by findepi** [comment]
Simplified case:
```
SELECT CAST(x AS BIGINT)
FROM (VALUES 42) t(x)
GROUP BY CAST(x AS bigint);
```

```
Query 20200228_204636_00004_if6ph failed: line 1:8: 'CAST(x AS BIGINT)' must be an aggregate expression or appear in GROUP BY clause
io.prestosql.spi.PrestoException: line 1:8: 'CAST(x AS BIGINT)' must be an aggregate expression or appear in GROUP BY clause
	at io.prestosql.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:57)
	at io.prestosql.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:52)
	at io.prestosql.sql.analyzer.AggregationAnalyzer.analyze(AggregationAnalyzer.java:164)
	at io.prestosql.sql.analyzer.AggregationAnalyzer.verifySourceAggregations(AggregationAnalyzer.java:117)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.analyzeAggregations(StatementAnalyzer.java:2312)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1271)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:293)
	at io.prestosql.sql.tree.QuerySpecification.accept(QuerySpecification.java:144)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:308)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:318)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:892)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:293)
	at io.prestosql.sql.tree.Query.accept(Query.java:107)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:308)
	at io.prestosql.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:285)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:75)
	at io.prestosql.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:221)
	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:180)
	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:97)
	at io.prestosql.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:732)
	at io.prestosql.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:121)
	at io.prestosql.$gen.Presto_null__testversion____20200228_204553_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by findepi** [comment]
@Svti thanks for reporting this.
BTW you can workaround this by using `GROUP BY 1` in the query:
```
SELECT CAST(....), a, b
FROM ...
GROUP BY 1, 2, 3      -- group by SELECT #1, #2 and #3 expressions
```

**Comment by tooptoop4** [comment]
do u know which release introduced the issue?

**Comment by findepi** [comment]
@tooptoop4 I don't think this ever worked.

**Comment by tooptoop4** [comment]
@findepi it works in prestodb 220
