### ISSUE TITLE
Presto cannot read from view defined by older version when ROW has field name being SQL keyword

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#2967]
### 312

```
USE hive.default;

CREATE TABLE t(x row("catalog" varchar, "schema" varchar, "table" varchar));

CREATE VIEW v AS SELECT * FROM t;
```

```
presto> SHOW CREATE TABLE t;
 CREATE TABLE hive.default.t (
    x row(catalog varchar, schema varchar, table varchar)
 )
 WITH (
    format = 'ORC'
 );
```
```
presto> SHOW CREATE VIEW v;
 CREATE VIEW hive.default.v AS
 SELECT *
 FROM
   t
```
```
presto> SELECT * FROM v;
...
```

### 330 
```
presto:default> SELECT * FROM v;
Query 20200228_130349_00009_edjpe failed: line 1:36: mismatched input 'table'. Expecting: <identifier>, <type>
io.prestosql.sql.parser.ParsingException: line 1:36: mismatched input 'table'. Expecting: <identifier>, <type>
	at io.prestosql.sql.parser.ErrorHandler.syntaxError(ErrorHandler.java:107)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportUnwantedToken(DefaultErrorStrategy.java:377)
	at org.antlr.v4.runtime.DefaultErrorStrategy.singleTokenDeletion(DefaultErrorStrategy.java:548)
	at org.antlr.v4.runtime.DefaultErrorStrategy.sync(DefaultErrorStrategy.java:266)
	at io.prestosql.sql.parser.SqlBaseParser.rowField(SqlBaseParser.java:10321)
	at io.prestosql.sql.parser.SqlBaseParser.type(SqlBaseParser.java:9987)
	at io.prestosql.sql.parser.SqlBaseParser.standaloneType(SqlBaseParser.java:385)
	at io.prestosql.sql.parser.SqlParser.invokeParser(SqlParser.java:146)
	at io.prestosql.sql.parser.SqlParser.createType(SqlParser.java:96)
	at io.prestosql.metadata.TypeRegistry.fromSqlType(TypeRegistry.java:164)
	at io.prestosql.metadata.TypeRegistry.getType(TypeRegistry.java:159)
	at io.prestosql.metadata.MetadataManager.getType(MetadataManager.java:1259)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.getViewColumnType(StatementAnalyzer.java:2381)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.isViewStale(StatementAnalyzer.java:2367)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.createScopeForView(StatementAnalyzer.java:1109)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:990)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:293)
	at io.prestosql.sql.tree.Table.accept(Table.java:53)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:308)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:2269)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1226)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:293)
	at io.prestosql.sql.tree.QuerySpecification.accept(QuerySpecification.java:144)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:308)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:318)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:892)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:293)
	at io.prestosql.sql.tree.Query.accept(Query.java:107)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:308)
	at io.prestosql.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:285)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:75)
	at io.prestosql.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:221)
	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:180)
	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:97)
	at io.prestosql.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:732)
	at io.prestosql.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:121)
	at io.prestosql.$gen.Presto_null__testversion____20200228_130311_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Error running command: begin 0, end 35, length 15
java.lang.StringIndexOutOfBoundsException: begin 0, end 35, length 15
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at io.prestosql.cli.Query.renderErrorLocation(Query.java:371)
	at io.prestosql.cli.Query.renderFailure(Query.java:361)
	at io.prestosql.cli.Query.renderQueryOutput(Query.java:196)
	at io.prestosql.cli.Query.renderOutput(Query.java:141)
	at io.prestosql.cli.Console.process(Console.java:331)
	at io.prestosql.cli.Console.runConsole(Console.java:257)
	at io.prestosql.cli.Console.run(Console.java:156)
	at io.prestosql.cli.Presto.main(Presto.java:31)
```

It works OK when the view is recreated in 330.

**Comment by martint** [comment]
What's the text of the stored view in 312 vs 330? I think this may be case where we stored what's arguably an incorrect representation of the view (not quoting identifiers that should've been quoted) and 330 is stricter in how it parses them.

**Comment by findepi** [comment]
When reading `ViewColumn`  from view  declared in 312, I see `row(.... , table varchar)`.
When view is defined in 323+, it's `row(.... , "table" varchar)`.
This makes a big difference when we use parser to get the type.

**Comment by martint** [comment]
Yeah, that's what I thought. FWIW, the view in 312 is "broken". Those identifiers should really be quoted, as they are reserved words in the grammar.

**Comment by electrum** [comment]
Could we read them in the older version? If so, this is compatibility issue for stored data that needs to be fixed.

**Comment by martint** [comment]
Yes, it could be read in the older version. It’s a compatibility issue resulting from “fixing” a bug, unfortunately. I don’t know if any good way to support the old version of those views, though.
