### ISSUE TITLE
An error is reported for field type conversion when a query view appears after the upgrade from 324

### ISSUE THREAD

**Issue by fly0512** [prestosql/presto#2992]
An error is reported when a field type conversion operation exists in the query view. This is not the case with version 324. I have reproduced the same problem in 327, 329 and 330.

Other service versions of my running environment are:
kudu 1.10
mongodb 4.0.5
hadoop 3.1.2
java version "1.8.0_211"
CentOS Linux release 7.6.1810 (Core)

presto> show create view hive.a003.dv_pos_check_discounts;
                           Create View                            
------------------------------------------------------------------
 CREATE VIEW hive.a003.dv_pos_check_discounts AS                  
 SELECT                                                           
   t1.tenant_id tenant_id                                         
 , t1.cdis_id cdis_id                                             
 , t1.cdis_bday_id cdis_bday_id                                   
 , t1.cdis_bper_id cdis_bper_id                                   
 , t1.cdis_bday_date bday_date                                    
 , t1.shop_id shop_id                                             
 , t1.cdis_olet_id cdis_olet_id                                   
 , t1.cdis_chks_id cdis_chks_id                                   
 , t1.cdis_cpty_id cdis_cpty_id                                   
 , t1.cdis_citm_id cdis_citm_id                                   
 , t1.cdis_dtyp_id cdis_dtyp_id                                   
 , COALESCE(t1.cdis_name_l1, '') cdis_name_l1                     
 , COALESCE(t1.cdis_name_l2, '') cdis_name_l2                     
 , COALESCE(t1.cdis_name_l3, '') cdis_name_l3                     
 , COALESCE(t1.cdis_name_l4, '') cdis_name_l4                     
 , COALESCE(t1.cdis_name_l5, '') cdis_name_l5                     
 , COALESCE(t1.cdis_short_name_l1, '') cdis_short_name_l1         
 , COALESCE(t1.cdis_short_name_l2, '') cdis_short_name_l2         
 , COALESCE(t1.cdis_short_name_l3, '') cdis_short_name_l3         
 , COALESCE(t1.cdis_short_name_l4, '') cdis_short_name_l4         
 , COALESCE(t1.cdis_short_name_l5, '') cdis_short_name_l5         
 , t1.cdis_dgrp_id cdis_dgrp_id                                   
 , CAST(t1.cdis_seq AS integer) cdis_seq                          
 , CAST(t1.cdis_round_total AS decimal(20, 4)) cdis_round_total   
 , CAST(t1.cdis_total AS decimal(20, 4)) cdis_total               
 , CAST(t1.cdis_round_amount AS decimal(20, 4)) cdis_round_amount 
 , t1.cdis_method cdis_method                                     
 , t1.cdis_type cdis_type                                         
 , t1.cdis_used_for cdis_used_for                                 
 , t1.cdis_class_key cdis_class_key                               
 , CAST(t1.cdis_rate AS decimal(20, 4)) cdis_rate                 
 , CAST(t1.cdis_fix_amount AS decimal(20, 4)) cdis_fix_amount     
 , t1.cdis_include_tax_sc_mask cdis_include_tax_sc_mask           
 , t1.cdis_include_pre_disc cdis_include_pre_disc                 
 , t1.cdis_include_mid_disc cdis_include_mid_disc                 
 , t1.cdis_apply_time cdis_apply_time                             
 , t1.cdis_apply_loctime cdis_apply_loctime                       
 , t1.cdis_apply_user_id cdis_apply_user_id                       
 , t1.cdis_apply_stat_id cdis_apply_stat_id                       
 , t1.cdis_void_time cdis_void_time                               
 , t1.cdis_void_loctime cdis_void_loctime                         
 , t1.cdis_void_user_id cdis_void_user_id                         
 , t1.cdis_void_stat_id cdis_void_stat_id                         
 , t1.cdis_void_vdrs_id cdis_void_vdrs_id                         
 , COALESCE(t1.cdis_status, '') cdis_status                       
 , t1.cdis_slave_id cdis_slave_id                                 
 , t1.cdis_slave_created cdis_slave_created                       
 , t1.cdis_slave_modified cdis_slave_modified                     
 , t1.cdis_sync_id cdis_sync_id                                   
 , t1.created created                                             
 , t1.modified modified                                           
 FROM                                                             
   kudu.a003.pos_check_discounts t1                               
(1 row)

Query 20200304_080507_00286_pzrxu, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0:03 [0 rows, 0B] [0 rows/s, 0B/s]

presto> 
presto>  WITH tmp_auth AS (SELECT node_id, node_type, tenant_id FROM mongodb.a003.busi_organization WHERE tenant_id = 't00010' AND status = '1' AND node_type <> '0') SELECT t1.bday_date AS bday_date, t1.shop_id AS shop_id, t1.cdis_olet_id AS olet_id, t1.cdis_chks_id AS chks_id, t1.cdis_citm_id AS citm_id, t1.cdis_name_l1 AS cdis_name, t1.cdis_bday_id AS cdis_bday_id, t1.cdis_total AS cdis_total, t1.cdis_dtyp_id AS cdis_dtyp_id, t1.tenant_id AS tenant_id, t1.cdis_id AS cdis_id, t1.cdis_rate AS cdis_rate, t1.cdis_round_total AS cdis_round_total, CASE WHEN coalesce(t1.cdis_citm_id, '') != '' THEN 'Item Discount' ELSE 'Check Discount' END AS Classfiy FROM hive.a003.dv_pos_check_discounts AS t1 WHERE (t1.tenant_id = 't00010') AND t1.shop_id IN (SELECT node_id FROM tmp_auth WHERE node_type = '1') LIMIT 100;

Query 20200304_075936_00283_pzrxu, FAILED, 5 nodes
Splits: 209 total, 1 done (0.48%)
0:01 [8 rows, 8B] [14 rows/s, 14B/s]

Query 20200304_075936_00283_pzrxu failed: Cannot cast VARCHAR '2018-01-15 04:56:51' to DECIMAL(20, 4). Value is not a number.

Below is the server.log

2020-03-04T15:58:03.170+0800	INFO	dispatcher-query-595	io.prestosql.event.QueryMonitor	TIMELINE: Query 20200304_075803_00282_pzrxu :: Transaction:[038e66db-b27c-4229-9a32-b4c516e32e5a] :: elapsed 149ms :: planning 72ms :: waiting 14ms :: scheduling 34ms :: running 28ms :: finishing 15ms :: begin 2020-03-04T15:58:03.013+08:00 :: end 2020-03-04T15:58:03.162+08:00
2020-03-04T15:59:37.640+0800	ERROR	remote-task-callback-845	io.prestosql.execution.StageStateMachine	Stage 20200304_075936_00283_pzrxu.2 failed
io.prestosql.spi.PrestoException: Cannot cast VARCHAR '2018-01-15 04:56:51' to DECIMAL(20, 4). Value is not a number.
	at io.prestosql.type.DecimalCasts.varcharToLongDecimal(DecimalCasts.java:499)
	at io.prestosql.$gen.CursorProcessor_20200304_075937_470.project_10(Unknown Source)
	at io.prestosql.$gen.CursorProcessor_20200304_075937_470.process(Unknown Source)
	at io.prestosql.operator.ScanFilterAndProjectOperator$RecordCursorToPages.process(ScanFilterAndProjectOperator.java:312)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.access$000(WorkProcessorUtils.java:37)
	at io.prestosql.operator.WorkProcessorUtils$YieldingProcess.process(WorkProcessorUtils.java:181)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:277)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:148)
	at io.prestosql.operator.Driver.processInternal(Driver.java:379)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_330____20200302_072006_2.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020-03-04T15:59:37.878+0800	INFO	dispatcher-query-600	io.prestosql.event.QueryMonitor	TIMELINE: Query 20200304_075936_00283_pzrxu :: Transaction:[50da18b0-672c-4283-a6e2-1235a08a7edc] :: elapsed 497ms :: planning 275ms :: waiting 87ms :: scheduling 119ms :: running 126ms :: finishing 0ms :: begin 2020-03-04T15:59:37.145+08:00 :: end 2020-03-04T15:59:37.642+08:00

**Comment by fly0512** [comment]
Other service versions of my running environment are:
kudu 1.10
hadoop 3.1.2
java version "1.8.0_211"
CentOS Linux release 7.6.1810 (Core)

**Comment by findepi** [comment]
> `Query 20200304_075936_00283_pzrxu failed: Cannot cast VARCHAR '2018-01-15 04:56:51' to DECIMAL(20, 4). Value is not a number.`

Obviously, such cast was never allowed, so there is some other problem.
@fly0512 can you try to dissect this eg by running `SELECT some_column FROM your_kudu_table` and see whether we return same data for each column in 324 vs 330?
You can also use `SELECT checksum(some_column) ..` instead of eye-balling the results.

**Comment by fly0512** [comment]
When I used the view's query Kudu field statement (as listed below) to query directly, the result returned was correct.
SELECT
t1.tenant_id tenant_id
, t1.cdis_id cdis_id
, t1.cdis_bday_id cdis_bday_id
...
FROM
kudu.a003.pos_check_discounts t1

Crucially, the same query did not fail in version 324.

**Comment by fly0512** [comment]
@findepi 
According to what you said, using checksum to query the data in Kudu table, no difference was found between 324 and 330.
![image](https://user-images.githubusercontent.com/50002522/75865868-25e5f700-5e3f-11ea-8a96-c8d2a623ac2c.png)

**Comment by fly0512** [comment]
The kudu connector was identified as the cause of the problem.The following issues have been moved to.
https://github.com/prestosql/presto/issues/3170
