### ISSUE TITLE
Flaky test TestTableFinishOperator.testStatisticsAggregation

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#2994]
```
2020-03-04T12:57:52.1622545Z [ERROR] Tests run: 6133, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 942.005 s <<< FAILURE! - in TestSuite
2020-03-04T12:57:52.1623333Z [ERROR] testStatisticsAggregation(io.prestosql.operator.TestTableFinishOperator)  Time elapsed: 0.016 s  <<< FAILURE!
2020-03-04T12:57:52.1623683Z java.lang.AssertionError: 
2020-03-04T12:57:52.1623904Z 
2020-03-04T12:57:52.1624154Z Expecting:
2020-03-04T12:57:52.1624403Z  <0.0>
2020-03-04T12:57:52.1624657Z to be greater than:
2020-03-04T12:57:52.1624912Z  <0.0> 
2020-03-04T12:57:52.1625236Z 	at io.prestosql.operator.TestTableFinishOperator.testStatisticsAggregation(TestTableFinishOperator.java:155)
2020-03-04T12:57:52.1625727Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-03-04T12:57:52.1630378Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-03-04T12:57:52.1632286Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-03-04T12:57:52.1633025Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2020-03-04T12:57:52.1638080Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-03-04T12:57:52.1638823Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-03-04T12:57:52.1642676Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-03-04T12:57:52.1644239Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-03-04T12:57:52.1647604Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-03-04T12:57:52.1649531Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-03-04T12:57:52.1652634Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-03-04T12:57:52.1654342Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-03-04T12:57:52.1654633Z 	at java.lang.Thread.run(Thread.java:748)
```

https://github.com/prestosql/presto/runs/484880838

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/601270627?check_suite_focus=true

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/1338510536
