### ISSUE TITLE
Flaky test TestTransactionManager.testExpiration

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#2995]
```
2020-03-04T12:57:52.1655156Z [ERROR] testExpiration(io.prestosql.transaction.TestTransactionManager)  Time elapsed: 4.282 s  <<< FAILURE!
2020-03-04T12:57:52.1655482Z java.lang.AssertionError: expected [true] but found [false]
2020-03-04T12:57:52.1656597Z 	at org.testng.Assert.fail(Assert.java:94)
2020-03-04T12:57:52.1658127Z 	at org.testng.Assert.failNotEquals(Assert.java:513)
2020-03-04T12:57:52.1659342Z 	at org.testng.Assert.assertTrue(Assert.java:42)
2020-03-04T12:57:52.1660657Z 	at org.testng.Assert.assertTrue(Assert.java:52)
2020-03-04T12:57:52.1664734Z 	at io.prestosql.transaction.TestTransactionManager.testExpiration(TestTransactionManager.java:190)
2020-03-04T12:57:52.1665435Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-03-04T12:57:52.1667878Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-03-04T12:57:52.1669151Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-03-04T12:57:52.1669995Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2020-03-04T12:57:52.1670706Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-03-04T12:57:52.1672332Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-03-04T12:57:52.1673163Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-03-04T12:57:52.1764208Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-03-04T12:57:52.6127617Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-03-04T12:57:52.6130414Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-03-04T12:57:52.6130731Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-03-04T12:57:52.6131016Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-03-04T12:57:52.6131257Z 	at java.lang.Thread.run(Thread.java:748)
```

https://github.com/prestosql/presto/runs/484880838

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/498530531

-- easy to reproduce. Just run `presto-main` test on CI 100 times. Don't know how to repro locally.
