### ISSUE TITLE
Unable to run singlenode-hdp3  product tests due lack of space

### ISSUE THREAD

**Issue by kokosing** [prestosql/presto#3121]
```
2020-03-17T09:51:47.6030258Z Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not pull image: failed to register layer: Error processing tar file(exit status 1): write /usr/hdp/3.1.0.0-78/hive/hive.tar.gz: no space left on device
2020-03-17T09:51:47.6030437Z 	at com.github.dockerjava.core.command.PullImageResultCallback.checkDockerClientPullSuccessful(PullImageResultCallback.java:96)
2020-03-17T09:51:47.6030585Z 	at com.github.dockerjava.core.command.PullImageResultCallback.throwFirstError(PullImageResultCallback.java:111)
2020-03-17T09:51:47.6032691Z 	at com.github.dockerjava.core.async.ResultCallbackTemplate.awaitCompletion(ResultCallbackTemplate.java:94)
2020-03-17T09:51:47.6032851Z 	at org.testcontainers.images.TimeLimitedLoggedPullImageResultCallback.awaitCompletion(TimeLimitedLoggedPullImageResultCallback.java:52)
2020-03-17T09:51:47.6032993Z 	at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:78)
2020-03-17T09:51:47.6033119Z 	... 13 more
```

This fails for:
```
2020-03-17T09:50:21.3236908Z + presto-product-tests-launcher/bin/run-launcher test run --environment singlenode-hdp3 -- -g hdp3_only,storage_formats,hive_transactional
```

**Comment by kokosing** [comment]
Please also see: https://github.com/prestosql/presto/pull/3084#issuecomment-599793302
