### ISSUE TITLE
SHOW CREATE TABLE fails if row type column contains special character

### ISSUE THREAD

**Issue by ebyhr** [prestosql/presto#3380]
Steps to reproduce
```sql
presto> create table memory.default.test as select CAST(ROW(1, 2e0) AS ROW("$x" BIGINT, y DOUBLE)) as c1;
CREATE TABLE: 1 row

presto> show create table memory.default.test;
Query 20200408_021754_00021_rp7e3 failed: value contains illegal characters: $x

presto> select * from memory.default.test;
      c1
---------------
 {$x=1, y=2.0}
(1 row)
```

```
java.lang.IllegalArgumentException: value contains illegal characters: $x
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:216)
	at io.prestosql.sql.tree.Identifier.<init>(Identifier.java:56)
	at io.prestosql.sql.tree.Identifier.<init>(Identifier.java:41)
	at io.prestosql.sql.analyzer.TypeSignatureTranslator.lambda$null$2(TypeSignatureTranslator.java:189)
	at java.util.Optional.map(Optional.java:215)
	at io.prestosql.sql.analyzer.TypeSignatureTranslator.lambda$toDataType$3(TypeSignatureTranslator.java:189)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.prestosql.sql.analyzer.TypeSignatureTranslator.toDataType(TypeSignatureTranslator.java:191)
	at io.prestosql.sql.analyzer.TypeSignatureTranslator.toSqlType(TypeSignatureTranslator.java:63)
	at io.prestosql.sql.rewrite.ShowQueriesRewrite$Visitor.lambda$visitShowCreate$8(ShowQueriesRewrite.java:472)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.prestosql.sql.rewrite.ShowQueriesRewrite$Visitor.visitShowCreate(ShowQueriesRewrite.java:474)
	at io.prestosql.sql.rewrite.ShowQueriesRewrite$Visitor.visitShowCreate(ShowQueriesRewrite.java:155)
	at io.prestosql.sql.tree.ShowCreate.accept(ShowCreate.java:67)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.rewrite.ShowQueriesRewrite.rewrite(ShowQueriesRewrite.java:152)
	at io.prestosql.sql.rewrite.StatementRewrite.rewrite(StatementRewrite.java:57)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:80)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:75)
	at io.prestosql.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:220)
	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:179)
	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:96)
	at io.prestosql.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:730)
	at io.prestosql.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:121)
	at io.prestosql.$gen.Presto_null__testversion____20200408_021428_4.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ebyhr** [comment]
Additionally, select statement fails if the field is nested like this.
```sql
presto> create table memory.default.test as select CAST(ROW(1, ROW(2, 3)) AS ROW(x BIGINT, ROW("$y" BIGINT, z BIGINT))) as c1;
CREATE TABLE: 1 row

presto>
presto> select * from memory.default.test;
            c1
---------------------------
 {x=1, field1={$y=2, z=3}}
(1 row)

presto>
presto> select c1[2] from memory.default.test;
Query 20200408_120452_00018_4rtfv failed: value contains illegal characters: $y
```
