### ISSUE TITLE
Incorrect handling of row expressions in VALUES

### ISSUE THREAD

**Issue by martint** [prestosql/presto#3398]
Row value expressions in the context of `VALUES` are currently handled incorrectly. For example, the following query:

```sql
VALUES CAST(row(1, 2) AS row(x int, y int));
```
fails with:

```
java.lang.IllegalArgumentException: Expected row to have 2 values, but row has 1 values
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:300)
	at io.prestosql.sql.planner.plan.ValuesNode.<init>(ValuesNode.java:46)
	at io.prestosql.sql.planner.RelationPlanner.visitValues(RelationPlanner.java:779)
	at io.prestosql.sql.planner.RelationPlanner.visitValues(RelationPlanner.java:108)
	at io.prestosql.sql.tree.Values.accept(Values.java:55)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.planner.QueryPlanner.planQueryBody(QueryPlanner.java:322)
	at io.prestosql.sql.planner.QueryPlanner.plan(QueryPlanner.java:135)
	at io.prestosql.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:740)
	at io.prestosql.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:108)
	at io.prestosql.sql.tree.Query.accept(Query.java:107)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.planner.LogicalPlanner.createRelationPlan(LogicalPlanner.java:594)
	at io.prestosql.sql.planner.LogicalPlanner.planStatementWithoutOutput(LogicalPlanner.java:246)
	at io.prestosql.sql.planner.LogicalPlanner.planStatement(LogicalPlanner.java:224)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:190)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:185)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:180)
	at io.prestosql.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:393)
	at io.prestosql.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:381)
	at io.prestosql.execution.SqlQueryExecution.start(SqlQueryExecution.java:336)
	at io.prestosql.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
```

Per the SQL specification, a row value expression can be either a `row value constructor` or a `row value special case`. A `row value constructor` is either an explicit constructor of the form `ROW(1, 2, ...)` or `(1, 2, ...)`, or an implicit one in the case of expressions that produce any type other than a `ROW`. In this case, an expression like `1 + 2` behaves as if had been written as `ROW(1 + 2)`.

A `row value special case` is an expression whose type is a `ROW`:

> The declared type of a `<row value special case>` shall be a row type.

For reference, here's the relevant portion of the grammar from the SQL specification:

```
<table value constructor> ::=  
    VALUES <row value expression list>
<row value expression list> ::= 
    <table row value expression> [ { <comma> <table row value expression> }... ]

<table row value expression> ::=
    <row value special case>
  | <row value constructor>

<row value constructor> ::=
    <common value expression>
  | <boolean value expression>
  | <explicit row value constructor>

<explicit row value constructor> ::=
    <left paren> <row value constructor element> <comma>
        <row value constructor element list> <right paren>
  | ROW <left paren> <row value constructor element list> <right paren>
  | <row subquery>
```

Some examples of expected behavior:

`VALUES 1` is equivalent to `VALUES ROW(1)`
`VALUES (1)` is equivalent to `VALUES ROW(1)`
`VALUES (1, 2)` is equivalent to `VALUES ROW(1, 2)`
`VALUES foo()` is equivalent to `VALUES ROW(foo())` if `foo()` returns anything other than a row type, otherwise, it returns the row returned by `foo()`

Fixing this issue will require changes to:
* The analysis of the `Values` syntax node
* The planning of `ValuesNode`
* The internal structure of `ValuesNode`, which currently encodes the rows as expanded fields (i.e., `List<Expression<Expression>>`). Instead, the rows should be represented as a `List<Expression>`, where each expression is either a row-producing expression or a row constructor.
* Any optimizer that uses ValuesNode
* ValuesOperator

**Comment by martint** [comment]
@Praveen2112, are you still working on this?

**Comment by Praveen2112** [comment]
I'll take it up next week !! I'll un-assign it now
