### ISSUE TITLE
Sporadic startup failure due to JMX agent automatic port allocation

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#3474]
* this happened in tests
* this can happen when starting Presto outside of tests too

```
2020-04-18T18:38:22.9764427Z 1) Error injecting constructor, com.sun.tools.attach.AttachOperationFailedException: java.lang.RuntimeException: jdk.internal.agent.AgentConfigurationError: java.rmi.server.ExportException: Port already in use: 41729; nested exception is: 	java.net.BindException: Address already in use (Bind failed)
2020-04-18T18:38:22.9764516Z 
2020-04-18T18:38:22.9764598Z   at io.airlift.jmx.JmxAgent9.<init>(JmxAgent9.java:47)
2020-04-18T18:38:22.9764640Z 
2020-04-18T18:38:22.9764720Z   at io.airlift.jmx.JmxModule.configure(JmxModule.java:55)
2020-04-18T18:38:22.9764762Z 
2020-04-18T18:38:22.9764888Z   while locating io.airlift.jmx.JmxAgent9
2020-04-18T18:38:22.9764984Z 
2020-04-18T18:38:22.9765045Z   while locating io.airlift.jmx.JmxAgent
2020-04-18T18:38:22.9765098Z 
2020-04-18T18:38:22.9765188Z     for the 1st parameter of io.airlift.jmx.JmxModule$JmxAnnouncementProvider.setJmxAgent(JmxModule.java:68)
2020-04-18T18:38:22.9765237Z 
2020-04-18T18:38:22.9765318Z   while locating io.airlift.jmx.JmxModule$JmxAnnouncementProvider
2020-04-18T18:38:22.9765361Z 
2020-04-18T18:38:22.9765458Z   while locating io.airlift.discovery.client.ServiceAnnouncement annotated with @com.google.inject.internal.Element(setName=,uniqueId=339, type=MULTIBINDER, keyType=)
2020-04-18T18:38:22.9765531Z 
2020-04-18T18:38:22.9765599Z   while locating java.util.Set<io.airlift.discovery.client.ServiceAnnouncement>
2020-04-18T18:38:22.9765661Z 
2020-04-18T18:38:22.9765748Z     for the 2nd parameter of io.airlift.discovery.client.Announcer.<init>(Announcer.java:68)
2020-04-18T18:38:22.9765795Z 
2020-04-18T18:38:22.9765881Z   at io.airlift.discovery.client.DiscoveryModule.configure(DiscoveryModule.java:64)
2020-04-18T18:38:22.9765931Z 
2020-04-18T18:38:22.9766010Z   while locating io.airlift.discovery.client.Announcer
2020-04-18T18:38:22.9766049Z 
2020-04-18T18:38:22.9766141Z     for the 2nd parameter of io.airlift.discovery.client.DiscoveryModule.createMergingServiceSelectorFactory(DiscoveryModule.java:122)
2020-04-18T18:38:22.9766208Z 
2020-04-18T18:38:22.9766281Z   at io.airlift.discovery.client.DiscoveryModule.createMergingServiceSelectorFactory(DiscoveryModule.java:122)
2020-04-18T18:38:22.9766348Z 
2020-04-18T18:38:22.9766426Z   while locating io.airlift.discovery.client.MergingServiceSelectorFactory
2020-04-18T18:38:22.9766470Z 
2020-04-18T18:38:22.9766550Z   at io.airlift.discovery.client.DiscoveryModule.configure(DiscoveryModule.java:73)
2020-04-18T18:38:22.9766594Z 
2020-04-18T18:38:22.9766673Z   while locating io.airlift.discovery.client.ServiceSelectorFactory
2020-04-18T18:38:22.9766714Z 
2020-04-18T18:38:22.9766810Z     for the 1st parameter of io.airlift.discovery.client.ServiceSelectorProvider.setServiceSelectorFactory(ServiceSelectorProvider.java:50)
2020-04-18T18:38:22.9766883Z 
2020-04-18T18:38:22.9766947Z   at io.prestosql.server.ServerMainModule.setup(ServerMainModule.java:218)
```

**Comment by findepi** [comment]
eg https://github.com/prestosql/presto/runs/598237598

**Comment by findepi** [comment]
Duplicates https://github.com/prestosql/presto/issues/2386
