### ISSUE TITLE
Aggregation function with lambda cannot be used as window function

### ISSUE THREAD

**Issue by electrum** [prestosql/presto#3561]
```
SELECT id, reduce_agg(value, 0, (a, b) -> a + b, (a, b) -> a + b) OVER (ORDER BY id)
FROM (
    VALUES
        (1, 3),
        (1, 4),
        (1, 5),
        (2, 6),
        (2, 7)
) AS t (id, value)
```
```
io.prestosql.spi.PrestoException: Lambda expression should always be used inside a function
	at io.prestosql.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:57)
	at io.prestosql.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:52)
	at io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.visitLambdaExpression(ExpressionAnalyzer.java:1276)
	at io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.visitLambdaExpression(ExpressionAnalyzer.java:324)
	at io.prestosql.sql.tree.LambdaExpression.accept(LambdaExpression.java:60)
	at io.prestosql.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:27)
	at io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:347)
	at io.prestosql.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:285)
	at io.prestosql.sql.analyzer.ExpressionAnalyzer.analyzeExpressions(ExpressionAnalyzer.java:1565)
	at io.prestosql.sql.planner.TypeAnalyzer.getTypes(TypeAnalyzer.java:52)
	at io.prestosql.sql.planner.TypeAnalyzer.getTypes(TypeAnalyzer.java:57)
	at io.prestosql.sql.planner.TypeAnalyzer.getType(TypeAnalyzer.java:62)
	at io.prestosql.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:125)
	at io.prestosql.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:59)
	at io.prestosql.sql.planner.plan.ProjectNode.accept(ProjectNode.java:82)
	at io.prestosql.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at io.prestosql.sql.planner.sanity.TypeValidator$Visitor.visitWindow(TypeValidator.java:106)
	at io.prestosql.sql.planner.sanity.TypeValidator$Visitor.visitWindow(TypeValidator.java:59)
	at io.prestosql.sql.planner.plan.WindowNode.accept(WindowNode.java:155)
	at io.prestosql.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at io.prestosql.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:116)
	at io.prestosql.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:59)
	at io.prestosql.sql.planner.plan.ProjectNode.accept(ProjectNode.java:82)
	at io.prestosql.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at io.prestosql.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:116)
	at io.prestosql.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:59)
	at io.prestosql.sql.planner.plan.ProjectNode.accept(ProjectNode.java:82)
	at io.prestosql.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at io.prestosql.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:116)
	at io.prestosql.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:59)
	at io.prestosql.sql.planner.plan.ProjectNode.accept(ProjectNode.java:82)
	at io.prestosql.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at io.prestosql.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:116)
	at io.prestosql.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:59)
	at io.prestosql.sql.planner.plan.ProjectNode.accept(ProjectNode.java:82)
	at io.prestosql.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at io.prestosql.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:19)
	at io.prestosql.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
	at io.prestosql.sql.planner.plan.OutputNode.accept(OutputNode.java:83)
	at io.prestosql.sql.planner.sanity.TypeValidator.validate(TypeValidator.java:56)
	at io.prestosql.sql.planner.sanity.PlanSanityChecker.lambda$validateIntermediatePlan$1(PlanSanityChecker.java:71)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:407)
	at io.prestosql.sql.planner.sanity.PlanSanityChecker.validateIntermediatePlan(PlanSanityChecker.java:71)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:194)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:187)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:182)
	at io.prestosql.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:393)
	at io.prestosql.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:381)
	at io.prestosql.execution.SqlQueryExecution.start(SqlQueryExecution.java:336)
	at io.prestosql.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.prestosql.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:132)
	at io.prestosql.$gen.Presto_null__testversion____20200427_201253_3.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ssquan** [comment]
This is the same as #3883

**Comment by findepi** [comment]
Done in https://github.com/prestosql/presto/pull/3885

@ssquan thanks
