### ISSUE TITLE
SpatialJoin ignored in RemoveUnsupportedDynamicFilters

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#3569]
`RemoveUnsupportedDynamicFilters`, `DynamicFiltersChecker` need to handle `SpatialJoin` explicitly.

> ```
> In 332, with a query like this:
>     select *
>     from hive.my_schema.my_table s
>     join geom g
>      on (st_contains(g.geometry, st_point(s.lng, s.lat)))
> ```
> I’m seeing the error below:
> ```
> java.lang.UnsupportedOperationException: undefined
> 	at io.prestosql.sql.DynamicFilters$Function.dynamicFilter(DynamicFilters.java:199)
> 	at io.prestosql.$gen.JoinFilterFunction_20200427_194225_6330.filter(Unknown Source)
> 	at io.prestosql.operator.StandardJoinFilterFunction.filter(StandardJoinFilterFunction.java:49)
> 	at io.prestosql.operator.PagesRTreeIndex.isJoinPositionEligible(PagesRTreeIndex.java:206)
> 	at io.prestosql.operator.SpatialJoinOperator.processProbe(SpatialJoinOperator.java:266)
> 	at io.prestosql.operator.SpatialJoinOperator.getOutput(SpatialJoinOperator.java:219)
> 	at io.prestosql.operator.Driver.processInternal(Driver.java:379)
> 	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
> 	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
> 	at io.prestosql.operator.Driver.processFor(Driver.java:276)
> 	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
> 	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
> 	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
> 	at io.prestosql.$gen.Presto_332_6____20200427_180557_2.run(Unknown Source)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> ```

**Comment by findepi** [comment]
cc @JamesRTaylor @raunaqmorarka @sopel39
