### ISSUE TITLE
Alter table and select throws Exception

### ISSUE THREAD

**Issue by AbhishekNew** [prestosql/presto#3668]
presto:default> create table hivetb_old(column_int int, cint int, column_char int, cchar char(5), clond varchar(5)) with (format='orc');
CREATE TABLE
presto:default> insert into hivetb_old select 66,36,88,'df','98k';
INSERT: 1 row

Query 20200508_060708_00005_9cdss, FINISHED, 1 node
Splits: 51 total, 51 done (100.00%)
0:01 [0 rows, 0B] [0 rows/s, 0B/s]

presto:default> select * from hivetb_old;
 column_int | cint | column_char | cchar | clond
------------+------+-------------+-------+-------
         66 |   36 |          88 | df    | 98k
(1 row)

presto:default>  alter table hivetb_old drop column cint;
DROP COLUMN
presto:default> select * from hivetb_old;

Query 20200508_061611_00004_rp8wz, FAILED, 1 node
Splits: 17 total, 0 done (0.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20200508_061611_00004_rp8wz failed: Error opening Hive split hdfs://localhost:9000/user/hive/warehouse/hivetb_old/20200508_060708_00005_9cdss_ed6f4dfb-f117-48f4-bc8c-b059bfdf3725 (offset=0, length=580): Malformed ORC file. Cannot read SQL type char(5) from ORC stream .column_char of type INT [hdfs://localhost:9000/user/hive/warehouse/hivetb_old/20200508_060708_00005_9cdss_ed6f4dfb-f117-48f4-bc8c-b059bfdf3725]
Stack Trace
io.prestosql.spi.PrestoException: Error opening Hive split hdfs://localhost:9000/user/hive/warehouse/hivetb_old/20200508_060708_00005_9cdss_ed6f4dfb-f117-48f4-bc8c-b059bfdf3725 (offset=0, length=580): Malformed ORC file. Cannot read SQL type char(5) from ORC stream .column_char of type INT [hdfs://localhost:9000/user/hive/warehouse/hivetb_old/20200508_060708_00005_9cdss_ed6f4dfb-f117-48f4-bc8c-b059bfdf3725]
	at io.prestosql.plugin.hive.orc.OrcPageSourceFactory.createOrcPageSource(OrcPageSourceFactory.java:270)
	at io.prestosql.plugin.hive.orc.OrcPageSourceFactory.createPageSource(OrcPageSourceFactory.java:128)
	at io.prestosql.plugin.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:188)
	at io.prestosql.plugin.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:108)
	at io.prestosql.plugin.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:91)
	at io.prestosql.plugin.base.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:49)
	at io.prestosql.split.PageSourceManager.createPageSource(PageSourceManager.java:63)
	at io.prestosql.operator.TableScanOperator.getOutput(TableScanOperator.java:284)
	at io.prestosql.operator.Driver.processInternal(Driver.java:379)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_329____20200508_061418_2.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.prestosql.orc.OrcCorruptionException: Malformed ORC file. Cannot read SQL type char(5) from ORC stream .column_char of type INT [hdfs://localhost:9000/user/hive/warehouse/hivetb_old/20200508_060708_00005_9cdss_ed6f4dfb-f117-48f4-bc8c-b059bfdf3725]
	at io.prestosql.orc.reader.ReaderUtils.verifyStreamType(ReaderUtils.java:40)
	at io.prestosql.orc.reader.LongColumnReader.<init>(LongColumnReader.java:88)
	at io.prestosql.orc.reader.ColumnReaders.createColumnReader(ColumnReaders.java:38)
	at io.prestosql.orc.OrcRecordReader.createColumnReaders(OrcRecordReader.java:557)
	at io.prestosql.orc.OrcRecordReader.<init>(OrcRecordReader.java:236)
	at io.prestosql.orc.OrcReader.createRecordReader(OrcReader.java:275)
	at io.prestosql.plugin.hive.orc.OrcPageSourceFactory.createOrcPageSource(OrcPageSourceFactory.java:239)
	... 18 more

Hive :
hive> select * from hivetb_old;
OK
66      88      df      98k
Time taken: 1.833 seconds, Fetched: 1 row(s)
hive>

**Comment by findepi** [comment]
@AbhishekNew can  you please add `hive.orc.use-column-names=true` to your hive.properties and try again?

**Comment by AbhishekNew** [comment]
Yes works when given hive.orc.use-column-names=true  in hive.properties

presto:default>  create table hivetb_old1(column_int int, cint int, column_char int, cchar char(5), clond varchar(5)) with (format='orc');
CREATE TABLE
presto:default> insert into hivetb_old1 select 66,36,88,'df','98k';
INSERT: 1 row
presto:default> select * from hivetb_old1;
 column_int | cint | column_char | cchar | clond
------------+------+-------------+-------+-------
         66 |   36 |          88 | df    | 98k
(1 row)

presto:default> alter table hivetb_old1 drop column cint;
DROP COLUMN
presto:default> select * from hivetb_old1;
 column_int | column_char | cchar | clond
------------+-------------+-------+-------
         66 |          88 | df    | 98k
(1 row)

**Comment by findepi** [comment]
@AbhishekNew thanks for checking. Let me close this issue in favor of https://github.com/prestosql/presto/issues/1558.
