### ISSUE TITLE
Failed to parse QueryResults due to MAP having ROW key

### ISSUE THREAD

**Issue by ebyhr** [prestosql/presto#3671]
This issue happens on both CLI and JDBC driver. The query finishes without error on the server side. Testing on upstream modules. 
```
presto> select MAP(ARRAY[ROW(3),ROW(4)], ARRAY[1,2]);
java.lang.RuntimeException: Error fetching next at http://localhost:8080/v1/statement/executing/20200508_155056_00016_5vae2/y7a087841dda30f6b94bafe37089323defe558ac6/0 returned an invalid response: JsonResponse{statusCode=200, statusMessage=OK, headers={content-type=[application/json], date=[Fri, 08 May 2020 15:50:56 GMT], vary=[Accept-Encoding, User-Agent], x-content-type-options=[nosniff]}, hasValue=false} [Error: {"id":"20200508_155056_00016_5vae2","infoUri":"http://localhost:8080/ui/query.html?20200508_155056_00016_5vae2","partialCancelUri":"http://localhost:8080/v1/statement/executing/partialCancel/20200508_155056_00016_5vae2/0/yd03036570592387b235511e676f81c2731072c30/1","nextUri":"http://localhost:8080/v1/statement/executing/20200508_155056_00016_5vae2/yd03036570592387b235511e676f81c2731072c30/1","columns":[{"name":"_col0","type":"map(row(integer), integer)","typeSignature":{"rawType":"map","arguments":[{"kind":"TYPE","value":{"rawType":"row","arguments":[{"kind":"NAMED_TYPE","value":{"typeSignature":{"rawType":"integer","arguments":[]}}}]}},{"kind":"TYPE","value":{"rawType":"integer","arguments":[]}}]}}],"data":[[{"[3]":1,"[4]":2}]],"stats":{"state":"RUNNING","queued":false,"scheduled":true,"nodes":1,"totalSplits":5,"queuedSplits":2,"runningSplits":3,"completedSplits":0,"cpuTimeMillis":0,"wallTimeMillis":0,"queuedTimeMillis":0,"elapsedTimeMillis":214,"processedRows":0,"processedBytes":0,"peakMemoryBytes":0,"spilledBytes":0,"rootStage":{"stageId":"0","state":"RUNNING","done":false,"nodes":1,"totalSplits":5,"queuedSplits":2,"runningSplits":3,"completedSplits":0,"cpuTimeMillis":0,"wallTimeMillis":0,"processedRows":1,"processedBytes":0,"subStages":[]},"progressPercentage":0.0},"warnings":[]}
]
	at io.prestosql.client.StatementClientV1.requestFailedException(StatementClientV1.java:466)
	at io.prestosql.client.StatementClientV1.advance(StatementClientV1.java:405)
	at io.prestosql.cli.StatusPrinter.printInitialStatusUpdates(StatusPrinter.java:132)
	at io.prestosql.cli.Query.renderQueryOutput(Query.java:156)
	at io.prestosql.cli.Query.renderOutput(Query.java:141)
	at io.prestosql.cli.Console.process(Console.java:331)
	at io.prestosql.cli.Console.runConsole(Console.java:257)
	at io.prestosql.cli.Console.run(Console.java:156)
	at io.prestosql.cli.Presto.main(Presto.java:31)
Caused by: java.lang.IllegalArgumentException: Unable to create class io.prestosql.client.QueryResults from JSON response:
[{"id":"20200508_155056_00016_5vae2","infoUri":"http://localhost:8080/ui/query.html?20200508_155056_00016_5vae2","partialCancelUri":"http://localhost:8080/v1/statement/executing/partialCancel/20200508_155056_00016_5vae2/0/yd03036570592387b235511e676f81c2731072c30/1","nextUri":"http://localhost:8080/v1/statement/executing/20200508_155056_00016_5vae2/yd03036570592387b235511e676f81c2731072c30/1","columns":[{"name":"_col0","type":"map(row(integer), integer)","typeSignature":{"rawType":"map","arguments":[{"kind":"TYPE","value":{"rawType":"row","arguments":[{"kind":"NAMED_TYPE","value":{"typeSignature":{"rawType":"integer","arguments":[]}}}]}},{"kind":"TYPE","value":{"rawType":"integer","arguments":[]}}]}}],"data":[[{"[3]":1,"[4]":2}]],"stats":{"state":"RUNNING","queued":false,"scheduled":true,"nodes":1,"totalSplits":5,"queuedSplits":2,"runningSplits":3,"completedSplits":0,"cpuTimeMillis":0,"wallTimeMillis":0,"queuedTimeMillis":0,"elapsedTimeMillis":214,"processedRows":0,"processedBytes":0,"peakMemoryBytes":0,"spilledBytes":0,"rootStage":{"stageId":"0","state":"RUNNING","done":false,"nodes":1,"totalSplits":5,"queuedSplits":2,"runningSplits":3,"completedSplits":0,"cpuTimeMillis":0,"wallTimeMillis":0,"processedRows":1,"processedBytes":0,"subStages":[]},"progressPercentage":0.0},"warnings":[]}
]
	at io.prestosql.client.JsonResponse.<init>(JsonResponse.java:70)
	at io.prestosql.client.JsonResponse.execute(JsonResponse.java:144)
	at io.prestosql.client.StatementClientV1.advance(StatementClientV1.java:391)
	... 7 more
Caused by: java.lang.IllegalArgumentException: Invalid JSON string for [simple type, class io.prestosql.client.QueryResults]
	at io.airlift.json.JsonCodec.fromJson(JsonCodec.java:137)
	at io.prestosql.client.JsonResponse.<init>(JsonResponse.java:67)
	... 9 more
Caused by: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `io.prestosql.client.QueryResults`, problem: class java.lang.String cannot be cast to class java.util.List (java.lang.String and java.util.List are in module java.base of loader 'bootstrap')
 at [Source: (String)"{"id":"20200508_155056_00016_5vae2","infoUri":"http://localhost:8080/ui/query.html?20200508_155056_00016_5vae2","partialCancelUri":"http://localhost:8080/v1/statement/executing/partialCancel/20200508_155056_00016_5vae2/0/yd03036570592387b235511e676f81c2731072c30/1","nextUri":"http://localhost:8080/v1/statement/executing/20200508_155056_00016_5vae2/yd03036570592387b235511e676f81c2731072c30/1","columns":[{"name":"_col0","type":"map(row(integer), integer)","typeSignature":{"rawType":"map","argument"[truncated 805 chars]; line: 1, column: 1304]
	at com.fasterxml.jackson.databind.exc.ValueInstantiationException.from(ValueInstantiationException.java:47)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1735)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:491)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:514)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:285)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:229)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:198)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:488)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1719)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1261)
	at io.airlift.json.JsonCodec.fromJson(JsonCodec.java:134)
	... 10 more
Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.List (java.lang.String and java.util.List are in module java.base of loader 'bootstrap')
	at io.prestosql.client.FixJsonDataUtils.fixValue(FixJsonDataUtils.java:108)
	at io.prestosql.client.FixJsonDataUtils.fixValue(FixJsonDataUtils.java:102)
	at io.prestosql.client.FixJsonDataUtils.fixData(FixJsonDataUtils.java:74)
	at io.prestosql.client.QueryResults.<init>(QueryResults.java:69)
	at jdk.internal.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:283)
	... 19 more
Query is gone (server restarted?)
```

If we replace key and value, it succeeded. 
```
presto> select MAP(ARRAY[1,2], ARRAY[ROW(3),ROW(4)]);
            _col0
------------------------------
 {1={field0=3}, 2={field0=4}}
```

**Comment by zhaner08** [comment]
Please assign this to me, already starting to work on this
