### ISSUE TITLE
Caching doesn't work when enabled for multiple hive catalogs

### ISSUE THREAD

**Issue by hashhar** [prestosql/presto#3723]
creating two hive catalogs with caching enabled causes Rubix to fail initialisation for the second catalog but allows Presto to start up successfully.

The stack-trace on PrestoSQL 333 (RPM build) is:

```
2020-05-13T17:38:28.752Z        ERROR   Thread-120      com.qubole.rubix.bookkeeper.BookKeeperServer    org.apache.thrift.shaded.transport.TTrans
portException: Could not create ServerSocket on address 0.0.0.0/0.0.0.0:8899.
        at org.apache.thrift.shaded.transport.TServerSocket.<init>(TServerSocket.java:109)
        at com.qubole.rubix.bookkeeper.BookKeeperServer.startThriftServer(BookKeeperServer.java:148)
        at com.qubole.rubix.bookkeeper.BookKeeperServer.access$100(BookKeeperServer.java:48)
        at com.qubole.rubix.bookkeeper.BookKeeperServer$2.run(BookKeeperServer.java:96)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.BindException: Address already in use (Bind failed)
        at java.base/java.net.PlainSocketImpl.socketBind(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:436)
        at java.base/java.net.ServerSocket.bind(ServerSocket.java:395)
        at org.apache.thrift.shaded.transport.TServerSocket.<init>(TServerSocket.java:106)
        ... 4 more
2020-05-13T17:38:28.767Z        ERROR   Thread-121      com.qubole.rubix.bookkeeper.LocalDataTransferServer     Error starting Local Transfer ser
ver                                                                                                                                              java.net.BindException: Address already in use
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:455)
        at java.base/sun.nio.ch.Net.bind(Net.java:447)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
        at com.qubole.rubix.bookkeeper.LocalDataTransferServer$LocalServer.run(LocalDataTransferServer.java:169)
        at java.base/java.lang.Thread.run(Thread.java:834)
2020-05-13T17:38:28.802Z        INFO    pool-59-thread-1        io.prestosql.plugin.hive.rubix.RubixInitializer Rubix initialized successfully
```

For additional context see https://prestosql.slack.com/archives/CGB0QHWSW/p1589392346340700

**Comment by hashhar** [comment]
As suggested by @losipiuk I'll try by providing a different config for rubix for each catalog and report here if it works under that configuration.

**Comment by sopel39** [comment]
@hashhar did you test @losipiuk suggestion?

**Comment by hashhar** [comment]
@sopel39 Sorry for the delay in getting back to this. Yes, I was able to configure different caching directories and different book-keeper and data-transfer ports for each catalog and then Rubix works without any issues with multiple catalogs.

I think we can resolve this by highlighting in the documentation that each hive catalog needs it's own Rubix config.

**Comment by sopel39** [comment]
Ok. I'm closing this ticket.

> I think we can resolve this by highlighting in the documentation that each hive catalog needs it's own Rubix config.

@mosabua Could you address that?

**Comment by mosabua** [comment]
Well.. there is no documentation in prestosql yet. I will raise priority on this.
