### ISSUE TITLE
JMX connector fails with NoClassDefFoundError when querying metrics from rubix

### ISSUE THREAD

**Issue by hashhar** [prestosql/presto#3737]
## Issue

Running a query like

```sql
presto:current> select * from "metrics:name=rubix.bookkeeper.gauge.cache_size_mb";
```

results in the following stack trace:

```
Query 20200514_071729_00021_fvmwy failed: java.lang.NoClassDefFoundError: org/apache/commons/lang/math/NumberUtils
javax.management.RuntimeErrorException: java.lang.NoClassDefFoundError: org/apache/commons/lang/math/NumberUtils
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.rethrow(DefaultMBeanServerInterceptor.java:831)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttributes(DefaultMBeanServerInterceptor.java:703)
	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.getAttributes(JmxMBeanServer.java:705)
	at io.prestosql.plugin.base.jmx.RebindSafeMBeanServer.getAttributes(RebindSafeMBeanServer.java:142)
	at io.prestosql.plugin.jmx.JmxRecordSetProvider.getAttributes(JmxRecordSetProvider.java:218)
	at io.prestosql.plugin.jmx.JmxRecordSetProvider.getLiveRow(JmxRecordSetProvider.java:65)
	at io.prestosql.plugin.jmx.JmxRecordSetProvider.getLiveRows(JmxRecordSetProvider.java:229)
	at io.prestosql.plugin.jmx.JmxRecordSetProvider.getRecordSet(JmxRecordSetProvider.java:166)
	at io.prestosql.split.RecordPageSourceProvider.createPageSource(RecordPageSourceProvider.java:50)
	at io.prestosql.split.PageSourceManager.createPageSource(PageSourceManager.java:64)
	at io.prestosql.operator.TableScanOperator.getOutput(TableScanOperator.java:299)
	at io.prestosql.operator.Driver.processInternal(Driver.java:379)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_333____20200514_063101_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang/math/NumberUtils
	at com.qubole.rubix.bookkeeper.utils.DiskUtils.getDirectorySizeInMB(DiskUtils.java:113)
	at com.qubole.rubix.bookkeeper.utils.DiskUtils.getCacheSizeMB(DiskUtils.java:83)
	at com.qubole.rubix.bookkeeper.BookKeeper$3.getValue(BookKeeper.java:220)
	at com.qubole.rubix.bookkeeper.BookKeeper$3.getValue(BookKeeper.java:216)
	at com.codahale.metrics.JmxReporter$JmxGauge.getValue(JmxReporter.java:189)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:260)
	at java.management/com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:112)
	at java.management/com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:46)
	at java.management/com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
	at java.management/com.sun.jmx.mbeanserver.PerInterface.getAttribute(PerInterface.java:83)
	at java.management/com.sun.jmx.mbeanserver.MBeanSupport.getAttribute(MBeanSupport.java:206)
	at java.management/com.sun.jmx.mbeanserver.MBeanSupport.getAttributes(MBeanSupport.java:213)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttributes(DefaultMBeanServerInterceptor.java:701)
	... 20 more
```

## Repro

Setup a presto cluster and run the following to add a hive config and a jmx config

```sh
cat > /etc/presto/catalog/hive.properties <<EOF
connector.name=hive-hadoop2
hive.metastore=thrift
hive.metastore.uri=${hive_metastore_uris}
hive.metastore-cache-ttl=20m
hive.metastore-refresh-interval=1m
hive.storage-format=PARQUET
hive.compression-codec=SNAPPY
hive.hdfs.impersonation.enabled=true
hive.non-managed-table-writes-enabled=true
hive.s3-file-system-type=PRESTO
hive.parquet.use-column-names=true
hive.cache.enabled=true
hive.cache.location=/var/cache/presto_fs_cache
EOF
```

```sh
cat > "/etc/presto/catalog/jmx.properties" <<EOF
connector.name=jmx
EOF
```

The start up presto cli as `presto --catalog jmx --schema current` and run the query mentioned at the beginning of the issue.

**Comment by findepi** [comment]
cc @stagraqubole

**Comment by sopel39** [comment]
This shows that we also need to add product test for Rubix Caching

**Comment by stagraqubole** [comment]
This is happening because only the shaded version of `commons-lang` is available in Presto which has relocated namespace. Will fix this in Rubix along with checks for assumptions over other `provided` dependencies.

**Comment by hashhar** [comment]
Closing since this was resolved by https://github.com/prestosql/presto/commit/6ba38eea13e90bad874fb60a506eb550ac2d114e.
