### ISSUE TITLE
Flaky test TestRubixCaching.testLargeFile

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#3861]
```
2020-05-27T07:17:21.5775481Z [ERROR] testLargeFile(io.prestosql.plugin.hive.rubix.TestRubixCaching)  Time elapsed: 14.537 s  <<< FAILURE!
2020-05-27T07:17:21.5778764Z java.lang.AssertionError: expected [247] but found [315]
2020-05-27T07:17:21.5780553Z 	at org.testng.Assert.fail(Assert.java:94)
2020-05-27T07:17:21.5783398Z 	at org.testng.Assert.failNotEquals(Assert.java:513)
2020-05-27T07:17:21.5786541Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
2020-05-27T07:17:21.5789312Z 	at org.testng.Assert.assertEquals(Assert.java:116)
2020-05-27T07:17:21.5792103Z 	at org.testng.Assert.assertEquals(Assert.java:284)
2020-05-27T07:17:21.5794861Z 	at org.testng.Assert.assertEquals(Assert.java:294)
2020-05-27T07:17:21.5800207Z 	at io.prestosql.plugin.hive.rubix.TestRubixCaching.lambda$testLargeFile$12(TestRubixCaching.java:411)
2020-05-27T07:17:21.5869248Z 	at io.prestosql.testing.assertions.Assert.assertEventually(Assert.java:58)
2020-05-27T07:17:21.5884374Z 	at io.prestosql.plugin.hive.rubix.TestRubixCaching.testLargeFile(TestRubixCaching.java:406)
2020-05-27T07:17:21.5889168Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-05-27T07:17:21.5894818Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-05-27T07:17:21.5900932Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-05-27T07:17:21.5904133Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-05-27T07:17:21.5912169Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-05-27T07:17:21.5929760Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-05-27T07:17:21.5933361Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-05-27T07:17:21.5937205Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-05-27T07:17:21.5942235Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-05-27T07:17:21.5946387Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-05-27T07:17:21.5951954Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-05-27T07:17:21.5957251Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-05-27T07:17:21.5961728Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/712025156

**Comment by sopel39** [comment]
Fix: https://github.com/prestosql/presto/pull/3862
