### ISSUE TITLE
Use only first char from escapeChar table property to be consistent with Hive

### ISSUE THREAD

**Issue by hashhar** [prestosql/presto#3868]
On Presto with hive connector enabled running the following:

```sql
 SELECT table_schema, table_name, column_name
 FROM information_schema.columns
 WHERE table_schema='<schema>'
```

results in:

```log
  HIVE_INVALID_METADATA (16777228)
 io.prestosql.spi.PrestoException: Only single character can be set for property: escapeChar
     at io.prestosql.plugin.hive.HiveMetadata.lambda$getCsvSerdeProperty$16(HiveMetadata.java:629)
     at java.base/java.util.Optional.map(Optional.java:265)
     at io.prestosql.plugin.hive.HiveMetadata.getCsvSerdeProperty(HiveMetadata.java:627)
     at io.prestosql.plugin.hive.HiveMetadata.doGetTableMetadata(HiveMetadata.java:617)
     at io.prestosql.plugin.hive.HiveMetadata.getTableMetadata(HiveMetadata.java:528)
     at io.prestosql.plugin.hive.HiveMetadata.listTableColumns(HiveMetadata.java:700)
     at io.prestosql.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.listTableColumns(ClassLoaderSafeConnectorMetadata.java:262)
     at io.prestosql.metadata.MetadataManager.listTableColumns(MetadataManager.java:567)
     at io.prestosql.metadata.MetadataListing.listTableColumns(MetadataListing.java:106)
     at io.prestosql.connector.informationschema.InformationSchemaPageSource.addColumnsRecords(InformationSchemaPageSource.java:240)
     at io.prestosql.connector.informationschema.InformationSchemaPageSource.buildPages(InformationSchemaPageSource.java:208)
     at io.prestosql.connector.informationschema.InformationSchemaPageSource.getNextPage(InformationSchemaPageSource.java:175)
     at io.prestosql.operator.ScanFilterAndProjectOperator$ConnectorPageSourceToPages.process(ScanFilterAndProjectOperator.java:376)
     at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
     at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
     at io.prestosql.operator.WorkProcessorUtils.access$000(WorkProcessorUtils.java:37)
     at io.prestosql.operator.WorkProcessorUtils$YieldingProcess.process(WorkProcessorUtils.java:181)
     at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
     at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
     at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
     at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
     at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
     at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
     at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
     at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
     at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
     at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
     at io.prestosql.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:277)
     at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
     at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
     at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
     at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
     at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
     at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
     at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
     at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
     at io.prestosql.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
     at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
     at io.prestosql.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:149)
     at io.prestosql.operator.Driver.processInternal(Driver.java:379)
     at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
     at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
     at io.prestosql.operator.Driver.processFor(Driver.java:276)
     at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
     at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
     at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
     at io.prestosql.$gen.Presto_333____20200523_145016_2.run(Unknown Source)
     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
     at java.base/java.lang.Thread.run(Thread.java:834) 
```

See https://prestosql.slack.com/archives/CGB0QHWSW/p1590602983180000?thread_ts=1590602983.180000&cid=CGB0QHWSW for additional context and discussion.

**Comment by kokosing** [comment]
From attached slack discussion:

> Hive ignores all but the first character. Presto should probably do the same, and only validate when creating a new table.

> At the moment, you'll need to fix the table metadata to only have a single character (or patch Presto to skip the validation).

**Comment by hashhar** [comment]
Huh, the fix looks too simple to work. It passes tests locally.

For reference for existing Hive behaviour see https://github.com/apache/hive/blob/master/serde/src/java/org/apache/hadoop/hive/serde2/OpenCSVSerde.java#L98-L106.

Looking into adding some tests for this new behaviour. Also, should we log when we come across csvSerdeProperties > 1 char?
