### ISSUE TITLE
Flaky test TestEventListener

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#3943]
```
2020-06-06T17:12:28.3436166Z [ERROR] testOutputStats(io.prestosql.execution.TestEventListener)  Time elapsed: 6.947 s  <<< FAILURE!
2020-06-06T17:12:28.3439451Z java.lang.AssertionError: expected [0] but found [24]
2020-06-06T17:12:28.3442216Z 	at org.testng.Assert.fail(Assert.java:94)
2020-06-06T17:12:28.3445438Z 	at org.testng.Assert.failNotEquals(Assert.java:513)
2020-06-06T17:12:28.3449104Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
2020-06-06T17:12:28.3452273Z 	at org.testng.Assert.assertEquals(Assert.java:116)
2020-06-06T17:12:28.3455393Z 	at org.testng.Assert.assertEquals(Assert.java:284)
2020-06-06T17:12:28.3458600Z 	at org.testng.Assert.assertEquals(Assert.java:294)
2020-06-06T17:12:28.3464297Z 	at io.prestosql.execution.TestEventListener.testOutputStats(TestEventListener.java:379)
2020-06-06T17:12:28.3469300Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-06-06T17:12:28.3475461Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-06-06T17:12:28.3481985Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-06-06T17:12:28.3485153Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-06-06T17:12:28.3490380Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-06-06T17:12:28.3495600Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-06-06T17:12:28.3500326Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-06-06T17:12:28.3504999Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-06-06T17:12:28.3510787Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-06-06T17:12:28.3515792Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-06-06T17:12:28.3522090Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-06-06T17:12:28.3528179Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-06-06T17:12:28.3532364Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/745469582

**Comment by findepi** [comment]
`TestEventListener`.`testNormalQuery`:

```
2020-06-06T21:16:01.4727191Z [ERROR] testNormalQuery(io.prestosql.execution.TestEventListener)  Time elapsed: 0.306 s  <<< FAILURE!
2020-06-06T21:16:01.4727521Z java.lang.AssertionError: expected [0] but found [219]
2020-06-06T21:16:01.4727833Z 	at org.testng.Assert.fail(Assert.java:94)
2020-06-06T21:16:01.4728145Z 	at org.testng.Assert.failNotEquals(Assert.java:513)
2020-06-06T21:16:01.4728442Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
2020-06-06T21:16:01.4729076Z 	at org.testng.Assert.assertEquals(Assert.java:116)
2020-06-06T21:16:01.4729790Z 	at org.testng.Assert.assertEquals(Assert.java:284)
2020-06-06T21:16:01.4730488Z 	at org.testng.Assert.assertEquals(Assert.java:294)
2020-06-06T21:16:01.4731832Z 	at io.prestosql.execution.TestEventListener.testNormalQuery(TestEventListener.java:224)
2020-06-06T21:16:01.4733056Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-06-06T21:16:01.4734634Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-06-06T21:16:01.4736402Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-06-06T21:16:01.4738930Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-06-06T21:16:01.4739341Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-06-06T21:16:01.4739911Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-06-06T21:16:01.4740986Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-06-06T21:16:01.4741992Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-06-06T21:16:01.4743415Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-06-06T21:16:01.4744554Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-06-06T21:16:01.4746176Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-06-06T21:16:01.4747726Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-06-06T21:16:01.4748423Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Lewuathe** [comment]
The test query (`SELECT sum(linenumber) FROM lineitem`) is an aggregation. The memory pool usage can be positive (>0)?

If so I'm going to fix the test. 

```
        assertTrue(statistics.getPeakUserMemoryBytes() >= 0);
        assertTrue(statistics.getPeakTaskUserMemory() >= 0);
        assertTrue(statistics.getPeakTaskTotalMemory() >= 0);
        assertTrue(statistics.getCumulativeMemory() >= 0);

```

**Comment by findepi** [comment]
Failed in https://github.com/prestosql/presto/pull/3953

**Comment by wendigo** [comment]
Failed in https://github.com/prestosql/presto/pull/3670: https://github.com/prestosql/presto/pull/3670/checks?check_run_id=749160602

**Comment by findepi** [comment]
```
2020-06-10T17:00:03.6809090Z [ERROR] testOutputStats(io.prestosql.execution.TestEventListener)  Time elapsed: 7.383 s  <<< FAILURE!
2020-06-10T17:00:03.6809525Z java.lang.AssertionError: expected [0] but found [254]
2020-06-10T17:00:03.6809861Z 	at org.testng.Assert.fail(Assert.java:94)
2020-06-10T17:00:03.6810179Z 	at org.testng.Assert.failNotEquals(Assert.java:513)
2020-06-10T17:00:03.6810493Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
2020-06-10T17:00:03.6810791Z 	at org.testng.Assert.assertEquals(Assert.java:116)
2020-06-10T17:00:03.6811353Z 	at org.testng.Assert.assertEquals(Assert.java:284)
2020-06-10T17:00:03.6811660Z 	at org.testng.Assert.assertEquals(Assert.java:294)
2020-06-10T17:00:03.6812016Z 	at io.prestosql.execution.TestEventListener.testOutputStats(TestEventListener.java:380)
2020-06-10T17:00:03.6812351Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-06-10T17:00:03.6812694Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-06-10T17:00:03.6813071Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-06-10T17:00:03.6813977Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-06-10T17:00:03.6815389Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-06-10T17:00:03.6816284Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-06-10T17:00:03.6817291Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-06-10T17:00:03.6818424Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-06-10T17:00:03.6819608Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-06-10T17:00:03.6820280Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-06-10T17:00:03.6824578Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-06-10T17:00:03.6825096Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-06-10T17:00:03.6825410Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

cc @Lewuathe

**Comment by Lewuathe** [comment]
Sorry, I’ll take a look.

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/791316376

**Comment by sopel39** [comment]
Fixed by: https://github.com/prestosql/presto/pull/3996
