### ISSUE TITLE
prestosql server 'array' data type is not backwards compatible with prestodb jdbc driver

### ISSUE THREAD

**Issue by tooptoop4** [prestosql/presto#3976]
1. create table via hiveserver2 pointing at json data
```
CREATE EXTERNAL TABLE `junk.tbl`(
  `destinationkey` string COMMENT 'from deserializer', 
  `securityid` string COMMENT 'from deserializer', 
  `settlementtype` string COMMENT 'from deserializer', 
  `snapshottimestamputcinmillis` string COMMENT 'from deserializer', 
  `destinationpricemode` string COMMENT 'from deserializer', 
  `pricelevels` array<struct<entryid:string,entrytype:string,entryprice:string,entrysize:string>> COMMENT 'from deserializer')
ROW FORMAT SERDE 
  'org.apache.hive.hcatalog.data.JsonSerDe' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.mapred.TextInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
  's3a://bla'
```
2. with prestodb 220 server and  prestodb 220 JDBC client , select SQL works
3. with prestosql 334 server and  prestosql 334 JDBC client , select SQL works
4. with prestosql 334 server and  prestodb 220 JDBC client , select SQL errors below:

```
2020-06-09 16:23:42,361 [Thread-5] DEBUG net.sourceforge.squirrel_sql.fw.util.TaskThreadPool  - Using a thread. 1 threads available
2020-06-09 16:23:42,677 [Thread-5] DEBUG net.sourceforge.squirrel_sql.fw.util.DefaultExceptionFormatter  - Error
java.sql.SQLException: Error executing query
	at com.facebook.presto.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:279)
	at com.facebook.presto.jdbc.PrestoStatement.execute(PrestoStatement.java:228)
	at net.sourceforge.squirrel_sql.client.session.StatementWrapper.execute(StatementWrapper.java:168)
	at net.sourceforge.squirrel_sql.client.session.SQLExecuterTask.processQuery(SQLExecuterTask.java:355)
	at net.sourceforge.squirrel_sql.client.session.SQLExecuterTask.run(SQLExecuterTask.java:209)
	at net.sourceforge.squirrel_sql.fw.util.TaskExecuter.run(TaskExecuter.java:82)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Error fetching next at https://redact/v1/statement/executing/20200609_152342_09394_mhsjf/y6f89a8f2fffb7ab3dd58e126400497a7d82e0783/0 returned an invalid response: JsonResponse{statusCode=200, statusMessage=OK, headers={content-type=[application/json], date=[Tue, 09 Jun 2020 15:23:42 GMT], vary=[Accept-Encoding, User-Agent], x-content-type-options=[nosniff]}, hasValue=false} [Error: 
]
	at com.facebook.presto.jdbc.internal.client.StatementClientV1.requestFailedException(StatementClientV1.java:458)
	at com.facebook.presto.jdbc.PrestoResultSet.getColumns(PrestoResultSet.java:1742)
	at com.facebook.presto.jdbc.PrestoResultSet.<init>(PrestoResultSet.java:119)
	at com.facebook.presto.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:250)
	... 6 more
Caused by: java.lang.IllegalArgumentException: Unable to create class com.facebook.presto.jdbc.internal.client.QueryResults from JSON response:
]
	at com.facebook.presto.jdbc.internal.client.JsonResponse.<init>(JsonResponse.java:70)
	at com.facebook.presto.jdbc.internal.client.JsonResponse.execute(JsonResponse.java:144)
	at com.facebook.presto.jdbc.internal.client.StatementClientV1.advance(StatementClientV1.java:383)
	... 9 more
Caused by: java.lang.IllegalArgumentException: Invalid JSON string for [simple type, class com.facebook.presto.jdbc.internal.client.QueryResults]
	at com.facebook.presto.jdbc.internal.airlift.json.JsonCodec.fromJson(JsonCodec.java:137)
	at com.facebook.presto.jdbc.internal.client.JsonResponse.<init>(JsonResponse.java:67)
	... 11 more
Caused by: com.facebook.presto.jdbc.internal.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.facebook.presto.jdbc.internal.spi.type.TypeSignature` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.facebook.presto.jdbc.internal.client.QueryResults["columns"]->java.util.ArrayList[5]->com.facebook.presto.jdbc.internal.client.Column["typeSignature"]->com.facebook.presto.jdbc.internal.client.ClientTypeSignature["arguments"]->java.util.ArrayList[0]->com.facebook.presto.jdbc.internal.client.ClientTypeSignature["arguments"]->java.util.ArrayList[0]->com.facebook.presto.jdbc.internal.spi.type.NamedTypeSignature["typeSignature"])
	at com.facebook.presto.jdbc.internal.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.facebook.presto.jdbc.internal.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1343)
	at com.facebook.presto.jdbc.internal.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1032)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1297)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.facebook.presto.jdbc.internal.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3984)
	at com.facebook.presto.jdbc.internal.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2276)
	at com.facebook.presto.jdbc.internal.client.ClientTypeSignatureParameter$ClientTypeSignatureParameterDeserializer.deserialize(ClientTypeSignatureParameter.java:151)
	at com.facebook.presto.jdbc.internal.client.ClientTypeSignatureParameter$ClientTypeSignatureParameterDeserializer.deserialize(ClientTypeSignatureParameter.java:133)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.facebook.presto.jdbc.internal.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3984)
	at com.facebook.presto.jdbc.internal.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2276)
	at com.facebook.presto.jdbc.internal.client.ClientTypeSignatureParameter$ClientTypeSignatureParameterDeserializer.deserialize(ClientTypeSignatureParameter.java:148)
	at com.facebook.presto.jdbc.internal.client.ClientTypeSignatureParameter$ClientTypeSignatureParameterDeserializer.deserialize(ClientTypeSignatureParameter.java:133)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.facebook.presto.jdbc.internal.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.facebook.presto.jdbc.internal.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3042)
	at com.facebook.presto.jdbc.internal.airlift.json.JsonCodec.fromJson(JsonCodec.java:134)
	... 12 more
2020-06-09 16:23:42,680 [Thread-5] DEBUG net.sourceforge.squirrel_sql.fw.util.TaskThreadPool  - Returning thread. 2 threads available
2020-06-09 16:23:52,932 [AWT-EventQueue-1] DEBUG net.sourceforge.squirrel_sql.fw.util.TaskThreadPool  - Reusing existing thread
2020-06-09 16:23:52,932 [Thread-4] DEBUG net.sourceforge.squirrel_sql.fw.util.TaskThreadPool  - Using a thread. 1 threads available
2020-06-09 16:23:53,298 [Thread-4] DEBUG net.sourceforge.squirrel_sql.fw.util.DefaultExceptionFormatter  - Error
java.sql.SQLException: Error executing query
	at com.facebook.presto.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:279)
	at com.facebook.presto.jdbc.PrestoStatement.execute(PrestoStatement.java:228)
	at net.sourceforge.squirrel_sql.client.session.StatementWrapper.execute(StatementWrapper.java:168)
	at net.sourceforge.squirrel_sql.client.session.SQLExecuterTask.processQuery(SQLExecuterTask.java:355)
	at net.sourceforge.squirrel_sql.client.session.SQLExecuterTask.run(SQLExecuterTask.java:209)
	at net.sourceforge.squirrel_sql.fw.util.TaskExecuter.run(TaskExecuter.java:82)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Error fetching next at https://redact/v1/statement/executing/20200609_152352_09395_mhsjf/y52e5cc1f5a467401fa210fde95a9b79e680f9606/0 returned an invalid response: JsonResponse{statusCode=200, statusMessage=OK, headers={content-type=[application/json], date=[Tue, 09 Jun 2020 15:23:53 GMT], vary=[Accept-Encoding, User-Agent], x-content-type-options=[nosniff]}, hasValue=false} [Error: {"id":"20200609_152352_09395_mhsjf","infoUri":"https://redact/ui/query.html?20200609_152352_09395_mhsjf","partialCancelUri":"https://redact/v1/statement/executing/partialCancel/20200609_152352_09395_mhsjf/1/y986825777ecfe806d242eb23f21445432be60b26/1","nextUri":"https://redact/v1/statement/executing/20200609_152352_09395_mhsjf/y986825777ecfe806d242eb23f21445432be60b26/1","columns":[{"name":"pricelevels","type":"array(row(entryid varchar, entrytype varchar, entryprice varchar, entrysize varchar))"
	at com.facebook.presto.jdbc.internal.client.StatementClientV1.requestFailedException(StatementClientV1.java:458)
	at com.facebook.presto.jdbc.internal.client.StatementClientV1.advance(StatementClientV1.java:397)
	at com.facebook.presto.jdbc.PrestoResultSet.getColumns(PrestoResultSet.java:1742)
	at com.facebook.presto.jdbc.PrestoResultSet.<init>(PrestoResultSet.java:119)
	at com.facebook.presto.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:250)
	... 6 more
Caused by: java.lang.IllegalArgumentException: Unable to create class com.facebook.presto.jdbc.internal.client.QueryResults from JSON response:
[{"id":"20200609_152352_09395_mhsjf","infoUri":"https://redact/ui/query.html?20200609_152352_09395_mhsjf","partialCancelUri":"https://redact/v1/statement/executing/partialCancel/20200609_152352_09395_mhsjf/1/y986825777ecfe806d242eb23f21445432be60b26/1","nextUri":"https://redact/v1/statement/executing/20200609_152352_09395_mhsjf/y986825777ecfe806d242eb23f21445432be60b26/1","columns":[{"name":"pricelevels","type":"array(row(entryid varchar, entrytype varchar, entryprice varchar, entrysize varchar))"
]
	at com.facebook.presto.jdbc.internal.client.JsonResponse.<init>(JsonResponse.java:70)
	at com.facebook.presto.jdbc.internal.client.JsonResponse.execute(JsonResponse.java:144)
	at com.facebook.presto.jdbc.internal.client.StatementClientV1.advance(StatementClientV1.java:383)
	... 9 more
Caused by: java.lang.IllegalArgumentException: Invalid JSON string for [simple type, class com.facebook.presto.jdbc.internal.client.QueryResults]
	at com.facebook.presto.jdbc.internal.airlift.json.JsonCodec.fromJson(JsonCodec.java:137)
	at com.facebook.presto.jdbc.internal.client.JsonResponse.<init>(JsonResponse.java:67)
	... 11 more
Caused by: com.facebook.presto.jdbc.internal.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.facebook.presto.jdbc.internal.spi.type.TypeSignature` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.facebook.presto.jdbc.internal.client.QueryResults["columns"]->java.util.ArrayList[0]->com.facebook.presto.jdbc.internal.client.Column["typeSignature"]->com.facebook.presto.jdbc.internal.client.ClientTypeSignature["arguments"]->java.util.ArrayList[0]->com.facebook.presto.jdbc.internal.client.ClientTypeSignature["arguments"]->java.util.ArrayList[0]->com.facebook.presto.jdbc.internal.spi.type.NamedTypeSignature["typeSignature"])
	at com.facebook.presto.jdbc.internal.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.facebook.presto.jdbc.internal.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1343)
	at com.facebook.presto.jdbc.internal.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1032)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1297)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.facebook.presto.jdbc.internal.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3984)
	at com.facebook.presto.jdbc.internal.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2276)
	at com.facebook.presto.jdbc.internal.client.ClientTypeSignatureParameter$ClientTypeSignatureParameterDeserializer.deserialize(ClientTypeSignatureParameter.java:151)
	at com.facebook.presto.jdbc.internal.client.ClientTypeSignatureParameter$ClientTypeSignatureParameterDeserializer.deserialize(ClientTypeSignatureParameter.java:133)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.facebook.presto.jdbc.internal.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3984)
	at com.facebook.presto.jdbc.internal.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2276)
	at com.facebook.presto.jdbc.internal.client.ClientTypeSignatureParameter$ClientTypeSignatureParameterDeserializer.deserialize(ClientTypeSignatureParameter.java:148)
	at com.facebook.presto.jdbc.internal.client.ClientTypeSignatureParameter$ClientTypeSignatureParameterDeserializer.deserialize(ClientTypeSignatureParameter.java:133)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.facebook.presto.jdbc.internal.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.facebook.presto.jdbc.internal.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.facebook.presto.jdbc.internal.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3042)
	at com.facebook.presto.jdbc.internal.airlift.json.JsonCodec.fromJson(JsonCodec.java:134)
	... 12 more
2020-06-09 16:23:53,299 [Thread-4] DEBUG net.sourceforge.squirrel_sql.fw.util.TaskThreadPool  - Returning thread. 2 threads available
```

I saw previously that "select uuid()" would not work with prestodb JDBC driver, now also sharing that ARRAY does not work

**Comment by asronihidayat** [comment]
so, is this expected for not backward compatible with prestodb jdbc driver?
we use metabase, that only support for presto, any plan for building custom trino driver for metabase?
thanks!
