### ISSUE TITLE
Flaky test TestDruidIntegrationSmokeTest.testConcurrentScans

### ISSUE THREAD

**Issue by sopel39** [prestosql/presto#4134]
```
2020-06-22T02:17:27.9605464Z 	at org.testng.Assert.fail(Assert.java:83)
2020-06-22T02:17:27.9612162Z 	at io.prestosql.testing.QueryAssertions.assertQuery(QueryAssertions.java:150)
2020-06-22T02:17:27.9618611Z 	at io.prestosql.testing.QueryAssertions.assertQuery(QueryAssertions.java:106)
2020-06-22T02:17:27.9626044Z 	at io.prestosql.testing.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:130)
2020-06-22T02:17:27.9634580Z 	at io.prestosql.testing.AbstractTestIntegrationSmokeTest.testConcurrentScans(AbstractTestIntegrationSmokeTest.java:195)
2020-06-22T02:17:27.9640818Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-06-22T02:17:27.9648465Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-06-22T02:17:27.9656562Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-06-22T02:17:27.9661630Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-06-22T02:17:27.9668495Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-06-22T02:17:27.9673535Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-06-22T02:17:27.9678810Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-06-22T02:17:27.9684565Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-06-22T02:17:27.9691329Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-06-22T02:17:27.9697215Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-06-22T02:17:27.9704266Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-06-22T02:17:27.9711376Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-06-22T02:17:27.9715812Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-06-22T02:17:27.9723188Z Caused by: java.lang.RuntimeException: Remote driver error: ISE: Too many connections, limit is[25]
2020-06-22T02:17:27.9730437Z 	at io.prestosql.testing.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:114)
2020-06-22T02:17:27.9737287Z 	at io.prestosql.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:443)
2020-06-22T02:17:27.9743350Z 	at io.prestosql.testing.QueryAssertions.assertQuery(QueryAssertions.java:147)
2020-06-22T02:17:27.9745338Z 	... 16 more
2020-06-22T02:17:27.9752960Z Caused by: io.prestosql.spi.PrestoException: Remote driver error: ISE: Too many connections, limit is[25]
2020-06-22T02:17:27.9759777Z 	at io.prestosql.plugin.jdbc.JdbcRecordCursor.handleSqlException(JdbcRecordCursor.java:250)
2020-06-22T02:17:27.9774137Z 	at io.prestosql.plugin.jdbc.JdbcRecordCursor.<init>(JdbcRecordCursor.java:106)
2020-06-22T02:17:27.9780071Z 	at io.prestosql.plugin.jdbc.JdbcRecordSet.cursor(JdbcRecordSet.java:60)
2020-06-22T02:17:27.9786190Z 	at io.prestosql.spi.connector.RecordPageSource.<init>(RecordPageSource.java:37)
2020-06-22T02:17:27.9793539Z 	at io.prestosql.split.RecordPageSourceProvider.createPageSource(RecordPageSourceProvider.java:50)
2020-06-22T02:17:27.9799906Z 	at io.prestosql.split.PageSourceManager.createPageSource(PageSourceManager.java:64)
```

**Comment by sopel39** [comment]
https://github.com/prestosql/presto/pull/3996/checks?check_run_id=793657965

**Comment by findepi** [comment]
cc @samarthjain

**Comment by findepi** [comment]
With

```diff
--- presto-testing/src/main/java/io/prestosql/testing/AbstractTestIntegrationSmokeTest.java
+++ presto-testing/src/main/java/io/prestosql/testing/AbstractTestIntegrationSmokeTest.java
@@ -188,11 +188,11 @@ public abstract class AbstractTestIntegrationSmokeTest
                 "WHERE orderkey BETWEEN 10 AND 50");
     }

-    @Test
+    @Test(invocationCount = 10)
     public void testConcurrentScans()
     {
-        String unionMultipleTimes = join(" UNION ALL ", nCopies(25, "SELECT * FROM orders"));
-        assertQuery("SELECT sum(if(rand() >= 0, orderkey)) FROM (" + unionMultipleTimes + ")", "VALUES 11246812500");
+        String unionMultipleTimes = join(" UNION ALL ", nCopies(50, "SELECT * FROM orders"));
+        assertQuery("SELECT sum(if(rand() >= 0, orderkey)) FROM (" + unionMultipleTimes + ")", "VALUES 11246812500 * 2");
     }
```

i got a failure (1 of 10, first time only).

**Comment by samarthjain** [comment]
Interesting. Taking a look.

**Comment by samarthjain** [comment]
Looks like there is a limit on number of open connections (default 25) through the Avatica Driver. 
https://druid.apache.org/docs/latest/configuration/index.html#sql
```
druid.sql.avatica.maxConnections  -  Maximum number of open connections for the Avatica server. These are not HTTP connections, but are logical client connections that may span multiple HTTP connections.

**Comment by samarthjain** [comment]
PR for fix - https://github.com/prestosql/presto/pull/4148

**Comment by findepi** [comment]
https://github.com/prestosql/presto/pull/4148
