### ISSUE TITLE
Presto error from Qubole

### ISSUE THREAD

**Issue by spachari** [prestosql/presto#4145]
I have a Presto sql (run from Qubole) that takes data from a table, does some ETL and loads the output to s3. I am getting this error. But if i remove the insert into statement, the sql works fine. Can anyone tell me what this error means?

`[2020-06-22T07:30:45.275476 #23540] ERROR -- : Command execution failed with exception: Query 20200622_073044_00044_2kaye failed: com.facebook.presto.spi.PrestoException
Expected response code from http://172.31.40.174:8081/v1/task/20200622_073044_00044_2kaye.3.13/status to be 200, but was 500: Internal Server Error
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@99f8bf8 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@75bc50dd[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 10196]
at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
at com.google.common.util.concurrent.TimeoutFuture.create(TimeoutFuture.java:44)
at com.google.common.util.concurrent.Futures.withTimeout(Futures.java:540)
at com.google.common.util.concurrent.FluentFuture.withTimeout(FluentFuture.java:209)`

**Comment by losipiuk** [comment]
@spachari  you are providing too little context. Not even a query you ara trying to run. The best way to approach investigation of problem like this one is to reach out to people on prestosql.slack.com on `#troubleshooting` channel. 

Would that be fine to close this issue for now and continue investigation on slack?

**Comment by raunaqmorarka** [comment]
@spachari please connect with Qubole support through zendesk (https://qubole.zendesk.com/agent/tickets/38447) first for any issues encountered while using Presto on Qubole platform. I believe our support is already working on solving your issues.
