### ISSUE TITLE
Failed to load a Hadoop configuration file with Xinclude as relative path in presto-hive

### ISSUE THREAD

**Issue by crossfire** [prestosql/presto#4208]
I found an issue that Presto failed to load a Hadoop configuration file with Xinclude which is specified as relative path after https://github.com/prestosql/presto/commit/5aa29ae7759c209b9c8bce330a45d17b0fb0470c is merged.
The cause is that Hadoop library converts from URI object to string using `toString()`, passes it to File constructor and fails to handle a relative path (I reported https://issues.apache.org/jira/browse/HADOOP-17088).
I think it is Hadoop issue rather than Presto one, but I can't load a configuration file now, so could you consider to revert [this change](https://github.com/prestosql/presto/commit/5aa29ae7759c209b9c8bce330a45d17b0fb0470c#diff-7eeb754f82d7f6a46829e6f9afbf9a08)?
Thanks.

```
28) Error injecting constructor, java.lang.RuntimeException: java.io.IOException: Fetch fail on include for 'mountTable.xml' with no fallback while loading 'file:/opt/hadoop/etc/hadoop/core-site.xml'
  at io.prestosql.plugin.hive.HdfsConfigurationInitializer.<init>(HdfsConfigurationInitializer.java:70)
  at io.prestosql.plugin.hive.HiveHdfsModule.configure(HiveHdfsModule.java:35) (via modules: io.prestosql.plugin.hive.HiveModule -> io.prestosql.plugin.hive.HiveHdfsModule)
  while locating io.prestosql.plugin.hive.HdfsConfigurationInitializer
Caused by: java.lang.RuntimeException: java.io.IOException: Fetch fail on include for 'mountTable.xml' with no fallback while loading 'file:/opt/hadoop/etc/hadoop/core-site.xml'
        at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:2978)
        at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:2930)
        at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2805)
        at org.apache.hadoop.conf.Configuration.iterator(Configuration.java:2853)
        at io.prestosql.plugin.hive.util.ConfigurationUtils.copy(ConfigurationUtils.java:57)
        at io.prestosql.plugin.hive.util.ConfigurationUtils.readConfiguration(ConfigurationUtils.java:79)
        at io.prestosql.plugin.hive.HdfsConfigurationInitializer.<init>(HdfsConfigurationInitializer.java:80)
        at io.prestosql.plugin.hive.HdfsConfigurationInitializer$$FastClassByGuice$$a796c3eb.newInstance(<generated>)
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
        at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
        at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
        at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:111)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:262)
        at io.prestosql.plugin.hive.InternalHiveConnectorFactory.createConnector(InternalHiveConnectorFactory.java:113)
        at io.prestosql.plugin.hive.InternalHiveConnectorFactory.createConnector(InternalHiveConnectorFactory.java:74)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.prestosql.plugin.hive.HiveConnectorFactory.create(HiveConnectorFactory.java:63)
        at io.prestosql.connector.ConnectorManager.createConnector(ConnectorManager.java:349)
        at io.prestosql.connector.ConnectorManager.createCatalog(ConnectorManager.java:208)
        at io.prestosql.connector.ConnectorManager.createCatalog(ConnectorManager.java:200)
        at io.prestosql.connector.ConnectorManager.createCatalog(ConnectorManager.java:186)
        at io.prestosql.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:88)
        at io.prestosql.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
        at io.prestosql.server.PrestoServer.run(PrestoServer.java:118)
        at io.prestosql.$gen.Presto_332____20200623_053410_1.run(Unknown Source)
        at io.prestosql.server.PrestoServer.main(PrestoServer.java:72)
Caused by: java.io.IOException: Fetch fail on include for 'mountTable.xml' with no fallback while loading 'file:/opt/hadoop/etc/hadoop/core-site.xml'
        at org.apache.hadoop.conf.Configuration$Parser.handleEndElement(Configuration.java:3228)
        at org.apache.hadoop.conf.Configuration$Parser.parseNext(Configuration.java:3288)
        at org.apache.hadoop.conf.Configuration$Parser.parse(Configuration.java:3071)
        at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:2964)
        ... 41 more
```

**Comment by crossfire** [comment]
I created a PR.
