### ISSUE TITLE
TestServer.testFirstResponseColumns is flaky

### ISSUE THREAD

**Issue by kokosing** [prestosql/presto#4218]
```
2020-06-25T08:40:18.3546134Z [ERROR] Tests run: 6592, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 892.455 s <<< FAILURE! - in TestSuite
2020-06-25T08:40:18.3553376Z [ERROR] testFirstResponseColumns(io.prestosql.server.TestServer)  Time elapsed: 0.012 s  <<< FAILURE!
2020-06-25T08:40:18.3555664Z java.lang.AssertionError: 
2020-06-25T08:40:18.3556507Z 
2020-06-25T08:40:18.3557907Z Expecting:
2020-06-25T08:40:18.3559508Z  <"FINISHING">
2020-06-25T08:40:18.3561148Z to be equal to:
2020-06-25T08:40:18.3562642Z  <"RUNNING">
2020-06-25T08:40:18.3564141Z but was not.
2020-06-25T08:40:18.3569102Z 	at io.prestosql.server.TestServer.testFirstResponseColumns(TestServer.java:161)
2020-06-25T08:40:18.3574496Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-06-25T08:40:18.3580529Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-06-25T08:40:18.3586921Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-06-25T08:40:18.3591220Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-06-25T08:40:18.3596814Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-06-25T08:40:18.3600892Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-06-25T08:40:18.3605164Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-06-25T08:40:18.3609517Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-06-25T08:40:18.3615004Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-06-25T08:40:18.3619536Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-06-25T08:40:18.3625180Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-06-25T08:40:18.3630806Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-06-25T08:40:18.3634313Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-06-25T08:40:18.3635172Z 
2020-06-25T08:40:19.6684713Z [INFO] 
2020-06-25T08:40:19.6691740Z [INFO] Results:
2020-06-25T08:40:19.6692313Z [INFO] 
2020-06-25T08:40:19.6692755Z [ERROR] Failures: 
2020-06-25T08:40:19.6693216Z [ERROR]   TestServer.testFirstResponseColumns:161 
2020-06-25T08:40:19.6693689Z Expecting:
```

**Comment by findepi** [comment]
cc @wendigo

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/810278829?check_suite_focus=true

**Comment by wendigo** [comment]
https://github.com/prestosql/presto/pull/4239 I've created an issue for this as well

**Comment by wendigo** [comment]
Should be solved.
