### ISSUE TITLE
Flaky TestServer.testFirstResponseColumns

### ISSUE THREAD

**Issue by wendigo** [prestosql/presto#4238]
```
2020-06-26T08:23:56.6979716Z [ERROR] testFirstResponseColumns(io.prestosql.server.TestServer)  Time elapsed: 0.011 s  <<< FAILURE!
2020-06-26T08:23:56.6982264Z java.lang.AssertionError: 
2020-06-26T08:23:56.6983206Z 
2020-06-26T08:23:56.6984757Z Expecting:
2020-06-26T08:23:56.6987171Z  <"FINISHED">
2020-06-26T08:23:56.6989054Z to be equal to:
2020-06-26T08:23:56.6990714Z  <"RUNNING">
2020-06-26T08:23:56.6992363Z but was not.
2020-06-26T08:23:56.6998385Z 	at io.prestosql.server.TestServer.testFirstResponseColumns(TestServer.java:161)
2020-06-26T08:23:56.7004657Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-06-26T08:23:56.7011730Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-06-26T08:23:56.7018963Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-06-26T08:23:56.7023510Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-06-26T08:23:56.7029709Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-06-26T08:23:56.7034640Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-06-26T08:23:56.7039606Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-06-26T08:23:56.7044518Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-06-26T08:23:56.7049890Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-06-26T08:23:56.7054982Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-06-26T08:23:56.7088716Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-06-26T08:23:56.7095265Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-06-26T08:23:56.7099350Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-06-26T08:23:56.7100360Z 
2020-06-26T08:23:58.9093910Z [INFO] 
2020-06-26T08:23:58.9094550Z [INFO] Results:
2020-06-26T08:23:58.9094882Z [INFO] 
2020-06-26T08:23:58.9095208Z [ERROR] Failures: 
2020-06-26T08:23:58.9095555Z [ERROR]   TestServer.testFirstResponseColumns:161 
2020-06-26T08:23:58.9095859Z Expecting:
2020-06-26T08:23:58.9096151Z  <"FINISHED">
2020-06-26T08:23:58.9096456Z to be equal to:
2020-06-26T08:23:58.9096747Z  <"RUNNING">
2020-06-26T08:23:58.9097060Z but was not.
```

Happened on https://github.com/prestosql/presto/pull/4223/checks

**Comment by wendigo** [comment]
Duplicate of https://github.com/prestosql/presto/issues/4218
