### ISSUE TITLE
Dynamic Filter failure in presence of NaN

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#4272]
```
java.lang.IllegalArgumentException: cannot use NaN as range bound
	at io.prestosql.spi.predicate.Marker.<init>(Marker.java:74)
	at io.prestosql.spi.predicate.Marker.create(Marker.java:83)
	at io.prestosql.spi.predicate.Marker.exactly(Marker.java:109)
	at io.prestosql.spi.predicate.Range.equal(Range.java:84)
	at io.prestosql.spi.predicate.ValueSet.lambda$copyOf$0(ValueSet.java:72)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.prestosql.spi.predicate.ValueSet.copyOf(ValueSet.java:73)
	at io.prestosql.operator.DynamicFilterSourceOperator.convertToDomain(DynamicFilterSourceOperator.java:260)
	at io.prestosql.operator.DynamicFilterSourceOperator.finish(DynamicFilterSourceOperator.java:243)
	at io.prestosql.operator.Driver.processInternal(Driver.java:397)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_testversion____20200630_114557_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by findepi** [comment]
cc @raunaqmorarka

**Comment by findepi** [comment]
Indeed, there is a potential failure. I added a stacktrace to the issue.
