### ISSUE TITLE
Flaky test TestMongoDistributedQueries.testWrittenStats

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#4275]
```
2020-06-29T23:57:43.9949802Z [ERROR] Tests run: 197, Failures: 1, Errors: 0, Skipped: 12, Time elapsed: 482.517 s <<< FAILURE! - in TestSuite
2020-06-29T23:57:43.9952140Z [ERROR] testWrittenStats(io.prestosql.plugin.mongodb.TestMongoDistributedQueries)  Time elapsed: 0.179 s  <<< FAILURE!
2020-06-29T23:57:43.9952536Z java.lang.AssertionError: expected [1] but found [0]
2020-06-29T23:57:43.9952812Z 	at org.testng.Assert.fail(Assert.java:94)
2020-06-29T23:57:43.9953073Z 	at org.testng.Assert.failNotEquals(Assert.java:513)
2020-06-29T23:57:43.9953319Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
2020-06-29T23:57:43.9953584Z 	at org.testng.Assert.assertEquals(Assert.java:116)
2020-06-29T23:57:43.9953839Z 	at org.testng.Assert.assertEquals(Assert.java:284)
2020-06-29T23:57:43.9954092Z 	at org.testng.Assert.assertEquals(Assert.java:294)
2020-06-29T23:57:43.9954395Z 	at io.prestosql.testing.AbstractTestDistributedQueries.testWrittenStats(AbstractTestDistributedQueries.java:1149)
2020-06-29T23:57:43.9955727Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-06-29T23:57:43.9956042Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-06-29T23:57:43.9956342Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-06-29T23:57:43.9956621Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-06-29T23:57:43.9956898Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-06-29T23:57:43.9957171Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-06-29T23:57:43.9957436Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-06-29T23:57:43.9957703Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-06-29T23:57:43.9958156Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-06-29T23:57:43.9958500Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-06-29T23:57:43.9958794Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-06-29T23:57:43.9959076Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-06-29T23:57:43.9959344Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by findepi** [comment]
Actually this looks more like a core or connector's bug, not test's.

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/1130654951

**Comment by sopel39** [comment]
https://github.com/prestosql/presto/pull/5237/checks?check_run_id=1149970099

**Comment by sopel39** [comment]
It looks like related to: https://github.com/prestosql/presto/issues/5172

**Comment by findepi** [comment]
Closing in favor of https://github.com/prestosql/presto/issues/5172
