### ISSUE TITLE
Flaky test TestHiveIntegrationSmokeTest.testParquetTimestampPredicatePushdown

### ISSUE THREAD

**Issue by sopel39** [prestosql/presto#4314]
```2020-07-01T22:33:57.6602506Z [ERROR] Tests run: 1506, Failures: 1, Errors: 0, Skipped: 72, Time elapsed: 1,774.171 s <<< FAILURE! - in TestSuite
2020-07-01T22:33:57.6609950Z [ERROR] testParquetTimestampPredicatePushdown(io.prestosql.plugin.hive.TestHiveIntegrationSmokeTest)  Time elapsed: 0.433 s  <<< FAILURE!
2020-07-01T22:33:57.6624879Z java.lang.AssertionError: 
2020-07-01T22:33:57.6625170Z 
2020-07-01T22:33:57.6626139Z Expecting:
2020-07-01T22:33:57.6626295Z  <0L>
2020-07-01T22:33:57.6627381Z to be greater than:
2020-07-01T22:33:57.6627791Z  <0L> 
2020-07-01T22:33:57.6635725Z 	at io.prestosql.plugin.hive.TestHiveIntegrationSmokeTest.testParquetTimestampPredicatePushdown(TestHiveIntegrationSmokeTest.java:4135)
2020-07-01T22:33:57.6640344Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-07-01T22:33:57.6645766Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-07-01T22:33:57.6651629Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-07-01T22:33:57.6662721Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-07-01T22:33:57.6666980Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-07-01T22:33:57.6669659Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-07-01T22:33:57.6672773Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-07-01T22:33:57.6676372Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-07-01T22:33:57.6748641Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-07-01T22:33:57.6752787Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-07-01T22:33:57.6757887Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-07-01T22:33:57.6762828Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-07-01T22:33:57.6765611Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

https://github.com/prestosql/presto/pull/4224/checks?check_run_id=828279182

**Comment by wendigo** [comment]
https://github.com/prestosql/presto/pull/4296/checks

**Comment by findepi** [comment]
cc @alexjo2144

**Comment by alexjo2144** [comment]
If query stats are updated async we might be reading them before they're updated?

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/832377534?check_suite_focus=true

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/834476582
