### ISSUE TITLE
Flaky io.prestosql.plugin.phoenix.TestPhoenixDistributedQueries.testWrittenStats

### ISSUE THREAD

**Issue by wendigo** [prestosql/presto#4386]
```
2020-07-08T10:27:04.0595962Z [ERROR] Tests run: 193, Failures: 1, Errors: 0, Skipped: 50, Time elapsed: 465.109 s <<< FAILURE! - in TestSuite
2020-07-08T10:27:04.0608071Z [ERROR] testWrittenStats(io.prestosql.plugin.phoenix.TestPhoenixDistributedQueries)  Time elapsed: 1.405 s  <<< FAILURE!
2020-07-08T10:27:04.0612206Z java.lang.AssertionError: expected [1] but found [0]
2020-07-08T10:27:04.0615653Z 	at org.testng.Assert.fail(Assert.java:94)
2020-07-08T10:27:04.0619668Z 	at org.testng.Assert.failNotEquals(Assert.java:513)
2020-07-08T10:27:04.0624135Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
2020-07-08T10:27:04.0628107Z 	at org.testng.Assert.assertEquals(Assert.java:116)
2020-07-08T10:27:04.0632022Z 	at org.testng.Assert.assertEquals(Assert.java:284)
2020-07-08T10:27:04.0636090Z 	at org.testng.Assert.assertEquals(Assert.java:294)
2020-07-08T10:27:04.0643701Z 	at io.prestosql.testing.AbstractTestDistributedQueries.testWrittenStats(AbstractTestDistributedQueries.java:1149)
2020-07-08T10:27:04.0649458Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-07-08T10:27:04.0656220Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-07-08T10:27:04.0663651Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-07-08T10:27:04.0668277Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-07-08T10:27:04.0675032Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-07-08T10:27:04.0679604Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-07-08T10:27:04.0684374Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-07-08T10:27:04.0689245Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-07-08T10:27:04.0695161Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-07-08T10:27:04.0700256Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-07-08T10:27:04.0706580Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-07-08T10:27:04.0713096Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-07-08T10:27:04.0717145Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-07-08T10:27:04.0718122Z 
```

**Comment by sopel39** [comment]
Looks like related to: https://github.com/prestosql/presto/issues/5172

**Comment by findepi** [comment]
Closing in favor of https://github.com/prestosql/presto/issues/5172
