### ISSUE TITLE
Flaky io.prestosql.tests.hive.TestCsv.testInsertIntoPartitionedCsvTable

### ISSUE THREAD

**Issue by wendigo** [prestosql/presto#4404]
```
2020-07-09T14:39:41.0265204Z tests               | 2020-07-09 20:24:41 INFO: FAILURE     /    io.prestosql.tests.hive.TestCsv.testInsertIntoPartitionedCsvTable (Groups: storage_formats) took 4.6 seconds
2020-07-09T14:39:41.0311897Z tests               | 2020-07-09 20:24:41 SEVERE: Failure cause:
2020-07-09T14:39:41.0317899Z tests               | io.prestosql.tempto.query.QueryExecutionException: java.sql.SQLException: Query failed (#20200709_143936_00641_rnjt5): Error committing write to Hive
2020-07-09T14:39:41.0319062Z tests               | 	at io.prestosql.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:114)
2020-07-09T14:39:41.0320269Z tests               | 	at io.prestosql.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:82)
2020-07-09T14:39:41.0321071Z tests               | 	at io.prestosql.tempto.query.QueryExecutor.query(QueryExecutor.java:57)
2020-07-09T14:39:41.0322557Z tests               | 	at io.prestosql.tests.hive.TestCsv.testInsertIntoPartitionedCsvTable(TestCsv.java:127)
2020-07-09T14:39:41.0323109Z tests               | 	at io.prestosql.tests.hive.TestCsv.testInsertIntoPartitionedCsvTable(TestCsv.java:102)
2020-07-09T14:39:41.0323278Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-07-09T14:39:41.0323440Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-07-09T14:39:41.0323801Z tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-07-09T14:39:41.0323950Z tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-07-09T14:39:41.0324098Z tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-07-09T14:39:41.0324501Z tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-07-09T14:39:41.0324644Z tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-07-09T14:39:41.0324789Z tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-07-09T14:39:41.0324934Z tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-07-09T14:39:41.0325074Z tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-07-09T14:39:41.0325222Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-07-09T14:39:41.0325365Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-07-09T14:39:41.0325501Z tests               | 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-07-09T14:39:41.0325655Z tests               | Caused by: java.sql.SQLException: Query failed (#20200709_143936_00641_rnjt5): Error committing write to Hive
2020-07-09T14:39:41.0325808Z tests               | 	at io.prestosql.jdbc.AbstractPrestoResultSet.resultsException(AbstractPrestoResultSet.java:1731)
2020-07-09T14:39:41.0326068Z tests               | 	at io.prestosql.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:216)
2020-07-09T14:39:41.0326213Z tests               | 	at io.prestosql.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:176)
2020-07-09T14:39:41.0326347Z tests               | 	at io.prestosql.jdbc.$internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
2020-07-09T14:39:41.0326495Z tests               | 	at io.prestosql.jdbc.$internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
2020-07-09T14:39:41.0326639Z tests               | 	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
2020-07-09T14:39:41.0326794Z tests               | 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
2020-07-09T14:39:41.0326959Z tests               | 	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
2020-07-09T14:39:41.0327118Z tests               | 	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
2020-07-09T14:39:41.0327266Z tests               | 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
2020-07-09T14:39:41.0327411Z tests               | 	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
2020-07-09T14:39:41.0327557Z tests               | 	at io.prestosql.jdbc.PrestoResultSet$AsyncIterator.lambda$new$0(PrestoResultSet.java:122)
2020-07-09T14:39:41.0327705Z tests               | 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
2020-07-09T14:39:41.0327832Z tests               | 	... 3 more
2020-07-09T14:39:41.0327956Z tests               | Caused by: io.prestosql.spi.PrestoException: Error committing write to Hive
2020-07-09T14:39:41.0328095Z tests               | 	at io.prestosql.plugin.hive.RecordFileWriter.commit(RecordFileWriter.java:184)
2020-07-09T14:39:41.0328236Z tests               | 	at io.prestosql.plugin.hive.HiveWriter.commit(HiveWriter.java:86)
2020-07-09T14:39:41.0328359Z tests               | 	at io.prestosql.plugin.hive.HivePageSink.doFinish(HivePageSink.java:190)
2020-07-09T14:39:41.0328510Z tests               | 	at io.prestosql.plugin.hive.authentication.UserGroupInformationUtils.lambda$executeActionInDoAs$0(UserGroupInformationUtils.java:29)
2020-07-09T14:39:41.0328657Z tests               | 	at java.base/java.security.AccessController.doPrivileged(Native Method)
2020-07-09T14:39:41.0328794Z tests               | 	at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
2020-07-09T14:39:41.0328983Z tests               | 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1710)
2020-07-09T14:39:41.0329136Z tests               | 	at io.prestosql.plugin.hive.authentication.UserGroupInformationUtils.executeActionInDoAs(UserGroupInformationUtils.java:27)
2020-07-09T14:39:41.0329290Z tests               | 	at io.prestosql.plugin.hive.authentication.ImpersonatingHdfsAuthentication.doAs(ImpersonatingHdfsAuthentication.java:39)
2020-07-09T14:39:41.0329435Z tests               | 	at io.prestosql.plugin.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:89)
2020-07-09T14:39:41.0329571Z tests               | 	at io.prestosql.plugin.hive.HivePageSink.finish(HivePageSink.java:181)
2020-07-09T14:39:41.0329717Z tests               | 	at io.prestosql.plugin.base.classloader.ClassLoaderSafeConnectorPageSink.finish(ClassLoaderSafeConnectorPageSink.java:77)
2020-07-09T14:39:41.0329866Z tests               | 	at io.prestosql.operator.TableWriterOperator.finish(TableWriterOperator.java:203)
2020-07-09T14:39:41.0330001Z tests               | 	at io.prestosql.operator.Driver.processInternal(Driver.java:397)
2020-07-09T14:39:41.0330181Z tests               | 	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
2020-07-09T14:39:41.0330301Z tests               | 	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
2020-07-09T14:39:41.0330433Z tests               | 	at io.prestosql.operator.Driver.processFor(Driver.java:276)
2020-07-09T14:39:41.0330574Z tests               | 	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
2020-07-09T14:39:41.0330718Z tests               | 	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
2020-07-09T14:39:41.0330858Z tests               | 	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
2020-07-09T14:39:41.0330999Z tests               | 	at io.prestosql.$gen.Presto_99f77ab____20200709_143147_2.run(Unknown Source)
2020-07-09T14:39:41.0331163Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-07-09T14:39:41.0331310Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-07-09T14:39:41.0331442Z tests               | 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-07-09T14:39:41.0332308Z tests               | Caused by: org.apache.hadoop.ipc.RemoteException: File /tmp/presto-hdfs/632d0042-d9f2-459b-8c12-9ceff83efcf4/suppkey=88/20200709_143936_00641_rnjt5_ad5c1e53-0479-4de9-9858-23818efc552f.gz could only be written to 0 of the 1 minReplication nodes. There are 1 datanode(s) running and no node(s) are excluded in this operation.
2020-07-09T14:39:41.0332514Z tests               | 	at org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.chooseTarget4NewBlock(BlockManager.java:2121)
2020-07-09T14:39:41.0332677Z tests               | 	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.chooseTargetForNewBlock(FSDirWriteFileOp.java:286)
2020-07-09T14:39:41.0332842Z tests               | 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:2706)
2020-07-09T14:39:41.0332998Z tests               | 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:875)
2020-07-09T14:39:41.0333162Z tests               | 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:561)
2020-07-09T14:39:41.0333334Z tests               | 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
2020-07-09T14:39:41.0333498Z tests               | 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:524)
2020-07-09T14:39:41.0333695Z tests               | 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1025)
2020-07-09T14:39:41.0333836Z tests               | 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:876)
2020-07-09T14:39:41.0333977Z tests               | 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:822)
2020-07-09T14:39:41.0334113Z tests               | 	at java.security.AccessController.doPrivileged(Native Method)
2020-07-09T14:39:41.0334231Z tests               | 	at javax.security.auth.Subject.doAs(Subject.java:422)
2020-07-09T14:39:41.0334372Z tests               | 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
2020-07-09T14:39:41.0334507Z tests               | 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2682)
2020-07-09T14:39:41.0334626Z tests               | 
2020-07-09T14:39:41.0334751Z tests               | 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1511)
2020-07-09T14:39:41.0334884Z tests               | 	at org.apache.hadoop.ipc.Client.call(Client.java:1457)
2020-07-09T14:39:41.0335016Z tests               | 	at org.apache.hadoop.ipc.Client.call(Client.java:1367)
2020-07-09T14:39:41.0335153Z tests               | 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:228)
2020-07-09T14:39:41.0335561Z tests               | 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116)
2020-07-09T14:39:41.0335700Z tests               | 	at com.sun.proxy.$Proxy256.addBlock(Unknown Source)
2020-07-09T14:39:41.0335842Z tests               | 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.addBlock(ClientNamenodeProtocolTranslatorPB.java:513)
2020-07-09T14:39:41.0335994Z tests               | 	at jdk.internal.reflect.GeneratedMethodAccessor943.invoke(Unknown Source)
2020-07-09T14:39:41.0336138Z tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-07-09T14:39:41.0336285Z tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-07-09T14:39:41.0336433Z tests               | 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
2020-07-09T14:39:41.0336585Z tests               | 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
2020-07-09T14:39:41.0336730Z tests               | 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
2020-07-09T14:39:41.0336878Z tests               | 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
2020-07-09T14:39:41.0337022Z tests               | 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
2020-07-09T14:39:41.0337164Z tests               | 	at com.sun.proxy.$Proxy257.addBlock(Unknown Source)
2020-07-09T14:39:41.0337308Z tests               | 	at org.apache.hadoop.hdfs.DFSOutputStream.addBlock(DFSOutputStream.java:1081)
2020-07-09T14:39:41.0337453Z tests               | 	at org.apache.hadoop.hdfs.DataStreamer.locateFollowingBlock(DataStreamer.java:1865)
2020-07-09T14:39:41.0337596Z tests               | 	at org.apache.hadoop.hdfs.DataStreamer.nextBlockOutputStream(DataStreamer.java:1668)
2020-07-09T14:39:41.0337816Z tests               | 	at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:716)
2020-07-09T14:39:41.0337940Z tests               | 
```

**Comment by wendigo** [comment]
I've seen that couple of times so I guess it's not generic hive flakyness

**Comment by martint** [comment]
https://github.com/prestosql/presto//runs/892613591

**Comment by findepi** [comment]
Duplicates https://github.com/prestosql/presto/issues/3161
