### ISSUE TITLE
Flaky tempto

### ISSUE THREAD

**Issue by sopel39** [prestosql/presto#4406]
```
2020-07-09T14:48:58.3188812Z tests               | 2020-07-09 20:33:58 SEVERE: Failure cause:
2020-07-09T14:48:58.3189160Z tests               | java.lang.RuntimeException: Cannot get query executor for database 'presto'
2020-07-09T14:48:58.3189331Z tests               | 	at io.prestosql.tempto.internal.convention.sql.SqlQueryConventionBasedTest.getQueryExecutor(SqlQueryConventionBasedTest.java:227)
2020-07-09T14:48:58.3189491Z tests               | 	at io.prestosql.tempto.internal.convention.sql.SqlQueryConventionBasedTest.runTestQuery(SqlQueryConventionBasedTest.java:111)
2020-07-09T14:48:58.3189717Z tests               | 	at io.prestosql.tempto.internal.convention.sql.SqlQueryConventionBasedTest.test(SqlQueryConventionBasedTest.java:101)
2020-07-09T14:48:58.3189901Z tests               | 	at io.prestosql.tempto.internal.convention.ConventionBasedTestProxyGenerator$ConventionBasedTestProxy.test(ConventionBasedTestProxyGenerator.java:123)
2020-07-09T14:48:58.3190085Z tests               | 	at io.prestosql.tempto.csv_tables_with_header_and_footer.SimplescanfromtablewithFooter(Unknown Source)
2020-07-09T14:48:58.3190250Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-07-09T14:48:58.3190417Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-07-09T14:48:58.3190588Z tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-07-09T14:48:58.3190747Z tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-07-09T14:48:58.3190911Z tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-07-09T14:48:58.3191063Z tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-07-09T14:48:58.3191262Z tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-07-09T14:48:58.3191411Z tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-07-09T14:48:58.3191571Z tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-07-09T14:48:58.3191713Z tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-07-09T14:48:58.3191872Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-07-09T14:48:58.3192035Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-07-09T14:48:58.3192189Z tests               | 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-07-09T14:48:58.3192365Z tests               | Caused by: io.prestosql.tempto.context.ThreadLocalTestContextHolder$ThreadLocalTestContextException: test context not set for current thread
2020-07-09T14:48:58.3192520Z tests               | 
2020-07-09T14:48:58.3192958Z tests               | 2020-07-09 20:33:58 INFO: [80 of 75] sql_tests.testcases.csv_tables_with_header_and_footer.SimplescanfromtablewithHeader (Groups: storage_formats)
2020-07-09T14:48:58.3193135Z tests               | io.prestosql.tempto.internal.initialization.TestInitializationListener$SuiteInitializationException: test suite not initialized
2020-07-09T14:48:58.3193449Z tests               | 2020-07-09 20:33:58 INFO: FAILURE
2020-07-09T14:48:58.3193758Z tests               | 2020-07-09 20:33:58 SEVERE: Failure cause:
2020-07-09T14:48:58.3194098Z tests               | java.lang.RuntimeException: Cannot get query executor for database 'presto'
2020-07-09T14:48:58.3194271Z tests               | 	at io.prestosql.tempto.internal.convention.sql.SqlQueryConventionBasedTest.getQueryExecutor(SqlQueryConventionBasedTest.java:227)
2020-07-09T14:48:58.3194449Z tests               | 	at io.prestosql.tempto.internal.convention.sql.SqlQueryConventionBasedTest.runTestQuery(SqlQueryConventionBasedTest.java:111)
2020-07-09T14:48:58.3194606Z tests               | 	at io.prestosql.tempto.internal.convention.sql.SqlQueryConventionBasedTest.test(SqlQueryConventionBasedTest.java:101)
2020-07-09T14:48:58.3194782Z tests               | 	at io.prestosql.tempto.internal.convention.ConventionBasedTestProxyGenerator$ConventionBasedTestProxy.test(ConventionBasedTestProxyGenerator.java:123)
2020-07-09T14:48:58.3194959Z tests               | 	at io.prestosql.tempto.csv_tables_with_header_and_footer.SimplescanfromtablewithHeader(Unknown Source)
2020-07-09T14:48:58.3195121Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-07-09T14:48:58.3195340Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-07-09T14:48:58.3195516Z tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-07-09T14:48:58.3195679Z tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-07-09T14:48:58.3195839Z tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-07-09T14:48:58.3195995Z tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-07-09T14:48:58.3196141Z tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-07-09T14:48:58.3196548Z tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-07-09T14:48:58.3196710Z tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-07-09T14:48:58.3196868Z tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-07-09T14:48:58.3197029Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-07-09T14:48:58.3197245Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-07-09T14:48:58.3197398Z tests               | 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-07-09T14:48:58.3197574Z tests               | Caused by: io.prestosql.tempto.context.ThreadLocalTestContextHolder$ThreadLocalTestContextException: test context not set for current thread
2020-07-09T14:48:58.3197728Z tests               | 
2020-07-09T14:48:58.3198211Z tests               | 2020-07-09 20:33:58 INFO: [81 of 75] sql_tests.testcases.csv_tables_with_header_and_footer.SimplescanfromtablewithHeaderandFooter (Groups: storage_formats)
2020-07-09T14:48:58.3198399Z tests               | io.prestosql.tempto.internal.initialization.TestInitializationListener$SuiteInitializationException: test suite not initialized
2020-07-09T14:48:58.3198759Z tests               | 2020-07-09 20:33:58 INFO: FAILURE
2020-07-09T14:48:58.3277087Z tests               | 2020-07-09 20:33:58 SEVERE: Failure cause:
2020-07-09T14:48:58.3277645Z tests               | java.lang.RuntimeException: Cannot get query executor for database 'presto'
2020-07-09T14:48:58.3277829Z tests               | 	at io.prestosql.tempto.internal.convention.sql.SqlQueryConventionBasedTest.getQueryExecutor(SqlQueryConventionBasedTest.java:227)
2020-07-09T14:48:58.3278009Z tests               | 	at io.prestosql.tempto.internal.convention.sql.SqlQueryConventionBasedTest.runTestQuery(SqlQueryConventionBasedTest.java:111)
2020-07-09T14:48:58.3278185Z tests               | 	at io.prestosql.tempto.internal.convention.sql.SqlQueryConventionBasedTest.test(SqlQueryConventionBasedTest.java:101)
2020-07-09T14:48:58.3278382Z tests               | 	at io.prestosql.tempto.internal.convention.ConventionBasedTestProxyGenerator$ConventionBasedTestProxy.test(ConventionBasedTestProxyGenerator.java:123)
2020-07-09T14:48:58.3278570Z tests               | 	at io.prestosql.tempto.csv_tables_with_header_and_footer.SimplescanfromtablewithHeaderandFooter(Unknown Source)
2020-07-09T14:48:58.3278726Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-07-09T14:48:58.3278894Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-07-09T14:48:58.3279067Z tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-07-09T14:48:58.3279229Z tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-07-09T14:48:58.3279391Z tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-07-09T14:48:58.3279735Z tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-07-09T14:48:58.3279971Z tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-07-09T14:48:58.3280128Z tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-07-09T14:48:58.3280285Z tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-07-09T14:48:58.3280442Z tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-07-09T14:48:58.3280602Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-07-09T14:48:58.3280765Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-07-09T14:48:58.3280917Z tests               | 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-07-09T14:48:58.3281081Z tests               | Caused by: io.prestosql.tempto.context.ThreadLocalTestContextHolder$ThreadLocalTestContextException: test context not set for current thread
2020-07-09T14:48:58.3281309Z tests               | 
2020-07-09T14:48:58.3281643Z tests               | 2020-07-09 20:33:58 INFO: 
2020-07-09T14:48:58.3281954Z tests               | 2020-07-09 20:33:58 INFO: Completed 81 tests
2020-07-09T14:48:58.3282312Z tests               | 2020-07-09 20:33:58 INFO: 0 SUCCEEDED      /      81 FAILED      /      0 SKIPPED
2020-07-09T14:48:58.3282659Z tests               | 2020-07-09 20:33:58 INFO: Tests execution took 8.6 seconds
```

**Comment by kokosing** [comment]
Can you please share the first error reported by tempto?

**Comment by sopel39** [comment]
I forgot to paste build url (I even had it copied), sorry :/

**Comment by sopel39** [comment]
I haven't observed these more. Closing for now
