### ISSUE TITLE
MongoDB connector can't query to Atlas

### ISSUE THREAD

**Issue by ebyhr** [prestosql/presto#4489]
```
presto> select * from mongodb.test.test;
Query 20200719_104255_00006_2dkyz failed: org.bson.BsonInvalidOperationException: Document does not contain key clusterTime
com.google.common.util.concurrent.UncheckedExecutionException: org.bson.BsonInvalidOperationException: Document does not contain key clusterTime
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
	at io.prestosql.plugin.mongodb.MongoSession.getTable(MongoSession.java:171)
	at io.prestosql.plugin.mongodb.MongoMetadata.getTableHandle(MongoMetadata.java:80)
	at io.prestosql.plugin.mongodb.MongoMetadata.getTableHandle(MongoMetadata.java:55)
	at io.prestosql.metadata.MetadataManager.getTableHandle(MetadataManager.java:331)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1033)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:306)
	at io.prestosql.sql.tree.Table.accept(Table.java:53)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:323)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:2329)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1284)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:306)
	at io.prestosql.sql.tree.QuerySpecification.accept(QuerySpecification.java:144)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:323)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:333)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:918)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:306)
	at io.prestosql.sql.tree.Query.accept(Query.java:107)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:323)
	at io.prestosql.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:292)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:75)
	at io.prestosql.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:246)
	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:180)
	at io.prestosql.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:746)
	at io.prestosql.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:121)
	at io.prestosql.$gen.Presto_338____20200719_104020_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.bson.BsonInvalidOperationException: Document does not contain key clusterTime
	at org.bson.BsonDocument.throwIfKeyAbsent(BsonDocument.java:859)
	at org.bson.BsonDocument.getTimestamp(BsonDocument.java:257)
	at com.mongodb.connection.ClusterClock.greaterOf(ClusterClock.java:40)
	at com.mongodb.connection.ClusterClock.advance(ClusterClock.java:31)
	at com.mongodb.connection.ClusterClockAdvancingSessionContext.advanceClusterTime(ClusterClockAdvancingSessionContext.java:71)
	at com.mongodb.connection.InternalStreamConnection.updateSessionContext(InternalStreamConnection.java:509)
	at com.mongodb.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:291)
	at com.mongodb.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:254)
	at com.mongodb.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:98)
	at com.mongodb.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:441)
	at com.mongodb.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:76)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:189)
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:263)
	at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:126)
	at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:118)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:226)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:217)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:120)
	at com.mongodb.operation.ListIndexesOperation$1.call(ListIndexesOperation.java:143)
	at com.mongodb.operation.ListIndexesOperation$1.call(ListIndexesOperation.java:138)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:470)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:414)
	at com.mongodb.operation.ListIndexesOperation.execute(ListIndexesOperation.java:138)
	at com.mongodb.operation.ListIndexesOperation.execute(ListIndexesOperation.java:69)
	at com.mongodb.Mongo$3.execute(Mongo.java:822)
	at com.mongodb.MongoIterableImpl.execute(MongoIterableImpl.java:130)
	at com.mongodb.MongoIterableImpl.iterator(MongoIterableImpl.java:77)
	at io.prestosql.plugin.mongodb.MongoIndex.parse(MongoIndex.java:36)
	at io.prestosql.plugin.mongodb.MongoSession.getIndexes(MongoSession.java:246)
	at io.prestosql.plugin.mongodb.MongoSession.loadTableSchema(MongoSession.java:206)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	... 39 more
```

`_schema` collection
```json
{
    "_id": {
        "$oid": "5f14233ad6b0fdfcab3dd428"
    },
    "table": "test",
    "fields": [{
        "name": "_id",
        "type": "ObjectId",
        "hidden": true
    }, {
        "name": "a",
        "type": "varchar",
        "hidden": false
    }]
}
```

**Comment by ebyhr** [comment]
Going to close this issue since it's fixed by the recent driver update (3.6.0 → 3.8.0).

**Comment by chickenPopcorn** [comment]
Can we reopen this issue? ! @ebyhr 
We connected the MongoDB atlas, where we can show schemas and tables. But unfortunately, when querying against any connection on MongoDB atlas data lake, we got the following error.

`SQL Error [65536]: Query failed (#20200722_142635_00035_336v5): com.mongodb.MongoCommandException: Command failed with error 115 (CommandNotSupported): 'command createIndexes is unsupported, correlationID = 1624194f36604763841986ad' on server MongoDB-Atlas-Address:27017. The full response is { "ok" : 0, "errmsg" : "command createIndexes is unsupported, correlationID = 1624194f36604763841986ad", "code" : 115, "codeName" : "CommandNotSupported" }`

**Comment by ebyhr** [comment]
@chickenPopcorn I can get data from Atlas using version 339. Could you share the following information?
* MongoDB cluster version
* Presto query
* Full stactrace using CLI --debug option or webui

**Comment by chickenPopcorn** [comment]
Never mind I was trying to connect to Atlas data lake

**Comment by ebyhr** [comment]
@chickenPopcorn Thanks for the information. I could reproduce it. Filed a new issue https://github.com/prestosql/presto/issues/4544.

**Comment by ruodingt** [comment]
Hi @ebyhr 

I am trying to connect trino to my mongodb atlas yet I wasn't get any luck so far.

In my `catalog/mongodb.properties` I put:

```
connector.name=mongodb
mongodb.seeds=datarepoxx-shard-00-00.lrdap.mongodb.net:27017,datarepoxxx-shard-00-01.lrdap.mongodb.net:27017,datarepoxx-shard-00-02.lrdap.mongodb.net:27017
mongodb.credentials=**user**:****password****@admin
mongodb.ssl.enabled=true

```

My mongo connection string looks like
```
mongodb://user:password@datarepoxx.lrdap.mongodb.net
```

I got error when I do:

```
trino> SHOW SCHEMAS in mongo;
```

**Comment by ebyhr** [comment]
@ruodingt Could you confirm `Network Access` in Atlas? Can you connect to Atlas without Trino?
<img width="820" alt="Screen Shot 2021-07-20 at 21 38 10" src="https://user-images.githubusercontent.com/6237050/126325420-93921227-62fd-4aa8-9eb0-e6f15aafed5e.png">
