### ISSUE TITLE
Timezone not supported +DDDD

### ISSUE THREAD

**Issue by janevelger** [prestosql/presto#4490]
Hello, starting from 338 version (it works on 335) we are getting the following error on the query:
```
select timestamp '2019-01-05 23:59:59.999 +0000';
```
`Error: Timezone not supported +0000`
But when changing the query to : `select timestamp '2019-01-05 23:59:59.999 +00:00';`
it works.

**Comment by findepi** [comment]
I am confirming this is a behavior change introduced in  https://github.com/prestosql/presto/commit/62cf1510d7cec2cd762711b6b3358d7e3259ac65 (Presto 337).

**Comment by martint** [comment]
```
Query 20200720_201203_00009_qgcxc failed: line 1:8: Time zone not supported: +0000
io.prestosql.spi.PrestoException: line 1:8: Time zone not supported: +0000
	at io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.visitTimestampLiteral(ExpressionAnalyzer.java:885)
	at io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.visitTimestampLiteral(ExpressionAnalyzer.java:340)
	at io.prestosql.sql.tree.TimestampLiteral.accept(TimestampLiteral.java:52)
	at io.prestosql.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:27)
	at io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:363)
	at io.prestosql.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:301)
	at io.prestosql.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:1693)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.analyzeExpression(StatementAnalyzer.java:2361)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.analyzeSelectSingleColumn(StatementAnalyzer.java:2201)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.analyzeSelect(StatementAnalyzer.java:2025)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1285)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:303)
	at io.prestosql.sql.tree.QuerySpecification.accept(QuerySpecification.java:144)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:320)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:330)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:915)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:303)
	at io.prestosql.sql.tree.Query.accept(Query.java:107)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:320)
	at io.prestosql.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:289)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:75)
	at io.prestosql.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:246)
	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:180)
	at io.prestosql.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:746)
	at io.prestosql.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:121)
	at io.prestosql.$gen.Presto_unknown____20200720_183506_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.prestosql.spi.type.TimeZoneNotSupportedException: Time zone not supported: +0000
	at io.prestosql.spi.type.TimeZoneKey.getTimeZoneKey(TimeZoneKey.java:133)
	at io.prestosql.spi.type.DateTimeEncoding.packDateTimeWithZone(DateTimeEncoding.java:38)
	at io.prestosql.type.Timestamps.parseShortTimestampWithTimeZone(Timestamps.java:441)
	at io.prestosql.type.Timestamps.parseTimestampWithTimeZone(Timestamps.java:340)
	at io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.visitTimestampLiteral(ExpressionAnalyzer.java:871)
	... 34 more
```

**Comment by martint** [comment]
This looks like a latent bug in `TimeZoneKey.getTimeZoneKey` the became visible once we got rid of Joda for parsing timestamps. That method attempts to do some normalization, but doesn't handle that pattern properly. My guess is Joda was normalizing that form so the downstream code never saw that pattern.
