### ISSUE TITLE
Hive 3.1: "Malformed ORC file. Invalid postscript length 17" when only one data-file in external table directory

### ISSUE THREAD

**Issue by archongum** [prestosql/presto#456]
# env
* Presto 305
* Hive 3.1.0
![Snipaste_2019-03-12_13-45-06](https://user-images.githubusercontent.com/20929338/54177654-f6233e00-44cd-11e9-9bd5-fa78e36522fe.jpg)

# step
```sql
-- create external table using presto
create table hive.dw.dim_date2 (
	d date
) with (
    format = 'ORC',
    external_location = '/user/hive/warehouse/dw.db/dim_date2/'
);

-- insert one row using presto
insert into dim_date2 values (current_date);
```

when using `hiveserver2` to query, it works only at the first query and error after then
![Snipaste_2019-03-12_12-14-34](https://user-images.githubusercontent.com/20929338/54177539-88771200-44cd-11e9-9683-f61f19cbfec0.jpg)

If I insert another row, it works
```sql
-- insert one row using presto
insert into dim_date2 values (current_date);
```

![Snipaste_2019-03-12_13-50-12](https://user-images.githubusercontent.com/20929338/54177606-c5430900-44cd-11e9-82a8-a5c06a4a7ddf.jpg)

In HDFS (BTY, how to change the replica factor to HDFS default)
![Snipaste_2019-03-12_12-16-22](https://user-images.githubusercontent.com/20929338/54177833-92e5db80-44ce-11e9-9216-3662208c6c5e.jpg)

**Comment by archongum** [comment]
# env
* Presto 305
* Hive 3.1.0

# step
```sql
-- create external table using presto
create table hive.dw.dim_date2 (
	d date
) with (
    format = 'ORC',
    external_location = '/user/hive/warehouse/dw.db/dim_date2/'
);

-- insert one row using presto
insert into dim_date2 values (current_date);
```

when using hive to query, it works only at the first query and error after then
![Snipaste_2019-03-12_12-14-34](https://user-images.githubusercontent.com/20929338/54177539-88771200-44cd-11e9-9683-f61f19cbfec0.jpg)

If I insert another row, it works
```sql
insert into dim_date2 values (current_date);
```

![Snipaste_2019-03-12_13-50-12](https://user-images.githubusercontent.com/20929338/54177606-c5430900-44cd-11e9-82a8-a5c06a4a7ddf.jpg)

**Comment by dain** [comment]
I'm not sure what is causing this exact issue, but we don't recommend that any one upgrade to Hive 3.1 yet, since Hive 3.1 is currently broken with regard to TIMESTAMP types.  From what we understand, the data written by Hive 3.1 can not be read by Hive <=3.0 and the other way around.  We have heard that this is being worked on, so I would hold off on upgrading until this is fixed.

**Comment by electrum** [comment]
Thanks for reporting this issue. If I'm understanding correctly, the problem occurs when reading data in Hive, and the error happens in a strange way (after the first read). I recommend also reporting this error to the Hive project, as this may be a regression in Hive 3.1: https://hive.apache.org/issue_tracking.html

As for the replication count, I believe you can change this by using the Hive connector `hive.config.resources` property to point at an `hdfs-site.xml` that contains the following property:
```xml
<property> 
  <name>dfs.replication<name> 
  <value>2<value> 
<property>
```

Let us know if this works and we can add a first-class Hive connector configuration property for this (normally users should not need to specify a Hadoop config file).

**Comment by archongum** [comment]
> As for the replication count, I believe you can change this by using the Hive connector `hive.config.resources` property to point at an `hdfs-site.xml` that contains the following property:
> 
> ```
> <property> 
>   <name>dfs.replication<name> 
>   <value>2<value> 
> <property>
> ```
> 

As for "Replication count" problem solved after following this instruction.

As for hive problem: [https://issues.apache.org/jira/browse/HIVE-21436](url)

**Comment by findepi** [comment]
@archongum are you using LLAP?

**Comment by archongum** [comment]
@findepi I think I don't. 
I just run `METASTORE` and `HIVESERVER2` only and nothing runs in YARN at all.

**Comment by archongum** [comment]
I've noticed presto use its own `presto-orc` module while hive use `org.apache.orc`.

|               |             presto-insert-into             | hive-insert-into | java-code |
|---------------|:------------------------------------------:|:----------------:|-----------|
| presto-select | ok                                         | ok               | ok        |
| hive-select   | error(if only one file in table directory) | ok               | ok        |





### 1. presto-insert-into.orc
* create
```sql
-- presto sql
insert into dim_date2 values (current_date);
```

* java -jar orc-tools-1.5.1-uber.jar meta *.orc

```
Processing data file presto-insert-into.orc [length: 255]
Structure for presto-insert-into.orc
File Version: 0.12 with PRESTO_ORIGINAL
Rows: 1
Compression: ZLIB
Compression size: 262144
Type: struct<d:date>

Stripe Statistics:
  Stripe 1:
    Column 0: count: 1 hasNull: true
    Column 1: count: 1 hasNull: true min: 2019-03-13 max: 2019-03-13

File Statistics:
  Column 0: count: 1 hasNull: true
  Column 1: count: 1 hasNull: true min: 2019-03-13 max: 2019-03-13

Stripes:
  Stripe: offset: 3 data: 7 rows: 1 tail: 45 index: 24
    Stream: column 1 section ROW_INDEX start: 3 length 24
    Stream: column 1 section DATA start: 27 length 7
    Encoding column 0: DIRECT
    Encoding column 1: DIRECT_V2

File length: 255 bytes
Padding length: 0 bytes
Padding ratio: 0%

User Metadata:
  presto.writer.version=305
  presto_query_id=20190313_060328_00174_vcbrs
  presto_version=305
```

### 2. hive-insert-into.orc
* create
```sql
-- hive sql
insert into dim_date2 values (current_date);
```

* java -jar orc-tools-1.5.1-uber.jar meta *.orc

```
Processing data file hive-insert-into.orc [length: 194]
Structure for hive-insert-into.orc
File Version: 0.12 with ORC_135
Rows: 1
Compression: ZLIB
Compression size: 262144
Type: struct<d:date>

Stripe Statistics:
  Stripe 1:
    Column 0: count: 1 hasNull: false
    Column 1: count: 1 hasNull: false bytesOnDisk: 7 min: 2019-03-18 max: 2019-03-18

File Statistics:
  Column 0: count: 1 hasNull: false
  Column 1: count: 1 hasNull: false bytesOnDisk: 7 min: 2019-03-18 max: 2019-03-18

Stripes:
  Stripe: offset: 3 data: 7 rows: 1 tail: 30 index: 37
    Stream: column 0 section ROW_INDEX start: 3 length 11
    Stream: column 1 section ROW_INDEX start: 14 length 26
    Stream: column 1 section DATA start: 40 length 7
    Encoding column 0: DIRECT
    Encoding column 1: DIRECT_V2

File length: 194 bytes
Padding length: 0 bytes
Padding ratio: 0%
```


### 3. org-apache-orc-java-code.orc
* create
```java
Configuration conf = new Configuration();
TypeDescription schema = TypeDescription.fromString("struct<d:date>");
Writer writer = OrcFile.createWriter(new Path("/tmp/org-apache-orc-java-code.orc"),
	OrcFile.writerOptions(conf)
		.setSchema(schema));

VectorizedRowBatch batch = schema.createRowBatch();
LongColumnVector x = (LongColumnVector) batch.cols[0];
int row = batch.size++;
x.vector[row] = 0; // set time to 0
writer.addRowBatch(batch);
batch.reset();
writer.close();
```

* java -jar orc-tools-1.5.1-uber.jar meta *.orc

```
Processing data file org-apache-orc-java-code.orc [length: 181]
Structure for org-apache-orc-java-code.orc
File Version: 0.12 with ORC_135
Rows: 1
Compression: ZLIB
Compression size: 262144
Type: struct<d:date>

Stripe Statistics:
  Stripe 1:
    Column 0: count: 1 hasNull: false
    Column 1: count: 1 hasNull: false bytesOnDisk: 6 min: 1970-01-01 max: 1970-01-01

File Statistics:
  Column 0: count: 1 hasNull: false
  Column 1: count: 1 hasNull: false bytesOnDisk: 6 min: 1970-01-01 max: 1970-01-01

Stripes:
  Stripe: offset: 3 data: 6 rows: 1 tail: 30 index: 33
    Stream: column 0 section ROW_INDEX start: 3 length 11
    Stream: column 1 section ROW_INDEX start: 14 length 22
    Stream: column 1 section DATA start: 36 length 6
    Encoding column 0: DIRECT
    Encoding column 1: DIRECT_V2

File length: 181 bytes
Padding length: 0 bytes
Padding ratio: 0%
```

**Comment by dain** [comment]
What do you mean by `error(if only one file in table directory)`?  If you execute 2 separate inserts, does it work?

Can you post the stack trace from Hive?

**Comment by archongum** [comment]
@dain 
I've mentioned on the first comment. 

And it's nothing to do with `CREATE TABLE` command  because I've tried both presto and hive.

presto `CREATE TABLE`
```sql
create table hive.dw.dim_date2 (
	d date
) with (
    format = 'ORC',
    external_location = '/user/hive/warehouse/dw.db/dim_date2/'
);
```

hive `CREATE TABLE`
```sql
CREATE EXTERNAL TABLE `dw.dim_date2`(
  `d` date
)
STORED AS ORC
LOCATION
  'hdfs://datacenter1:8020/user/hive/warehouse/dw.db/dim_date2'
;
```

**Comment by dain** [comment]
We'll try to reproduce locally, but my guess is we are triggering a bug in Hive since the files are readable when there are multiple files in the directory.  We'll try to find a work around.

**Comment by electrum** [comment]
Do you know of an easy way to get Hive 3.1 running for testing? I wasn't able to find any working virtual images, Docker container, etc., and I failed to get it running after trying for several hours.

**Comment by findepi** [comment]
I was able to reproduce this.

```
env HADOOP_BASE_IMAGE="prestodev/hdp3.1-hive" ./presto-product-tests/conf/docker/singlenode/compose.sh up
```

```
./presto-product-tests/bin/run_presto_cli_on_docker.sh singlenode --catalog hive --schema default --user hive

CREATE TABLE t(a bigint) WITH (format='ORC');
INSERT INTO t(a) VALUES (42);
```

```
./presto-product-tests/conf/docker/singlenode/compose.sh exec hadoop-master beeline --verbose -n hive

jdbc:hive2://localhost:10000/default> SELECT * FROM t;
...
+------+
| 42   |
+------+

jdbc:hive2://localhost:10000/default> SELECT * FROM t;
going to print operations logs
printed operations logs
Getting log thread is interrupted, since query is done!
INFO  : Compiling command(queryId=hive_20191004151730_e7c48562-51c8-4d39-9622-62231a499768): SELECT * FROM t
INFO  : Semantic Analysis Completed (retrial = false)
INFO  : Returning Hive schema: Schema(fieldSchemas:[FieldSchema(name:t.a, type:bigint, comment:null)], properties:null)
INFO  : Completed compiling command(queryId=hive_20191004151730_e7c48562-51c8-4d39-9622-62231a499768); Time taken: 0.24 seconds
INFO  : Executing command(queryId=hive_20191004151730_e7c48562-51c8-4d39-9622-62231a499768): SELECT * FROM t
INFO  : Completed executing command(queryId=hive_20191004151730_e7c48562-51c8-4d39-9622-62231a499768); Time taken: 0.0 seconds
INFO  : OK
Error: java.io.IOException: java.lang.RuntimeException: ORC split generation failed with exception: Malformed ORC file. Invalid postscript length 17 (state=,code=0)
org.apache.hive.service.cli.HiveSQLException: java.io.IOException: java.lang.RuntimeException: ORC split generation failed with exception: Malformed ORC file. Invalid postscript length 17
	at org.apache.hive.jdbc.Utils.verifySuccess(Utils.java:300)
	at org.apache.hive.jdbc.Utils.verifySuccessWithInfo(Utils.java:286)
	at org.apache.hive.jdbc.HiveQueryResultSet.next(HiveQueryResultSet.java:379)
	at org.apache.hive.beeline.BufferedRows.<init>(BufferedRows.java:56)
	at org.apache.hive.beeline.IncrementalRowsWithNormalization.<init>(IncrementalRowsWithNormalization.java:50)
	at org.apache.hive.beeline.BeeLine.print(BeeLine.java:2305)
	at org.apache.hive.beeline.Commands.executeInternal(Commands.java:1026)
	at org.apache.hive.beeline.Commands.execute(Commands.java:1201)
	at org.apache.hive.beeline.Commands.sql(Commands.java:1130)
	at org.apache.hive.beeline.BeeLine.dispatch(BeeLine.java:1480)
	at org.apache.hive.beeline.BeeLine.execute(BeeLine.java:1342)
	at org.apache.hive.beeline.BeeLine.begin(BeeLine.java:1126)
	at org.apache.hive.beeline.BeeLine.mainWithInputRedirection(BeeLine.java:546)
	at org.apache.hive.beeline.BeeLine.main(BeeLine.java:528)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:318)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:232)
Caused by: org.apache.hive.service.cli.HiveSQLException: java.io.IOException: java.lang.RuntimeException: ORC split generation failed with exception: Malformed ORC file. Invalid postscript length 17
	at org.apache.hive.service.cli.operation.SQLOperation.getNextRowSet(SQLOperation.java:478)
	at org.apache.hive.service.cli.operation.OperationManager.getOperationNextRowSet(OperationManager.java:328)
	at org.apache.hive.service.cli.session.HiveSessionImpl.fetchResults(HiveSessionImpl.java:952)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hive.service.cli.session.HiveSessionProxy.invoke(HiveSessionProxy.java:78)
	at org.apache.hive.service.cli.session.HiveSessionProxy.access$000(HiveSessionProxy.java:36)
	at org.apache.hive.service.cli.session.HiveSessionProxy$1.run(HiveSessionProxy.java:63)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
	at org.apache.hive.service.cli.session.HiveSessionProxy.invoke(HiveSessionProxy.java:59)
	at com.sun.proxy.$Proxy50.fetchResults(Unknown Source)
	at org.apache.hive.service.cli.CLIService.fetchResults(CLIService.java:564)
	at org.apache.hive.service.cli.thrift.ThriftCLIService.FetchResults(ThriftCLIService.java:792)
	at org.apache.hive.service.rpc.thrift.TCLIService$Processor$FetchResults.getResult(TCLIService.java:1837)
	at org.apache.hive.service.rpc.thrift.TCLIService$Processor$FetchResults.getResult(TCLIService.java:1822)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
	at org.apache.hive.service.auth.TSetIpAddressProcessor.process(TSetIpAddressProcessor.java:56)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: java.lang.RuntimeException: ORC split generation failed with exception: Malformed ORC file. Invalid postscript length 17
	at org.apache.hadoop.hive.ql.exec.FetchOperator.getNextRow(FetchOperator.java:602)
	at org.apache.hadoop.hive.ql.exec.FetchOperator.pushRow(FetchOperator.java:509)
	at org.apache.hadoop.hive.ql.exec.FetchTask.fetch(FetchTask.java:146)
	at org.apache.hadoop.hive.ql.Driver.getResults(Driver.java:2738)
	at org.apache.hadoop.hive.ql.reexec.ReExecDriver.getResults(ReExecDriver.java:229)
	at org.apache.hive.service.cli.operation.SQLOperation.getNextRowSet(SQLOperation.java:473)
	... 25 more
Caused by: java.lang.RuntimeException: ORC split generation failed with exception: Malformed ORC file. Invalid postscript length 17
	at org.apache.hadoop.hive.ql.io.orc.OrcInputFormat.generateSplitsInfo(OrcInputFormat.java:1851)
	at org.apache.hadoop.hive.ql.io.orc.OrcInputFormat.getSplits(OrcInputFormat.java:1939)
	at org.apache.hadoop.hive.ql.exec.FetchOperator.generateWrappedSplits(FetchOperator.java:425)
	at org.apache.hadoop.hive.ql.exec.FetchOperator.getNextSplits(FetchOperator.java:395)
	at org.apache.hadoop.hive.ql.exec.FetchOperator.getRecordReader(FetchOperator.java:314)
	at org.apache.hadoop.hive.ql.exec.FetchOperator.getNextRow(FetchOperator.java:540)
	... 30 more
Caused by: org.apache.orc.FileFormatException: Malformed ORC file. Invalid postscript length 17
	at org.apache.orc.impl.ReaderImpl.ensureOrcFooter(ReaderImpl.java:297)
	at org.apache.orc.impl.ReaderImpl.extractFileTail(ReaderImpl.java:463)
	at org.apache.hadoop.hive.ql.io.orc.LocalCache.getAndValidate(LocalCache.java:107)
	at org.apache.hadoop.hive.ql.io.orc.OrcInputFormat$ETLSplitStrategy.getSplits(OrcInputFormat.java:881)
	at org.apache.hadoop.hive.ql.io.orc.OrcInputFormat$ETLSplitStrategy.runGetSplitsSync(OrcInputFormat.java:995)
	at org.apache.hadoop.hive.ql.io.orc.OrcInputFormat$ETLSplitStrategy.generateSplitWork(OrcInputFormat.java:968)
	at org.apache.hadoop.hive.ql.io.orc.OrcInputFormat.scheduleSplits(OrcInputFormat.java:1879)
	at org.apache.hadoop.hive.ql.io.orc.OrcInputFormat.generateSplitsInfo(OrcInputFormat.java:1823)
	... 35 more
```

**Comment by findepi** [comment]
[20191004_092959_00001_5g5sx_d609b289-f8b0-4b29-abe7-69cfebe70fcb.zip](https://github.com/prestosql/presto/files/3689932/20191004_092959_00001_5g5sx_d609b289-f8b0-4b29-abe7-69cfebe70fcb.zip)
