### ISSUE TITLE
bug: phoenix connector overwrite former value when insert without specified column

### ISSUE THREAD

**Issue by wgzhao** [prestosql/presto#4562]
I has two columns in a hbase table (create it via phoenix client), first, I insert a record using specified  column `col1` with value `val1`, then I insert another record using specified column `col2`  with it's value `val2`.  as result , the value of column `col1` became `NULL` instead of former value `val1`.
both records using the same row-key value.

using the following instructions can trigger the above bug:

```sql
phoenix-client> create table test_col_insert(pk varchar not null primary key, col1 varchar, col2 varchar) COLUMN_ENCODED_BYTES=0;
No rows affected (1.394 seconds)

presto:test> insert into test_col_insert(pk, col1) values('1', 'val1');
INSERT: 1 row

Query 20200724_075447_00048_ts45i, FINISHED, 1 node
Splits: 51 total, 51 done (100.00%)
0.61 [0 rows, 0B] [0 rows/s, 0B/s]

presto:test> select * from test_col_insert;
 pk | col1 | col2
----+------+------
 1  | val1 | NULL
(1 row)

Query 20200724_075452_00049_ts45i, FINISHED, 1 node
Splits: 17 total, 17 done (100.00%)
0.54 [1 rows, 0B] [1 rows/s, 0B/s]

presto:test> insert into test_col_insert(pk, col2) values('1', 'val2');
INSERT: 1 row

Query 20200724_075512_00050_ts45i, FINISHED, 1 node
Splits: 51 total, 51 done (100.00%)
0.63 [0 rows, 0B] [0 rows/s, 0B/s]

presto:test> select * from test_col_insert;
 pk | col1 | col2
----+------+------
 1  | NULL | val2
(1 row)

Query 20200724_075516_00051_ts45i, FINISHED, 1 node
Splits: 17 total, 17 done (100.00%)
0.59 [1 rows, 0B] [1 rows/s, 0B/s]
```

using phoenix can get correct result:

```sql
0: jdbc:phoenix:dn01,dn02,dn03> delete from test.test_col_insert;
1 row affected (0.008 seconds)
0: jdbc:phoenix:dn01,dn02,dn03> upsert into  test.test_col_insert (pk, col1)values('1','val1');
1 row affected (0.011 seconds)
0: jdbc:phoenix:dn01,dn02,dn03> select * from test.test_col_insert;
+-----+-------+-------+
| PK  | COL1  | COL2  |
+-----+-------+-------+
| 1   | val1  |       |
+-----+-------+-------+
1 row selected (0.013 seconds)

0: jdbc:phoenix:dn01,dn02,dn03> upsert into  test.test_col_insert (pk, col2)values('1','val2');
1 row affected (0.006 seconds)
0: jdbc:phoenix:dn01,dn02,dn03> select * from test.test_col_insert;
+-----+-------+-------+
| PK  | COL1  | COL2  |
+-----+-------+-------+
| 1   | val1  | val2  |
+-----+-------+-------+
1 row selected (0.016 seconds)
```

my environment:

- HBase: 1.4.13
- Phoenix: 4.14.3-HBase-1.4
- PrestoSQL: 339

`phoenix.properties` 

```ini
connector.name=phoenix
phoenix.connection-url=jdbc:phoenix:node1,node2,nod3:2181:/hbase-secure:presto@EXAMPLE.COM:/e
tc/presto/presto.headless.keytab
phoenix.config.resources=/etc/hbase/conf/hbase-site.xml,/etc/hadoop/conf/core-site.xml
case-insensitive-name-matching=true
```

**Comment by findepi** [comment]
The first step would be to change `io.prestosql.plugin.phoenix.PhoenixMetadata#supportsMissingColumnsOnInsert`
to return true (ie remove, as superclass impl returns `true`).

**Comment by wgzhao** [comment]
when I change the return value of  `io.prestosql.plugin.phoenix.PhoenixMetadata#supportsMissingColumnsOnInser` function  to `true`, the following errors occurred.

```
2020-07-24T22:55:04.838+0800    ERROR   remote-task-callback-11 io.prestosql.execution.StageStateMachine Stage 20200724_145503_00008_pb8ab.1 failed
io.prestosql.spi.PrestoException: ERROR 2004 (INT05): Parameter value unbound. Parameter 3 is unbound
        at io.prestosql.plugin.jdbc.JdbcPageSink.appendPage(JdbcPageSink.java:117)
        at io.prestosql.plugin.base.classloader.ClassLoaderSafeConnectorPageSink.appendPage(ClassLoaderSafeConnectorPageSink.java:69)
        at io.prestosql.operator.TableWriterOperator.addInput(TableWriterOperator.java:252)
        at io.prestosql.operator.Driver.processInternal(Driver.java:384)
        at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
        at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
        at io.prestosql.operator.Driver.processFor(Driver.java:276)
        at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
        at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
        at io.prestosql.$gen.Presto_339____20200724_145305_2.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.sql.SQLException: ERROR 2004 (INT05): Parameter value unbound. Parameter 3 is unbound
        at org.apache.phoenix.exception.SQLExceptionCode$Factory$1.newException(SQLExceptionCode.java:494)
        at org.apache.phoenix.exception.SQLExceptionInfo.buildException(SQLExceptionInfo.java:150)
        at org.apache.phoenix.jdbc.PhoenixPreparedStatement.throwIfUnboundParameters(PhoenixPreparedStatement.java:151)
        at org.apache.phoenix.jdbc.PhoenixPreparedStatement.addBatch(PhoenixPreparedStatement.java:110)
        at io.prestosql.plugin.jdbc.JdbcPageSink.appendPage(JdbcPageSink.java:105)
        ... 13 more
```

**Comment by findepi** [comment]
@wgzhao this is why i said this is the first step. I am no expert in Phoenix, so from my POV more investigation is needed.
cc @vincentpoon

**Comment by lhofhansl** [comment]
Workaround:
`insert into test_col_insert select pk, col1, 'val2' from test_col_insert where pk = '1';`

Phoenix internally handles INSERT and UPDATE exactly the same. Absent columns (Cells in HBase) are inferred NULL.
This is clearly a bug in the connector.

**Comment by lhofhansl** [comment]
Looking at the code I see what's going. It's always inserting all columns. The fix is simple - if perhaps a bit tedious since the generated ROWKEY column still has to work.
(For the record, I'm not a fan of an automatically added ROWKEY column anyway, in Phoenix is *never* what you want in real life. It just allows for all the JDBC tests to run unchanged, perhaps we can find a better solution for that.)

**Comment by lhofhansl** [comment]
Please have a look at the fix.

**Comment by ebyhr** [comment]
Confirmed this issue was already fixed. 
```bash
presto:tpch> insert into test_col_insert(pk, col1) values('1', 'val1');
INSERT: 1 row

presto:tpch> select * from test_col_insert;
 pk | col1 | col2
----+------+------
 1  | val1 | NULL
(1 row)

presto:tpch> insert into test_col_insert(pk, col2) values('1', 'val2');
INSERT: 1 row

presto:tpch> select * from test_col_insert;
 pk | col1 | col2
----+------+------
 1  | val1 | val2
```
