### ISSUE TITLE
Flaky TestHiveDistributedQueries.testWrittenStats

### ISSUE THREAD

**Issue by ebyhr** [prestosql/presto#4586]
```
2020-07-26T07:57:12.7952656Z [ERROR] testWrittenStats(io.prestosql.plugin.hive.TestHiveDistributedQueries)  Time elapsed: 0.2 s  <<< FAILURE!
2020-07-26T07:57:12.8008247Z java.lang.AssertionError: expected [1] but found [0]
2020-07-26T07:57:12.8010231Z 	at org.testng.Assert.fail(Assert.java:94)
2020-07-26T07:57:12.8012685Z 	at org.testng.Assert.failNotEquals(Assert.java:513)
2020-07-26T07:57:12.8015258Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
2020-07-26T07:57:12.8017676Z 	at org.testng.Assert.assertEquals(Assert.java:116)
2020-07-26T07:57:12.8020063Z 	at org.testng.Assert.assertEquals(Assert.java:284)
2020-07-26T07:57:12.8022465Z 	at org.testng.Assert.assertEquals(Assert.java:294)
2020-07-26T07:57:12.8027602Z 	at io.prestosql.testing.AbstractTestDistributedQueries.testWrittenStats(AbstractTestDistributedQueries.java:1157)
2020-07-26T07:57:12.8031641Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-07-26T07:57:12.8037295Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-07-26T07:57:12.8043098Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-07-26T07:57:12.8046762Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-07-26T07:57:12.8051994Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-07-26T07:57:12.8055269Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-07-26T07:57:12.8058827Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-07-26T07:57:12.8062411Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-07-26T07:57:12.8066814Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-07-26T07:57:12.8070518Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-07-26T07:57:12.8075346Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-07-26T07:57:12.8080128Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-07-26T07:57:12.8083850Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by ebyhr** [comment]
https://github.com/prestosql/presto/pull/4585/checks?check_run_id=911223669

**Comment by wendigo** [comment]
Related https://github.com/prestosql/presto/issues/4275

**Comment by wendigo** [comment]
https://github.com/prestosql/presto/pull/4779/checks?check_run_id=970676241

**Comment by sopel39** [comment]
Looks like related to: https://github.com/prestosql/presto/issues/5172

**Comment by findepi** [comment]
Closing in favor of https://github.com/prestosql/presto/issues/5172
