### ISSUE TITLE
Add support for composite types in CLI's JSON output format

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#4589]
Currently formatting rows or maps fails:

```
Error running command: No ObjectCodec defined for the generator, can only serialize simple wrapper types (type passed java.util.LinkedHashMap)
java.lang.IllegalStateException: No ObjectCodec defined for the generator, can only serialize simple wrapper types (type passed java.util.LinkedHashMap)
	at com.fasterxml.jackson.core.JsonGenerator._writeSimpleObject(JsonGenerator.java:2168)
	at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:391)
	at com.fasterxml.jackson.core.JsonGenerator.writeObjectField(JsonGenerator.java:1769)
	at io.prestosql.cli.JsonPrinter.printRows(JsonPrinter.java:49)
```

**Comment by sweet-mentat** [comment]
Has this been addressed? I am getting this error:
Error running command: No ObjectCodec defined for the generator, can only serialize simple wrapper types (type passed java.util.ArrayList)
Does the CLI JSON output format only support simple data types?

**Comment by njpeterman** [comment]
There's too much red tape for me to PR this myself, but I was able to get this working locally with some minor changes.

Specifically, in the [JsonPrinter](https://github.com/trinodb/trino/blob/99ef4ec162b3b099762e4d6727ee3db641e1445c/client/trino-cli/src/main/java/io/trino/cli/JsonPrinter.java), the `printRows` method needs to configure an object mapper for the json generator: 

```
         ...
         JsonFactory jsonFactory = new JsonFactory();
         for (List<?> row : rows) {
             JsonGenerator jsonGenerator = jsonFactory.createGenerator(writer);
+            jsonGenerator.setCodec(new ObjectMapper());
             jsonGenerator.writeStartObject();
             ...
```

And then in order to access the object mapper, the trino-cli module needs to declare jackson-databind as a dependency in its pom.xml: 

```
<dependency>
     <groupId>com.fasterxml.jackson.core</groupId>
     <artifactId>jackson-databind</artifactId>
</dependency>
```

Hope this helps!

**Comment by hackeryang** [comment]
> There's too much red tape for me to PR this myself, but I was able to get this working locally with some minor changes.
> 
> Specifically, in the [JsonPrinter](https://github.com/trinodb/trino/blob/99ef4ec162b3b099762e4d6727ee3db641e1445c/client/trino-cli/src/main/java/io/trino/cli/JsonPrinter.java), the `printRows` method needs to configure an object mapper for the json generator:
> 
> ```
>          ...
>          JsonFactory jsonFactory = new JsonFactory();
>          for (List<?> row : rows) {
>              JsonGenerator jsonGenerator = jsonFactory.createGenerator(writer);
> +            jsonGenerator.setCodec(new ObjectMapper());
>              jsonGenerator.writeStartObject();
>              ...
> ```
> 
> And then in order to access the object mapper, the trino-cli module needs to declare jackson-databind as a dependency in its pom.xml:
> 
> ```
> <dependency>
>      <groupId>com.fasterxml.jackson.core</groupId>
>      <artifactId>jackson-databind</artifactId>
> </dependency>
> ```
> 
> Hope this helps!

Thank you for your advice, we encountered a similar problem too, there was some complex row and map column types in our hive table:  
![image](https://user-images.githubusercontent.com/26461591/220819130-88da5ed5-5a41-4111-bbd2-18bb09dfc41e.png)  
After we modified some source codes just as what you suggested, the error is fixed.
