### ISSUE TITLE
Compatibility issue casting real to decimal

### ISSUE THREAD

**Issue by mh-amount** [prestosql/presto#4626]
We recently upgraded from prestosql 329 to 338, and it seems that something changed on the server side that is causing conflicts with a jdbc driver when casting `real` values to `decimal`.

The quirky part of this is that I'm not sure if it's a server or a client issue. This is because it works fine with a newer prestosql jdbc driver, but it fails with a prestodb jdbc driver. At some point in time we switched over to prestosql from prestodb, but some client applications (ex: Looker) only support the prestodb driver. It is my understanding that this is the first time we've encountered a compatibility issue related to the jdbc driver mismatch, but I don't know if that was a fluke or if prestosql intends to maintain a certain level of compatibility with prestodb. 

Recreating this bug is pretty simple:

```
select cast(foo as decimal(30, 2))
from
(
  values
  	(real '10.3')
) as t (foo)
```

This produces a valid result using a prestosql driver, but this is what we get from the PrestoDB 0.230 driver:

```
ParameterKind is [TYPE] but expected [LONG]

java.lang.IllegalArgumentException: ParameterKind is [TYPE] but expected [LONG]
	at com.facebook.presto.jdbc.internal.spi.type.TypeSignatureParameter.getValue(TypeSignatureParameter.java:87)
	at com.facebook.presto.jdbc.internal.spi.type.TypeSignatureParameter.getLongLiteral(TypeSignatureParameter.java:99)
	at com.facebook.presto.jdbc.ColumnInfo.setTypeInfo(ColumnInfo.java:194)
	at com.facebook.presto.jdbc.PrestoResultSet.getColumnInfo(PrestoResultSet.java:1868)
	at com.facebook.presto.jdbc.PrestoResultSet.<init>(PrestoResultSet.java:121)
	at com.facebook.presto.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:250)
	at com.facebook.presto.jdbc.PrestoStatement.execute(PrestoStatement.java:228)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:467)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:407)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:405)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:849)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2776)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3271)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

If you believe this is something that's wrong with the prestodb driver, please let me know. I started here since the server changed rather than the client. Also, if you have any information about compatibility expectations in the short/medium/long term, that would also be helpful.

**Comment by martint** [comment]
I'm looking into this. It started happening in Presto 336

**Comment by martint** [comment]
There was a change in Presto 337 that caused the rendering of the type to switch from `decimal(30,2)` to `decimal(30, 2)` (note the space between then `,` and the `2`). This seems to be a bug in the prestodb driver, which doesn't seem to be able to parse that as a valid type. I haven't been able to reproduce the issue with any of the 3xx drivers.

**Comment by findepi** [comment]
> if you have any information about compatibility expectations in the short/medium/long term, that would also be helpful.

@mh-amount we do care a lot about client-server protocol compatibility. This is hard to test
in general (let's assume that for a moment; there are many details that need to be taken care of,
besides protocol structure itself). There is e.g. ongoing work on https://github.com/prestosql/presto/issues/1787.

We still need to do backwards incompatible changes though, e.g. to fix bugs in the data representation.
So I would strongly recommend that you upgrade your client applications to use a recent Presto driver.
There should be no technical obstacle for Looker not to use a recent driver and this is a prerequisite
to be able to use some of the recent additions to Presto, like timestamp with defined precision.

**Comment by mh-amount** [comment]
@martint given the nature of the underlying cause, is this something that can/should be reverted for compatibility reasons on the prestosql side, or do you believe that the only path forward is using a different driver/fixing the prestodb driver?

**Comment by electrum** [comment]
This sounds like something we should fix, both for compatibility and to be consistent with how types are rendered, as user visible places like `DESCRIBE` do not have a space.

Note that we don't guarantee any compatible with the Facebook driver as these are effectively two separately projects almost two years apart with significant differences that will continue to grow, so for many reasons, we encourage you to use the latest driver that matches the server version.

**Comment by mh-amount** [comment]
Yeah, we're doing what we can to get off of the prestodb driver as soon as possible. That's definitely the best path forward.

@martint it sounds like you're aware of the change in 337 that is associated with this. If you agree with @electrum that it's okay to remove the space for compatibility purposes, is there any chance you can point out the commit that altered the behavior? I'd be happy to make changes and open a PR, but I'm pretty new to the presto codebase. It'd be very helpful if you could point me in the right direction.

**Comment by martint** [comment]
This is probably the line that's causing the issue, but I'm not confident it's the only place that may affect how the types are presented to clients: https://github.com/prestosql/presto/blob/master/presto-main/src/main/java/io/prestosql/server/protocol/Query.java#L653

I'm ok with changing that for now, but at some point, we'll have to accept that old drivers are broken and change it back - maybe after a long enough period to give people a chance to update to more recent versions of the driver. Clients that attempt to parse the types should do so according to SQL syntax rules.

Regarding David's comment:
> to be consistent with how types are rendered

Rendering with the space after the comma *does make* everything more consistent, as that's how map and row types have always been rendered. For some reason, DECIMAL didn't follow that pattern when we added it.

**Comment by jerryleooo** [comment]
Just noticed the error query will also affect `/ui/api/stats`, we are using version 356

**Comment by findepi** [comment]
from the issue description

> This produces a valid result using a prestosql driver, but this is what we get from the PrestoDB 0.230 driver (which is what Looker is using):

@mh-amount i guess this is obvious, but i will say this explicitly: we have no control of the prestodb driver.
We cannot (and we do not) guarantee compatibility with it. Also, innovation requires a change, so we cannot be held a hostage of some specific, potentially old (or incompatible) driver version.

Please work with Looker on using a Trino-provided driver, that is the only way forward to me.

Let me close this issue.

@jerryleooo  I am closing this issue because this is something we cannot fix.
If your context of usage is different, please open a separate bug report.

**Comment by jerryleooo** [comment]
@findepi my point is the `/ui/api/stats` should decouple with the error, imagine the `/ui/api/stats` is an important dependency while one single SQL could break it ..

**Comment by findepi** [comment]
cannot reproduce on current master.
Steps i tried

1. run dev server as described @ https://github.com/trinodb/trino/blob/master/README.md#running-the-full-server
2. using Trino CLI (also built on current master) run
    ```sql
    SELECT CAST(foo AS decimal(30, 2))
    FROM (VALUES REAL '10.3') AS t(foo);
    ```
3. open http://localhost:8080/ui/, log in using "admin" user name and no password
4. go to http://localhost:8080/ui/api/stats
    i got `{"runningQueries":0,"blockedQueries":0,"queuedQueries":0,"activeCoordinators":1,"activeWorkers":1,"runningDrivers":0,"totalAvailableProcessors":10,"reservedMemory":0.0,"totalInputRows":1,"totalInputBytes":0,"totalCpuTimeSecs":0}` as the response, no stacktrace

**Comment by jerryleooo** [comment]
@findepi thank for taking time to reproduce. I guess the issue has been fixed in https://github.com/trinodb/trino/pull/8017 which is 357. Let me try and back here.

**Comment by findepi** [comment]
I just noticed that the stacktrace in https://github.com/trinodb/trino/issues/4626#issuecomment-1342405179 doesn't match the Trino version "356" it is supposed to come from.

It is recommended to reproduce a problem on "vanilla" Trino build (without custom modifications) before filing a bug report,
