### ISSUE TITLE
Flaky test TestOracleDistributedQueries

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#4654]
```
2020-07-30T11:28:19.0797531Z [ERROR] testDataMappingSmokeTest(io.prestosql.plugin.oracle.TestOracleDistributedQueries)  Time elapsed: 1.578 s  <<< FAILURE!
2020-07-30T11:28:19.0798099Z java.lang.AssertionError: Execution of 'actual' query failed: SELECT id FROM presto_tmp_298968869824 WHERE value IS NULL
2020-07-30T11:28:19.0798418Z 	at org.testng.Assert.fail(Assert.java:83)
2020-07-30T11:28:19.0799099Z 	at io.prestosql.testing.QueryAssertions.assertQuery(QueryAssertions.java:150)
2020-07-30T11:28:19.0799995Z 	at io.prestosql.testing.QueryAssertions.assertQuery(QueryAssertions.java:106)
2020-07-30T11:28:19.0801120Z 	at io.prestosql.testing.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:130)
2020-07-30T11:28:19.0802722Z 	at io.prestosql.testing.AbstractTestDistributedQueries.testDataMappingSmokeTest(AbstractTestDistributedQueries.java:1313)
2020-07-30T11:28:19.0803795Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-07-30T11:28:19.0804676Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-07-30T11:28:19.0805909Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-07-30T11:28:19.0806462Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-07-30T11:28:19.0807503Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-07-30T11:28:19.0808115Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-07-30T11:28:19.0808772Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-07-30T11:28:19.0809477Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-07-30T11:28:19.0810430Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-07-30T11:28:19.0811200Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-07-30T11:28:19.0812268Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-07-30T11:28:19.0813302Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-07-30T11:28:19.0813777Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-07-30T11:28:19.0814530Z Caused by: java.lang.RuntimeException: No more data to read from socket
2020-07-30T11:28:19.0815662Z 	at io.prestosql.testing.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:114)
2020-07-30T11:28:19.0816609Z 	at io.prestosql.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:442)
2020-07-30T11:28:19.0817481Z 	at io.prestosql.testing.QueryAssertions.assertQuery(QueryAssertions.java:147)
2020-07-30T11:28:19.0817724Z 	... 16 more
2020-07-30T11:28:19.0818291Z Caused by: io.prestosql.spi.PrestoException: No more data to read from socket
2020-07-30T11:28:19.0819205Z 	at io.prestosql.plugin.jdbc.BaseJdbcClient.getTableHandle(BaseJdbcClient.java:257)
2020-07-30T11:28:19.0820262Z 	at io.prestosql.plugin.jdbc.ForwardingJdbcClient.getTableHandle(ForwardingJdbcClient.java:78)
2020-07-30T11:28:19.0822353Z 	at io.prestosql.plugin.jdbc.jmx.StatisticsAwareJdbcClient.lambda$getTableHandle$3(StatisticsAwareJdbcClient.java:94)
2020-07-30T11:28:19.0823425Z 	at io.prestosql.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
2020-07-30T11:28:19.0825280Z 	at io.prestosql.plugin.jdbc.jmx.StatisticsAwareJdbcClient.getTableHandle(StatisticsAwareJdbcClient.java:94)
2020-07-30T11:28:19.0826710Z 	at io.prestosql.plugin.jdbc.CachingJdbcClient.getTableHandle(CachingJdbcClient.java:191)
2020-07-30T11:28:19.0828167Z 	at io.prestosql.plugin.jdbc.CachingJdbcClient.getTableHandle(CachingJdbcClient.java:191)
2020-07-30T11:28:19.0829427Z 	at io.prestosql.plugin.jdbc.JdbcMetadata.getTableHandle(JdbcMetadata.java:97)
2020-07-30T11:28:19.0830656Z 	at io.prestosql.plugin.jdbc.JdbcMetadata.getTableHandle(JdbcMetadata.java:66)
2020-07-30T11:28:19.0832043Z 	at io.prestosql.metadata.MetadataManager.getTableHandle(MetadataManager.java:341)
2020-07-30T11:28:19.0833583Z 	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1036)
2020-07-30T11:28:19.0835211Z 	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:307)
2020-07-30T11:28:19.0835795Z 	at io.prestosql.sql.tree.Table.accept(Table.java:53)
2020-07-30T11:28:19.0836584Z 	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
2020-07-30T11:28:19.0837767Z 	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:324)
2020-07-30T11:28:19.0839060Z 	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:2244)
2020-07-30T11:28:19.0840480Z 	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1287)
2020-07-30T11:28:19.0842392Z 	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:307)
2020-07-30T11:28:19.0843247Z 	at io.prestosql.sql.tree.QuerySpecification.accept(QuerySpecification.java:144)
2020-07-30T11:28:19.0843834Z 	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
2020-07-30T11:28:19.0845154Z 	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:324)
2020-07-30T11:28:19.0845632Z 	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:334)
2020-07-30T11:28:19.0846535Z 	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:921)
2020-07-30T11:28:19.0847877Z 	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:307)
2020-07-30T11:28:19.0849161Z 	at io.prestosql.sql.tree.Query.accept(Query.java:107)
2020-07-30T11:28:19.0849626Z 	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
2020-07-30T11:28:19.0850536Z 	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:324)
2020-07-30T11:28:19.0851824Z 	at io.prestosql.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:293)
2020-07-30T11:28:19.0852315Z 	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
2020-07-30T11:28:19.0853155Z 	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:75)
2020-07-30T11:28:19.0854510Z 	at io.prestosql.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:246)
2020-07-30T11:28:19.0855444Z 	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:180)
2020-07-30T11:28:19.0855735Z 	at io.prestosql.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:746)
2020-07-30T11:28:19.0856033Z 	at io.prestosql.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:123)
2020-07-30T11:28:19.0856342Z 	at io.prestosql.$gen.Presto_testversion____20200730_112107_3.call(Unknown Source)
2020-07-30T11:28:19.0856768Z 	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
2020-07-30T11:28:19.0857137Z 	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
2020-07-30T11:28:19.0857440Z 	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
2020-07-30T11:28:19.0858518Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-07-30T11:28:19.0859714Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-07-30T11:28:19.0860287Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-07-30T11:28:19.0861247Z Caused by: java.sql.SQLRecoverableException: No more data to read from socket
2020-07-30T11:28:19.0862341Z 	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:784)
2020-07-30T11:28:19.0863310Z 	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:429)
2020-07-30T11:28:19.0864009Z 	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:407)
2020-07-30T11:28:19.0864658Z 	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268)
2020-07-30T11:28:19.0865767Z 	at oracle.jdbc.driver.T4CTTIoauthenticate.doOSESSKEY(T4CTTIoauthenticate.java:521)
2020-07-30T11:28:19.0866554Z 	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:691)
2020-07-30T11:28:19.0867534Z 	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:793)
2020-07-30T11:28:19.0868621Z 	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:57)
2020-07-30T11:28:19.0869369Z 	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:747)
2020-07-30T11:28:19.0870203Z 	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:562)
2020-07-30T11:28:19.0871554Z 	at io.prestosql.plugin.jdbc.DriverConnectionFactory.openConnection(DriverConnectionFactory.java:73)
2020-07-30T11:28:19.0873384Z 	at io.prestosql.plugin.jdbc.jmx.StatisticsAwareConnectionFactory.lambda$openConnection$0(StatisticsAwareConnectionFactory.java:42)
2020-07-30T11:28:19.0874191Z 	at io.prestosql.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
2020-07-30T11:28:19.0875832Z 	at io.prestosql.plugin.jdbc.jmx.StatisticsAwareConnectionFactory.openConnection(StatisticsAwareConnectionFactory.java:42)
2020-07-30T11:28:19.0876849Z 	at io.prestosql.plugin.jdbc.BaseJdbcClient.getTableHandle(BaseJdbcClient.java:235)
2020-07-30T11:28:19.0877130Z 	... 40 more
```

https://github.com/prestosql/presto/runs/927078310

Related: https://github.com/prestosql/presto/issues/4568

**Comment by kokosing** [comment]
Fixed with https://github.com/prestosql/presto/pull/4947
