### ISSUE TITLE
MySQL connector always throws java.lang.NullPointerException when record cursor is closed

### ISSUE THREAD

**Issue by sopel39** [prestosql/presto#469]
The exception is:
```
java.lang.NullPointerException
	at com.mysql.jdbc.MysqlIO.clearInputStream(MysqlIO.java:899)
	at com.mysql.jdbc.RowDataDynamic.close(RowDataDynamic.java:172)
	at com.mysql.jdbc.ResultSetImpl.realClose(ResultSetImpl.java:6680)
	at com.mysql.jdbc.ResultSetImpl.close(ResultSetImpl.java:851)
	at io.prestosql.plugin.jdbc.JdbcRecordCursor.close(JdbcRecordCursor.java:219)
	at io.prestosql.operator.ScanFilterAndProjectOperator.finish(ScanFilterAndProjectOperator.java:176)
	at io.prestosql.operator.ScanFilterAndProjectOperator.close(ScanFilterAndProjectOperator.java:160)
	at io.prestosql.operator.Driver.closeAndDestroyOperators(Driver.java:546)
	at io.prestosql.operator.Driver.processInternal(Driver.java:406)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
```
Yet it's only logged because of `io.prestosql.operator.Driver#addSuppressedException` during operator close/destroy.

**Comment by ebyhr** [comment]
Is this the same as https://github.com/prestosql/presto/issues/443? If so, I'll close my issue.

**Comment by sopel39** [comment]
Yes. It's a duplicate.
