### ISSUE TITLE
Can't query postgres tables that have a "time with time zone" column.

### ISSUE THREAD

**Issue by jvlasblom** [prestosql/presto#4715]
In Presto 339 I can't query postgres tables that have a "time with time zone".

```
Postgres
=======
datetimetest=# create table foo(id serial, thetimewithtimezone time with time zone);
datetimetest=# insert into foo(thetimewithtimezone) VALUES('2020-05-27 12:22:27.000 America/Los_Angeles');
datetimetest=# select * from foo;
 id | thetimewithtimezone 
----+---------------------
  1 | 12:22:27-07
(1 row)
Presto
=====
presto> SELECT * FROM postgres.public.foo;
Query 20200806_143055_00002_uc997, FAILED, 1 node
Splits: 1 total, 0 done (0.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]
Query 20200806_143055_00002_uc997 failed: Bad value for type timestamp/date/time: {1}
```

However, 'timestamp with time zone' columns seem to work fine.   The Presto output shows the following:

```
2020-08-06T10:30:55.698-0400    ERROR   remote-task-callback-12 io.prestosql.execution.StageStateMachine        Stage 20200806_143055_00002_uc997.1 failed
io.prestosql.spi.PrestoException: Bad value for type timestamp/date/time: {1}
        at io.prestosql.plugin.jdbc.JdbcRecordCursor.handleSqlException(JdbcRecordCursor.java:250)
        at io.prestosql.plugin.jdbc.JdbcRecordCursor.getLong(JdbcRecordCursor.java:163)
        at io.prestosql.spi.connector.RecordPageSource.getNextPage(RecordPageSource.java:106)
        at io.prestosql.operator.TableScanOperator.getOutput(TableScanOperator.java:301)
        at io.prestosql.operator.Driver.processInternal(Driver.java:379)
        at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
        at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
        at io.prestosql.operator.Driver.processFor(Driver.java:276)
        at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
        at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
        at io.prestosql.$gen.Presto_339____20200806_142439_2.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.postgresql.util.PSQLException: Bad value for type timestamp/date/time: {1}
        at org.postgresql.jdbc.TimestampUtils.toLocalTime(TimestampUtils.java:433)
        at org.postgresql.jdbc.PgResultSet.getLocalTime(PgResultSet.java:563)
        at org.postgresql.jdbc.PgResultSet.getObject(PgResultSet.java:3391)
        at io.prestosql.plugin.jdbc.StandardColumnMappings.lambda$timeColumnMapping$21(StandardColumnMappings.java:332)
        at io.prestosql.plugin.jdbc.JdbcRecordCursor.getLong(JdbcRecordCursor.java:160)
        ... 13 more
Caused by: java.time.format.DateTimeParseException: Text '12:22:27-07' could not be parsed, unparsed text found at index 8
        at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2049)
        at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948)
        at java.base/java.time.LocalTime.parse(LocalTime.java:463)
        at java.base/java.time.LocalTime.parse(LocalTime.java:448)
        at org.postgresql.jdbc.TimestampUtils.toLocalTime(TimestampUtils.java:430)
        ... 17 more
```

**Comment by findepi** [comment]
@jvlasblom PostgreSQL `TIME WITH TIME ZONE` is not supported and thus has no tests.
Since it is advertised by PostgreSQL JDBC  as `TIME`, it is attempted to be read as such.

did this work in older Presto versions?

you can probably temporarily workaround by adding
```
jdbc-types-mapped-to-varchar=timetz
```

to the postgresql catalog properties file.
