### ISSUE TITLE
MySQL Connector via JDBC - INSERT - limited to about 100 rows - observed 98 to 115

### ISSUE THREAD

**Issue by walter-weinmann** [prestosql/presto#4732]
Presto version : 339 (same JDBC and CLI)

both Presto and MySQL via Docker container

the following run is supposed to insert another 50 rows - but fails:

```
[main] Start MySQL Database
[main] database table country           -         50 rows created
[main] database table timezone          -         11 rows created
java.sql.SQLException: Query failed (#20200807_112716_00725_g8ca2): Could not create connection to database server. Attempted reconnect 3 times. Giving up.
        at io.prestosql.jdbc.AbstractPrestoResultSet.resultsException(AbstractPrestoResultSet.java:1730)
        at io.prestosql.jdbc.PrestoResultSet.getColumns(PrestoResultSet.java:249)
        at io.prestosql.jdbc.PrestoResultSet.create(PrestoResultSet.java:52)
        at io.prestosql.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:249)
        at io.prestosql.jdbc.PrestoStatement.execute(PrestoStatement.java:227)
        at io.prestosql.jdbc.PrestoPreparedStatement.executeLargeUpdate(PrestoPreparedStatement.java:129)
        at io.prestosql.jdbc.PrestoPreparedStatement.executeUpdate(PrestoPreparedStatement.java:122)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.createDataInsert(AbstractJdbcSeeder.java:467)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.createData(AbstractJdbcSeeder.java:407)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.createData(AbstractJdbcSeeder.java:365)
        at ch.konnexions.db_seeder.DatabaseSeeder.main(DatabaseSeeder.java:150)
Caused by: io.prestosql.spi.PrestoException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
        at io.prestosql.plugin.jdbc.BaseJdbcClient.beginInsertTable(BaseJdbcClient.java:524)
        at io.prestosql.plugin.jdbc.ForwardingJdbcClient.beginInsertTable(ForwardingJdbcClient.java:153)
        at io.prestosql.plugin.jdbc.jmx.StatisticsAwareJdbcClient.lambda$beginInsertTable$19(StatisticsAwareJdbcClient.java:199)
        at io.prestosql.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
        at io.prestosql.plugin.jdbc.jmx.StatisticsAwareJdbcClient.beginInsertTable(StatisticsAwareJdbcClient.java:199)
        at io.prestosql.plugin.jdbc.CachingJdbcClient.beginInsertTable(CachingJdbcClient.java:208)
        at io.prestosql.plugin.jdbc.CachingJdbcClient.beginInsertTable(CachingJdbcClient.java:208)
        at io.prestosql.plugin.jdbc.JdbcMetadata.beginInsert(JdbcMetadata.java:405)
        at io.prestosql.metadata.MetadataManager.beginInsert(MetadataManager.java:815)
        at io.prestosql.sql.planner.optimizations.BeginTableWrite$Rewriter.createWriterTarget(BeginTableWrite.java:184)
        at io.prestosql.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:143)
        at io.prestosql.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:76)
        at io.prestosql.sql.planner.plan.TableFinishNode.accept(TableFinishNode.java:106)
        at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
        at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Collections$2.tryAdvance(Collections.java:4820)
        at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4828)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
        at io.prestosql.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:38)
        at io.prestosql.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:22)
        at io.prestosql.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
        at io.prestosql.sql.planner.plan.OutputNode.accept(OutputNode.java:83)
        at io.prestosql.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:32)
        at io.prestosql.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:73)
        at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:200)
        at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:189)
        at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:184)
        at io.prestosql.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:425)
        at io.prestosql.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:413)
        at io.prestosql.execution.SqlQueryExecution.start(SqlQueryExecution.java:365)
        at io.prestosql.execution.SqlQueryManager.createQuery(SqlQueryManager.java:245)
        at io.prestosql.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:132)
        at io.prestosql.$gen.Presto_339____20200807_075701_2.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.Util.getInstance(Util.java:408)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
        at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2095)
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2020)
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768)
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
        at jdk.internal.reflect.GeneratedConstructorAccessor134.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
        at io.prestosql.plugin.jdbc.DriverConnectionFactory.openConnection(DriverConnectionFactory.java:73)
        at io.prestosql.plugin.jdbc.jmx.StatisticsAwareConnectionFactory.lambda$openConnection$0(StatisticsAwareConnectionFactory.java:42)
        at io.prestosql.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
        at io.prestosql.plugin.jdbc.jmx.StatisticsAwareConnectionFactory.openConnection(StatisticsAwareConnectionFactory.java:42)
        at io.prestosql.plugin.jdbc.BaseJdbcClient.beginInsertTable(BaseJdbcClient.java:493)
        ... 41 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
        at jdk.internal.reflect.GeneratedConstructorAccessor174.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
        at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:335)
        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2187)
        at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2036)
        ... 56 more
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:589)
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
        at java.base/java.net.Socket.connect(Socket.java:648)
        at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
        at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:299)
        ... 58 more
PS D:\SoftDevelopment\Projects\Konnexions\db_seeder>
```

**Comment by ebyhr** [comment]
Could you share the steps to reproduce?

**Comment by walter-weinmann** [comment]
I am working on the following project https://github.com/KonnexionsGmbH/db_seeder which supports MySQL, Oracle, PostgreSQL and SQL Server. I would like to use the Presto JDBC driver as an alternative to the original JDBC drivers.

The main work is to insert a given number of rows into freely definable tables (simple INSERT via JDBC and PreparedStatement). The setup of the respective database (database, schema, user etc.) is done with the original driver and only the INSERTs are done alternatively with the original driver or the Presto driver.

But this seems to be not so easy, with all four connectors I run into different problems. Oracle seems to be solved in the meantime, which gives me some hope.

**Comment by walter-weinmann** [comment]
see #4812
