### ISSUE TITLE
Support Oracle's NUMBER data type

### ISSUE THREAD

**Issue by walter-weinmann** [prestosql/presto#4750]
```
java.sql.SQLException: Query failed (#20200808_125219_00020_tm2rm): Insert column name does not exist in target table: pk_country_id
        at io.prestosql.jdbc.AbstractPrestoResultSet.resultsException(AbstractPrestoResultSet.java:1730)
        at io.prestosql.jdbc.PrestoResultSet.getColumns(PrestoResultSet.java:249)
        at io.prestosql.jdbc.PrestoResultSet.create(PrestoResultSet.java:52)
        at io.prestosql.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:249)
        at io.prestosql.jdbc.PrestoStatement.execute(PrestoStatement.java:227)
        at io.prestosql.jdbc.PrestoPreparedStatement.executeLargeUpdate(PrestoPreparedStatement.java:129)
        at io.prestosql.jdbc.PrestoPreparedStatement.executeUpdate(PrestoPreparedStatement.java:122)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.createDataInsert(AbstractJdbcSeeder.java:458)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.createData(AbstractJdbcSeeder.java:398)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.createData(AbstractJdbcSeeder.java:356)
        at ch.konnexions.db_seeder.DatabaseSeeder.main(DatabaseSeeder.java:170)
Caused by: io.prestosql.spi.PrestoException: Insert column name does not exist in target table: pk_country_id
        at io.prestosql.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
        at io.prestosql.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitInsert(StatementAnalyzer.java:399)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitInsert(StatementAnalyzer.java:303)
        at io.prestosql.sql.tree.Insert.accept(Insert.java:63)
        at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:320)
        at io.prestosql.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:289)
        at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
        at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:75)
        at io.prestosql.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:246)
        at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:180)
        at io.prestosql.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:746)
        at io.prestosql.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:121)
        at io.prestosql.$gen.Presto_339____20200808_120500_2.call(Unknown Source)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
PS D:\SoftDevelopment\Projects\Konnexions\db_seeder>
```

## DBeaver:

![image](https://user-images.githubusercontent.com/1956149/89710895-15eeb800-d987-11ea-8372-5056308ad1cc.png)

![image](https://user-images.githubusercontent.com/1956149/89710914-3c145800-d987-11ea-827f-205fbd0be615.png)

## Presto:

```
D:\SoftDevelopment\Projects\Konnexions\db_seeder>docker exec -it db_seeder_presto bash
root@c27339bae67e:/# presto
presto> show catalogs;
     Catalog
------------------
 db_seeder_mysql
 db_seeder_oracle
 system
 tpch
(4 rows)
Query 20200808_125723_00021_tm2rm, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
0.24 [0 rows, 0B] [0 rows/s, 0B/s]

presto> show schemas from db_seeder_oracle;
         Schema
------------------------
 anonymous
 appqossys
 audsys
 dbsfwuser
 dbsnmp
 dip
 dvf
 dvsys
 ggsys
 gsmadmin_internal
 gsmcatuser
 gsmuser
 information_schema
 kxn_user
 lbacsys
 mddata
 ojvmsys
 olapsys
 oracle_ocm
 orddata
 ordplugins
 ordsys
 pdbadmin
 remote_scheduler_agent
 si_informtn_schema
 sys$umf
 sysbackup
 sysdg
 syskm
 sysrac
 wmsys
(31 rows)
Query 20200808_125746_00022_tm2rm, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
0.24 [31 rows, 415B] [127 rows/s, 1.67KB/s]

presto> use db_seeder_oracle.kxn_user;
USE
presto:kxn_user> show tables;
     Table
---------------
 city
 company
 country
 country_state
 timezone
(5 rows)
Query 20200808_125820_00026_tm2rm, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
0.22 [5 rows, 129B] [22 rows/s, 586B/s]

presto> show columns from country

presto:kxn_user> show columns from country;
   Column    |     Type     | Extra | Comment
-------------+--------------+-------+---------
 country_map | varbinary    |       |
 created     | timestamp(3) |       |
 iso3166     | varchar(50)  |       |
 modified    | timestamp(3) |       |
 name        | varchar(100) |       |
(5 rows)
Query 20200808_125919_00029_tm2rm, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
0.44 [5 rows, 363B] [11 rows/s, 819B/s]

presto:kxn_user>


```

**Comment by findepi** [comment]
Please try adding  something like 
```
oracle.number.default-scale=38
```
to your oracle connector configuration properties file (`db_seeder_oracle.properties`)

**Comment by walter-weinmann** [comment]
#### I have changed the configuration:

```
connector.name=oracle
connection-url=jdbc:oracle:thin:@//192.168.1.109:1521/orclpdb1
connection-user=kxn_user
connection-password=oracle
oracle.number.default-scale=38
```
#### and got now:

```
java.sql.SQLException: Query failed (#20200809_065847_00002_pum6z): Cannot cast BIGINT '1' to DECIMAL(38, 38)
        at io.prestosql.jdbc.AbstractPrestoResultSet.resultsException(AbstractPrestoResultSet.java:1730)
        at io.prestosql.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:225)
        at io.prestosql.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:185)
        at io.prestosql.jdbc.$internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
        at io.prestosql.jdbc.$internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
        at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
        at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
        at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
        at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
        at io.prestosql.jdbc.PrestoResultSet$AsyncIterator.lambda$new$0(PrestoResultSet.java:131)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: io.prestosql.spi.PrestoException: Cannot cast BIGINT '1' to DECIMAL(38, 38)
        at io.prestosql.type.DecimalCasts.bigintToLongDecimal(DecimalCasts.java:233)
        at io.prestosql.$gen.PageProjectionWork_20200809_065849_9.evaluate(Unknown Source)
        at io.prestosql.$gen.PageProjectionWork_20200809_065849_9.process(Unknown Source)
        at io.prestosql.operator.project.DictionaryAwarePageProjection$DictionaryAwarePageProjectionWork.processInternal(DictionaryAwarePageProjection.java:185)
        at io.prestosql.operator.project.DictionaryAwarePageProjection$DictionaryAwarePageProjectionWork.process(DictionaryAwarePageProjection.java:121)
        at io.prestosql.operator.project.PageProcessor$ProjectSelectedPositions.processBatch(PageProcessor.java:333)
        at io.prestosql.operator.project.PageProcessor$ProjectSelectedPositions.process(PageProcessor.java:205)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.prestosql.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:277)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
        at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.prestosql.operator.WorkProcessorOperatorAdapter.getOutput(WorkProcessorOperatorAdapter.java:188)
        at io.prestosql.operator.Driver.processInternal(Driver.java:379)
        at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
        at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
        at io.prestosql.operator.Driver.processFor(Driver.java:276)
        at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
        at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
        at io.prestosql.$gen.Presto_339____20200809_064840_2.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by kokosing** [comment]
It is expected behavior. You used all digits for scale. Please use lower default scale and it should work.

**Comment by walter-weinmann** [comment]
Great that solved my problems with the Oracle Connector - thank you very much. But I think that the connector documentation needs some additions.

**Comment by kokosing** [comment]
> But I think that the connector documentation needs some additions.

Could you please elaborate what needs to improved? What was misleading?

> Great that solved my problems with the Oracle Connector 

Great, thank you! Let me close the issue then.

**Comment by walter-weinmann** [comment]
It is not obvious that the data type BIGINT needs the surprise entry `oracle.number.default-scale=99` in the catalog properties file and that the given number must be less than `38`,

**Comment by kokosing** [comment]
> given number must be less than 38,

This is maximal decimal precision in Presto.

> It is not obvious that the data type BIGINT needs the surprise entry oracle.number.default-scale=99 

I think we could change a default value for this so it get's a bit more user friendly. Would you like to open an issue for that? I think `oracle.number.default-scale=10` could be in most cases good enough.

**Comment by walter-weinmann** [comment]
The default value is a good idea (I chose 10 myself) but there should still be a note in the Oracle connector documentation.

**Comment by kokosing** [comment]
@mosabua What do you think about the above? ^^^

**Comment by mosabua** [comment]
Sounds good to me. When we implement that we can just add the doc update to the same PR. I can review as desired.
