### ISSUE TITLE
Cannot insert BLOB using Presto JDBC

### ISSUE THREAD

**Issue by walter-weinmann** [prestosql/presto#4751]
```
java.sql.SQLFeatureNotSupportedException: setBinaryStream
        at io.prestosql.jdbc.PrestoPreparedStatement.setBinaryStream(PrestoPreparedStatement.java:633)
        at ch.konnexions.db_seeder.jdbc.postgresql.PostgresqlSeeder.prepStmntColBlob(PostgresqlSeeder.java:156)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.prepStmntColBlobOpt(AbstractJdbcSeeder.java:1092)
        at ch.konnexions.db_seeder.generated.AbstractGenSeeder.prepDmlStmntInsertCountry(AbstractGenSeeder.java:407)
        at ch.konnexions.db_seeder.generated.AbstractGenSeeder.insertTable(AbstractGenSeeder.java:171)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.createDataInsert(AbstractJdbcSeeder.java:453)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.createData(AbstractJdbcSeeder.java:398)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.createData(AbstractJdbcSeeder.java:356)
        at ch.konnexions.db_seeder.DatabaseSeeder.main(DatabaseSeeder.java:182)
```

**Comment by findepi** [comment]
`java.sql.PreparedStatement#setBinaryStream` is not supported.
Did you try using `java.sql.PreparedStatement#setBytes` instead?

**Comment by walter-weinmann** [comment]
I'm already using setBytes:

```
  protected void prepStmntColBlob(PreparedStatement preparedStatement, String tableName, String columnName, int columnPos, long rowNo) {
    try {
      preparedStatement.setBytes(columnPos,
                                 getContentBlob(tableName,
                                                columnName,
                                                rowNo));
    } catch (SQLException e) {
      e.printStackTrace();
      System.exit(1);
    }
  }

```

**Comment by ebyhr** [comment]
Could you share the steps to reproduce? What is the latest error message & stacktrace? I can insert bytes as follows:
```java
  public static void main(String[] args) throws Exception {
    String url = "jdbc:presto://localhost:8080";
    Connection connection = DriverManager.getConnection(url, "test", null);

    Statement statement = connection.createStatement();
    statement.execute("DROP TABLE IF EXISTS postgresql.tpch.test");
    statement.execute("CREATE TABLE postgresql.tpch.test (c1 int, c2 varbinary)");

    PreparedStatement preparedStatement = connection.prepareStatement("INSERT INTO postgresql.tpch.test VALUES (?, ?)");
    preparedStatement.setInt(1, 1);
    preparedStatement.setBytes(2, new byte[]{1});
    preparedStatement.execute();
  }
```

**Comment by walter-weinmann** [comment]
Sorry you are right - everything is ok now - I missed that one method was overwritten. Thanks for the support.
