### ISSUE TITLE
SQL Server Connector - Login failed

### ISSUE THREAD

**Issue by walter-weinmann** [prestosql/presto#4757]
#### This is the content of my catalog file (db_seeder_mssqlserver.properties):

```
connector.name=sqlserver
connection-url=jdbc:sqlserver://192.168.1.109:1433
connection-user=kxn_user
connection-password=mssqlserver_2019
```

#### No problem connecting with DBeaver:

![image](https://user-images.githubusercontent.com/1956149/89727552-476a9080-da26-11ea-97b8-4c517da9c2a9.png)

#### Presto gives me:

```
presto> show catalogs;
        Catalog
-----------------------
 db_seeder_mssqlserver
 db_seeder_mysql
 db_seeder_oracle
 db_seeder_postgresql
 system
 tpch
(6 rows)
Query 20200809_074637_00005_pum6z, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
0.24 [0 rows, 0B] [0 rows/s, 0B/s]

presto> show schemas from db_seeder_mssqlserver;
Query 20200809_074705_00006_pum6z, FAILED, 1 node
Splits: 19 total, 0 done (0.00%)
0.21 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20200809_074705_00006_pum6z failed: Login failed for user 'kxn_user'. ClientConnectionId:1c832f69-9607-42f7-8dfe-6997ea5848a7

```

**Comment by ebyhr** [comment]
Does the connection fail even after appending database to url as `jdbc:sqlserver://192.168.1.109:1433/kxn_db`?

**Comment by walter-weinmann** [comment]
I'll try - but according to the SQL Server Connector documentation the url ends with the port number.

**Comment by kokosing** [comment]
Can you please try to connect to SQL Server with https://dbeaver.io/ which is using JDBC internally. SQL Server connector is also using JDBC internally so when you can get JDBC working it should be straightforward to setup a connector.

**Comment by walter-weinmann** [comment]
As you can see above I can connect to the SQL Server with DBeaver.

#### Adding the database to the url string:

```
connector.name=sqlserver
connection-url=jdbc:sqlserver://192.168.1.109:1433/kxn_db
connection-user=kxn_user
connection-password=sqlserver_2019
```

#### gives:

```
java.sql.SQLException: Query failed (#20200810_082244_00000_9qeyf): The port number 1433/kxn_db is not valid.
        at io.prestosql.jdbc.AbstractPrestoResultSet.resultsException(AbstractPrestoResultSet.java:1730)
        at io.prestosql.jdbc.PrestoResultSet.getColumns(PrestoResultSet.java:249)
        at io.prestosql.jdbc.PrestoResultSet.create(PrestoResultSet.java:52)
        at io.prestosql.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:249)
        at io.prestosql.jdbc.PrestoStatement.execute(PrestoStatement.java:227)
        at io.prestosql.jdbc.PrestoStatement.executeQuery(PrestoStatement.java:76)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.countData(AbstractJdbcSeeder.java:320)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.createData(AbstractJdbcSeeder.java:394)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.createData(AbstractJdbcSeeder.java:362)
        at ch.konnexions.db_seeder.DatabaseSeeder.main(DatabaseSeeder.java:188)
Caused by: io.prestosql.spi.PrestoException: The port number 1433/kxn_db is not valid.
        at io.prestosql.plugin.jdbc.BaseJdbcClient.getTableHandle(BaseJdbcClient.java:255)
        at io.prestosql.plugin.jdbc.ForwardingJdbcClient.getTableHandle(ForwardingJdbcClient.java:78)
        at io.prestosql.plugin.jdbc.jmx.StatisticsAwareJdbcClient.lambda$getTableHandle$3(StatisticsAwareJdbcClient.java:94)
        at io.prestosql.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
        at io.prestosql.plugin.jdbc.jmx.StatisticsAwareJdbcClient.getTableHandle(StatisticsAwareJdbcClient.java:94)
        at io.prestosql.plugin.jdbc.CachingJdbcClient.getTableHandle(CachingJdbcClient.java:191)
        at io.prestosql.plugin.jdbc.CachingJdbcClient.getTableHandle(CachingJdbcClient.java:191)
        at io.prestosql.plugin.jdbc.JdbcMetadata.getTableHandle(JdbcMetadata.java:97)
        at io.prestosql.plugin.jdbc.JdbcMetadata.getTableHandle(JdbcMetadata.java:66)
        at io.prestosql.metadata.MetadataManager.getTableHandle(MetadataManager.java:331)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1032)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:303)
        at io.prestosql.sql.tree.Table.accept(Table.java:53)
        at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:320)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:2240)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1283)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:303)
        at io.prestosql.sql.tree.QuerySpecification.accept(QuerySpecification.java:144)
        at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:320)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:330)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:917)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:303)
        at io.prestosql.sql.tree.Query.accept(Query.java:107)
        at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:320)
        at io.prestosql.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:289)
        at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
        at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:75)
        at io.prestosql.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:246)
        at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:180)
        at io.prestosql.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:746)
        at io.prestosql.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:121)
        at io.prestosql.$gen.Presto_339____20200810_082048_2.call(Unknown Source)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The port number 1433/kxn_db is not valid.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:226)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:1652)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1120)
        at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:700)
        at io.prestosql.plugin.jdbc.DriverConnectionFactory.openConnection(DriverConnectionFactory.java:73)
        at io.prestosql.plugin.jdbc.jmx.StatisticsAwareConnectionFactory.lambda$openConnection$0(StatisticsAwareConnectionFactory.java:42)
        at io.prestosql.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
        at io.prestosql.plugin.jdbc.jmx.StatisticsAwareConnectionFactory.openConnection(StatisticsAwareConnectionFactory.java:42)
        at io.prestosql.plugin.jdbc.BaseJdbcClient.getTableHandle(BaseJdbcClient.java:233)
        ... 40 more
PS D:\SoftDevelopment\Projects\Konnexions\db_seeder>
```

**Comment by ebyhr** [comment]
Sorry, wrote the invalid url. Could you try `jdbc:sqlserver://192.168.1.109:1433?databaseName=kxn_db`?

**Comment by walter-weinmann** [comment]
#### catalog properties

```
connector.name=sqlserver
connection-url=jdbc:sqlserver://192.168.1.109:1433;databaseName=kxn_db
connection-user=kxn_user
connection-password=sqlserver_2019
```
#### result:

```
java.sql.SQLException: Query failed (#20200810_085958_00000_whzva): line 1:22: Schema 'kxn_db' does not exist
        at io.prestosql.jdbc.AbstractPrestoResultSet.resultsException(AbstractPrestoResultSet.java:1730)
        at io.prestosql.jdbc.PrestoResultSet.getColumns(PrestoResultSet.java:249)
        at io.prestosql.jdbc.PrestoResultSet.create(PrestoResultSet.java:52)
        at io.prestosql.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:249)
        at io.prestosql.jdbc.PrestoStatement.execute(PrestoStatement.java:227)
        at io.prestosql.jdbc.PrestoStatement.executeQuery(PrestoStatement.java:76)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.countData(AbstractJdbcSeeder.java:320)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.createData(AbstractJdbcSeeder.java:394)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.createData(AbstractJdbcSeeder.java:362)
        at ch.konnexions.db_seeder.DatabaseSeeder.main(DatabaseSeeder.java:188)
Caused by: io.prestosql.spi.PrestoException: line 1:22: Schema 'kxn_db' does not exist
        at io.prestosql.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
        at io.prestosql.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1038)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:303)
        at io.prestosql.sql.tree.Table.accept(Table.java:53)
        at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:320)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:2240)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1283)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:303)
        at io.prestosql.sql.tree.QuerySpecification.accept(QuerySpecification.java:144)
        at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:320)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:330)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:917)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:303)
        at io.prestosql.sql.tree.Query.accept(Query.java:107)
        at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:320)
        at io.prestosql.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:289)
        at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
        at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:75)
        at io.prestosql.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:246)
        at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:180)
        at io.prestosql.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:746)
        at io.prestosql.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:121)
        at io.prestosql.$gen.Presto_339____20200810_085855_2.call(Unknown Source)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

#### DBeaver screenshots:

![image](https://user-images.githubusercontent.com/1956149/89766826-1018e400-daf9-11ea-9731-83bc91674d7b.png)

![image](https://user-images.githubusercontent.com/1956149/89766911-33439380-daf9-11ea-864a-ee5895c86899.png)

**Comment by ebyhr** [comment]
I think the connection failure is resolved now. You need to know SQL Server schema & database mapping in Presto is little tricky as https://github.com/prestosql/presto/issues/643

**Comment by walter-weinmann** [comment]
#### Sorry I don't understand - this is how it looks on my side:

```
D:\SoftDevelopment\Projects\Konnexions\db_seeder>docker exec -it db_seeder_presto bash
root@fa85d519d9cc:/# presto
presto> show catalogs
       Catalog
----------------------
 db_seeder_mysql
 db_seeder_oracle
 db_seeder_postgresql
 db_seeder_sqlserver
 system
 tpch
(6 rows)
Query 20200810_093708_00001_whzva, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
1.58 [0 rows, 0B] [0 rows/s, 0B/s]

presto> show schemas from db_seeder_sqlserver;
       Schema
--------------------
 db_accessadmin
 db_backupoperator
 db_datareader
 db_datawriter
 db_ddladmin
 db_denydatareader
 db_denydatawriter
 db_owner
 db_securityadmin
 dbo
 guest
 information_schema
 kxn_schema
 sys
(14 rows)
Query 20200810_093836_00004_whzva, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
0.43 [14 rows, 235B] [32 rows/s, 543B/s]
``````

#### What is the url supposed to be ?

`connection-url=jdbc:sqlserver://192.168.1.109:1433;databaseName=kxn_schema`

or

`connection-url=jdbc:sqlserver://192.168.1.109:1433;databaseName=kxn_db;schemaName=kxn_schema`

or

`connection-url=jdbc:sqlserver://192.168.1.109:1433;schemaName=kxn_schema`

Again - shouldn't this be clarified by the SQL Server Connector documentation ?

**Comment by ebyhr** [comment]
While we may need to improve the documentation, I'm not sure the current problem. 

> Schema 'kxn_db' does not exist

The message comes from db_seeder. You shouldn't pass `kxn_db` as the schema name. As far as I know, SQL Server doesn't have `schemaName` JDBC properties.

**Comment by walter-weinmann** [comment]
Sorry that's not true - the error message is coming from the Presto JDBC driver.

#### My latest connection properties - same url as with the original JDBC driver:

```
connector.name=sqlserver
connection-url=jdbc:sqlserver://192.168.1.109:1433;databaseName=kxn_db;user=kxn_user;password=sqlserver_2019
```

#### Same response from 

**io.prestosql.jdbc.AbstractPrestoResultSet.resultsException(AbstractPrestoResultSet.java:1730)**:

```
java.sql.SQLException: Query failed (#20200810_112259_00000_dpqxb): line 1:22: Schema 'kxn_db' does not exist
        at io.prestosql.jdbc.AbstractPrestoResultSet.resultsException(AbstractPrestoResultSet.java:1730)
        at io.prestosql.jdbc.PrestoResultSet.getColumns(PrestoResultSet.java:249)
        at io.prestosql.jdbc.PrestoResultSet.create(PrestoResultSet.java:52)
        at io.prestosql.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:249)
        at io.prestosql.jdbc.PrestoStatement.execute(PrestoStatement.java:227)
        at io.prestosql.jdbc.PrestoStatement.executeQuery(PrestoStatement.java:76)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.countData(AbstractJdbcSeeder.java:320)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.createData(AbstractJdbcSeeder.java:394)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.createData(AbstractJdbcSeeder.java:362)
        at ch.konnexions.db_seeder.DatabaseSeeder.main(DatabaseSeeder.java:188)
Caused by: io.prestosql.spi.PrestoException: line 1:22: Schema 'kxn_db' does not exist
        at io.prestosql.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
        at io.prestosql.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1038)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:303)
        at io.prestosql.sql.tree.Table.accept(Table.java:53)
        at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:320)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:2240)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1283)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:303)
        at io.prestosql.sql.tree.QuerySpecification.accept(QuerySpecification.java:144)
        at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:320)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:330)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:917)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:303)
        at io.prestosql.sql.tree.Query.accept(Query.java:107)
        at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:320)
        at io.prestosql.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:289)
        at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
        at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:75)
        at io.prestosql.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:246)
        at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:180)
        at io.prestosql.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:746)
        at io.prestosql.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:121)
        at io.prestosql.$gen.Presto_339____20200810_112056_2.call(Unknown Source)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)

```

**Comment by ebyhr** [comment]
I mean db_seeder is causing the error as the stacktrace has the following 
```
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.countData(AbstractJdbcSeeder.java:320)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.createData(AbstractJdbcSeeder.java:394)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.createData(AbstractJdbcSe
```

**Comment by walter-weinmann** [comment]
I think the issue is with the connection made by Presto based on the connection properties file.

The method countData issues only a statement like "SELECT COUNT(*) FROM <table>". Since the url in the connection properties file is the same what the Original driver gets - the issue must be caused by Presto.

Funny enough the SQL Server url does not contain a schema and db_seeder does also not make use of schema in connection with the SQL Server.

**Comment by ebyhr** [comment]
Then, can you share the steps to reproduce with pure Java code (without db_seeder)? Maybe, I'm not understanding your situation perfectly.

**Comment by walter-weinmann** [comment]
Two questions (I am pretty confused now):

According to SQL Server Connector documentaion the url syntax is as follows:

`jdbc:sqlserver://[serverName[\instanceName][:portNumber]]
`

The original Microsoft driver accepts:

`jdbc:sqlserver://localhost:1433;databaseName=master;user=sa;password=sqlserver_2019
`

My questions now:  

#### 1. Is the syntax definition in the SQL Connector Documentation restrictive, that is other addons are not allowed or is the full spectrum defined by Microsoft allowed?

#### 2. And do the same principles apply to the other connectors, i.e. MySQL, Oracle and PostgreSQL?

**Comment by ebyhr** [comment]
1. All JDBC properties Microsoft allow (e.g. `databaseName`) will work. 
2. It depends on the connector, but most JDBC based connector allow it. One exception I remember is MySQL connector prohibit to specify database name in the url.

**Comment by walter-weinmann** [comment]
I have now a demo program available - but first I want to show you a different view to my problem:

![image](https://user-images.githubusercontent.com/1956149/90011365-c3bcd800-dca1-11ea-8f0d-c52fed449712.png)

On the left side you can see the Presto view and on the right side the DBeaver view to the same database.

Running my tests with the original Microsoft driver is fine - with Presto I get the following:

```
java.sql.SQLException: Query failed (#20200812_113804_00001_96vyi): Table 'db_seeder_sqlserver.kxn_db.issue_table' does not exist
        at io.prestosql.jdbc.AbstractPrestoResultSet.resultsException(AbstractPrestoResultSet.java:1730)
        at io.prestosql.jdbc.PrestoResultSet.getColumns(PrestoResultSet.java:249)
        at io.prestosql.jdbc.PrestoResultSet.create(PrestoResultSet.java:52)
        at io.prestosql.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:249)
        at io.prestosql.jdbc.PrestoStatement.execute(PrestoStatement.java:227)
        at io.prestosql.jdbc.PrestoPreparedStatement.executeLargeUpdate(PrestoPreparedStatement.java:129)
        at io.prestosql.jdbc.PrestoPreparedStatement.executeUpdate(PrestoPreparedStatement.java:122)
        at ch.konnexions.db_seeder.IssuePresto4757.insertData(IssuePresto4757.java:248)
        at ch.konnexions.db_seeder.IssuePresto4757.demonstratePresto(IssuePresto4757.java:198)
        at ch.konnexions.db_seeder.IssuePresto4757.main(IssuePresto4757.java:301)
Caused by: io.prestosql.spi.PrestoException: Table 'db_seeder_sqlserver.kxn_db.issue_table' does not exist
        at io.prestosql.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
        at io.prestosql.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitInsert(StatementAnalyzer.java:361)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitInsert(StatementAnalyzer.java:303)
        at io.prestosql.sql.tree.Insert.accept(Insert.java:63)
        at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:320)
        at io.prestosql.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:289)
        at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
        at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:75)
        at io.prestosql.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:246)
        at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:180)
        at io.prestosql.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:746)
        at io.prestosql.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:121)
        at io.prestosql.$gen.Presto_339____20200812_113530_2.call(Unknown Source)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Processing of the script was aborted, error code=1
```

The connection properties are:

```
connector.name=sqlserver
connection-url=jdbc:sqlserver://192.168.1.109:1433;databaseName=kxn_db;user=kxn_user;password=sqlserver_2019
```
And the same URL as above I'm feeding the Microsoft driver with.

**Comment by ebyhr** [comment]
As I already wrote previously, it's known behavior. Getting `Table 'db_seeder_sqlserver.kxn_db.issue_table' does not exist' does not exist` is natural because `kxn_db` doesn't exist in `db_seeder_sqlserver` catalog.

**Comment by walter-weinmann** [comment]
View from Presto:

```
root@4d18bdee0064:/# presto
presto> show catalogs;
       Catalog
----------------------
 db_seeder_mysql
 db_seeder_oracle
 db_seeder_postgresql
 db_seeder_sqlserver
 system
 tpch
(6 rows)
Query 20200812_122658_00004_96vyi, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
0.24 [0 rows, 0B] [0 rows/s, 0B/s]

presto> show schemas from db_seeder_sqlserver;
       Schema
--------------------
 db_accessadmin
 db_backupoperator
 db_datareader
 db_datawriter
 db_ddladmin
 db_denydatareader
 db_denydatawriter
 db_owner
 db_securityadmin
 dbo
 guest
 information_schema
 kxn_schema
 sys
(14 rows)
Query 20200812_123253_00005_96vyi, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
0.25 [14 rows, 235B] [55 rows/s, 936B/s]

presto> show tables from db_seeder_sqlserver.dbo;
    Table
-------------
 issue_table
(1 row)
Query 20200812_123327_00006_96vyi, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
0.84 [1 rows, 24B] [1 rows/s, 29B/s]
```

View from DBeaver:

![image](https://user-images.githubusercontent.com/1956149/90015595-1948b300-dca9-11ea-9889-03f8ffb749d2.png)

I cannot use 

`jdbc:presto://localhost:8080/db_seeder_sqlserver/kxn_db/dbo?user=presto
`

since I get:

```
java.sql.SQLException: Invalid path segments in URL: presto://localhost:8080/db_seeder_sqlserver/kxn_db/dbo?user=presto
        at io.prestosql.jdbc.PrestoDriverUri.initCatalogAndSchema(PrestoDriverUri.java:321)
        at io.prestosql.jdbc.PrestoDriverUri.<init>(PrestoDriverUri.java:110)
        at io.prestosql.jdbc.PrestoDriverUri.<init>(PrestoDriverUri.java:95)
        at io.prestosql.jdbc.PrestoDriver.connect(PrestoDriver.java:85)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
        at ch.konnexions.db_seeder.IssuePresto4757.connect(IssuePresto4757.java:109)
        at ch.konnexions.db_seeder.IssuePresto4757.demonstratePresto(IssuePresto4757.java:190)
        at ch.konnexions.db_seeder.IssuePresto4757.main(IssuePresto4757.java:312)
Processing of the script was aborted, error code=1

```

I'm also avail on Slack.

**Comment by walter-weinmann** [comment]
The problem is now solved - thanks for the support.

**Comment by Alexander-Beskhlebnyy** [comment]
How did you resolve the problem?

**Comment by ebyhr** [comment]
@Alexander-Beskhlebnyy It was resolved by `databaseName` option in `connection-url`.
