### ISSUE TITLE
Serialization Exception for Tagged Union Type Fetched via HTTP Protocol

### ISSUE THREAD

**Issue by andrii-kovalchuk-exa** [prestosql/presto#4778]
Hello,

Starting from 339 version (works on 338) we are getting exception when trying to serialize tagged union type.
The exception is reproduced on custom client and PopSQL, both fetching data via [Presto HTTP Protocol](https://github.com/prestosql/presto/wiki/HTTP-Protocol). 
Querying via presto cli works fine.

Sample query:
`SELECT fields FROM events WHERE (id = '22b7efa1-0000-0000-0000-6069d59fca88')`

Error message:
```
io.prestosql.spi.PrestoException: Could not serialize column 'fields' of type 'map(varchar, row(tag varchar, tostring varchar, string varchar, bool boolean, int integer, long bigint, double double, timestamp timestamp(3), ip varchar, ipv4 varchar, ipv6 varchar, array_string array(varchar), array_bool array(boolean), array_int array(integer), array_long array(bigint), array_double array(double), array_timestamp array(timestamp(3)), array_ip array(varchar), array_ipv4 array(varchar), array_ipv6 array(varchar)))' at position 1:49
	at io.prestosql.server.protocol.QueryResultRows.lambda$propagateException$6(QueryResultRows.java:262)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.prestosql.server.protocol.QueryResultRows.propagateException(QueryResultRows.java:262)
	at io.prestosql.server.protocol.QueryResultRows.getRowValues(QueryResultRows.java:179)
	at io.prestosql.server.protocol.QueryResultRows.computeNext(QueryResultRows.java:150)
	at io.prestosql.server.protocol.QueryResultRows.computeNext(QueryResultRows.java:60)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at com.fasterxml.jackson.databind.ser.std.IterableSerializer.serializeContents(IterableSerializer.java:83)
	at com.fasterxml.jackson.databind.ser.std.IterableSerializer.serialize(IterableSerializer.java:74)
	at com.fasterxml.jackson.databind.ser.std.IterableSerializer.serialize(IterableSerializer.java:12)
	at com.fasterxml.jackson.databind.ser.std.StdDelegatingSerializer.serialize(StdDelegatingSerializer.java:168)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:166)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1433)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:921)
	at io.airlift.jaxrs.JsonMapper.writeTo(JsonMapper.java:233)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:266)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:251)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:109)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:85)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1135)
	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:662)
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:395)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:385)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$3.run(ServerRuntime.java:884)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:916)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:872)
	at io.airlift.jaxrs.AsyncResponseHandler$1.onSuccess(AsyncResponseHandler.java:102)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1089)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException: undefined
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:878)
	at com.google.common.collect.ImmutableList$Builder.add(ImmutableList.java:786)
	at io.prestosql.server.protocol.QueryResultRows.getLegacyValue(QueryResultRows.java:244)
	at io.prestosql.server.protocol.QueryResultRows.lambda$getLegacyValue$3(QueryResultRows.java:223)
	at com.google.common.collect.CollectCollectors.lambda$toImmutableMap$1(CollectCollectors.java:61)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.lambda$entryConsumer$0(Collections.java:1576)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1746)
	at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntrySetSpliterator.forEachRemaining(Collections.java:1601)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.prestosql.server.protocol.QueryResultRows.getLegacyValue(QueryResultRows.java:223)
	at io.prestosql.server.protocol.QueryResultRows.getRowValues(QueryResultRows.java:175)
	... 42 more
```

Sample record:
```
{
  product={
    tag=string,
    string=CatoNetworks,
    bool=NULL,
    int=NULL,
    long=NULL,
    double=NULL,
    timestamp=NULL,
    ipv4=NULL,
    ipv6=NULL,
    array_string=NULL,
    array_bool=NULL,
    array_int=NULL,
    array_long=NULL,
    array_double=NULL,
    array_timestamp=NULL,
    array_ip=NULL,
    array_ipv4=NULL,
    array_ipv6=NULL,
    tostring=CatoNetworks
  },
  os={
    tag=string,
    string=OS_MAC,
    bool=NULL,
    int=NULL,
    long=NULL,
    double=NULL,
    timestamp=NULL,
    ipv4=NULL,
    ipv6=NULL,
    array_string=NULL,
    array_bool=NULL,
    array_int=NULL,
    array_long=NULL,
    array_double=NULL,
    array_timestamp=NULL,
    array_ip=NULL,
    array_ipv4=NULL,
    array_ipv6=NULL,
    tostring=OS_MAC
  }
}
```

**Comment by losipiuk** [comment]
@wendigo can you take a look? It seems you played with that code most recently.

**Comment by yurii-talashko-exa** [comment]
Probably [here](https://github.com/prestosql/presto/commit/0e4e41939b0b000418cd38d06b8f9c58cfb9484a#diff-bfa38c1ce8a849b4d405c9882f627becR242) we want a structure that accepts `null` values, as tagged union contains most of them.

**Comment by wendigo** [comment]
@losipiuk sure. As @yurii-talashko-exa pointed out recent changes related to timestamp handling could introduce that regression. As it is a server-side bug it should affect both cli and JDBC clients.
