### ISSUE TITLE
[PrestoSQL 316] - Select cast query fails from presto cli with cannot cast error but works in spark-sql

### ISSUE THREAD

**Issue by chetandb** [prestosql/presto#4810]
Environment - PrestoSQL 316, Spark 2.4.5, Carbondata 2.0.1

Steps -
From Spark-SQL create carbondata table and load data to table.
create table all_datatypes_2048 (imei string,deviceInformationId int,MAC string,deviceColor string,device_backColor string,modelId string,marketName string,AMSize string,ROMSize string,CUPAudit string,CPIClocked string,series string,productionDate timestamp,bomCode string,internalModels string, deliveryTime string, channelsId string, channelsName string , deliveryAreaId string, deliveryCountry string, deliveryProvince string, deliveryCity string,deliveryDistrict string, deliveryStreet string, oxSingleNumber string, ActiveCheckTime string, ActiveAreaId string, ActiveCountry string, ActiveProvince string, Activecity string, ActiveDistrict string, ActiveStreet string, ActiveOperatorId string, Active_releaseId string, Active_EMUIVersion string, Active_operaSysVersion string, Active_BacVerNumber string, Active_BacFlashVer string, Active_webUIVersion string, Active_webUITypeCarrVer string,Active_webTypeDataVerNumber string, Active_operatorsVersion string, Active_phonePADPartitionedVersions string, Latest_YEAR int, Latest_MONTH int, Latest_DAY Decimal(30,10), Latest_HOUR string, Latest_areaId string, Latest_country string, Latest_province string, Latest_city string, Latest_district string, Latest_street string, Latest_releaseId string, Latest_EMUIVersion string, Latest_operaSysVersion string, Latest_BacVerNumber string, Latest_BacFlashVer string, Latest_webUIVersion string, Latest_webUITypeCarrVer string, Latest_webTypeDataVerNumber string, Latest_operatorsVersion string, Latest_phonePADPartitionedVersions string, Latest_operatorId string, gamePointDescription string,gamePointId double,contractNumber BigInt) stored as carbondata TBLPROPERTIES('table_blocksize'='2048','flat_folder'='true');
LOAD DATA INPATH 'hdfs://hacluster/chetan/100_olap_C20.csv' INTO table all_datatypes_2048 options ('DELIMITER'=',', 'QUOTECHAR'='\', 'BAD_RECORDS_ACTION'='FORCE','FILEHEADER'='imei,deviceInformationId,MAC,deviceColor,device_backColor,modelId,marketName,AMSize,ROMSize,CUPAudit,CPIClocked,series,productionDate,bomCode,internalModels,deliveryTime,channelsId,channelsName,deliveryAreaId,deliveryCountry,deliveryProvince,deliveryCity,deliveryDistrict,deliveryStreet,oxSingleNumber,contractNumber,ActiveCheckTime,ActiveAreaId,ActiveCountry,ActiveProvince,Activecity,ActiveDistrict,ActiveStreet,ActiveOperatorId,Active_releaseId,Active_EMUIVersion,Active_operaSysVersion,Active_BacVerNumber,Active_BacFlashVer,Active_webUIVersion,Active_webUITypeCarrVer,Active_webTypeDataVerNumber,Active_operatorsVersion,Active_phonePADPartitionedVersions,Latest_YEAR,Latest_MONTH,Latest_DAY,Latest_HOUR,Latest_areaId,Latest_country,Latest_province,Latest_city,Latest_district,Latest_street,Latest_releaseId,Latest_EMUIVersion,Latest_operaSysVersion,Latest_BacVerNumber,Latest_BacFlashVer,Latest_webUIVersion,Latest_webUITypeCarrVer,Latest_webTypeDataVerNumber,Latest_operatorsVersion,Latest_phonePADPartitionedVersions,Latest_operatorId,gamePointId,gamePointDescription');

From prestosql cli the select cast query is executed as shown below.
presto:chetan> select cast(gamepointid as int) as a from all_datatypes_2048 limit 10;
Query 20200803_121832_00309_etxj6, FAILED, 2 nodes
Splits: 34 total, 33 done (97.06%)
0:00 [99 rows, 516B] [469 rows/s, 2.39KB/s]

Query 20200803_121832_00309_etxj6 failed: Cannot cast '7Series' to INT

Log-
2020-08-06T19:59:21.831+0800 ERROR remote-task-callback-2041 io.prestosql.execution.StageStateMachine Stage 20200806_115921_00196_ed34h.0 failed
io.prestosql.spi.PrestoException: Cannot cast '7Series' to INT
 at io.prestosql.type.VarcharOperators.castToInteger(VarcharOperators.java:198)
 at io.prestosql.$gen.PageProjectionWork_20200804_091212_390.evaluate(Unknown Source)
 at io.prestosql.$gen.PageProjectionWork_20200804_091212_390.process(Unknown Source)
 at io.prestosql.operator.project.DictionaryAwarePageProjection$DictionaryAwarePageProjectionWork.process(DictionaryAwarePageProjection.java:175)
 at io.prestosql.operator.project.PageProcessor$ProjectSelectedPositions.processBatch(PageProcessor.java:295)
 at io.prestosql.operator.project.PageProcessor$ProjectSelectedPositions.process(PageProcessor.java:183)
 at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
 at io.prestosql.operator.WorkProcessorUtils$YieldingIterator.computeNext(WorkProcessorUtils.java:80)
 at io.prestosql.operator.WorkProcessorUtils$YieldingIterator.computeNext(WorkProcessorUtils.java:66)
 at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
 at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
 at io.prestosql.operator.project.MergingPageOutput.getOutput(MergingPageOutput.java:111)
 at io.prestosql.operator.FilterAndProjectOperator.getOutput(FilterAndProjectOperator.java:102)
 at io.prestosql.operator.Driver.processInternal(Driver.java:379)
 at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
 at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
 at io.prestosql.operator.Driver.processFor(Driver.java:276)
 at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
 at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
 at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
 at io.prestosql.$gen.Presto_316____20200804_042858_1.run(Unknown Source)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)

**Comment by dain** [comment]
The error is caused by invalid data in the table.  The error message is `Cannot cast '7Series' to INT`.  This means the column contains a value that is not a number.  The error is expected.  You can skip these invalid values by using `tryCast` https://prestosql.io/docs/current/functions/conversion.html#id1
