### ISSUE TITLE
PostgreSQL Connector: Connection failure

### ISSUE THREAD

**Issue by walter-weinmann** [prestosql/presto#4813]
The program should insert 2500 rows into a PostgreSQL database table. This can also be done with the original PostgreSQL JDBC driver. The Presto JDB driver loses the database connection when writing 50 to 100 rows.

The environment is Windows 10 2004 with a Docker container containing the Presto server and a second Docker container containing the PostgreSQL database.

The whole thing can be easily reproduced with the following repository: https://github.com/KonnexionsGmbH/db_seeder. In this repository there is a simple Java class for demonstration purposes for the Presto connectors MySQL, Oracle, PostgreSQL and SQL Server (please see here: https://github.com/KonnexionsGmbH/db_seeder/blob/master/Test_Presto.md). With these classes you can easily investigate the behaviour of the original JDBC driver and the Presto JDBC driver under identical conditions. In Windows, the mentioned two Docker Containers with the Presto Sever and the DBMS are used for this. In Linux the Presto server is installed locally and the DBMS container is used for the database. The DBMS containers are based on the original images of the DBMS manufacturers. 

### `run_db_seeder_presto_environment`

With this script you can create a Docker Container containing a Presto Server.

```
D:\SoftDevelopment\Projects\Konnexions\db_seeder>run_db_seeder_presto_environment
============================================================
complete           - All implemented Presto enabled DBMSs
sqlserver          - Microsoft SQL Server
mysql              - MySQL Database
oracle             - Oracle Database
postgresql         - PostgreSQL Database
-----------------------------------------------------------
Enter the desired database management system [default: complete]
Enter the local IP address [default: 192.168.1.109]
================================================================================
Start run_db_seeder_presto_environment
--------------------------------------------------------------------------------
DB Seeder - Creating a Presto environment.
--------------------------------------------------------------------------------
DBMS_DEFAULT                  : complete

....


D:\SoftDevelopment\Projects\Konnexions\db_seeder>docker ps
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS                    NAMES
340cc851271e        konnexionsgmbh/db_seeder_presto   "presto-server/bin/l…"   36 seconds ago      Up 35 seconds       0.0.0.0:8080->8080/tcp   db_seeder_presto
```

### `scripts\run_db_seeder_setup_postgresql`

With this script you can create a docker container that contains a PostgreSQL DBMS.

```
D:\SoftDevelopment\Projects\Konnexions\db_seeder>scripts\run_test_presto_postgresql
================================================================================
Start scripts\run_test_presto_postgresql
--------------------------------------------------------------------------------
DB Seeder - Demonstration Issues PostgreSQL Connector.
--------------------------------------------------------------------------------
The current time is: 17:07:54.15
Enter the new time:
--------------------------------------------------------------------------------
[main] Start TestPrestoPostgresql
[main]
[main] ----------------------------------------------
[main] 1 - Setup the database (includes reset)
[main] 2 - Run the demo with the original JDBC driver
[main] 3 - Run the demo with the Presto JDBC driver
[main] 4 - Reset the database
[main] 9 - Terminate the processing
[main] ----------------------------------------------
[main]
[main] Please make a choice:
1
[main] Reset the database
[main]
[main] driver  ='org.postgresql.Driver'
[main] url     ='jdbc:postgresql://localhost:5432/kxn_db_sys?user=kxn_user_sys&password=postgresql'
[main] sqlStmnt='DROP DATABASE IF EXISTS kxn_db'
[main] sqlStmnt='DROP USER IF EXISTS kxn_user'
[main]
[main] Setup the database
[main]
[main] driver  ='org.postgresql.Driver'
[main] url     ='jdbc:postgresql://localhost:5432/kxn_db_sys?user=kxn_user_sys&password=postgresql'
[main] sqlStmnt='CREATE DATABASE kxn_db'
[main] sqlStmnt='CREATE USER kxn_user WITH ENCRYPTED PASSWORD 'postgresql''
[main] sqlStmnt='GRANT ALL PRIVILEGES ON DATABASE kxn_db TO kxn_user'
[main] driver  ='org.postgresql.Driver'
[main] url     ='jdbc:postgresql://localhost:5432/kxn_db?user=kxn_user&password=postgresql'
[main] sqlStmnt='CREATE TABLE issue_table (
    column_pk        BIGINT         NOT NULL
                                    PRIMARY KEY,
    column_blob      BYTEA,
    column_clob      TEXT,
    column_timestamp TIMESTAMP      NOT NULL,
    column_varchar   VARCHAR(100)   NOT NULL
                                    UNIQUE
)
'
[main]
[main] ----------------------------------------------
[main] 1 - Setup the database (includes reset)
[main] 2 - Run the demo with the original JDBC driver
[main] 3 - Run the demo with the Presto JDBC driver
[main] 4 - Reset the database
[main] 9 - Terminate the processing
[main] ----------------------------------------------
[main]
[main] Please make a choice:
2
[main] Run the demo with the original JDBC driver
[main]
[main] driver  ='org.postgresql.Driver'
[main] url     ='jdbc:postgresql://localhost:5432/kxn_db?user=kxn_user&password=postgresql'
[main]
[main]     50 rows inserted so far
[main]    100 rows inserted so far
[main]    150 rows inserted so far
[main]    200 rows inserted so far
[main]    250 rows inserted so far
[main]    300 rows inserted so far
[main]    350 rows inserted so far
[main]    400 rows inserted so far
[main]    450 rows inserted so far
[main]    500 rows inserted so far
[main]    550 rows inserted so far
[main]    600 rows inserted so far
[main]    650 rows inserted so far
[main]    700 rows inserted so far
[main]    750 rows inserted so far
[main]    800 rows inserted so far
[main]    850 rows inserted so far
[main]    900 rows inserted so far
[main]    950 rows inserted so far
[main]   1000 rows inserted so far
[main]   1050 rows inserted so far
[main]   1100 rows inserted so far
[main]   1150 rows inserted so far
[main]   1200 rows inserted so far
[main]   1250 rows inserted so far
[main]   1300 rows inserted so far
[main]   1350 rows inserted so far
[main]   1400 rows inserted so far
[main]   1450 rows inserted so far
[main]   1500 rows inserted so far
[main]   1550 rows inserted so far
[main]   1600 rows inserted so far
[main]   1650 rows inserted so far
[main]   1700 rows inserted so far
[main]   1750 rows inserted so far
[main]   1800 rows inserted so far
[main]   1850 rows inserted so far
[main]   1900 rows inserted so far
[main]   1950 rows inserted so far
[main]   2000 rows inserted so far
[main]   2050 rows inserted so far
[main]   2100 rows inserted so far
[main]   2150 rows inserted so far
[main]   2200 rows inserted so far
[main]   2250 rows inserted so far
[main]   2300 rows inserted so far
[main]   2350 rows inserted so far
[main]   2400 rows inserted so far
[main]   2450 rows inserted so far
[main]   2500 rows inserted so far
[main]
[main]   2500 rows inserted totally - duration in seconds:         13
[main]
[main] ----------------------------------------------
[main] 1 - Setup the database (includes reset)
[main] 2 - Run the demo with the original JDBC driver
[main] 3 - Run the demo with the Presto JDBC driver
[main] 4 - Reset the database
[main] 9 - Terminate the processing
[main] ----------------------------------------------
[main]
[main] Please make a choice:
1
[main] Reset the database
[main]
[main] driver  ='org.postgresql.Driver'
[main] url     ='jdbc:postgresql://localhost:5432/kxn_db_sys?user=kxn_user_sys&password=postgresql'
[main] sqlStmnt='DROP DATABASE IF EXISTS kxn_db'
[main] sqlStmnt='DROP USER IF EXISTS kxn_user'
[main]
[main] Setup the database
[main]
[main] driver  ='org.postgresql.Driver'
[main] url     ='jdbc:postgresql://localhost:5432/kxn_db_sys?user=kxn_user_sys&password=postgresql'
[main] sqlStmnt='CREATE DATABASE kxn_db'
[main] sqlStmnt='CREATE USER kxn_user WITH ENCRYPTED PASSWORD 'postgresql''
[main] sqlStmnt='GRANT ALL PRIVILEGES ON DATABASE kxn_db TO kxn_user'
[main] driver  ='org.postgresql.Driver'
[main] url     ='jdbc:postgresql://localhost:5432/kxn_db?user=kxn_user&password=postgresql'
[main] sqlStmnt='CREATE TABLE issue_table (
    column_pk        BIGINT         NOT NULL
                                    PRIMARY KEY,
    column_blob      BYTEA,
    column_clob      TEXT,
    column_timestamp TIMESTAMP      NOT NULL,
    column_varchar   VARCHAR(100)   NOT NULL
                                    UNIQUE
)
'
[main]
[main] ----------------------------------------------
[main] 1 - Setup the database (includes reset)
[main] 2 - Run the demo with the original JDBC driver
[main] 3 - Run the demo with the Presto JDBC driver
[main] 4 - Reset the database
[main] 9 - Terminate the processing
[main] ----------------------------------------------
[main]
[main] Please make a choice:
3
[main] Run the demo with the Presto JDBC driver
[main]
[main] driver  ='io.prestosql.jdbc.PrestoDriver'
[main] url     ='jdbc:presto://localhost:8080/db_seeder_postgresql/public?user=presto'
[main]
[main]     50 rows inserted so far
java.sql.SQLException: Query failed (#20200813_150843_00077_nqfn5): Connection to 192.168.1.109:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/I
        at io.prestosql.jdbc.AbstractPrestoResultSet.resultsException(AbstractPrestoResultSet.java:1754)
        at io.prestosql.jdbc.PrestoResultSet.getColumns(PrestoResultSet.java:249)
        at io.prestosql.jdbc.PrestoResultSet.create(PrestoResultSet.java:52)
        at io.prestosql.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:249)
        at io.prestosql.jdbc.PrestoStatement.execute(PrestoStatement.java:227)
        at io.prestosql.jdbc.PrestoPreparedStatement.executeLargeUpdate(PrestoPreparedStatement.java:129)
        at io.prestosql.jdbc.PrestoPreparedStatement.executeUpdate(PrestoPreparedStatement.java:122)
        at ch.konnexions.db_seeder.test.TestPrestoPostgresql.insertData(TestPrestoPostgresql.java:252)
        at ch.konnexions.db_seeder.test.TestPrestoPostgresql.demonstratePresto(TestPrestoPostgresql.java:199)
        at ch.konnexions.db_seeder.test.TestPrestoPostgresql.main(TestPrestoPostgresql.java:315)
Caused by: io.prestosql.spi.PrestoException: Connection to 192.168.1.109:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
        at io.prestosql.plugin.jdbc.BaseJdbcClient.beginInsertTable(BaseJdbcClient.java:524)
        at io.prestosql.plugin.jdbc.ForwardingJdbcClient.beginInsertTable(ForwardingJdbcClient.java:153)
        at io.prestosql.plugin.jdbc.jmx.StatisticsAwareJdbcClient.lambda$beginInsertTable$19(StatisticsAwareJdbcClient.java:199)
        at io.prestosql.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
        at io.prestosql.plugin.jdbc.jmx.StatisticsAwareJdbcClient.beginInsertTable(StatisticsAwareJdbcClient.java:199)
        at io.prestosql.plugin.jdbc.CachingJdbcClient.beginInsertTable(CachingJdbcClient.java:208)
        at io.prestosql.plugin.jdbc.CachingJdbcClient.beginInsertTable(CachingJdbcClient.java:208)
        at io.prestosql.plugin.jdbc.JdbcMetadata.beginInsert(JdbcMetadata.java:405)
        at io.prestosql.metadata.MetadataManager.beginInsert(MetadataManager.java:815)
        at io.prestosql.sql.planner.optimizations.BeginTableWrite$Rewriter.createWriterTarget(BeginTableWrite.java:184)
        at io.prestosql.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:143)
        at io.prestosql.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:76)
        at io.prestosql.sql.planner.plan.TableFinishNode.accept(TableFinishNode.java:106)
        at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
        at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Collections$2.tryAdvance(Collections.java:4820)
        at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4828)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
        at io.prestosql.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:38)
        at io.prestosql.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:22)
        at io.prestosql.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
        at io.prestosql.sql.planner.plan.OutputNode.accept(OutputNode.java:83)
        at io.prestosql.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:32)
        at io.prestosql.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:73)
        at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:200)
        at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:189)
        at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:184)
        at io.prestosql.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:425)
        at io.prestosql.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:413)
        at io.prestosql.execution.SqlQueryExecution.start(SqlQueryExecution.java:365)
        at io.prestosql.execution.SqlQueryManager.createQuery(SqlQueryManager.java:245)
        at io.prestosql.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:132)
        at io.prestosql.$gen.Presto_339____20200813_135712_2.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: org.postgresql.util.PSQLException: Connection to 192.168.1.109:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:280)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
        at org.postgresql.Driver.makeConnection(Driver.java:454)
        at org.postgresql.Driver.connect(Driver.java:256)
        at io.prestosql.plugin.jdbc.DriverConnectionFactory.openConnection(DriverConnectionFactory.java:73)
        at io.prestosql.plugin.jdbc.jmx.StatisticsAwareConnectionFactory.lambda$openConnection$0(StatisticsAwareConnectionFactory.java:42)
        at io.prestosql.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
        at io.prestosql.plugin.jdbc.jmx.StatisticsAwareConnectionFactory.openConnection(StatisticsAwareConnectionFactory.java:42)
        at io.prestosql.plugin.jdbc.BaseJdbcClient.beginInsertTable(BaseJdbcClient.java:493)
        ... 41 more
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:589)
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
        at java.base/java.net.Socket.connect(Socket.java:648)
        at org.postgresql.core.PGStream.<init>(PGStream.java:70)
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:91)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
        ... 50 more
Processing of the script was aborted, error code=1
PS D:\SoftDevelopment\Projects\Konnexions\db_seeder>
```

**Comment by electrum** [comment]
Similar to my comment on the MySQL issue, the `Connection refused` indicates that the Presto container cannot connect to the PostgreSQL container on port 5432.

**Comment by walter-weinmann** [comment]
Same solution as in issue #4812 applies.
