### ISSUE TITLE
[PrestoSQL 316] Select filter query failed with bigint and integer addition overflow error from presto cli

### ISSUE THREAD

**Issue by chetandb** [prestosql/presto#4815]
Environment - PrestoSQL 316, Spark -2.4.5, Carbondata 2.0.1

Steps -
From Spark-SQL create carbondata table and load data.
create table Test_Boundary (c1_int int,c2_Bigint Bigint,c3_Decimal Decimal(38,38),c4_double double,c5_string string,c6_Timestamp Timestamp,c7_Datatype_Desc string) stored as carbondata;
LOAD DATA INPATH 'hdfs://hacluster/chetan/Test_Data1.csv' INTO table Test_Boundary OPTIONS('DELIMITER'=',','QUOTECHAR'='','BAD_RECORDS_ACTION'='FORCE','FILEHEADER'='');

Issue- Select filter query failed with bigint and integer addition overflow error from presto cli
presto:chetan> select min(c2_Bigint),max(c2_Bigint),sum(c2_Bigint),avg(c2_Bigint) , count(c2_Bigint), variance(c2_Bigint) from test_boundary where exp(c1_int)=0.0 or exp(c1_int)=1.0;

Query 20200804_142308_00524_ed34h, FAILED, 1 node
Splits: 18 total, 0 done (0.00%)
0:00 [16 rows, 0B] [66 rows/s, 0B/s]

Query 20200804_142308_00524_ed34h failed: bigint addition overflow: -9223372036854775808 + -9223372036854775807

Log-
2020-08-04T22:23:08.870+0800 ERROR SplitRunner-4-3650 io.prestosql.execution.executor.TaskExecutor Error processing Split 20200804_142308_00524_ed34h.1.0-0 {path=hdfs://hacluster/user/sparkhive/warehouse/chetan.db/test_boundary, start=0, length=0, fileSize=0, hosts=[vm1, vm3, vm2], database=chetan, table=test_boundary, forceLocalScheduling=false, partitionName=test_boundary, s3SelectPushdownEnabled=false} (start = 8.15894005351617E9, wall = 36 ms, cpu = 0 ms, wait = 1 ms, calls = 1): NUMERIC_VALUE_OUT_OF_RANGE: bigint addition overflow: -9223372036854775808 + -9223372036854775807
2020-08-04T22:23:08.875+0800 ERROR remote-task-callback-625 io.prestosql.execution.StageStateMachine Stage 20200804_142308_00524_ed34h.1 failed
io.prestosql.spi.PrestoException: bigint addition overflow: -9223372036854775808 + -9223372036854775807
 at io.prestosql.type.BigintOperators.add(BigintOperators.java:74)
 at io.prestosql.operator.aggregation.LongSumAggregation.sum(LongSumAggregation.java:37)
 at io.prestosql.$gen.BigintBigintSumAccumulator_20200804_140200_848.addInput(Unknown Source)
 at io.prestosql.operator.Aggregator.processPage(Aggregator.java:58)
 at io.prestosql.operator.AggregationOperator.addInput(AggregationOperator.java:152)
 at io.prestosql.operator.Driver.processInternal(Driver.java:384)
 at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
 at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
 at io.prestosql.operator.Driver.processFor(Driver.java:276)
 at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
 at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
 at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
 at io.prestosql.$gen.Presto_316____20200804_042858_1.run(Unknown Source)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArithmeticException: long overflow
 at java.lang.Math.addExact(Math.java:809)
 at io.prestosql.type.BigintOperators.add(BigintOperators.java:71)
 ... 15 more

**Comment by dain** [comment]
I believe this is the same issue as #4816
