### ISSUE TITLE
[PrestoSQL 316] select query on binary type table data from prestocli fails with error

### ISSUE THREAD

**Issue by chetandb** [prestosql/presto#4817]
Environment - PrestoSQL 316, Spark 2.4.5, Carbondata 2.0.1

Steps -
From Spark SQL create carbondata table and load data to table.
CREATE TABLE IF NOT EXISTS binaryTable (id int,label boolean,name string,image binary,autoLabel boolean)stored as carbondata;
LOAD DATA INPATH 'hdfs://hacluster/chetan/binarydata.csv' INTO TABLE binaryTable OPTIONS('header'='false');

Issue -
select query on binary type table data from prestocli fails with error

presto:chetan> SELECT * FROM binaryTable limit 10;
Query is gone (server restarted?)

Log-
2020-08-05T14:08:40.990+0800 WARN statement-response-224 io.prestosql.server.ThrowableMapper Request failed for /v1/statement/executing/20200805_060840_00041_ed34h/xf528f461e490425eb8d02b3b46309709/0
com.fasterxml.jackson.databind.JsonMappingException: position is not valid (through reference chain: io.prestosql.client.QueryResults["data"])
 at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
 at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:353)
 at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
 at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:727)
 at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
 at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
 at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
 at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1396)
 at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:913)
 at io.airlift.jaxrs.JsonMapper.writeTo(JsonMapper.java:233)
 at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:266)
 at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:251)
 at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
 at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:109)
 at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
 at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:85)
 at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
 at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1135)
 at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:662)
 at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:395)
 at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:385)
 at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$3.run(ServerRuntime.java:884)
 at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
 at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
 at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
 at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
 at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
 at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
 at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:916)
 at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:872)
 at io.airlift.http.server.AsyncResponseHandler$1.onSuccess(AsyncResponseHandler.java:102)
 at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1058)
 at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: position is not valid
 at io.prestosql.spi.block.RunLengthEncodedBlock.checkReadablePosition(RunLengthEncodedBlock.java:297)
 at io.prestosql.spi.block.RunLengthEncodedBlock.isNull(RunLengthEncodedBlock.java:269)
 at io.prestosql.spi.type.VarbinaryType.getObjectValue(VarbinaryType.java:53)
 at io.prestosql.server.protocol.RowIterable$RowIterator.computeNext(RowIterable.java:77)
 at io.prestosql.server.protocol.RowIterable$RowIterator.computeNext(RowIterable.java:50)
 at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
 at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
 at com.google.common.collect.Iterators$ConcatenatedIterator.hasNext(Iterators.java:1323)
 at com.google.common.collect.Iterators$1.hasNext(Iterators.java:136)
 at com.fasterxml.jackson.databind.ser.std.IterableSerializer.serializeContents(IterableSerializer.java:83)
 at com.fasterxml.jackson.databind.ser.std.IterableSerializer.serialize(IterableSerializer.java:74)
 at com.fasterxml.jackson.databind.ser.std.IterableSerializer.serialize(IterableSerializer.java:12)
 at com.fasterxml.jackson.databind.ser.std.StdDelegatingSerializer.serialize(StdDelegatingSerializer.java:168)
 at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
 at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
 ... 32 more

**Comment by dain** [comment]
How are you integrating with carbon data? I don't believe that Presto supports this natively. I ask because it looks like there are bugs in that code.

**Comment by dain** [comment]
Let's consolidate the discussion in  #4820.  We can reopen this issue it it turns out to be a different problem.
