### ISSUE TITLE
[PrestoSQL 316] select query with regexp_extract function throws error in prestocli

### ISSUE THREAD

**Issue by chetandb** [prestosql/presto#4819]
Environment - PrestoSQL 316, Spark 2.4.5, Carbondata 2.0.1

Steps -
From Spark SQL create carbondata table and load data to table.
CREATE TABLE uniqdata (CUST_ID int,CUST_NAME String,ACTIVE_EMUI_VERSION string, DOB timestamp, DOJ timestamp, BIGINT_COLUMN1 bigint,BIGINT_COLUMN2 bigint,DECIMAL_COLUMN1 decimal(30,10), DECIMAL_COLUMN2 decimal(36,36),Double_COLUMN1 double, Double_COLUMN2 double,INTEGER_COLUMN1 int) stored as carbondata;
LOAD DATA INPATH 'hdfs://hacluster/chetan/2000_UniqData.csv' into table uniqdata OPTIONS('DELIMITER'=',' , 'QUOTECHAR'='"','BAD_RECORDS_ACTION'='FORCE','FILEHEADER'='CUST_ID,CUST_NAME,ACTIVE_EMUI_VERSION,DOB,DOJ,BIGINT_COLUMN1,BIGINT_COLUMN2,DECIMAL_COLUMN1,DECIMAL_COLUMN2,Double_COLUMN1,Double_COLUMN2,INTEGER_COLUMN1');

Issue : select query with regexp_extract function throws error in prestocli
presto:priyesh> select regexp_extract(CUST_NAME,'a',1)from uniqdata where regexp_extract(CUST_NAME,'a',1) IS NULL;
Query 20200805_065236_00068_ed34h, FAILED, 1 node
Splits: 17 total, 0 done (0.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]
Query 20200805_065236_00068_ed34h failed: Pattern has 0 groups. Cannot access group 1

logs-
2020-08-05T14:52:36.389+0800    ERROR   SplitRunner-8-107       io.prestosql.execution.executor.TaskExecutor    Eser/sparkhive/warehouse/priyesh.db/uniqdata, start=0, length=0, fileSize=0, hosts=[vm1, vm3, vm2], database=priyePushdownEnabled=false} (start = 8.218307578675225E9, wall = 29 ms, cpu = 0 ms, wait = 0 ms, calls = 1): INVALID_F
2020-08-05T14:52:36.391+0800    INFO    SplitRunner-8-107       stdout  2020-08-05 14:52:36 INFO  UnsafeMemoryMan-ab9350947b52 is 0. Current running tasks are 6ae2bcdd-0f84-4191-bbd8-4ed16d6fd0cb, 00f45ada-ffe7-4c48-b04b-940a0

2020-08-05T14:52:36.393+0800    ERROR   remote-task-callback-1004       io.prestosql.execution.StageStateMachine
io.prestosql.spi.PrestoException: Pattern has 0 groups. Cannot access group 1
        at io.prestosql.operator.scalar.JoniRegexpFunctions.validateGroup(JoniRegexpFunctions.java:308)
        at io.prestosql.operator.scalar.JoniRegexpFunctions.regexpExtract(JoniRegexpFunctions.java:252)
        at io.prestosql.$gen.PageFilter_20200805_065236_1728.filter(Unknown Source)
        at io.prestosql.$gen.PageFilter_20200805_065236_1728.filter(Unknown Source)
        at io.prestosql.operator.project.DictionaryAwarePageFilter.filter(DictionaryAwarePageFilter.java:83)
        at io.prestosql.operator.project.PageProcessor.createWorkProcessor(PageProcessor.java:115)
        at io.prestosql.operator.ScanFilterAndProjectOperator$SplitToPages.lambda$processPageSource$1(ScanFilterA
        at io.prestosql.operator.WorkProcessorUtils.lambda$flatMap$4(WorkProcessorUtils.java:246)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:320)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:307)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:307)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
        at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
        at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
        at io.prestosql.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:278)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:320)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:307)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
        at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
        at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
        at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
        at io.prestosql.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
        at io.prestosql.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.
        at io.prestosql.operator.Driver.processInternal(Driver.java:379)
        at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
        at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
        at io.prestosql.operator.Driver.processFor(Driver.java:276)
        at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
        at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
        at io.prestosql.$gen.Presto_316____20200804_042858_1.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

2020-08-05T14:52:36.403+0800    INFO    dispatcher-query-787    io.prestosql.event.QueryMonitor TIMELINE: Query 2 :: elapsed 162ms :: planning 77ms :: waiting 25ms :: scheduling 54ms :: running 27ms :: finishing 4ms :: begin 2

**Comment by martint** [comment]
> `select regexp_extract(CUST_NAME,'a',1)from uniqdata where regexp_extract(CUST_NAME,'a',1) IS NULL;`

Your pattern doesn't have any capturing groups, hence the `Pattern has 0 groups. Cannot access group 1` error. Capturing groups are specified by surrounding the parts of the pattern you're interested in capturing with parentheses. Please, see the documentation for regexp_extract at https://prestosql.io/docs/current/functions/regexp.html#regexp_extract
