### ISSUE TITLE
[PrestoSQL 316] Select with floor function on decimal value and int type columns failed. Log shows ArrayIndexOutOfBoundsException(decimal) and decimaloverflow(Int)

### ISSUE THREAD

**Issue by chetandb** [prestosql/presto#4820]
Environment - PrestoSQL 316, Spark 2.4.5, Carbonata 2.0.1

Steps -
From Spark-SQL create  carbondata table and load data to table.
create table Test_Boundary (c1_int int,c2_Bigint Bigint,c3_Decimal Decimal(38,38),c4_double double,c5_string string,c6_Timestamp Timestamp,c7_Datatype_Desc string) stored as carbondata;
LOAD DATA INPATH 'hdfs://hacluster/chetan/Test_Data1.csv' INTO table Test_Boundary OPTIONS('DELIMITER'=',','QUOTECHAR'='','BAD_RECORDS_ACTION'='FORCE','FILEHEADER'='');

Issue - Select with floor function on decimal value and int type columns failed. Log shows ArrayIndexOutOfBoundsException(decimal) and decimaloverflow(Int) errors.

presto:priyesh> select c3_Decimal from test_boundary where floor(c3_Decimal)=0.0 or floor(c3_Decimal) IS NULL;

Query 20200805_071704_00108_ed34h, FAILED, 2 nodes
Splits: 17 total, 0 done (0.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20200805_071704_00108_ed34h failed: 38

log-

2020-08-05T15:17:04.450+0800    ERROR   remote-task-callback-1022       io.prestosql.execution.StageStateMachine        Stage 20200805_071704_00108_ed34h.1 failed
java.lang.ArrayIndexOutOfBoundsException: 38
        at io.prestosql.operator.scalar.MathFunctions$Floor.floorLong(MathFunctions.java:426)
        at io.prestosql.operator.scalar.MathFunctions$Floor.floorLongShort(MathFunctions.java:436)
        at io.prestosql.$gen.PageFilter_20200804_141446_933.filter(Unknown Source)
        at io.prestosql.$gen.PageFilter_20200804_141446_933.filter(Unknown Source)
        at io.prestosql.operator.project.DictionaryAwarePageFilter.filter(DictionaryAwarePageFilter.java:83)
        at io.prestosql.operator.project.PageProcessor.createWorkProcessor(PageProcessor.java:115)
        at io.prestosql.operator.ScanFilterAndProjectOperator$SplitToPages.lambda$processPageSource$1(ScanFilterAndProjectOperator.java:254)
        at io.prestosql.operator.WorkProcessorUtils.lambda$flatMap$4(WorkProcessorUtils.java:246)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:320)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:307)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:307)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
        at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
        at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
        at io.prestosql.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:278)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:320)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:307)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
        at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
        at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
        at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
        at io.prestosql.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
        at io.prestosql.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:133)
        at io.prestosql.operator.Driver.processInternal(Driver.java:379)
        at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
        at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
        at io.prestosql.operator.Driver.processFor(Driver.java:276)
        at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
        at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
        at io.prestosql.$gen.Presto_316____20200804_042858_1.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by dain** [comment]
How are you integrating with carbon data?  I don't believe that Presto supports this natively.  I ask because it looks like there are bugs in that code.

**Comment by chetandb** [comment]
We installed multinode presto-sql carbondata cluster by following the steps mentioned in link - https://github.com/apache/carbondata/blob/master/docs/prestosql-guide.md#presto-multinode-cluster-setup-for-carbondata

**Comment by dain** [comment]
Ah, so that is an external project.  I expect that this is an issue with the code in that project.  Can you file an issue with that project?  I believe their issue tracker is https://issues.apache.org/jira/projects/CARBONDATA/

**Comment by dain** [comment]
BTW in the future, for issues like this, I suggest you ask on slack (https://prestosql.io/slack.html).  There are folks from the carbondata project on there that can help.

**Comment by chetandb** [comment]
Which among the issues that i have reported do you think is of Carbondata ?

**Comment by ajantha-bhat** [comment]
@chetandb : you need to run with open source presto, without carbon. If you find issue in just that you can report here. Else if you don't find issue with just presto and only find in carbondata. You need to report in carbondata community.

So please close all issues and verify and rise applicable issues properly. 

@dain @martint : sorry for the trouble!

**Comment by chetandb** [comment]
Issues to be discussed and tracked in relevant community.
