### ISSUE TITLE
TestHiveTransactionalTable.testReadFullAcidBucketedV1 is flaky

### ISSUE THREAD

**Issue by kokosing** [prestosql/presto#4857]
```
2020-08-14T21:33:30.9912976Z tests               | 2020-08-15 03:18:30 INFO: FAILURE     /    io.prestosql.tests.hive.TestHiveTransactionalTable.testReadFullAcidBucketedV1 (Groups: hive_transactional) took 1 minutes and 25 seconds
2020-08-14T21:33:30.9923757Z tests               | 2020-08-15 03:18:30 SEVERE: Failure cause:
2020-08-14T21:33:30.9929151Z tests               | io.prestosql.tempto.query.QueryExecutionException: java.sql.SQLException: Query failed (#20200814_213330_00043_ie3bx): Hive table 'default.test_read_full_acid_false_bucketed_v1_18qrheidvg1r' is corrupt. Found sub-directory in bucket directory for partition: <UNPARTITIONED>
2020-08-14T21:33:30.9929806Z tests               | 	at io.prestosql.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:114)
2020-08-14T21:33:30.9930265Z tests               | 	at io.prestosql.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:82)
2020-08-14T21:33:30.9930691Z tests               | 	at io.prestosql.tempto.query.QueryExecutor.query(QueryExecutor.java:57)
2020-08-14T21:33:30.9931156Z tests               | 	at io.prestosql.tests.hive.TestHiveTransactionalTable.doTestReadFullAcid(TestHiveTransactionalTable.java:129)
2020-08-14T21:33:30.9931625Z tests               | 	at io.prestosql.tests.hive.TestHiveTransactionalTable.testReadFullAcidBucketedV1(TestHiveTransactionalTable.java:91)
2020-08-14T21:33:30.9932103Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-08-14T21:33:30.9932573Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-08-14T21:33:30.9933244Z tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-08-14T21:33:30.9933690Z tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-08-14T21:33:30.9934101Z tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-08-14T21:33:30.9934583Z tests               | 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
2020-08-14T21:33:30.9935054Z tests               | 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
2020-08-14T21:33:30.9935498Z tests               | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2020-08-14T21:33:30.9935964Z tests               | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2020-08-14T21:33:30.9936451Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-08-14T21:33:30.9936951Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-08-14T21:33:30.9937382Z tests               | 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-08-14T21:33:30.9938662Z tests               | Caused by: java.sql.SQLException: Query failed (#20200814_213330_00043_ie3bx): Hive table 'default.test_read_full_acid_false_bucketed_v1_18qrheidvg1r' is corrupt. Found sub-directory in bucket directory for partition: <UNPARTITIONED>
2020-08-14T21:33:30.9939218Z tests               | 	at io.prestosql.jdbc.AbstractPrestoResultSet.resultsException(AbstractPrestoResultSet.java:1754)
2020-08-14T21:33:30.9939698Z tests               | 	at io.prestosql.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:225)
2020-08-14T21:33:30.9940422Z tests               | 	at io.prestosql.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:185)
2020-08-14T21:33:30.9941208Z tests               | 	at io.prestosql.jdbc.$internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
2020-08-14T21:33:30.9941704Z tests               | 	at io.prestosql.jdbc.$internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
2020-08-14T21:33:30.9942194Z tests               | 	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
2020-08-14T21:33:30.9942703Z tests               | 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
2020-08-14T21:33:30.9943194Z tests               | 	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
2020-08-14T21:33:30.9943616Z tests               | 	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
2020-08-14T21:33:30.9944126Z tests               | 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
2020-08-14T21:33:30.9944614Z tests               | 	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
2020-08-14T21:33:30.9945093Z tests               | 	at io.prestosql.jdbc.PrestoResultSet$AsyncIterator.lambda$new$0(PrestoResultSet.java:131)
2020-08-14T21:33:30.9945578Z tests               | 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
2020-08-14T21:33:30.9945971Z tests               | 	... 3 more
2020-08-14T21:33:30.9947047Z tests               | Caused by: io.prestosql.spi.PrestoException: Hive table 'default.test_read_full_acid_false_bucketed_v1_18qrheidvg1r' is corrupt. Found sub-directory in bucket directory for partition: <UNPARTITIONED>
2020-08-14T21:33:30.9947620Z tests               | 	at io.prestosql.plugin.hive.BackgroundHiveSplitLoader.loadPartition(BackgroundHiveSplitLoader.java:519)
2020-08-14T21:33:30.9948140Z tests               | 	at io.prestosql.plugin.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:303)
2020-08-14T21:33:30.9948647Z tests               | 	at io.prestosql.plugin.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:232)
2020-08-14T21:33:30.9949116Z tests               | 	at io.prestosql.plugin.hive.util.ResumableTasks$1.run(ResumableTasks.java:38)
2020-08-14T21:33:30.9949558Z tests               | 	at io.prestosql.$gen.Presto_4151e70____20200814_212633_2.run(Unknown Source)
2020-08-14T21:33:30.9950011Z tests               | 	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
2020-08-14T21:33:30.9950499Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-08-14T21:33:30.9951020Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-08-14T21:33:30.9951392Z tests               | 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-08-14T21:33:30.9951771Z tests             
```

**Comment by kokosing** [comment]
This test was executed with `config-empty`

**Comment by findepi** [comment]
Superseded by #4927
