### ISSUE TITLE
Flaky TestPostgreSqlTypeMapping # testDecimalExceedingPrecisionMaxWithNonExceedingIntegerValues, testDecimalExceedingPrecisionMaxWithExceedingIntegerValues

### ISSUE THREAD

**Issue by sopel39** [prestosql/presto#4885]
```
2020-08-19T03:15:30.9378194Z 2020-08-18T22:15:30.937-0500 INFO Life cycle stopped
2020-08-19T03:15:31.2133659Z [ERROR] Tests run: 267, Failures: 1, Errors: 0, Skipped: 11, Time elapsed: 330.303 s <<< FAILURE! - in TestSuite
2020-08-19T03:15:31.2134416Z [ERROR] testDecimalExceedingPrecisionMaxWithNonExceedingIntegerValues(io.prestosql.plugin.postgresql.TestPostgreSqlTypeMapping)  Time elapsed: 0.375 s  <<< FAILURE!
2020-08-19T03:15:31.2139352Z java.lang.AssertionError: Execution of 'actual' query failed: SELECT column_name, data_type FROM information_schema.columns WHERE table_schema = 'tpch' AND table_schema||'.'||table_name = 'tpch.test_exceeding_max_decimal_lc6dm'
2020-08-19T03:15:31.2139946Z 	at org.testng.Assert.fail(Assert.java:83)
2020-08-19T03:15:31.2140254Z 	at io.prestosql.testing.QueryAssertions.assertQuery(QueryAssertions.java:150)
2020-08-19T03:15:31.2141881Z 	at io.prestosql.testing.QueryAssertions.assertQuery(QueryAssertions.java:106)
2020-08-19T03:15:31.2143742Z 	at io.prestosql.testing.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:152)
2020-08-19T03:15:31.2146606Z 	at io.prestosql.plugin.postgresql.TestPostgreSqlTypeMapping.testDecimalExceedingPrecisionMaxWithNonExceedingIntegerValues(TestPostgreSqlTypeMapping.java:447)
2020-08-19T03:15:31.2147890Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-08-19T03:15:31.2149634Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-08-19T03:15:31.2151708Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-08-19T03:15:31.2152600Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-08-19T03:15:31.2154151Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-08-19T03:15:31.2155066Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-08-19T03:15:31.2156103Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-08-19T03:15:31.2157143Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-08-19T03:15:31.2158536Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-08-19T03:15:31.2159525Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-08-19T03:15:31.2160885Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-08-19T03:15:31.2162266Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-08-19T03:15:31.2163148Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-08-19T03:15:31.2165496Z Caused by: java.lang.RuntimeException: Unsupported type handling is set to CONVERT_TO_VARCHAR, but toPrestoType() returned empty
2020-08-19T03:15:31.2167360Z 	at io.prestosql.testing.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:114)
2020-08-19T03:15:31.2168978Z 	at io.prestosql.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:442)
2020-08-19T03:15:31.2170408Z 	at io.prestosql.testing.QueryAssertions.assertQuery(QueryAssertions.java:147)
2020-08-19T03:15:31.2170722Z 	... 16 more
2020-08-19T03:15:31.2173240Z Caused by: com.google.common.base.VerifyException: Unsupported type handling is set to CONVERT_TO_VARCHAR, but toPrestoType() returned empty
2020-08-19T03:15:31.2174630Z 	at com.google.common.base.Verify.verify(Verify.java:181)
2020-08-19T03:15:31.2175386Z 	at io.prestosql.plugin.postgresql.PostgreSqlClient.getColumns(PostgreSqlClient.java:291)
2020-08-19T03:15:31.2176537Z 	at io.prestosql.plugin.jdbc.ForwardingJdbcClient.getColumns(ForwardingJdbcClient.java:84)
```
https://github.com/prestosql/presto/runs/1001221160
red on master

**Comment by kokosing** [comment]
CC: @iirekm  I recall you hit that as well.

**Comment by kokosing** [comment]
I spent some time on it today. Running it 1000 times by 10 threads does not reproduce the issue for me. 

Convert unsupported types to varchar is very simple, if mapping is empty and session property is set map to varchar. To me it looks like at some point of query execution session property has one value and then a bit later it has different value which sounds implausible to me.

**Comment by kokosing** [comment]
https://github.com/prestosql/presto/pull/4891

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/1020997426

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/1021766380

**Comment by findepi** [comment]
btw i think this flakiness is a regression, or an environmental change. I am seeing this every day or every other day now (at random) and I don't recall seeing it earlier than "recently" (past weeks?).

IMO we should try bisecting this.

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/1022374337

**Comment by findepi** [comment]
I run `TestPostgreSqlTypeMapping.testDecimalExceedingPrecisionMaxWithExceedingIntegerValues` locally 1000 times, with 4 threads (trying to mimic parallel test execution on CI).
did not reproduce the problem.

**Comment by sopel39** [comment]
https://github.com/prestosql/presto/pull/4971/checks?check_run_id=1027092185

**Comment by findepi** [comment]
With additional verification info (https://github.com/prestosql/presto/pull/4970) i got this:

```
2020-08-25T22:39:30.5039551Z [ERROR] testDecimalExceedingPrecisionMaxWithNonExceedingIntegerValues(io.prestosql.plugin.postgresql.TestPostgreSqlTypeMapping)  Time elapsed: 0.578 s  <<< FAILURE!
2020-08-25T22:39:30.5054546Z java.lang.AssertionError: Execution of 'actual' query failed: SELECT column_name, data_type FROM information_schema.columns WHERE table_schema = 'tpch' AND table_schema||'.'||table_name = 'tpch.test_exceeding_max_decimal_yzdhv'
2020-08-25T22:39:30.5056540Z 	at org.testng.Assert.fail(Assert.java:83)
2020-08-25T22:39:30.5061565Z 	at io.prestosql.testing.QueryAssertions.assertQuery(QueryAssertions.java:150)
2020-08-25T22:39:30.5066745Z 	at io.prestosql.testing.QueryAssertions.assertQuery(QueryAssertions.java:106)
2020-08-25T22:39:30.5073064Z 	at io.prestosql.testing.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:152)
2020-08-25T22:39:30.5083026Z 	at io.prestosql.plugin.postgresql.TestPostgreSqlTypeMapping.testDecimalExceedingPrecisionMaxWithNonExceedingIntegerValues(TestPostgreSqlTypeMapping.java:450)
2020-08-25T22:39:30.5088207Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-08-25T22:39:30.5094906Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-08-25T22:39:30.5101780Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-08-25T22:39:30.5105864Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-08-25T22:39:30.5112121Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-08-25T22:39:30.5115935Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-08-25T22:39:30.5120458Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-08-25T22:39:30.5124567Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-08-25T22:39:30.5130181Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-08-25T22:39:30.5135279Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-08-25T22:39:30.5140895Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-08-25T22:39:30.5146508Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-08-25T22:39:30.5150254Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-08-25T22:39:30.5164130Z Caused by: java.lang.RuntimeException: Unsupported type handling is set to CONVERT_TO_VARCHAR, but toPrestoType() returned empty for JdbcTypeHandle{jdbcType=2003, jdbcTypeName=_timestamp, columnSize=29, decimalDigits=6}
2020-08-25T22:39:30.5170305Z 	at io.prestosql.testing.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:114)
2020-08-25T22:39:30.5176131Z 	at io.prestosql.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:442)
2020-08-25T22:39:30.5181233Z 	at io.prestosql.testing.QueryAssertions.assertQuery(QueryAssertions.java:147)
2020-08-25T22:39:30.5181922Z 	... 16 more
2020-08-25T22:39:30.5196524Z Caused by: com.google.common.base.VerifyException: Unsupported type handling is set to CONVERT_TO_VARCHAR, but toPrestoType() returned empty for JdbcTypeHandle{jdbcType=2003, jdbcTypeName=_timestamp, columnSize=29, decimalDigits=6}
```

**Comment by findepi** [comment]
Superseded with https://github.com/prestosql/presto/issues/4981
