### ISSUE TITLE
Flaky tests due to: unable to create native thread: possibly out of memory or process/resource limits reached

### ISSUE THREAD

**Issue by kokosing** [prestosql/presto#4973]
```
020-08-25T15:39:05.0332160Z java.nio.channels.AsynchronousCloseException
2020-08-25T15:39:05.0332505Z 	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
2020-08-25T15:39:05.0332848Z 	at java.base/sun.nio.ch.ServerSocketChannelImpl.end(ServerSocketChannelImpl.java:269)
2020-08-25T15:39:05.0333207Z 	at java.base/sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:288)
2020-08-25T15:39:05.0333549Z 	at com.qubole.rubix.bookkeeper.LocalDataTransferServer$LocalServer.run(LocalDataTransferServer.java:196)
2020-08-25T15:39:05.0333874Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-08-25T15:39:05.0334120Z 
2020-08-25T15:39:05.0334368Z 
2020-08-25T15:39:05.0347658Z 2020-08-25T10:39:05.034-0500	INFO	pool-3-thread-1	com.qubole.rubix.bookkeeper.BookKeeper	total free space 48505MB, maximum size of cache 36863MB
2020-08-25T15:39:05.0820823Z 2020-08-25T10:39:05.081-0500	INFO	pool-3-thread-1	com.qubole.rubix.bookkeeper.BookKeeperServer	Starting BookKeeperServer on port 8899
2020-08-25T15:39:05.0889694Z 2020-08-25T10:39:05.085-0500	INFO	pool-3-thread-1	io.prestosql.plugin.hive.rubix.RubixInitializer	Rubix initialized successfully
2020-08-25T15:39:08.3336352Z 2020-08-25T10:39:08.332-0500	WARN	Thread-1789	com.qubole.rubix.bookkeeper.LocalDataTransferServer	Stopping Local Transfer server
2020-08-25T15:39:08.3338656Z java.nio.channels.AsynchronousCloseException
2020-08-25T15:39:08.3339107Z 	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
2020-08-25T15:39:08.3339457Z 	at java.base/sun.nio.ch.ServerSocketChannelImpl.end(ServerSocketChannelImpl.java:269)
2020-08-25T15:39:08.3339812Z 	at java.base/sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:288)
2020-08-25T15:39:08.3340150Z 	at com.qubole.rubix.bookkeeper.LocalDataTransferServer$LocalServer.run(LocalDataTransferServer.java:196)
2020-08-25T15:39:08.3340475Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-08-25T15:39:08.3340718Z 
2020-08-25T15:39:08.3340960Z 
2020-08-25T15:39:08.3350175Z 2020-08-25T10:39:08.334-0500	INFO	pool-3-thread-1	com.qubole.rubix.bookkeeper.BookKeeperServer	Bookkeeper Server Stopped
2020-08-25T15:39:08.3739151Z 2020-08-25T10:39:08.372-0500	INFO	pool-3-thread-1	com.qubole.rubix.bookkeeper.BookKeeper	total free space 48505MB, maximum size of cache 36863MB
2020-08-25T15:39:08.4194962Z 2020-08-25T10:39:08.418-0500	INFO	pool-3-thread-1	com.qubole.rubix.bookkeeper.BookKeeperServer	Starting BookKeeperServer on port 8899
2020-08-25T15:39:08.4240438Z 2020-08-25T10:39:08.422-0500	INFO	pool-3-thread-1	io.prestosql.plugin.hive.rubix.RubixInitializer	Rubix initialized successfully
2020-08-25T15:39:10.3333339Z 2020-08-25T10:39:10.332-0500	WARN	Thread-1815	com.qubole.rubix.bookkeeper.LocalDataTransferServer	Stopping Local Transfer server
2020-08-25T15:39:10.3335076Z java.nio.channels.AsynchronousCloseException
2020-08-25T15:39:10.3335458Z 	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
2020-08-25T15:39:10.3335758Z 	at java.base/sun.nio.ch.ServerSocketChannelImpl.end(ServerSocketChannelImpl.java:269)
2020-08-25T15:39:10.3336037Z 	at java.base/sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:288)
2020-08-25T15:39:10.3336328Z 	at com.qubole.rubix.bookkeeper.LocalDataTransferServer$LocalServer.run(LocalDataTransferServer.java:196)
2020-08-25T15:39:10.3336587Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-08-25T15:39:10.3336889Z 
2020-08-25T15:39:10.3337052Z 
2020-08-25T15:39:10.3361172Z 2020-08-25T10:39:10.333-0500	INFO	pool-3-thread-1	com.qubole.rubix.bookkeeper.BookKeeperServer	Bookkeeper Server Stopped
2020-08-25T15:39:12.2278289Z [ERROR] Tests run: 2672, Failures: 33, Errors: 0, Skipped: 312, Time elapsed: 1,213.043 s <<< FAILURE! - in TestSuite
2020-08-25T15:39:12.2286743Z [ERROR] testCachedDirectoryLister(io.prestosql.plugin.hive.TestBackgroundHiveSplitLoader)  Time elapsed: 3.937 s  <<< FAILURE!
2020-08-25T15:39:12.2294273Z java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
2020-08-25T15:39:12.2298345Z 	at java.base/java.lang.Thread.start0(Native Method)
2020-08-25T15:39:12.2302450Z 	at java.base/java.lang.Thread.start(Thread.java:803)
2020-08-25T15:39:12.2308760Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:937)
2020-08-25T15:39:12.2315015Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1354)
2020-08-25T15:39:12.2321796Z 	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
2020-08-25T15:39:12.2330255Z 	at io.prestosql.plugin.hive.TestBackgroundHiveSplitLoader.testCachedDirectoryLister(TestBackgroundHiveSplitLoader.java:370)
2020-08-25T15:39:12.2335859Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-08-25T15:39:12.2342279Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-08-25T15:39:12.2349361Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-08-25T15:39:12.2354069Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-08-25T15:39:12.2360918Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-08-25T15:39:12.2365553Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-08-25T15:39:12.2370424Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-08-25T15:39:12.2375417Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-08-25T15:39:12.2381313Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-08-25T15:39:12.2440189Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-08-25T15:39:12.2445524Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-08-25T15:39:12.2451576Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-08-25T15:39:12.2455582Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-08-25T15:39:12.2456669Z 
2020-08-25T15:39:12.2464723Z [ERROR] testPropagateException(io.prestosql.plugin.hive.TestBackgroundHiveSplitLoader)  Time elapsed: 0 s  <<< FAILURE!
2020-08-25T15:39:12.2472928Z java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
2020-08-25T15:39:12.2476914Z 	at java.base/java.lang.Thread.start0(Native Method)
2020-08-25T15:39:12.2480740Z 	at java.base/java.lang.Thread.start(Thread.java:803)
2020-08-25T15:39:12.2486586Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:937)
2020-08-25T15:39:12.2492393Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1343)
2020-08-25T15:39:12.2498269Z 	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
2020-08-25T15:39:12.2503092Z 	at org.testng.internal.thread.ExecutorAdapter.submitRunnable(ExecutorAdapter.java:30)
2020-08-25T15:39:12.2509971Z 	at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:265)
2020-08-25T15:39:12.2516095Z 	at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:242)
2020-08-25T15:39:12.2520496Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:651)
2020-08-25T15:39:12.2524977Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-08-25T15:39:12.2529547Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-08-25T15:39:12.2535592Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-08-25T15:39:12.2540749Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-08-25T15:39:12.2547199Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-08-25T15:39:12.2554242Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-08-25T15:39:12.2558433Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-08-25T1
```

**Comment by kokosing** [comment]
> That test is bad. It submits 1000 tasks at once to newCachedThreadPool().

> We might want to add `jvmkill` to the tests so that we fail immediately.

https://prestosql.slack.com/archives/CP1MUNEUX/p1598379803063000

**Comment by sopel39** [comment]
https://github.com/prestosql/presto/pull/4887/checks?check_run_id=1031118622

**Comment by findepi** [comment]
`TestHiveCreateExternalTable` failed with `unable to create native thread: possibly out of memory or process/resource limits reached` in https://github.com/prestosql/presto/runs/1089890636

**Comment by findepi** [comment]
`testCachedDirectoryLister`, others in https://github.com/prestosql/presto/runs/1090181502

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/1090181502

**Comment by sopel39** [comment]
https://github.com/prestosql/presto/pull/2307/checks?check_run_id=1093508748

**Comment by findepi** [comment]
again in https://github.com/prestosql/presto/pull/5188 (log discarded)
