### ISSUE TITLE
Flaky test TestFullParquetReader.testArrayOfMapOfStruct

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#4984]
https://github.com/prestosql/presto/runs/1030241159

```
2020-08-26T07:24:09.0925092Z [ERROR] testArrayOfMapOfStruct(io.prestosql.plugin.hive.parquet.TestFullParquetReader)  Time elapsed: 0.677 s  <<< FAILURE!
2020-08-26T07:24:09.0933098Z java.lang.IllegalArgumentException: maxCapacityHint can't be less than initialSlabSize 1024 100
2020-08-26T07:24:09.0938887Z 	at org.apache.parquet.Preconditions.checkArgument(Preconditions.java:53)
2020-08-26T07:24:09.0946630Z 	at org.apache.parquet.bytes.CapacityByteArrayOutputStream.<init>(CapacityByteArrayOutputStream.java:153)
2020-08-26T07:24:09.0954965Z 	at org.apache.parquet.column.values.delta.DeltaBinaryPackingValuesWriter.<init>(DeltaBinaryPackingValuesWriter.java:91)
2020-08-26T07:24:09.0974030Z 	at org.apache.parquet.column.values.delta.DeltaBinaryPackingValuesWriterForLong.<init>(DeltaBinaryPackingValuesWriterForLong.java:72)
2020-08-26T07:24:09.0983110Z 	at org.apache.parquet.column.values.delta.DeltaBinaryPackingValuesWriterForLong.<init>(DeltaBinaryPackingValuesWriterForLong.java:67)
2020-08-26T07:24:09.0992309Z 	at org.apache.parquet.column.values.factory.DefaultV2ValuesWriterFactory.getInt64ValuesWriter(DefaultV2ValuesWriterFactory.java:97)
2020-08-26T07:24:09.1003023Z 	at org.apache.parquet.column.values.factory.DefaultV2ValuesWriterFactory.newValuesWriter(DefaultV2ValuesWriterFactory.java:64)
2020-08-26T07:24:09.1011541Z 	at org.apache.parquet.column.values.factory.DefaultValuesWriterFactory.newValuesWriter(DefaultValuesWriterFactory.java:52)
2020-08-26T07:24:09.1019559Z 	at org.apache.parquet.column.ParquetProperties.newValuesWriter(ParquetProperties.java:149)
2020-08-26T07:24:09.1026636Z 	at org.apache.parquet.column.impl.ColumnWriterBase.<init>(ColumnWriterBase.java:66)
2020-08-26T07:24:09.1033333Z 	at org.apache.parquet.column.impl.ColumnWriterV2.<init>(ColumnWriterV2.java:59)
2020-08-26T07:24:09.1040357Z 	at org.apache.parquet.column.impl.ColumnWriteStoreV2.createColumnWriter(ColumnWriteStoreV2.java:35)
2020-08-26T07:24:09.1046915Z 	at org.apache.parquet.column.impl.ColumnWriteStoreBase.<init>(ColumnWriteStoreBase.java:94)
2020-08-26T07:24:09.1053344Z 	at org.apache.parquet.column.impl.ColumnWriteStoreV2.<init>(ColumnWriteStoreV2.java:30)
2020-08-26T07:24:09.1060015Z 	at org.apache.parquet.column.ParquetProperties.newColumnWriteStore(ParquetProperties.java:182)
2020-08-26T07:24:09.1067587Z 	at org.apache.parquet.hadoop.InternalParquetRecordWriter.initStore(InternalParquetRecordWriter.java:106)
2020-08-26T07:24:09.1074623Z 	at org.apache.parquet.hadoop.InternalParquetRecordWriter.<init>(InternalParquetRecordWriter.java:96)
2020-08-26T07:24:09.1080976Z 	at org.apache.parquet.hadoop.ParquetRecordWriter.<init>(ParquetRecordWriter.java:153)
2020-08-26T07:24:09.1087860Z 	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:487)
2020-08-26T07:24:09.1094572Z 	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:416)
2020-08-26T07:24:09.1101286Z 	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:411)
2020-08-26T07:24:09.1110201Z 	at org.apache.hadoop.hive.ql.io.parquet.write.ParquetRecordWriterWrapper.<init>(ParquetRecordWriterWrapper.java:70)
2020-08-26T07:24:09.1120065Z 	at org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat.getParquerRecordWriterWrapper(MapredParquetOutputFormat.java:137)
2020-08-26T07:24:09.1129000Z 	at org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat.getHiveRecordWriter(MapredParquetOutputFormat.java:126)
2020-08-26T07:24:09.1140037Z 	at io.prestosql.plugin.hive.parquet.write.TestMapredParquetOutputFormat.getHiveRecordWriter(TestMapredParquetOutputFormat.java:64)
2020-08-26T07:24:09.1147152Z 	at io.prestosql.plugin.hive.parquet.ParquetTester.writeParquetColumn(ParquetTester.java:585)
2020-08-26T07:24:09.1153712Z 	at io.prestosql.plugin.hive.parquet.ParquetTester.assertRoundTrip(ParquetTester.java:324)
2020-08-26T07:24:09.1160390Z 	at io.prestosql.plugin.hive.parquet.ParquetTester.testRoundTripType(ParquetTester.java:288)
2020-08-26T07:24:09.1167008Z 	at io.prestosql.plugin.hive.parquet.ParquetTester.testRoundTrip(ParquetTester.java:204)
2020-08-26T07:24:09.1199214Z 	at io.prestosql.plugin.hive.parquet.AbstractTestParquetReader.testArrayOfMapOfStruct(AbstractTestParquetReader.java:369)
2020-08-26T07:24:09.1207729Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-08-26T07:24:09.1215142Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-08-26T07:24:09.1223001Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-08-26T07:24:09.1228472Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-08-26T07:24:09.1235160Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-08-26T07:24:09.1239983Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-08-26T07:24:09.1245062Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-08-26T07:24:09.1250409Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-08-26T07:24:09.1257478Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-08-26T07:24:09.1267362Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-08-26T07:24:09.1274809Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-08-26T07:24:09.1282657Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-08-26T07:24:09.1286944Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by findepi** [comment]
https://github.com/trinodb/trino/runs/2034630746

**Comment by sopel39** [comment]
Another one https://github.com/trinodb/trino/pull/7462/checks?check_run_id=2233104610

**Comment by ebyhr** [comment]
`testSingleLevelSchemaArrayOfArrayOfStructOfArray` is also flaky. 
https://github.com/trinodb/trino/runs/3699615757 

```
2021-09-24T13:40:21.1144001Z [ERROR] Tests run: 83, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 778.509 s <<< FAILURE! - in io.trino.plugin.hive.parquet.TestFullParquetReader
2021-09-24T13:40:21.1148332Z [ERROR] io.trino.plugin.hive.parquet.TestFullParquetReader.testSingleLevelSchemaArrayOfArrayOfStructOfArray  Time elapsed: 7.488 s  <<< FAILURE!
2021-09-24T13:40:21.1152669Z org.apache.parquet.io.ParquetDecodingException: Dictionary is missing for Page
2021-09-24T13:40:21.1155109Z 	at io.trino.parquet.reader.PrimitiveColumnReader.initDataReader(PrimitiveColumnReader.java:409)
2021-09-24T13:40:21.1157974Z 	at io.trino.parquet.reader.PrimitiveColumnReader.readPageV2(PrimitiveColumnReader.java:393)
2021-09-24T13:40:21.1160771Z 	at io.trino.parquet.reader.PrimitiveColumnReader.readNextPage(PrimitiveColumnReader.java:356)
2021-09-24T13:40:21.1163622Z 	at io.trino.parquet.reader.PrimitiveColumnReader.readPrimitive(PrimitiveColumnReader.java:210)
2021-09-24T13:40:21.1166269Z 	at io.trino.parquet.reader.ParquetReader.readPrimitive(ParquetReader.java:370)
2021-09-24T13:40:21.1168555Z 	at io.trino.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:444)
2021-09-24T13:40:21.1170541Z 	at io.trino.parquet.reader.ParquetReader.readStruct(ParquetReader.java:325)
2021-09-24T13:40:21.1172553Z 	at io.trino.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:435)
2021-09-24T13:40:21.1174514Z 	at io.trino.parquet.reader.ParquetReader.readArray(ParquetReader.java:289)
2021-09-24T13:40:21.1176499Z 	at io.trino.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:441)
2021-09-24T13:40:21.1178487Z 	at io.trino.parquet.reader.ParquetReader.readArray(ParquetReader.java:289)
2021-09-24T13:40:21.1180896Z 	at io.trino.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:441)
2021-09-24T13:40:21.1183022Z 	at io.trino.parquet.reader.ParquetReader.readBlock(ParquetReader.java:427)
2021-09-24T13:40:21.1185049Z 	at io.trino.plugin.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:224)
2021-09-24T13:40:21.1187040Z 	at io.trino.spi.block.LazyBlock$LazyData.load(LazyBlock.java:396)
2021-09-24T13:40:21.1188388Z 	at io.trino.spi.block.LazyBlock$LazyData.getTopLevelBlock(LazyBlock.java:365)
2021-09-24T13:40:21.1189796Z 	at io.trino.spi.block.LazyBlock.getBlock(LazyBlock.java:270)
2021-09-24T13:40:21.1191114Z 	at io.trino.spi.block.LazyBlock.isNull(LazyBlock.java:253)
2021-09-24T13:40:21.1193013Z 	at io.trino.plugin.hive.parquet.ParquetTester.decodeObject(ParquetTester.java:712)
2021-09-24T13:40:21.1195347Z 	at io.trino.plugin.hive.parquet.ParquetTester.assertPageSource(ParquetTester.java:492)
2021-09-24T13:40:21.1197788Z 	at io.trino.plugin.hive.parquet.ParquetTester.assertPageSource(ParquetTester.java:473)
2021-09-24T13:40:21.1200262Z 	at io.trino.plugin.hive.parquet.ParquetTester.assertFileContents(ParquetTester.java:465)
2021-09-24T13:40:21.1202718Z 	at io.trino.plugin.hive.parquet.ParquetTester.assertRoundTrip(ParquetTester.java:367)
2021-09-24T13:40:21.1206441Z 	at io.trino.plugin.hive.parquet.ParquetTester.testRoundTripType(ParquetTester.java:301)
2021-09-24T13:40:21.1209037Z 	at io.trino.plugin.hive.parquet.ParquetTester.testRoundTrip(ParquetTester.java:281)
2021-09-24T13:40:21.1212008Z 	at io.trino.plugin.hive.parquet.ParquetTester.testSingleLevelArrayRoundTrip(ParquetTester.java:248)
2021-09-24T13:40:21.1215739Z 	at io.trino.plugin.hive.parquet.ParquetTester.testSingleLevelArraySchemaRoundTrip(ParquetTester.java:209)
2021-09-24T13:40:21.1221287Z 	at io.trino.plugin.hive.parquet.AbstractTestParquetReader.testSingleLevelSchemaArrayOfArrayOfStructOfArray(AbstractTestParquetReader.java:271)
2021-09-24T13:40:21.1225489Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-09-24T13:40:21.1227769Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-09-24T13:40:21.1230696Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-09-24T13:40:21.1232827Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-09-24T13:40:21.1234789Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-09-24T13:40:21.1238775Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2021-09-24T13:40:21.1240351Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2021-09-24T13:40:21.1242407Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2021-09-24T13:40:21.1244490Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2021-09-24T13:40:21.1246588Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2021-09-24T13:40:21.1248604Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-09-24T13:40:21.1250694Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-09-24T13:40:21.1251993Z 	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by sopel39** [comment]
cc @skrzypo987
