### ISSUE TITLE
Cannot read .lzo files when using hive.config.resources ("native-lzo library not available")

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#501]
### Steps to reproduce

1. Take existing Hive site xml that includes `com.hadoop.compression.lzo.LzopCodec` in `io.compression.codecs` config property.
2. Configure hive connector using `hive.config.resources`
3. Try to read .lzo

```
java.lang.RuntimeException: native-lzo library not available
        at com.hadoop.compression.lzo.LzopCodec.getDecompressorType(LzopCodec.java:120)
        at org.apache.hadoop.io.compress.CodecPool.getDecompressor(CodecPool.java:181)
        at org.apache.hadoop.mapred.LineRecordReader.<init>(LineRecordReader.java:111)
        at org.apache.hadoop.mapred.TextInputFormat.getRecordReader(TextInputFormat.java:67)
        at com.facebook.presto.hive.HiveUtil.createRecordReader(HiveUtil.java:204)
        at com.facebook.presto.hive.GenericHiveRecordCursorProvider.lambda$createRecordCursor$0(GenericHiveRecordCursorProvider.java:71)
```

**Comment by findepi** [comment]
My bad. This is actually misconfiguration.
To get
```
java.lang.RuntimeException: native-lzo library not available
        at com.hadoop.compression.lzo.LzopCodec.getDecompressorType(LzopCodec.java:120)
```

one needs to add some additional jar, and without some native component.

**Comment by Dkbei** [comment]
> My bad. This is actually misconfiguration. To get
> 
> ```
> java.lang.RuntimeException: native-lzo library not available
>         at com.hadoop.compression.lzo.LzopCodec.getDecompressorType(LzopCodec.java:120)
> ```
> 
> one needs to add some additional jar, and without some native component.

Hello, I have also encountered the same problem. May I ask which jar packages you have added at what location? Looking forward to your reply, thank you.
