### ISSUE TITLE
when i Running Presto in my  IDE  ,java.lang.RuntimeException: Failed to read class: io.prestosql.plugin.hive.parquet.ParquetFileWriter

### ISSUE THREAD

**Issue by wangfeigithub** [prestosql/presto#5040]
2020-09-01T14:28:57.772+0800	ERROR	main	io.prestosql.server.Server	Failed to read class: io.prestosql.plugin.hive.parquet.ParquetFileWriter
java.lang.RuntimeException: Failed to read class: io.prestosql.plugin.hive.parquet.ParquetFileWriter
	at io.prestosql.server.PluginDiscovery.readClass(PluginDiscovery.java:121)
	at io.prestosql.server.PluginDiscovery.classInterfaces(PluginDiscovery.java:107)
	at io.prestosql.server.PluginDiscovery.classInterfaces(PluginDiscovery.java:112)
	at io.prestosql.server.PluginDiscovery.lambda$discoverPlugins$0(PluginDiscovery.java:69)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.prestosql.server.PluginDiscovery.discoverPlugins(PluginDiscovery.java:70)
	at io.prestosql.server.PluginManager.buildClassLoaderFromPom(PluginManager.java:269)
	at io.prestosql.server.PluginManager.buildClassLoader(PluginManager.java:254)
	at io.prestosql.server.PluginManager.loadPlugin(PluginManager.java:162)
	at io.prestosql.server.PluginManager.loadPlugins(PluginManager.java:150)
	at io.prestosql.server.Server.doStart(Server.java:117)
	at io.prestosql.server.Server.lambda$start$0(Server.java:73)
	at io.prestosql.$gen.Presto_unknown____20200901_062803_1.run(Unknown Source)
	at io.prestosql.server.Server.start(Server.java:73)
	at io.prestosql.server.PrestoServer.main(PrestoServer.java:39)

2020-09-01T14:28:57.774+0800	INFO	Thread-76	io.airlift.bootstrap.LifeCycleManager	JVM is shutting down, cleaning up

**Comment by wangfeigithub** [comment]
What causes this ?  thinks!

**Comment by sopel39** [comment]
Please compile whole Project before running tests.

**Comment by wangfeigithub** [comment]
> Please compile whole Project before running tests.

I've already compiled it,
Then I found that I needed the following modifications to be successful.




#plugin.bundles=\
#  ../presto-resource-group-managers/pom.xml,\
#  ../presto-password-authenticators/pom.xml, \
#  ../presto-iceberg/pom.xml,\
#  ../presto-blackhole/pom.xml,\
#  ../presto-memory/pom.xml,\
#  ../presto-jmx/pom.xml,\
#  ../presto-raptor-legacy/pom.xml,\
#  ../presto-hive-hadoop2/pom.xml,\
#  ../presto-example-http/pom.xml,\
#  ../presto-kafka/pom.xml, \
#  ../presto-tpch/pom.xml, \
#  ../presto-local-file/pom.xml, \
#  ../presto-mysql/pom.xml,\
#  ../presto-memsql/pom.xml,\
#  ../presto-sqlserver/pom.xml, \
#  ../presto-prometheus/pom.xml, \
#  ../presto-postgresql/pom.xml, \
#  ../presto-thrift/pom.xml, \
#  ../presto-tpcds/pom.xml, \
#  ../presto-google-sheets/pom.xml, \
#  ../presto-druid/pom.xml

plugin.dir=../presto-server/target/presto-server-341-SNAPSHOT/plugin/

**Comment by sopel39** [comment]
Since you managed to run Presto, I'm closing the issue
