### ISSUE TITLE
Failure while cleaning up transaction in transitionToFailed

### ISSUE THREAD

**Issue by wangfeigithub** [prestosql/presto#5062]
```
presto> create table hive."default".test100("文档" int comment '中文用户ID');
CREATE TABLE
presto> insert into  hive."default".test100 values(111);
INSERT: 1 row

Query 20200903_100942_00046_2xbda, FAILED, 1 node
Splits: 35 total, 35 done (100.00%)
10.72 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20200903_100942_00046_2xbda failed: air1:9083: java.net.SocketTimeoutException: Read timed out

presto> insert into  hive."default".test100 values(111);
INSERT: 1 row

Query 20200903_100956_00047_2xbda, FINISHED, 1 node
Splits: 35 total, 35 done (100.00%)
0.68 [0 rows, 0B] [0 rows/s, 0B/s]

presto> select * from hive."default".test100 ;
 文档 
------
  111 
(1 row)

Query 20200903_101008_00048_2xbda, FINISHED, 1 node
Splits: 17 total, 17 done (100.00%)
0.21 [1 rows, 289B] [4 rows/s, 1.33KB/s]

presto> 

```

**Comment by wangfeigithub** [comment]
The first time will fail. But it successful the second time.

**Comment by wangfeigithub** [comment]
2020-09-03T18:09:53.338+0800	ERROR	transaction-finishing-9	com.google.common.util.concurrent.AbstractFuture	RuntimeException while executing runnable CallbackListener{io.prestosql.execution.QueryStateMachine$1@41f57c64} with executor MoreExecutors.directExecutor()
io.prestosql.NotInTransactionException: Unknown transaction ID: f75f1ba0-9300-4dbe-a3a9-dd0b703ba029. Possibly expired? Commands ignored until end of transaction block
	at io.prestosql.transaction.InMemoryTransactionManager.getTransactionMetadata(InMemoryTransactionManager.java:257)
	at io.prestosql.transaction.InMemoryTransactionManager.getTransactionInfo(InMemoryTransactionManager.java:155)
	at io.prestosql.transaction.TransactionManager.isAutoCommit(TransactionManager.java:37)
	at io.prestosql.execution.QueryStateMachine.lambda$transitionToFailed$13(QueryStateMachine.java:889)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.prestosql.execution.QueryStateMachine.transitionToFailed(QueryStateMachine.java:888)
	at io.prestosql.execution.QueryStateMachine$1.onFailure(QueryStateMachine.java:852)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1075)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1174)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:969)
	at com.google.common.util.concurrent.AbstractFuture.setFuture(AbstractFuture.java:800)
	at com.google.common.util.concurrent.Futures$NonCancellationPropagatingFuture.run(Futures.java:790)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1174)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:969)
	at com.google.common.util.concurrent.AbstractFuture.setFuture(AbstractFuture.java:800)
	at com.google.common.util.concurrent.Futures$NonCancellationPropagatingFuture.run(Futures.java:790)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1174)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:969)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:760)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:100)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1174)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:969)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:760)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.afterRanInterruptibly(TrustedListenableFutureTask.java:133)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:133)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
	at io.prestosql.$gen.Presto_unknown____20200903_092436_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by dain** [comment]
@wangfeigithub  I put up a PR to fix the stack trace you provided, but I don't think my fix will resolve the root issue.  The problem in the stack trace is we are getting an error while cleaning up the **already** failed query.  So, once my fix goes in, you may find a new problem.

**Comment by wangfeigithub** [comment]
> I put up a PR to fix the stack trace you provided, but I don't think my fix will resolve the root issue. The problem in the stack trace is we are getting an error while cleaning up the **already** failed query. So, once my fix goes in, you may find a new problem.

This problem does not occur in non-Chinese contexts, but using Chinese fields can cause errors
