### ISSUE TITLE
is there a way for presto server to remove semicolon at the the end of query string?

### ISSUE THREAD

**Issue by ythung1** [prestosql/presto#5078]
The reason I ask this because there is a tool called JMP that will automatically insert semicolon at the end of query string, and presto server will throw an exception `mismatched input ';'. Expecting: ',', 'EXCEPT', 'FETCH', 'FROM', 'GROUP', 'HAVING', 'INTERSECT', 'LIMIT', 'OFFSET', 'ORDER', 'UNION', 'WHERE', <EOF>`

Below is the example using JDBC driver:

>val r = stmt.executeQuery("select 'abc' as abc;")

>java.sql.SQLException: Query failed (#20200904_100723_00012_nubnw): line 1:20: mismatched input ';'. Expecting: ',', 'EXCEPT', 'FETCH', 'FROM', 'GROUP', 'HAVING', 'INTERSECT', 'LIMIT', 'OFFSET', 'ORDER', 'UNION', 'WHERE', <EOF>
  at io.prestosql.jdbc.AbstractPrestoResultSet.resultsException(AbstractPrestoResultSet.java:1754)
  at io.prestosql.jdbc.PrestoResultSet.getColumns(PrestoResultSet.java:249)
  at io.prestosql.jdbc.PrestoResultSet.create(PrestoResultSet.java:52)
  at io.prestosql.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:249)
  at io.prestosql.jdbc.PrestoStatement.execute(PrestoStatement.java:227)
  at io.prestosql.jdbc.PrestoStatement.executeQuery(PrestoStatement.java:76)
  ... 32 elided
Caused by: io.prestosql.jdbc.$internal.client.FailureInfo$FailureException: line 1:20: mismatched input ';'. Expecting: ',', 'EXCEPT', 'FETCH', 'FROM', 'GROUP', 'HAVING', 'INTERSECT', 'LIMIT', 'OFFSET', 'ORDER', 'UNION', 'WHERE', <EOF>
  at io.prestosql.sql.parser.ErrorHandler.syntaxError(ErrorHandler.java:108)
  at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
  at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
  at org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch(DefaultErrorStrategy.java:327)
  at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:139)
  at io.prestosql.sql.parser.SqlBaseParser.singleStatement(SqlBaseParser.java:254)
  at io.prestosql.sql.parser.SqlParser.invokeParser(SqlParser.java:156)
  at io.prestosql.sql.parser.SqlParser.createStatement(SqlParser.java:95)
  at io.prestosql.execution.QueryPreparer.prepareQuery(QueryPreparer.java:55)
  at io.prestosql.dispatcher.DispatchManager.createQueryInternal(DispatchManager.java:179)
  at io.prestosql.dispatcher.DispatchManager.lambda$createQuery$0(DispatchManager.java:148)
  at io.prestosql.$gen.Presto_340____20200903_074336_2.run(Unknown Source)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.prestosql.jdbc.$internal.client.FailureInfo$FailureException
  at io.prestosql.sql.parser.SqlParser$2.recoverInline(SqlParser.java:133)
  at org.antlr.v4.runtime.Parser.match(Parser.java:206)
  at io.prestosql.sql.parser.SqlBaseParser.singleStatement(SqlBaseParser.java:249)
  ... 9 more

**Comment by findepi** [comment]
Separating query script into indivudal statements (be it splitting on `;` or what else is required) is inherently
client's problem, so the server should not deal with semicolons.
I think the behavior of not allowing `;` is not uncommon among databases, Presto is not a lonely exception.

I am not familiar with JMP so do not know what it takes to fix the issue.
Still I am closing this and I suggest you report this to the tool maintainers.

We can continue conversation here  or on [our slack](https://prestosql.io/slack.html)
