### ISSUE TITLE
Flaky test TestHiveDynamicPartitionPruning.testJoinWithEmptyBuildSide

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#5120]
https://github.com/prestosql/presto/runs/1090722809

```
2020-09-09T12:11:51.7948261Z [ERROR] Tests run: 2653, Failures: 1, Errors: 0, Skipped: 72, Time elapsed: 2,114.537 s <<< FAILURE! - in TestSuite
2020-09-09T12:11:51.7958245Z [ERROR] testJoinWithEmptyBuildSide(io.prestosql.plugin.hive.TestHiveDynamicPartitionPruning)  Time elapsed: 2.075 s  <<< FAILURE!
2020-09-09T12:11:51.7961452Z java.util.NoSuchElementException
2020-09-09T12:11:51.7969810Z 	at com.google.common.collect.MoreCollectors$ToOptionalState.getElement(MoreCollectors.java:158)
2020-09-09T12:11:51.7976091Z 	at com.google.common.collect.MoreCollectors.lambda$static$1(MoreCollectors.java:70)
2020-09-09T12:11:51.7982708Z 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:582)
2020-09-09T12:11:51.7996425Z 	at io.prestosql.testing.AbstractTestQueryFramework.searchScanFilterAndProjectOperatorStats(AbstractTestQueryFramework.java:456)
2020-09-09T12:11:51.8013108Z 	at io.prestosql.plugin.hive.TestHiveDynamicPartitionPruning.testJoinWithEmptyBuildSide(TestHiveDynamicPartitionPruning.java:101)
2020-09-09T12:11:51.8019346Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-09-09T12:11:51.8029044Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-09-09T12:11:51.8043208Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-09-09T12:11:51.8058741Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-09-09T12:11:51.8065615Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-09-09T12:11:51.8071641Z 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
2020-09-09T12:11:51.8077924Z 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
2020-09-09T12:11:51.8117275Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2020-09-09T12:11:51.8123918Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2020-09-09T12:11:51.8130697Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-09-09T12:11:51.8137850Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-09-09T12:11:51.8142529Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by findepi** [comment]
cc @raunaqmorarka

**Comment by findepi** [comment]
When i did `@Test(invocationCount = 100, threadPoolSize = 4)` on this test, I got failures, but different then the original

```

java.lang.RuntimeException: Query was canceled

	at io.prestosql.testing.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:114)
	at io.prestosql.testing.DistributedQueryRunner.executeWithQueryId(DistributedQueryRunner.java:453)
	at io.prestosql.plugin.hive.TestHiveDynamicPartitionPruning.testJoinWithEmptyBuildSidex(TestHiveDynamicPartitionPruning.java:96)
	at jdk.internal.reflect.GeneratedMethodAccessor1294.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNoExecutor(MethodInvocationHelper.java:251)
	at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:240)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:651)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.prestosql.spi.PrestoException: Query was canceled
	at io.prestosql.execution.QueryStateMachine.transitionToCanceled(QueryStateMachine.java:920)
	at io.prestosql.execution.SqlQueryExecution.cancelQuery(SqlQueryExecution.java:524)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.prestosql.execution.SqlQueryManager.cancelQuery(SqlQueryManager.java:263)
	at io.prestosql.testing.DistributedQueryRunner.cancelAllQueries(DistributedQueryRunner.java:504)
	at io.prestosql.testing.DistributedQueryRunner.close(DistributedQueryRunner.java:490)
	at io.airlift.testing.Closeables.closeAllRuntimeException(Closeables.java:82)
	at io.prestosql.testing.AbstractTestQueryFramework.close(AbstractTestQueryFramework.java:104)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:115)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)

```

```

java.lang.RuntimeException: StatementClient thread was interrupted

	at io.prestosql.client.StatementClientV1.advance(StatementClientV1.java:392)
	at io.prestosql.testing.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:91)
	at io.prestosql.testing.DistributedQueryRunner.executeWithQueryId(DistributedQueryRunner.java:453)
	at io.prestosql.plugin.hive.TestHiveDynamicPartitionPruning.testJoinWithEmptyBuildSidex(TestHiveDynamicPartitionPruning.java:96)
	at jdk.internal.reflect.GeneratedMethodAccessor1294.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNoExecutor(MethodInvocationHelper.java:251)
	at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:240)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:651)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by sopel39** [comment]
I could not reproduce it. I expect this might be due to:
1. query provides results quickly
2. Yet Presto doesn't have up to date (or final) `TaskInfo` objects yet. These are fetched by `TaskInfoFetcher` periodically.
I think we could use `assertEventually` to wait for final query info before asserting other conditions

**Comment by sopel39** [comment]
> Would it be sufficient to wait on QueryInfo#isCompleteInfo to be true before using QueryInfo in searchScanFilterAndProjectOperatorStats ?

I think that works too

**Comment by raunaqmorarka** [comment]
Created https://github.com/prestosql/presto/pull/5134, though I haven't been able to reproduce locally with large no. of iterations as well.

**Comment by findepi** [comment]
https://github.com/prestosql/presto/pull/5156/checks?check_run_id=1112628014 cc @losipiuk

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/1116301733

**Comment by sopel39** [comment]
related to: https://github.com/prestosql/presto/issues/5120
