### ISSUE TITLE
When I configure OPENLDAP according to the PrestosQL document, then log in to the HTTPS url

### ISSUE THREAD

**Issue by wangfeigithub** [prestosql/presto#5130]
`2020-09-10T16:08:25.171+0800	WARN	http-worker-140	io.prestosql.server.ThrowableMapper	Request failed for /ui/login
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: Authentication error
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
	at io.prestosql.plugin.password.ldap.LdapAuthenticator.createAuthenticatedPrincipal(LdapAuthenticator.java:128)
	at io.prestosql.server.ui.PasswordManagerFormAuthenticator.isValidCredential(PasswordManagerFormAuthenticator.java:67)
	at io.prestosql.server.ui.FormWebUiAuthenticationFilter.checkLoginCredentials(FormWebUiAuthenticationFilter.java:221)
	at io.prestosql.server.ui.LoginResource.login(LoginResource.java:93)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)`

**Comment by wangfeigithub** [comment]
What usually causes this? thank you!

**Comment by wangfeigithub** [comment]
![image](https://user-images.githubusercontent.com/29723968/92700149-106b0000-f381-11ea-9abb-f12badcc40bb.png)

**Comment by wangfeigithub** [comment]
And my page after the meeting looks like this

**Comment by findepi** [comment]
This is likely a configuration issue. Let's please move the discussion to `#troubleshooting` channel on [our slack](https://prestosql.io/slack.html).
See you there!
