### ISSUE TITLE
TestHiveDynamicPartitionPruning.testJoinWithEmptyBuildSide flaky

### ISSUE THREAD

**Issue by losipiuk** [prestosql/presto#5159]
```
2020-09-14T16:04:16.4269696Z [ERROR] testJoinWithEmptyBuildSide(io.prestosql.plugin.hive.TestHiveDynamicPartitionPruning)  Time elapsed: 1.984 s  <<< FAILURE!
2020-09-14T16:04:16.4271994Z java.util.NoSuchElementException
2020-09-14T16:04:16.4274955Z 	at com.google.common.collect.MoreCollectors$ToOptionalState.getElement(MoreCollectors.java:158)
2020-09-14T16:04:16.4280632Z 	at com.google.common.collect.MoreCollectors.lambda$static$1(MoreCollectors.java:70)
2020-09-14T16:04:16.4285923Z 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:582)
2020-09-14T16:04:16.4296011Z 	at io.prestosql.testing.AbstractTestQueryFramework.searchScanFilterAndProjectOperatorStats(AbstractTestQueryFramework.java:464)
2020-09-14T16:04:16.4303427Z 	at io.prestosql.plugin.hive.TestHiveDynamicPartitionPruning.testJoinWithEmptyBuildSide(TestHiveDynamicPartitionPruning.java:101)
2020-09-14T16:04:16.4341185Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-09-14T16:04:16.4348407Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-09-14T16:04:16.4356642Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-09-14T16:04:16.4361081Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-09-14T16:04:16.4369185Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-09-14T16:04:16.4374159Z 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
2020-09-14T16:04:16.4380329Z 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
2020-09-14T16:04:16.4387516Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2020-09-14T16:04:16.4393525Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2020-09-14T16:04:16.4401068Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-09-14T16:04:16.4408028Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-09-14T16:04:16.4478398Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-09-14T16:04:16.4479140Z 
```

https://github.com/prestosql/presto/pull/5156/checks?check_run_id=1112628014

cc: @sopel39

**Comment by findepi** [comment]
Let's reopen https://github.com/prestosql/presto/issues/5120 instead.
