### ISSUE TITLE
Too large query causes StackOverFlowError.

### ISSUE THREAD

**Issue by yukiito2** [prestosql/presto#5164]
Our Presto thrown StackOverFlow Error when an user execute too large query (over 150KB).  

In addition, this error continued to throw for a long time, and something went wrong with the webUI, resource group, etc.

```
$ presto-cli --server localhost:8080 --catalog hive --debug --file too_long_query.sql

java.lang.StackOverflowError
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitSetOperation(StatementAnalyzer.java:315)
	at io.prestosql.sql.tree.AstVisitor.visitUnion(AstVisitor.java:257)
	at io.prestosql.sql.tree.Union.accept(Union.java:57)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:332)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.lambda$visitSetOperation$20(StatementAnalyzer.java:1381)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitSetOperation(StatementAnalyzer.java:1382)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitSetOperation(StatementAnalyzer.java:315)
	at io.prestosql.sql.tree.AstVisitor.visitUnion(AstVisitor.java:257)
	at io.prestosql.sql.tree.Union.accept(Union.java:57)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:332)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.lambda$visitSetOperation$20(StatementAnalyzer.java:1381)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
...
```

Our presto version: v340
query example: [too_long_query.txt](https://github.com/prestosql/presto/files/5222726/too_long_query.txt) (151kb)

Is there any way to prevent this  StackOverFlow Error (or prevent such too large query) ?

**Comment by findepi** [comment]
The limitation is less related to query length, but more to query structure.
And yes, some query structures are harder to deal with than others.

In this particular example, i would work with the user to educate them how they can use `VALUES` to achieve the same results in a more convenient manner.

**Comment by yukiito2** [comment]
> And yes, some query structures are harder to deal with than others.

Is it difficult to prevent with Presto's system (such as "Limit request size to 50KB") ?

**Comment by electrum** [comment]
There is a config for the limit on the size of the SQL text, but this is unrelated to the problem you encountered. Consider a simple query with a huge string literal. This could hit the text size limit, but would not be a problem for the parser or analyzer.

It might be possible to change the internals of Presto to avoid this specific issue, but there will always be a limitation of some sort, if you try hard enough to find it.

**Comment by findepi** [comment]
> Is it difficult to prevent with Presto's system (such as "Limit request size to 50KB") ?

You can set
```
query.max-length=50000
```

However, i would be wary of doing that. You can block many legitimate queries with such a setting that Presto would have no problem executing.
(it's not inconceivable for a BI tool to generate query longer than 50 KB)



> there will always be a limitation of some sort, if you try hard enough to find it.

i totally agree. With this let me close the issue. It's not actionable in general.
While we could fix this one case specifically, it feels it's more reasonable to change query to use `VALUES`.

If you feel like this particular query pattern is important to support (eg very common or very hard to change), please comment.
