### ISSUE TITLE
No FileSystem for s3 scheme

### ISSUE THREAD

**Issue by martindekov** [prestosql/presto#5182]
Hello Presto community,

I am trying to deploy Presto on Kubernetes and connect it to Amazon S3 through MinIO. I followed this documentation:
https://prestodb.io/docs/current/connector/hive.html

And my hive.properties looks like:
```
   hive.properties: |
      connector.name=hive-hadoop2
      hive.metastore.uri=thrift://hive-metastore:9083
      hive.s3.aws-access-key=<key>
      hive.s3.aws-secret-key=<secret>
      hive.s3.endpoint=http://minio:9000
      hive.s3.ssl.enabled=false
      hive.s3.path-style-access=true
```

Also used the presto helm charts with slight augmentations to support 341 release taken from here:
https://github.com/helm/charts/tree/master/stable/presto

When I try to create table in my bucket with the following query as per the documentation:
```
CREATE SCHEMA hive.web
WITH (location = 's3://my-bucket/')
```

I get the following exception:
```
io.prestosql.spi.PrestoException: Got exception: java.io.IOException No FileSystem for scheme: s3
	at io.prestosql.plugin.hive.metastore.thrift.ThriftHiveMetastore.createDatabase(ThriftHiveMetastore.java:987)
	at io.prestosql.plugin.hive.metastore.thrift.BridgingHiveMetastore.createDatabase(BridgingHiveMetastore.java:158)
	at io.prestosql.plugin.hive.metastore.cache.CachingHiveMetastore.createDatabase(CachingHiveMetastore.java:448)
	at io.prestosql.plugin.hive.HiveMetastoreClosure.createDatabase(HiveMetastoreClosure.java:120)
	at io.prestosql.plugin.hive.metastore.SemiTransactionalHiveMetastore.lambda$createDatabase$2(SemiTransactionalHiveMetastore.java:328)
	at io.prestosql.plugin.hive.metastore.SemiTransactionalHiveMetastore.commit(SemiTransactionalHiveMetastore.java:975)
	at io.prestosql.plugin.hive.HiveMetadata.commit(HiveMetadata.java:2643)
	at io.prestosql.plugin.hive.HiveConnector.commit(HiveConnector.java:212)
	at io.prestosql.transaction.InMemoryTransactionManager$TransactionMetadata$ConnectorTransactionMetadata.commit(InMemoryTransactionManager.java:594)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
	at io.prestosql.$gen.Presto_341____20200916_073949_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.hadoop.hive.metastore.api.MetaException: Got exception: java.io.IOException No FileSystem for scheme: s3
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_database_result$create_database_resultStandardScheme.read(ThriftHiveMetastore.java:39343)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_database_result$create_database_resultStandardScheme.read(ThriftHiveMetastore.java:39311)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_database_result.read(ThriftHiveMetastore.java:39245)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:86)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_create_database(ThriftHiveMetastore.java:1106)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.create_database(ThriftHiveMetastore.java:1093)
	at io.prestosql.plugin.hive.metastore.thrift.ThriftHiveMetastoreClient.createDatabase(ThriftHiveMetastoreClient.java:138)
	at io.prestosql.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.lambda$createDatabase$4(FailureAwareThriftMetastoreClient.java:108)
	at io.prestosql.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.runWithHandle(FailureAwareThriftMetastoreClient.java:422)
	at io.prestosql.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.createDatabase(FailureAwareThriftMetastoreClient.java:108)
	at io.prestosql.plugin.hive.metastore.thrift.ThriftHiveMetastore.lambda$createDatabase$48(ThriftHiveMetastore.java:978)
	at io.prestosql.plugin.hive.metastore.thrift.ThriftMetastoreApiStats.lambda$wrap$0(ThriftMetastoreApiStats.java:42)
	at io.prestosql.plugin.hive.util.RetryDriver.run(RetryDriver.java:130)
	at io.prestosql.plugin.hive.metastore.thrift.ThriftHiveMetastore.createDatabase(ThriftHiveMetastore.java:976)
	... 17 more
```

Can you point out where I can find why this is happening? Thank you in advance!

**Comment by findepi** [comment]
> I followed this documentation:
https://prestodb.io/docs/current/connector/hive.html

Note: the current documentation is here: https://prestosql.io/docs/current/connector/hive.html

> Can you point out where I can find why this is happening? 

The error is coming from Hive metastore (HMS), not directly from Presto.
Hive metastore is not, as the name could suggest, a passive store for metadata. 
The metastore also accesses the data locations and needs to be configured appropriately.

I do not know your metastore setup, but you may try to change `s3://` to `s3a://` in your table location.
(Doesn't matter for Presto, but may be a big change for HMS).

**Comment by findepi** [comment]
I closed this as not-an-issue in Presto.
We can continue conversation here, or on `#troubleshooting` channel on [our slack](https://prestosql.io/slack.html).
See you there!

**Comment by martindekov** [comment]
Thank you for the response @findepi I will join slack for further discussion 🍻
