### ISSUE TITLE
Possible query failure when inserting non-BMP varchar value in SQL Server: "String or binary data would be truncated"

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#5238]
Using `io.prestosql.plugin.sqlserver.SqlServerQueryRunner#main` for setup

```
presto:dbo> CREATE TABLE t(a varchar(1));
CREATE TABLE
presto:dbo> INSERT INTO t VALUES (U&'\+01F602');

Query 20200921_114104_00007_mpq6w failed: Failed to insert data: String or binary data would be truncated.
io.prestosql.spi.PrestoException: Failed to insert data: String or binary data would be truncated.
	at io.prestosql.plugin.jdbc.JdbcPageSink.finish(JdbcPageSink.java:168)
	at io.prestosql.operator.TableWriterOperator.finish(TableWriterOperator.java:208)
	at io.prestosql.operator.Driver.processInternal(Driver.java:397)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_testversion____20200921_113746_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.sql.BatchUpdateException: String or binary data would be truncated.
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeBatch(SQLServerPreparedStatement.java:2065)
	at io.prestosql.plugin.jdbc.JdbcPageSink.finish(JdbcPageSink.java:160)
	... 12 more
```

similarly, 

```
presto:dbo> CREATE TABLE t(a) AS VALUES U&'\+01F602';


Query 20200921_113953_00005_mpq6w failed: Failed to insert data: String or binary data would be truncated.
io.prestosql.spi.PrestoException: Failed to insert data: String or binary data would be truncated.
	at io.prestosql.plugin.jdbc.JdbcPageSink.finish(JdbcPageSink.java:168)
	at io.prestosql.operator.TableWriterOperator.finish(TableWriterOperator.java:208)
	at io.prestosql.operator.Driver.processInternal(Driver.java:397)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_testversion____20200921_113745_1.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.sql.BatchUpdateException: String or binary data would be truncated.
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeBatch(SQLServerPreparedStatement.java:2065)
	at io.prestosql.plugin.jdbc.JdbcPageSink.finish(JdbcPageSink.java:160)
	... 12 more
```

this can be tested with adding the following to `TestSqlServerTypeMapping`
```java
@Test
public void testVarchar()
{
    String nonBmpCharacter = "\uD83D\uDE02";
    verify(nonBmpCharacter.codePoints().count() == 1);

    DataTypeTest.create()
            .addRoundTrip(varcharDataType(5), null)
            .addRoundTrip(varcharDataType(5), "hello")
            .addRoundTrip(varcharDataType(1 /*2*/), nonBmpCharacter)
            .execute(getQueryRunner(), prestoCreateAsSelect("test_varchar"));
}
```

**Comment by findepi** [comment]
This comes from the fact that SQL Server's `varchar(1)` cannot hold single character outside of Basic Multilingual Plane (such as "😂" used in the example).
SQL Server treats the value as 2 characters.

**Comment by findepi** [comment]
In https://prestosql.slack.com/archives/CP1MUNEUX/p1600689274028600 we decided not to fix this.
