### ISSUE TITLE
Failure when accessing a bucketed table with timestamp columns: "TIMESTAMP precision must be in range [0, 12]"

### ISSUE THREAD

**Issue by leoChaoGlut** [prestosql/presto#5295]
Upgrade from 339 to 342, Error occured as below: 

```
io.prestosql.spi.PrestoException: TIMESTAMP precision must be in range [0, 12]
	at io.prestosql.spi.type.TimestampType.createTimestampType(TimestampType.java:58)
	at io.prestosql.plugin.hive.HiveType.getType(HiveType.java:135)
	at io.prestosql.plugin.hive.util.HiveUtil.getRegularColumnHandles(HiveUtil.java:915)
	at io.prestosql.plugin.hive.util.HiveBucketing.getHiveBucketHandle(HiveBucketing.java:186)
	at io.prestosql.plugin.hive.HiveMetadata.getTableHandle(HiveMetadata.java:376)
	at io.prestosql.plugin.hive.HiveMetadata.getTableHandle(HiveMetadata.java:263)
	at io.prestosql.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getTableHandle(ClassLoaderSafeConnectorMetadata.java:196)
	at io.prestosql.metadata.MetadataManager.getTableHandle(MetadataManager.java:345)
	at io.prestosql.sql.rewrite.ShowQueriesRewrite$Visitor.visitShowColumns(ShowQueriesRewrite.java:387)
	at io.prestosql.sql.rewrite.ShowQueriesRewrite$Visitor.visitShowColumns(ShowQueriesRewrite.java:164)
	at io.prestosql.sql.tree.ShowColumns.accept(ShowColumns.java:68)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.rewrite.ShowQueriesRewrite.rewrite(ShowQueriesRewrite.java:161)
	at io.prestosql.sql.rewrite.StatementRewrite.rewrite(StatementRewrite.java:57)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:80)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:75)
	at io.prestosql.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:256)
	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:182)
	at io.prestosql.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:757)
	at io.prestosql.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:123)
	at io.prestosql.$gen.Presto_342____20200925_093241_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by leoChaoGlut** [comment]
table DDL as below:

`
     Column     |     Type      |     Extra     |  Comment
----------------+---------------+---------------+------------
 sheetid        | varchar       |               | ?????
 sheettype      | bigint        |               | ????
 sdate          | timestamp(3)  |               | ????
 saledate       | timestamp(3)  |               | ??????
`

when executing sql: "desc tableName" 
error occured

**Comment by findepi** [comment]
The failure occurs on a bucketed table with a timestamp column.
cc @aalbu

**Comment by findepi** [comment]
Will be fixed by https://github.com/prestosql/presto/pull/5297

**Comment by findepi** [comment]
thanks @leoChaoGlut for your report!
