### ISSUE TITLE
Regexp functions should work on CHAR terms in addition to VARCHAR terms

### ISSUE THREAD

**Issue by alec-heif** [prestosql/presto#5386]
Steps to reproduce:

```
> SELECT REGEXP_LIKE('abc', 'abc');

 _col0
-------
 true

> SELECT REGEXP_LIKE(CHAR 'abc', 'abc');

io.prestosql.spi.PrestoException: line 1:8: Unexpected parameters (char(3), varchar(3)) for function regexp_like. Expected: regexp_like(varchar(x), joniregexp)
        at io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:969)
        at io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:343)
        ...
```

I think this is because the functions in `JoniRegexpFunctions` and `Re2JRegexpFunctions` only declare support for varchar(x) types, where they should actually probably overload to accept either char(x) or varchar(x). Notably, they do overload the regexp term, so the following does work:

```
> SELECT REGEXP_LIKE('abc', CHAR 'abc');

 _col0
-------
 true
```

and other non-regexp commands that take a string also accept chars, e.g.

```
> SELECT CHAR 'abc' LIKE 'abc';

 _col0
-------
 true

**Comment by alec-heif** [comment]
this is not a particularly urgent issue for my use case, but we noticed it when we started using the postgres connector against an existing table that had been created with fixed-length CHAR types. would be a nice convenience to not have to cast these to VARCHAR just to be able to regex match against them.
