### ISSUE TITLE
Flaky TestCoordinatorDynamicFiltering.testSemiJoinWithMultipleDynamicFiltersOnProbe

### ISSUE THREAD

**Issue by kokosing** [prestosql/presto#5424]
```
2020-10-05T21:53:24.4536149Z [ERROR] Tests run: 1993, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 2,792.62 s <<< FAILURE! - in TestSuite
2020-10-05T21:53:24.4539195Z [ERROR] testSemiJoinWithMultipleDynamicFiltersOnProbe(io.prestosql.execution.TestCoordinatorDynamicFiltering)  Time elapsed: 0.895 s  <<< FAILURE!
2020-10-05T21:53:24.4541514Z java.lang.RuntimeException: Task dynamic filter is set twice
2020-10-05T21:53:24.4543648Z 	at io.prestosql.testing.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:115)
2020-10-05T21:53:24.4546497Z 	at io.prestosql.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:453)
2020-10-05T21:53:24.4549217Z 	at io.prestosql.testing.AbstractTestQueryFramework.computeActual(AbstractTestQueryFramework.java:128)
2020-10-05T21:53:24.4554044Z 	at io.prestosql.execution.TestCoordinatorDynamicFiltering.assertQueryDynamicFilters(TestCoordinatorDynamicFiltering.java:277)
2020-10-05T21:53:24.4561228Z 	at io.prestosql.execution.TestCoordinatorDynamicFiltering.assertQueryDynamicFilters(TestCoordinatorDynamicFiltering.java:271)
2020-10-05T21:53:24.4605705Z 	at io.prestosql.execution.TestCoordinatorDynamicFiltering.testSemiJoinWithMultipleDynamicFiltersOnProbe(TestCoordinatorDynamicFiltering.java:252)
2020-10-05T21:53:24.4609782Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-10-05T21:53:24.4611802Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-10-05T21:53:24.4614248Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-10-05T21:53:24.4615897Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-10-05T21:53:24.4617398Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-10-05T21:53:24.4619298Z 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
2020-10-05T21:53:24.4620920Z 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
2020-10-05T21:53:24.4622268Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2020-10-05T21:53:24.4623385Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2020-10-05T21:53:24.4625056Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-10-05T21:53:24.4626733Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-10-05T21:53:24.4645606Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-10-05T21:53:24.4652048Z Caused by: java.lang.IllegalStateException: Task dynamic filter is set twice
2020-10-05T21:53:24.4659632Z 	at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
2020-10-05T21:53:24.4671707Z 	at io.prestosql.server.DynamicFilterService$DynamicFilterContext.lambda$addTaskDynamicFilters$7(DynamicFilterService.java:662)
2020-10-05T21:53:24.4679688Z 	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:185)
2020-10-05T21:53:24.4690626Z 	at io.prestosql.server.DynamicFilterService$DynamicFilterContext.addTaskDynamicFilters(DynamicFilterService.java:653)
2020-10-05T21:53:24.4699481Z 	at io.prestosql.server.DynamicFilterService.addTaskDynamicFilters(DynamicFilterService.java:305)
2020-10-05T21:53:24.4709950Z 	at io.prestosql.server.remotetask.DynamicFiltersFetcher.updateDynamicFilterDomains(DynamicFiltersFetcher.java:224)
2020-10-05T21:53:24.4720754Z 	at io.prestosql.server.remotetask.DynamicFiltersFetcher.success(DynamicFiltersFetcher.java:171)
2020-10-05T21:53:24.4731988Z 	at io.prestosql.server.remotetask.DynamicFiltersFetcher.success(DynamicFiltersFetcher.java:47)
2020-10-05T21:53:24.4741732Z 	at io.prestosql.server.remotetask.SimpleHttpResponseHandler.onSuccess(SimpleHttpResponseHandler.java:49)
2020-10-05T21:53:24.4753010Z 	at io.prestosql.server.remotetask.SimpleHttpResponseHandler.onSuccess(SimpleHttpResponseHandler.java:27)
2020-10-05T21:53:24.4762186Z 	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1089)
2020-10-05T21:53:24.4769875Z 	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
2020-10-05T21:53:24.4778061Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-10-05T21:53:24.4785792Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-10-05T21:53:24.4790387Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by kokosing** [comment]
@sopel39 Are familiar with this?

**Comment by sopel39** [comment]
Yes, I will take a look at it.
