### ISSUE TITLE
Failure when CTAS with long or unbounded varchar column in MemSQL

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#5454]
## long varchar

```
java.lang.RuntimeException: Error executing sql:
CREATE TABLE presto_test_parameterized_varchar_1i631 AS SELECT CAST('text_a' AS varchar(10)) col_0,
CAST('text_b' AS varchar(255)) col_1,
CAST('text_c' AS varchar(256)) col_2,
CAST('text_d' AS varchar(65535)) col_3,
CAST('text_e' AS varchar(65536)) col_4
	at io.prestosql.testing.sql.PrestoSqlExecutor.execute(PrestoSqlExecutor.java:45)
	at io.prestosql.testing.sql.TestTable.<init>(TestTable.java:44)
	at io.prestosql.testing.sql.TestTable.<init>(TestTable.java:37)
	at io.prestosql.testing.datatype.CreateAsSelectDataSetup.setupTestTable(CreateAsSelectDataSetup.java:48)
	at io.prestosql.testing.datatype.DataTypeTest.execute(DataTypeTest.java:78)
	at io.prestosql.testing.datatype.DataTypeTest.execute(DataTypeTest.java:71)
	at io.prestosql.plugin.memsql.TestMemSqlTypeMapping.testPrestoCreatedParameterizedVarchar(TestMemSqlTypeMapping.java:251)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
Caused by: java.lang.RuntimeException: (conn=13) Column length too big for column 'col_3' (max = 21845); use BLOB or TEXT instead
	at io.prestosql.testing.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:115)
	at io.prestosql.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:453)
	at io.prestosql.testing.sql.PrestoSqlExecutor.execute(PrestoSqlExecutor.java:42)
	... 30 more
Caused by: io.prestosql.spi.PrestoException: (conn=13) Column length too big for column 'col_3' (max = 21845); use BLOB or TEXT instead
	at io.prestosql.plugin.jdbc.BaseJdbcClient.execute(BaseJdbcClient.java:875)
	at io.prestosql.plugin.jdbc.BaseJdbcClient.createTable(BaseJdbcClient.java:482)
	at io.prestosql.plugin.jdbc.BaseJdbcClient.beginCreateTable(BaseJdbcClient.java:441)
	at io.prestosql.plugin.jdbc.ForwardingJdbcClient.beginCreateTable(ForwardingJdbcClient.java:147)
	at io.prestosql.plugin.jdbc.jmx.StatisticsAwareJdbcClient.lambda$beginCreateTable$19(StatisticsAwareJdbcClient.java:200)
	at io.prestosql.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
	at io.prestosql.plugin.jdbc.jmx.StatisticsAwareJdbcClient.beginCreateTable(StatisticsAwareJdbcClient.java:200)
	at io.prestosql.plugin.jdbc.CachingJdbcClient.beginCreateTable(CachingJdbcClient.java:322)
	at io.prestosql.plugin.jdbc.CachingJdbcClient.beginCreateTable(CachingJdbcClient.java:322)
	at io.prestosql.plugin.jdbc.JdbcMetadata.beginCreateTable(JdbcMetadata.java:387)
	at io.prestosql.metadata.MetadataManager.beginCreateTable(MetadataManager.java:807)
	at io.prestosql.sql.planner.optimizations.BeginTableWrite$Rewriter.createWriterTarget(BeginTableWrite.java:180)
	at io.prestosql.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:143)
	at io.prestosql.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:76)
	at io.prestosql.sql.planner.plan.TableFinishNode.accept(TableFinishNode.java:106)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:38)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:22)
	at io.prestosql.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
	at io.prestosql.sql.planner.plan.OutputNode.accept(OutputNode.java:83)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:32)
	at io.prestosql.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:73)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:206)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:195)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:190)
	at io.prestosql.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:444)
	at io.prestosql.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:424)
	at io.prestosql.execution.SqlQueryExecution.start(SqlQueryExecution.java:376)
	at io.prestosql.execution.SqlQueryManager.createQuery(SqlQueryManager.java:245)
	at io.prestosql.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:132)
	at io.prestosql.$gen.Presto_testversion____20201007_153312_3.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: java.lang.RuntimeException: Query: CREATE TABLE `tpch`.`tmp_presto_843f7d10e9b041edb2e49fbbf1bdcc62` (`col_0` varchar(10), `col_1` varchar(255), `col_2` varchar(256), `col_3` varchar(65535), `col_4` varchar(65536))
		at io.prestosql.plugin.jdbc.BaseJdbcClient.execute(BaseJdbcClient.java:876)
		... 43 more
```

## unbounded varchar

```
java.lang.RuntimeException: Error executing sql:
CREATE TABLE presto_test_parameterized_varchar_gat9g AS SELECT CAST('text_a' AS varchar(10)) col_0,
CAST('text_b' AS varchar(255)) col_1,
CAST('text_c' AS varchar(256)) col_2,
CAST('text_d' AS varchar(65535)) col_3,
CAST('text_e' AS varchar(65536)) col_4,
CAST('text_f' AS varchar(16777215)) col_5,
CAST('text_g' AS varchar(16777216)) col_6,
CAST('text_h' AS varchar(2147483646)) col_7,
CAST('unbounded' AS varchar) col_8
	at io.prestosql.testing.sql.PrestoSqlExecutor.execute(PrestoSqlExecutor.java:45)
	at io.prestosql.testing.sql.TestTable.<init>(TestTable.java:44)
	at io.prestosql.testing.sql.TestTable.<init>(TestTable.java:37)
	at io.prestosql.testing.datatype.CreateAsSelectDataSetup.setupTestTable(CreateAsSelectDataSetup.java:48)
	at io.prestosql.testing.datatype.DataTypeTest.execute(DataTypeTest.java:78)
	at io.prestosql.testing.datatype.DataTypeTest.execute(DataTypeTest.java:71)
	at io.prestosql.plugin.memsql.TestMemSqlTypeMapping.testPrestoCreatedParameterizedVarchar(TestMemSqlTypeMapping.java:128)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
Caused by: java.lang.RuntimeException: (conn=143) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1
	at io.prestosql.testing.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:115)
	at io.prestosql.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:453)
	at io.prestosql.testing.sql.PrestoSqlExecutor.execute(PrestoSqlExecutor.java:42)
	... 30 more
Caused by: io.prestosql.spi.PrestoException: (conn=143) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1
	at io.prestosql.plugin.jdbc.BaseJdbcClient.execute(BaseJdbcClient.java:875)
	at io.prestosql.plugin.jdbc.BaseJdbcClient.createTable(BaseJdbcClient.java:482)
	at io.prestosql.plugin.jdbc.BaseJdbcClient.beginCreateTable(BaseJdbcClient.java:441)
	at io.prestosql.plugin.jdbc.ForwardingJdbcClient.beginCreateTable(ForwardingJdbcClient.java:147)
	at io.prestosql.plugin.jdbc.jmx.StatisticsAwareJdbcClient.lambda$beginCreateTable$19(StatisticsAwareJdbcClient.java:200)
	at io.prestosql.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
	at io.prestosql.plugin.jdbc.jmx.StatisticsAwareJdbcClient.beginCreateTable(StatisticsAwareJdbcClient.java:200)
	at io.prestosql.plugin.jdbc.CachingJdbcClient.beginCreateTable(CachingJdbcClient.java:322)
	at io.prestosql.plugin.jdbc.CachingJdbcClient.beginCreateTable(CachingJdbcClient.java:322)
	at io.prestosql.plugin.jdbc.JdbcMetadata.beginCreateTable(JdbcMetadata.java:387)
	at io.prestosql.metadata.MetadataManager.beginCreateTable(MetadataManager.java:807)
	at io.prestosql.sql.planner.optimizations.BeginTableWrite$Rewriter.createWriterTarget(BeginTableWrite.java:180)
	at io.prestosql.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:143)
	at io.prestosql.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:76)
	at io.prestosql.sql.planner.plan.TableFinishNode.accept(TableFinishNode.java:106)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:38)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:22)
	at io.prestosql.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
	at io.prestosql.sql.planner.plan.OutputNode.accept(OutputNode.java:83)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:32)
	at io.prestosql.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:73)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:206)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:195)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:190)
	at io.prestosql.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:444)
	at io.prestosql.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:424)
	at io.prestosql.execution.SqlQueryExecution.start(SqlQueryExecution.java:376)
	at io.prestosql.execution.SqlQueryManager.createQuery(SqlQueryManager.java:245)
	at io.prestosql.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:132)
	at io.prestosql.$gen.Presto_testversion____20201007_151637_3.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: java.lang.RuntimeException: Query: CREATE TABLE `tpch`.`tmp_presto_83ef763b334a44788a7be28ca89b0279` (`col_0` varchar(10), `col_1` varchar(255), `col_2` varchar(256), `col_3` varchar(65535), `col_4` varchar(65536), `col_5` varchar(16777215), `col_6` varchar(16777216), `col_7` varchar(2147483646), `col_8` varchar)
		at io.prestosql.plugin.jdbc.BaseJdbcClient.execute(BaseJdbcClient.java:876)
		... 43 more
Caused by: java.sql.SQLSyntaxErrorException: (conn=143) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:236)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:165)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:327)
	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:378)
	at io.prestosql.plugin.jdbc.BaseJdbcClient.execute(BaseJdbcClient.java:872)
	... 43 more
Caused by: java.sql.SQLException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1
Query is: CREATE TABLE `tpch`.`tmp_presto_83ef763b334a44788a7be28ca89b0279` (`col_0` varchar(10), `col_1` varchar(255), `col_2` varchar(256), `col_3` varchar(65535), `col_4` varchar(65536), `col_5` varchar(16777215), `col_6` varchar(16777216), `col_7` varchar(2147483646), `col_8` varchar)
java thread: Query-20201007_151655_00027_8cev9-411
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:126)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:233)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:321)
	... 45 more
```

**Comment by findepi** [comment]
See also TODO in the code (being added in https://github.com/prestosql/presto/pull/5455)
