### ISSUE TITLE
Error: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 41984

### ISSUE THREAD

**Issue by xkwangcn** [prestosql/presto#5568]
Hi, Friends.
When I run presto on my environment, I encountered the following problems `ArrayIndexOutOfBoundsException`,  I want to resolve it but don't know what the `Block` mean and the presto operating principle about this error, could you give me some debugging ideas or related code documentation?
```
2020-10-15T07:56:18.510Z	INFO	20201015_075618_00218_33tjz.3.0-2-401	stdout	in DictionaryBlock: ids[0] = 41472
2020-10-15T07:56:18.510Z	INFO	20201015_075618_00218_33tjz.3.0-2-401	stdout	in DictionaryBlock: ids[1] = 48384
2020-10-15T07:56:18.510Z	INFO	20201015_075618_00218_33tjz.3.0-2-401	stdout	in DictionaryBlock: ids[2] = 65024
2020-10-15T07:56:18.510Z	INFO	20201015_075618_00218_33tjz.3.0-2-401	stdout	positionCount: 3
2020-10-15T07:56:18.510Z	INFO	20201015_075618_00218_33tjz.3.0-2-401	stdout	the dictionary.getPositionCount 293
2020-10-15T07:56:18.510Z	INFO	20201015_075618_00218_33tjz.3.0-2-401	stdout	position: 41472 # i:0
2020-10-15T07:56:18.510Z	ERROR	remote-task-callback-21	io.prestosql.execution.StageStateMachine	Stage 20201015_075618_00218_33tjz.3 failed
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 41984
	at io.prestosql.spi.block.DictionaryBlock.calculateCompactSize(DictionaryBlock.java:231)
	at io.prestosql.spi.block.DictionaryBlock.getSizeInBytes(DictionaryBlock.java:211)
	at io.prestosql.orc.OrcRecordReader.blockLoaded(OrcRecordReader.java:418)
	at io.prestosql.orc.OrcRecordReader.lambda$nextPage$9(OrcRecordReader.java:404)
	at io.prestosql.orc.OrcRecordReader$$Lambda$5919/00000000B80503D0.accept(Unknown Source)
	at io.prestosql.spi.block.LazyBlock$LazyData.lambda$load$0(LazyBlock.java:403)
	at io.prestosql.spi.block.LazyBlock$LazyData$$Lambda$5921/00000000E006AAB0.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at io.prestosql.spi.block.LazyBlock$LazyData.load(LazyBlock.java:403)
	at io.prestosql.spi.block.LazyBlock$LazyData.getBlock(LazyBlock.java:354)
	at io.prestosql.spi.block.LazyBlock.getBlock(LazyBlock.java:264)
	at io.prestosql.spi.block.LazyBlock.isNull(LazyBlock.java:253)
	at io.prestosql.spi.block.AbstractSingleMapBlock.isNull(AbstractSingleMapBlock.java:58)
	at io.prestosql.spi.type.TypeUtils.readNativeValue(TypeUtils.java:39)
	at io.prestosql.operator.scalar.MapElementAtFunction.elementAt(MapElementAtFunction.java:149)
	at java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:302)
	at java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
	at java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
	at java.lang.invoke.FilterReturnHandle.invokeExact_thunkArchetype_X(FilterReturnHandle.java:59)
	at java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
	at io.prestosql.$gen.PageFilter_20201015_075454_72.filter(Unknown Source)
	at io.prestosql.$gen.PageFilter_20201015_075454_72.filter(Unknown Source)
	at io.prestosql.operator.project.PageProcessor.createWorkProcessor(PageProcessor.java:121)
	at io.prestosql.operator.ScanFilterAndProjectOperator$SplitToPages.lambda$processPageSource$1(ScanFilterAndProjectOperator.java:266)
	at io.prestosql.operator.ScanFilterAndProjectOperator$SplitToPages$$Lambda$6752/00000000E4059870.apply(Unknown Source)
	at io.prestosql.operator.WorkProcessorUtils.lambda$flatMap$4(WorkProcessorUtils.java:245)
	at io.prestosql.operator.WorkProcessorUtils$$Lambda$6192/00000000B80546F0.process(Unknown Source)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.prestosql.operator.WorkProcessorUtils$$Lambda$6197/00000000B8056610.process(Unknown Source)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:277)
	at io.prestosql.operator.WorkProcessorUtils$$Lambda$6194/00000000B8055710.process(Unknown Source)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.prestosql.operator.WorkProcessorUtils$$Lambda$6197/00000000B8056610.process(Unknown Source)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
	at io.prestosql.operator.WorkProcessorUtils$$Lambda$6725/00000000B40DBE70.process(Unknown Source)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:148)
	at io.prestosql.operator.Driver.processInternal(Driver.java:379)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver$$Lambda$5427/00000000CC0A1210.get(Unknown Source)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_64ff0f9_dirty____20201015_075353_2.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:823)

**Comment by xkwangcn** [comment]
It seems the position and ids[] in DictionaryBlock.java is not correct, when the code ` if (!used[position]) {` is run, the position is a wrong value. 
```
private void calculateCompactSize()
    {
        DictionaryBlock unnested = unnest();
        if (unnested != this) {
            this.sizeInBytes = unnested.getSizeInBytes();
            return;
        }

        int uniqueIds = 0;
        boolean[] used = new boolean[dictionary.getPositionCount()];
        for (int i = 0; i < positionCount; i++) {
            int position = getId(i);
            // System.out.println("position: " + position + " # i:" + i);
            // System.out.println("used[i]" + used[i] + " # used[position]" + used[position]);
            if (!used[position]) {
                uniqueIds++;
                used[position] = true;
            }
        }
        this.sizeInBytes = dictionary.getPositionsSizeInBytes(used) + (Integer.BYTES * (long) positionCount);
        this.uniqueIds = uniqueIds;
    }
```
But I run the test cases in presto-spi module, all PASS. I think maybe the incorrect parameter value(ids[]) was passed in the previous procedure. Can you give me some information or presto document or methods to debug this process? I will debug it in my local environment. Thank you very much.

**Comment by xkwangcn** [comment]
more log info
```
2020-10-15T07:56:17.788Z	INFO	20201015_075617_00216_33tjz.3.0-5-433	stdout	in DictionaryBlock: ids[0] = 65280
2020-10-15T07:56:17.788Z	INFO	20201015_075617_00216_33tjz.3.0-5-433	stdout	in DictionaryBlock: ids[1] = 37632
2020-10-15T07:56:17.788Z	INFO	20201015_075617_00216_33tjz.3.0-5-433	stdout	in DictionaryBlock: ids[2] = 48384
2020-10-15T07:56:17.788Z	INFO	20201015_075617_00216_33tjz.3.0-5-433	stdout	positionCount: 3
2020-10-15T07:56:17.788Z	INFO	20201015_075617_00216_33tjz.3.0-5-433	stdout	the dictionary.getPositionCount 294
2020-10-15T07:56:17.788Z	INFO	20201015_075617_00216_33tjz.3.0-5-433	stdout	position: 65280 # i:0
2020-10-15T07:56:17.788Z	INFO	20201015_075617_00216_33tjz.3.0-4-461	stdout	in DictionaryBlock: ids[0] = 0
2020-10-15T07:56:17.788Z	INFO	20201015_075617_00216_33tjz.3.0-4-461	stdout	in DictionaryBlock: ids[1] = 1
2020-10-15T07:56:17.788Z	INFO	20201015_075617_00216_33tjz.3.0-4-461	stdout	in DictionaryBlock: ids[2] = 2
2020-10-15T07:56:17.788Z	INFO	20201015_075617_00216_33tjz.3.0-4-461	stdout	positionCount: 3
2020-10-15T07:56:17.788Z	INFO	20201015_075617_00216_33tjz.3.0-4-461	stdout	the dictionary.getPositionCount 4
2020-10-15T07:56:17.788Z	INFO	20201015_075617_00216_33tjz.3.0-4-461	stdout	position: 0 # i:0
2020-10-15T07:56:17.788Z	INFO	20201015_075617_00216_33tjz.3.0-4-461	stdout	position: 1 # i:1
2020-10-15T07:56:17.788Z	INFO	20201015_075617_00216_33tjz.3.0-4-461	stdout	position: 2 # i:2
2020-10-15T07:56:17.789Z	INFO	20201015_075617_00216_33tjz.3.0-2-401	stdout	in DictionaryBlock: ids[0] = 2
2020-10-15T07:56:17.789Z	INFO	20201015_075617_00216_33tjz.3.0-2-401	stdout	in DictionaryBlock: ids[1] = 0
2020-10-15T07:56:17.789Z	INFO	20201015_075617_00216_33tjz.3.0-2-401	stdout	in DictionaryBlock: ids[2] = 1
2020-10-15T07:56:17.789Z	INFO	20201015_075617_00216_33tjz.3.0-2-401	stdout	positionCount: 3
2020-10-15T07:56:17.789Z	INFO	20201015_075617_00216_33tjz.3.0-2-401	stdout	the dictionary.getPositionCount 4
2020-10-15T07:56:17.789Z	INFO	20201015_075617_00216_33tjz.3.0-4-461	stdout	in DictionaryBlock: ids[0] = 33024
2020-10-15T07:56:17.789Z	INFO	20201015_075617_00216_33tjz.3.0-4-461	stdout	in DictionaryBlock: ids[1] = 48384
2020-10-15T07:56:17.789Z	INFO	20201015_075617_00216_33tjz.3.0-4-461	stdout	in DictionaryBlock: ids[2] = 53504
2020-10-15T07:56:17.789Z	INFO	20201015_075617_00216_33tjz.3.0-4-461	stdout	positionCount: 3
2020-10-15T07:56:17.789Z	INFO	20201015_075617_00216_33tjz.3.0-4-461	stdout	the dictionary.getPositionCount 293
2020-10-15T07:56:17.789Z	INFO	20201015_075617_00216_33tjz.3.0-4-461	stdout	position: 33024 # i:0
2020-10-15T07:56:17.789Z	INFO	20201015_075617_00216_33tjz.3.0-2-401	stdout	position: 2 # i:0
2020-10-15T07:56:17.789Z	INFO	20201015_075617_00216_33tjz.3.0-2-401	stdout	position: 0 # i:1
2020-10-15T07:56:17.789Z	INFO	20201015_075617_00216_33tjz.3.0-2-401	stdout	position: 1 # i:2
2020-10-15T07:56:17.790Z	INFO	20201015_075617_00216_33tjz.3.0-2-401	stdout	in DictionaryBlock: ids[0] = 52480
2020-10-15T07:56:17.790Z	INFO	20201015_075617_00216_33tjz.3.0-2-401	stdout	in DictionaryBlock: ids[1] = 32768
2020-10-15T07:56:17.790Z	INFO	20201015_075617_00216_33tjz.3.0-2-401	stdout	in DictionaryBlock: ids[2] = 47616
2020-10-15T07:56:17.790Z	INFO	20201015_075617_00216_33tjz.3.0-2-401	stdout	positionCount: 3
2020-10-15T07:56:17.790Z	INFO	20201015_075617_00216_33tjz.3.0-2-401	stdout	the dictionary.getPositionCount 287
2020-10-15T07:56:17.790Z	INFO	20201015_075617_00216_33tjz.3.0-2-401	stdout	position: 52480 # i:0
2020-10-15T07:56:17.810Z	INFO	dispatcher-query-18	io.prestosql.event.QueryMonitor	TIMELINE: Query 20201015_075617_00216_33tjz :: Transaction:[c3887ae5-a383-48c0-8623-d32c48d7ce8a] :: elapsed 244ms :: planning 112ms :: waiting 110ms :: scheduling 126ms :: running 5ms :: finishing 1ms :: begin 2020-10-15T07:56:17.544Z :: end 2020-10-15T07:56:17.788Z
2020-10-15T07:56:18.117Z	INFO	20201015_075617_00217_33tjz.3.0-0-397	stdout	in DictionaryBlock: ids[0] = 0
2020-10-15T07:56:18.117Z	INFO	20201015_075617_00217_33tjz.3.0-0-397	stdout	in DictionaryBlock: ids[1] = 1
2020-10-15T07:56:18.117Z	INFO	20201015_075617_00217_33tjz.3.0-0-397	stdout	in DictionaryBlock: ids[2] = 2
2020-10-15T07:56:18.117Z	INFO	20201015_075617_00217_33tjz.3.0-0-397	stdout	positionCount: 3
2020-10-15T07:56:18.117Z	INFO	20201015_075617_00217_33tjz.3.0-0-397	stdout	the dictionary.getPositionCount 4
2020-10-15T07:56:18.117Z	INFO	20201015_075617_00217_33tjz.3.0-0-397	stdout	position: 0 # i:0
2020-10-15T07:56:18.117Z	INFO	20201015_075617_00217_33tjz.3.0-0-397	stdout	position: 1 # i:1
2020-10-15T07:56:18.117Z	INFO	20201015_075617_00217_33tjz.3.0-0-397	stdout	position: 2 # i:2
2020-10-15T07:56:18.118Z	INFO	20201015_075617_00217_33tjz.3.0-0-397	stdout	in DictionaryBlock: ids[0] = 42240
2020-10-15T07:56:18.118Z	INFO	20201015_075617_00217_33tjz.3.0-0-397	stdout	in DictionaryBlock: ids[1] = 48896
2020-10-15T07:56:18.118Z	INFO	20201015_075617_00217_33tjz.3.0-0-397	stdout	in DictionaryBlock: ids[2] = 56576
2020-10-15T07:56:18.118Z	INFO	20201015_075617_00217_33tjz.3.0-0-397	stdout	positionCount: 3
2020-10-15T07:56:18.118Z	INFO	20201015_075617_00217_33tjz.3.0-0-397	stdout	the dictionary.getPositionCount 295
2020-10-15T07:56:18.118Z	INFO	20201015_075617_00217_33tjz.3.0-0-397	stdout	position: 42240 # i:0
2020-10-15T07:56:18.118Z	ERROR	SplitRunner-228-397	io.prestosql.execution.executor.TaskExecutor	Error processing Split 20201015_075617_00217_33tjz.3.0-0 {path=file:/user/hive/warehouse/metering.db/datasource_metering_pod_request_cpu_cores/dt=2020-10-15/20201015_075506_00189_33tjz_fe8f94e0-d486-473e-9a79-f8d8be76ba8c, start=0, length=15472, fileSize=15472, hosts=[], database=metering, table=datasource_metering_pod_request_cpu_cores, forceLocalScheduling=false, partitionName=dt=2020-10-15, s3SelectPushdownEnabled=false} (start = 1.6027486051018206E12, wall = 4 ms, cpu = 0 ms, wait = 0 ms, calls = 1)
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 42240
	at io.prestosql.spi.block.DictionaryBlock.calculateCompactSize(DictionaryBlock.java:231)
	at io.prestosql.spi.block.DictionaryBlock.getSizeInBytes(DictionaryBlock.java:211)
	at io.prestosql.orc.OrcRecordReader.blockLoaded(OrcRecordReader.java:418)
	at io.prestosql.orc.OrcRecordReader.lambda$nextPage$9(OrcRecordReader.java:404)
	at io.prestosql.orc.OrcRecordReader$$Lambda$5919/00000000B80503D0.accept(Unknown Source)
	at io.prestosql.spi.block.LazyBlock$LazyData.lambda$load$0(LazyBlock.java:403)
	at io.prestosql.spi.block.LazyBlock$LazyData$$Lambda$5921/00000000E006AAB0.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at io.prestosql.spi.block.LazyBlock$LazyData.load(LazyBlock.java:403)
	at io.prestosql.spi.block.LazyBlock$LazyData.getBlock(LazyBlock.java:354)
	at io.prestosql.spi.block.LazyBlock.getBlock(LazyBlock.java:264)
	at io.prestosql.spi.block.LazyBlock.isNull(LazyBlock.java:253)
	at io.prestosql.spi.block.AbstractSingleMapBlock.isNull(AbstractSingleMapBlock.java:58)
	at io.prestosql.spi.type.TypeUtils.readNativeValue(TypeUtils.java:39)
	at io.prestosql.operator.scalar.MapElementAtFunction.elementAt(MapElementAtFunction.java:149)
	at java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:302)
	at java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
	at java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
	at java.lang.invoke.FilterReturnHandle.invokeExact_thunkArchetype_X(FilterReturnHandle.java:59)
	at java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
	at io.prestosql.$gen.PageFilter_20201015_075454_72.filter(Unknown Source)
	at io.prestosql.$gen.PageFilter_20201015_075454_72.filter(Unknown Source)
	at io.prestosql.operator.project.PageProcessor.createWorkProcessor(PageProcessor.java:121)
	at io.prestosql.operator.ScanFilterAndProjectOperator$SplitToPages.lambda$processPageSource$1(ScanFilterAndProjectOperator.java:266)
	at io.prestosql.operator.ScanFilterAndProjectOperator$SplitToPages$$Lambda$6752/00000000E4059870.apply(Unknown Source)
	at io.prestosql.operator.WorkProcessorUtils.lambda$flatMap$4(WorkProcessorUtils.java:245)
	at io.prestosql.operator.WorkProcessorUtils$$Lambda$6192/00000000B80546F0.process(Unknown Source)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.prestosql.operator.WorkProcessorUtils$$Lambda$6197/00000000B8056610.process(Unknown Source)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:277)
	at io.prestosql.operator.WorkProcessorUtils$$Lambda$6194/00000000B8055710.process(Unknown Source)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.prestosql.operator.WorkProcessorUtils$$Lambda$6197/00000000B8056610.process(Unknown Source)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
	at io.prestosql.operator.WorkProcessorUtils$$Lambda$6725/00000000B40DBE70.process(Unknown Source)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:148)
	at io.prestosql.operator.Driver.processInternal(Driver.java:379)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver$$Lambda$5427/00000000CC0A1210.get(Unknown Source)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_64ff0f9_dirty____20201015_075353_2.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:823)


2020-10-15T07:56:18.119Z	ERROR	remote-task-callback-7	io.prestosql.execution.StageStateMachine	Stage 20201015_075617_00217_33tjz.3 failed
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 42240
	at io.prestosql.spi.block.DictionaryBlock.calculateCompactSize(DictionaryBlock.java:231)
	at io.prestosql.spi.block.DictionaryBlock.getSizeInBytes(DictionaryBlock.java:211)
	at io.prestosql.orc.OrcRecordReader.blockLoaded(OrcRecordReader.java:418)
	at io.prestosql.orc.OrcRecordReader.lambda$nextPage$9(OrcRecordReader.java:404)
	at io.prestosql.orc.OrcRecordReader$$Lambda$5919/00000000B80503D0.accept(Unknown Source)
	at io.prestosql.spi.block.LazyBlock$LazyData.lambda$load$0(LazyBlock.java:403)
	at io.prestosql.spi.block.LazyBlock$LazyData$$Lambda$5921/00000000E006AAB0.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at io.prestosql.spi.block.LazyBlock$LazyData.load(LazyBlock.java:403)
	at io.prestosql.spi.block.LazyBlock$LazyData.getBlock(LazyBlock.java:354)
	at io.prestosql.spi.block.LazyBlock.getBlock(LazyBlock.java:264)
	at io.prestosql.spi.block.LazyBlock.isNull(LazyBlock.java:253)
	at io.prestosql.spi.block.AbstractSingleMapBlock.isNull(AbstractSingleMapBlock.java:58)
	at io.prestosql.spi.type.TypeUtils.readNativeValue(TypeUtils.java:39)
	at io.prestosql.operator.scalar.MapElementAtFunction.elementAt(MapElementAtFunction.java:149)
	at java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:302)
	at java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
	at java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
	at java.lang.invoke.FilterReturnHandle.invokeExact_thunkArchetype_X(FilterReturnHandle.java:59)
	at java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
	at io.prestosql.$gen.PageFilter_20201015_075454_72.filter(Unknown Source)
	at io.prestosql.$gen.PageFilter_20201015_075454_72.filter(Unknown Source)
	at io.prestosql.operator.project.PageProcessor.createWorkProcessor(PageProcessor.java:121)
	at io.prestosql.operator.ScanFilterAndProjectOperator$SplitToPages.lambda$processPageSource$1(ScanFilterAndProjectOperator.java:266)
	at io.prestosql.operator.ScanFilterAndProjectOperator$SplitToPages$$Lambda$6752/00000000E4059870.apply(Unknown Source)
	at io.prestosql.operator.WorkProcessorUtils.lambda$flatMap$4(WorkProcessorUtils.java:245)
	at io.prestosql.operator.WorkProcessorUtils$$Lambda$6192/00000000B80546F0.process(Unknown Source)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.prestosql.operator.WorkProcessorUtils$$Lambda$6197/00000000B8056610.process(Unknown Source)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:277)
	at io.prestosql.operator.WorkProcessorUtils$$Lambda$6194/00000000B8055710.process(Unknown Source)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.prestosql.operator.WorkProcessorUtils$$Lambda$6197/00000000B8056610.process(Unknown Source)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
	at io.prestosql.operator.WorkProcessorUtils$$Lambda$6725/00000000B40DBE70.process(Unknown Source)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:148)
	at io.prestosql.operator.Driver.processInternal(Driver.java:379)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver$$Lambda$5427/00000000CC0A1210.get(Unknown Source)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_64ff0f9_dirty____20201015_075353_2.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:823)

**Comment by sopel39** [comment]
Are you trying to implement your own connector?

**Comment by xkwangcn** [comment]
@sopel39 Basically, and I want to use it in my platform.
Do you know what the function of `calculateCompactSize(), compact(), ids`mean in https://github.com/prestosql/presto/blob/master/presto-spi/src/main/java/io/prestosql/spi/block/DictionaryBlock.java,  I want to debug my error from here. 
Thanks for you reply and help.

**Comment by sopel39** [comment]
`ids` are selected positions from dictionary block. `calculateCompactSize()` computes dictionary block size when compacted. `compact` reduces block mem usage by removing unused positions from dictionary.

I suggest joining PrestoSQL slack (https://prestosql.io/slack.html, particularly #dev channel) so we could help you with the connector. I will close this issue now.
