### ISSUE TITLE
"Unsupported column type" exception should give details on the unsupported type

### ISSUE THREAD

**Issue by tooptoop4** [prestosql/presto#5577]
https://github.com/prestosql/presto/blob/344/presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcRecordCursor.java#L75

"Unsupported column type" is not very helpful, it could give more details like what exact type is unsupported

got below error when making (incomplete) code changes:

io.prestosql.spi.PrestoException: Unsupported column type
	at io.prestosql.plugin.jdbc.JdbcRecordCursor.handleSqlException(JdbcRecordCursor.java:250)
	at io.prestosql.plugin.jdbc.JdbcRecordCursor.<init>(JdbcRecordCursor.java:106)
	at io.prestosql.plugin.jdbc.JdbcRecordSet.cursor(JdbcRecordSet.java:60)
	at io.prestosql.spi.connector.RecordPageSource.<init>(RecordPageSource.java:37)
	at io.prestosql.split.RecordPageSourceProvider.createPageSource(RecordPageSourceProvider.java:50)
	at io.prestosql.spi.connector.ConnectorPageSourceProvider.createPageSource(ConnectorPageSourceProvider.java:68)
	at io.prestosql.split.PageSourceManager.createPageSource(PageSourceManager.java:64)
	at io.prestosql.operator.TableScanOperator.getOutput(TableScanOperator.java:298)
	at io.prestosql.operator.Driver.processInternal(Driver.java:379)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_344_41_g3758d9f____20201016_181614_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.google.common.base.VerifyException: Unsupported column type
	at io.prestosql.plugin.jdbc.JdbcRecordCursor.lambda$new$0(JdbcRecordCursor.java:75)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at io.prestosql.plugin.jdbc.JdbcRecordCursor.<init>(JdbcRecordCursor.java:75)
	... 17 more

**Comment by findepi** [comment]
This exception can happen only when there is a bug in a connector, supposedly during development.
This is why it is scarce in details. And indeed I see this was raised in a SNAPSHOT version.
Let me close this. Please reopen if you see this for a released version.

Also, if you run into this during development often, please consider proposing an improvement.
