### ISSUE TITLE
Flaky test TestSystemConnector due to clock adjustment

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#5608]
```
Error:  Tests run: 2000, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 2,337.709 s <<< FAILURE! - in TestSuite
Error:  testRuntimeTasksTimestamps(io.prestosql.connector.system.TestSystemConnector)  Time elapsed: 0.154 s  <<< FAILURE!
java.lang.AssertionError: 
[value for field 1] 
Expecting:
  <2020-10-19T20:44:47.434Z[UTC]>
to be after or equal to:
  <2020-10-19T15:44:47.458564-05:00[America/Bahia_Banderas]>
	at io.prestosql.connector.system.TestSystemConnector.testRuntimeTasksTimestamps(TestSystemConnector.java:149)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

https://github.com/prestosql/presto/runs/1277310864

**Comment by findepi** [comment]
The situation was anticipated (https://github.com/prestosql/presto/pull/5465#discussion_r501852108).
I (naively?) hoped GHA runners did something to prevent clock adjustments during test execution.

(Clock adjustment is my assumption, based on the fact it is the only explanation that I know of.)
