### ISSUE TITLE
"DISTINCT *, column_A ORDER BY column_A" failed

### ISSUE THREAD

**Issue by qfrtrt** [prestosql/presto#5647]
```sql
...
SELECT DISTINCT support_order.*,
                support_order_oper.*,
                support_order.created_at,
                support_order_oper.operation_title,
                support_order_oper.order_id
FROM support_order
LEFT JOIN support_order_oper ON support_order.id=support_order_oper.order_id
ORDER BY support_order.created_at,
         support_order_oper.order_id,
         support_order_oper.operation_title ASC
```
```
io.prestosql.spi.PrestoException: line 41:1: For SELECT DISTINCT, ORDER BY expressions must appear in select list
	at io.prestosql.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
	at io.prestosql.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.verifySelectDistinct(StatementAnalyzer.java:3049)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1583)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:322)
	at io.prestosql.sql.tree.QuerySpecification.accept(QuerySpecification.java:144)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:339)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:349)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1039)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:322)
	at io.prestosql.sql.tree.Query.accept(Query.java:107)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:339)
	at io.prestosql.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:308)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:75)
	at io.prestosql.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:257)
	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:183)
	at io.prestosql.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:759)
	at io.prestosql.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:123)
	at io.prestosql.$gen.Presto_344____20201022_084917_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by martint** [comment]
Relates to https://github.com/prestosql/presto/issues/5660
