### ISSUE TITLE
Planning failure for DELETE with complex subquery

### ISSUE THREAD

**Issue by martint** [prestosql/presto#5665]
Given

```sql
CREATE TABLE t (a BIGINT)
```
The following query:

```sql
DELETE t WHERE a > ANY (SELECT a FROM t t1 WHERE t1.a = t.a)
```

fails with

```
Query 20201022_201203_00013_eenfw failed: Invalid descendant for DeleteNode: io.prestosql.sql.planner.plan.JoinNode
java.lang.IllegalArgumentException: Invalid descendant for DeleteNode: io.prestosql.sql.planner.plan.JoinNode
	at io.prestosql.sql.planner.optimizations.BeginTableWrite$Rewriter.rewriteDeleteTableScan(BeginTableWrite.java:229)
	at io.prestosql.sql.planner.optimizations.BeginTableWrite$Rewriter.rewriteDeleteTableScan(BeginTableWrite.java:225)
	at io.prestosql.sql.planner.optimizations.BeginTableWrite$Rewriter.rewriteDeleteTableScan(BeginTableWrite.java:215)
	at io.prestosql.sql.planner.optimizations.BeginTableWrite$Rewriter.rewriteDeleteTableScan(BeginTableWrite.java:211)
	at io.prestosql.sql.planner.optimizations.BeginTableWrite$Rewriter.rewriteDeleteTableScan(BeginTableWrite.java:215)
	at io.prestosql.sql.planner.optimizations.BeginTableWrite$Rewriter.visitDelete(BeginTableWrite.java:113)
	at io.prestosql.sql.planner.optimizations.BeginTableWrite$Rewriter.visitDelete(BeginTableWrite.java:76)
	at io.prestosql.sql.planner.plan.DeleteNode.accept(DeleteNode.java:91)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:38)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:22)
	at io.prestosql.sql.planner.plan.PlanVisitor.visitExchange(PlanVisitor.java:189)
	at io.prestosql.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:243)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
```

**Comment by Lewuathe** [comment]
We need `FROM`? Since explaining also fails, I could not obtain the correct execution plan of the query. 

```
presto:default> DELETE FROM t WHERE a > ANY (SELECT a FROM t t1 WHERE t1.a = t.a);
Query 20201030_075246_00006_iqcbj failed: Invalid descendant for DeleteNode: io.prestosql.sql.planner.plan.JoinNode
presto:default> explain DELETE FROM t WHERE a > ANY (SELECT a FROM t t1 WHERE t1.a = t.a);
Query 20201030_075255_00008_iqcbj failed: Invalid descendant for DeleteNode: io.prestosql.sql.planner.plan.JoinNode
```


But looks like the right node of the join is not returning true for `isAtMostScalar`. (cardinality can be over 1?)

```java
            if (node instanceof JoinNode) {
                JoinNode joinNode = (JoinNode) node;
                if (joinNode.getType() == JoinNode.Type.INNER && isAtMostScalar(joinNode.getRight())) {
                    PlanNode source = rewriteDeleteTableScan(joinNode.getLeft(), handle);
                    return replaceChildren(node, ImmutableList.of(source, joinNode.getRight()));
                }
            }
```

**Comment by sopel39** [comment]
You could run `EXPLAIN SELECT FROM t WHERE a > ANY (SELECT a FROM t t1 WHERE t1.a = t.a);` to see what plan is under `DeleteNode`
IIRC here decorrelation will increase (temporarily) cardinality of probe rows, so it's more complex pattern which is not handled by `BeginTableWrite`

**Comment by Lewuathe** [comment]
@sopel39 Thanks! Looks like `CrossJoin` is used.

```
 Fragment 1 [SOURCE]
     Output layout: [a_11]
     Output partitioning: SINGLE []
     Stage Execution Strategy: UNGROUPED_EXECUTION
     FilterProject[filterPredicate = (CASE "count_all" WHEN BIGINT '0' THEN false ELSE (("a_11" > "min") OR (CASE WHEN
     │   Layout: [a_11:bigint]
     │   Estimates: {rows: ? (?), cpu: ?, memory: ?, network: ?}/{rows: ? (?), cpu: ?, memory: ?, network: ?}
     └─ CrossJoin
        │   Layout: [a_11:bigint, min:bigint, count_all:bigint, count_non_null:bigint]
        │   Estimates: {rows: ? (?), cpu: ?, memory: ?, network: ?}
        │   Distribution: REPLICATED
        ├─ TableScan[kudu:default.t3, grouped = false]
        │      Layout: [a_11:bigint]
        │      Estimates: {rows: ? (?), cpu: ?, memory: 0B, network: 0B}
        │      a_11 := KuduColumnHandle{name=a, ordinalPosition=0, type=bigint}
        └─ LocalExchange[SINGLE] ()
           │   Layout: [min:bigint, count_all:bigint, count_non_null:bigint]
           │   Estimates: {rows: ? (?), cpu: ?, memory: ?, network: ?}
           └─ RemoteSource[2]
                  Layout: [min:bigint, count_all:bigint, count_non_null:bigint]
```

> IIRC here decorrelation will increase (temporarily) cardinality of probe rows, so it's more complex pattern which is not handled by BeginTableWrite

If an unsupporting to rewrite of the delete table scan is reasonable, the problem would be the error message? The message can be `Only inner join is supported` instead of `Invalid descendant for DeleteNode: io.prestosql.sql.planner.plan.JoinNode` which is confusing.

**Comment by sopel39** [comment]
What is full `EXPLAIN` with all stages?

**Comment by martint** [comment]
This is because we only support very simple plans for Delete due to the constraint that the tablescan and the delete operation need to be in the same “pipeline” (I.e, no exchanges, etc). The query I provided as an example uses are more complex structure due to containing a correlated subquery.
