### ISSUE TITLE
Wrong exception type when units cannot be parsed

### ISSUE THREAD

**Issue by JamesRTaylor** [prestosql/presto#5731]
When attempting to set a session variable with the incorrect units, we get an INTERNAL_ERROR instead of a USER_ERROR. For example:

    SET SESSION query_max_memory='32g'

produces the following exception:

    java.lang.IllegalArgumentException: Unknown unit: g
	at io.airlift.units.DataSize$Unit.fromUnitString(DataSize.java:322)
	at io.airlift.units.DataSize$Unit.access$100(DataSize.java:286)
	at io.airlift.units.DataSize.valueOf(DataSize.java:241)
	at io.prestosql.plugin.base.session.PropertyMetadataUtil.lambda$dataSizeProperty$0(PropertyMetadataUtil.java:35)
	at io.prestosql.spi.session.PropertyMetadata.decode(PropertyMetadata.java:130)
	at io.prestosql.execution.SetSessionTask.execute(SetSessionTask.java:90)
	at io.prestosql.execution.SetSessionTask.execute(SetSessionTask.java:41)
	at io.prestosql.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:167)
	at io.prestosql.execution.SqlQueryManager.createQuery(SqlQueryManager.java:232)
	at io.prestosql.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:132)
	at io.prestosql.$gen.Presto_338_12____20201024_015729_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by endoplasmicR** [comment]
We would expect the exception to be of the `USER_ERROR` type from https://github.com/prestosql/presto/blob/master/presto-spi/src/main/java/io/prestosql/spi/ErrorType.java#L18

**Comment by electrum** [comment]
We should wrap the `decode()` call with a catch block like we do in `SessionPropertyManager` so that it can use the `INVALID_SESSION_PROPERTY` error code.

**Comment by phd3** [comment]
Closed via #5740
