### ISSUE TITLE
Query planning error since Presto 338: "Invalid node. Predicate dependencies ... not in source plan output"

### ISSUE THREAD

**Issue by kongul** [prestosql/presto#5846]
We are updating Presto from version 326 to 345 and found that some of our SQL ETL's are failing.

Let's say we have following table `some_catalog.some_schema.some_table`

| msid | challenge_id |
|---|---|
| 77b652cc-da50-4524-84c2-c0ff0930ee2b  | 1 |
| 77b652cc-da50-4524-84c2-c0ff0930ee2b  | 2 |
| d5b84f9a-c951-4b39-8a15-98d1c5871e07  | 3 |
| d5b84f9a-c951-4b39-8a15-98d1c5871e07  | 4 |
| d282d3aa-0e1f-4bc9-90f5-a1f3606f65e7  | 5 |
| d574723c-4edf-475d-9220-6df029c10609  | 6 |
| 7bbe8d9e-a844-4321-9adb-5f51795cf3fc  | 7 |
| 96314d3f-6d32-4459-b69b-5de06b28d312  | 8 |
| 279d8d60-27d6-468a-a455-45835ddcf85c  | 9 |
| 461f179b-b96d-4125-8e45-b99ec9f93de4  | 10 |

Here's the simplified a lot (but still failing) snipped of that ETL that's failing.
I know that some of the clauses of that snippet may not have sense, but again I simplified it removing a lot of conditions.

```sql
WITH challenges AS (
    SELECT  msid,
            min(challenge_id) as challenge_id
    FROM some_catalog.some_schema.some_table
    WHERE msid = 'd5b84f9a-c951-4b39-8a15-98d1c5871e07'
    GROUP BY 1
)
    SELECT
            a.msid,
            a.challenge_id
    FROM challenges a
    INNER JOIN challenges b
    ON a.msid = b.msid
    AND EXISTS (SELECT * FROM challenges c WHERE b.msid = c.msid)
;
```

And we are getting the following error reproduced on all connectors that we tried:

`Invalid node. Predicate dependencies ([msid_0, msid_4]) not in source plan output ([msid_4])`

And here's the stacktrace:

```
java.lang.IllegalArgumentException: Invalid node. Predicate dependencies ([msid_0, msid_4]) not in source plan output ([msid_4])
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:164)
	at io.prestosql.sql.planner.sanity.ValidateDependenciesChecker.checkDependencies(ValidateDependenciesChecker.java:705)
	at io.prestosql.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitFilter(ValidateDependenciesChecker.java:239)
	at io.prestosql.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitFilter(ValidateDependenciesChecker.java:108)
	at io.prestosql.sql.planner.plan.FilterNode.accept(FilterNode.java:72)
	at io.prestosql.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitProject(ValidateDependenciesChecker.java:257)
	at io.prestosql.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitProject(ValidateDependenciesChecker.java:108)
	at io.prestosql.sql.planner.plan.ProjectNode.accept(ProjectNode.java:82)
	at io.prestosql.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitAggregation(ValidateDependenciesChecker.java:130)
	at io.prestosql.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitAggregation(ValidateDependenciesChecker.java:108)
	at io.prestosql.sql.planner.plan.AggregationNode.accept(AggregationNode.java:203)
	at io.prestosql.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitExchange(ValidateDependenciesChecker.java:537)
	at io.prestosql.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitExchange(ValidateDependenciesChecker.java:108)
	at io.prestosql.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:243)
	at io.prestosql.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitExchange(ValidateDependenciesChecker.java:537)
	at io.prestosql.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitExchange(ValidateDependenciesChecker.java:108)
	at io.prestosql.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:243)
	at io.prestosql.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitAggregation(ValidateDependenciesChecker.java:130)
	at io.prestosql.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitAggregation(ValidateDependenciesChecker.java:108)
	at io.prestosql.sql.planner.plan.AggregationNode.accept(AggregationNode.java:203)
	at io.prestosql.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitExchange(ValidateDependenciesChecker.java:537)
	at io.prestosql.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitExchange(ValidateDependenciesChecker.java:108)
	at io.prestosql.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:243)
	at io.prestosql.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitFilter(ValidateDependenciesChecker.java:233)
	at io.prestosql.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitFilter(ValidateDependenciesChecker.java:108)
	at io.prestosql.sql.planner.plan.FilterNode.accept(FilterNode.java:72)
	at io.prestosql.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitProject(ValidateDependenciesChecker.java:257)
	at io.prestosql.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitProject(ValidateDependenciesChecker.java:108)
	at io.prestosql.sql.planner.plan.ProjectNode.accept(ProjectNode.java:82)
	at io.prestosql.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitExchange(ValidateDependenciesChecker.java:537)
	at io.prestosql.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitExchange(ValidateDependenciesChecker.java:108)
	at io.prestosql.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:243)
	at io.prestosql.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitExchange(ValidateDependenciesChecker.java:537)
	at io.prestosql.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitExchange(ValidateDependenciesChecker.java:108)
	at io.prestosql.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:243)
	at io.prestosql.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitJoin(ValidateDependenciesChecker.java:355)
	at io.prestosql.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitJoin(ValidateDependenciesChecker.java:108)
	at io.prestosql.sql.planner.plan.JoinNode.accept(JoinNode.java:320)
	at io.prestosql.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitExchange(ValidateDependenciesChecker.java:537)
	at io.prestosql.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitExchange(ValidateDependenciesChecker.java:108)
	at io.prestosql.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:243)
	at io.prestosql.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitOutput(ValidateDependenciesChecker.java:307)
	at io.prestosql.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitOutput(ValidateDependenciesChecker.java:108)
	at io.prestosql.sql.planner.plan.OutputNode.accept(OutputNode.java:83)
	at io.prestosql.sql.planner.sanity.ValidateDependenciesChecker.validate(ValidateDependenciesChecker.java:105)
	at io.prestosql.sql.planner.sanity.ValidateDependenciesChecker.validate(ValidateDependenciesChecker.java:100)
	at io.prestosql.sql.planner.sanity.PlanSanityChecker.lambda$validateFinalPlan$0(PlanSanityChecker.java:73)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:405)
	at io.prestosql.sql.planner.sanity.PlanSanityChecker.validateFinalPlan(PlanSanityChecker.java:73)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:213)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:195)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:190)
	at io.prestosql.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:444)
	at io.prestosql.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:424)
	at io.prestosql.execution.SqlQueryExecution.start(SqlQueryExecution.java:376)
	at io.prestosql.execution.SqlQueryManager.createQuery(SqlQueryManager.java:245)
	at io.prestosql.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:132)
	at io.prestosql.$gen.Presto_345____20201105_125003_1.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by sopel39** [comment]
cc @martint

**Comment by findepi** [comment]
Reproducible with:

```
CREATE TABLE memory.default.some_table(msid varchar, challenge_id bigint);

WITH challenges AS (
    SELECT msid, min(challenge_id) as challenge_id
    FROM memory.default.some_table
    GROUP BY 1
)
SELECT a.msid
FROM challenges a
JOIN challenges b ON a.msid = b.msid
AND EXISTS (SELECT * FROM challenges c WHERE b.msid = c.msid);
```

**Comment by findepi** [comment]
This is a regression between 337 and 338.

**Comment by kasiafi** [comment]
A fix is ready. I'll post a PR as soon as I add tests.
