### ISSUE TITLE
Query planning error: "Compiler failed - IllegalArgumentException: bad parameter count 256"

### ISSUE THREAD

**Issue by kongul** [prestosql/presto#5855]
Hello we are updating Presto from version 326 to 345 and found that some of our SQL ETL's started to fail.

We have a script with `with` clause and bunch of aggregation in it, the se do a select from some table an do a `cross join` with result of `unnest` function call

```sql
with table_a as(...)
select ...
    from table_a
    inner join
    unnest(
        array[128+ string literal elements],
        array[128+ aggregation columns from table_a]
    ) table_b (key, value)
```

We get following error:

```java
io.prestosql.spi.PrestoException: Compiler failed
Caused by: com.google.common.util.concurrent.UncheckedExecutionException
Caused by: java.lang.IllegalArgumentException: bad parameter count 256
```

If we are passing less arguments to unnest all works fine:
```sql
unnest(
    array[127 string literal elements],
    array[127 aggregation columns from table_a]
)
```
Is it expected behaviour or it's bug?

Here's the full stacktrace:
```
io.prestosql.spi.PrestoException: Compiler failed
	at io.prestosql.sql.planner.LocalExecutionPlanner$Visitor.visitScanFilterAndProject(LocalExecutionPlanner.java:1362)
	at io.prestosql.sql.planner.LocalExecutionPlanner$Visitor.visitProject(LocalExecutionPlanner.java:1241)
	at io.prestosql.sql.planner.LocalExecutionPlanner$Visitor.visitProject(LocalExecutionPlanner.java:743)
	at io.prestosql.sql.planner.plan.ProjectNode.accept(ProjectNode.java:82)
	at io.prestosql.sql.planner.LocalExecutionPlanner$Visitor.createLocalExchange(LocalExecutionPlanner.java:2685)
	at io.prestosql.sql.planner.LocalExecutionPlanner$Visitor.visitExchange(LocalExecutionPlanner.java:2602)
	at io.prestosql.sql.planner.LocalExecutionPlanner$Visitor.visitExchange(LocalExecutionPlanner.java:743)
	at io.prestosql.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:243)
	at io.prestosql.sql.planner.LocalExecutionPlanner$Visitor.visitUnnest(LocalExecutionPlanner.java:1444)
	at io.prestosql.sql.planner.LocalExecutionPlanner$Visitor.visitUnnest(LocalExecutionPlanner.java:743)
	at io.prestosql.sql.planner.plan.UnnestNode.accept(UnnestNode.java:133)
	at io.prestosql.sql.planner.LocalExecutionPlanner$Visitor.visitLimit(LocalExecutionPlanner.java:1096)
	at io.prestosql.sql.planner.LocalExecutionPlanner$Visitor.visitLimit(LocalExecutionPlanner.java:743)
	at io.prestosql.sql.planner.plan.LimitNode.accept(LimitNode.java:109)
	at io.prestosql.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:478)
	at io.prestosql.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:400)
	at io.prestosql.execution.SqlTaskExecutionFactory.create(SqlTaskExecutionFactory.java:84)
	at io.prestosql.execution.SqlTask.updateTask(SqlTask.java:418)
	at io.prestosql.execution.SqlTaskManager.updateTask(SqlTaskManager.java:394)
	at io.prestosql.server.TaskResource.createOrUpdateTask(TaskResource.java:132)
	at jdk.internal.reflect.GeneratedMethodAccessor716.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:755)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1617)
	at io.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
	at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:51)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:717)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1300)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1215)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: bad parameter count 256
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
	at io.prestosql.sql.gen.PageFunctionCompiler.compileProjection(PageFunctionCompiler.java:169)
	at io.prestosql.sql.gen.ExpressionCompiler.lambda$compilePageProcessor$3(ExpressionCompiler.java:107)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.prestosql.sql.gen.ExpressionCompiler.compilePageProcessor(ExpressionCompiler.java:108)
	at io.prestosql.sql.gen.ExpressionCompiler.compilePageProcessor(ExpressionCompiler.java:96)
	at io.prestosql.sql.planner.LocalExecutionPlanner$Visitor.visitScanFilterAndProject(LocalExecutionPlanner.java:1345)
	... 81 more
Caused by: java.lang.IllegalArgumentException: bad parameter count 256
	at java.base/java.lang.invoke.MethodHandleStatics.newIllegalArgumentException(MethodHandleStatics.java:123)
	at java.base/java.lang.invoke.MethodType.checkSlotCount(MethodType.java:180)
	at java.base/java.lang.invoke.MethodType.checkPtypes(MethodType.java:170)
	at java.base/java.lang.invoke.MethodType.makeImpl(MethodType.java:307)
	at java.base/java.lang.invoke.LambdaForm.methodType(LambdaForm.java:655)
	at java.base/java.lang.invoke.LambdaForm.compileToBytecode(LambdaForm.java:868)
	at java.base/java.lang.invoke.LambdaForm.prepare(LambdaForm.java:829)
	at java.base/java.lang.invoke.MethodHandle.<init>(MethodHandle.java:468)
	at java.base/java.lang.invoke.BoundMethodHandle.<init>(BoundMethodHandle.java:54)
	at java.base/java.lang.invoke.BoundMethodHandle$Species_LLLLLLL.<init>(java/lang/invoke/BoundMethodHandle$Species_LLLLLLL)
	at java.base/java.lang.invoke.BoundMethodHandle$Species_LLLLLLL.make(java/lang/invoke/BoundMethodHandle$Species_LLLLLLL)
	at java.base/java.lang.invoke.BoundMethodHandle$Species_LLLLLL.copyWithExtendL(java/lang/invoke/BoundMethodHandle$Species_LLLLLL)
	at java.base/java.lang.invoke.MethodHandles.collectArguments(MethodHandles.java:4033)
	at io.prestosql.spi.function.ScalarFunctionAdapter.adaptParameter(ScalarFunctionAdapter.java:465)
	at io.prestosql.spi.function.ScalarFunctionAdapter.adapt(ScalarFunctionAdapter.java:221)
	at io.prestosql.operator.scalar.ChoicesScalarFunctionImplementation.getScalarFunctionInvoker(ChoicesScalarFunctionImplementation.java:119)
	at io.prestosql.metadata.FunctionRegistry.getScalarFunctionInvoker(FunctionRegistry.java:855)
	at io.prestosql.metadata.MetadataManager.getScalarFunctionInvoker(MetadataManager.java:1873)
	at io.prestosql.sql.gen.BytecodeUtils.lambda$generateFullInvocation$3(BytecodeUtils.java:228)
	at io.prestosql.sql.gen.BytecodeUtils.generateFullInvocation(BytecodeUtils.java:270)
	at io.prestosql.sql.gen.BytecodeUtils.generateFullInvocation(BytecodeUtils.java:225)
	at io.prestosql.sql.gen.BytecodeGeneratorContext.generateFullCall(BytecodeGeneratorContext.java:102)
	at io.prestosql.sql.gen.RowExpressionCompiler$Visitor.visitCall(RowExpressionCompiler.java:93)
	at io.prestosql.sql.gen.RowExpressionCompiler$Visitor.visitCall(RowExpressionCompiler.java:80)
	at io.prestosql.sql.relational.CallExpression.accept(CallExpression.java:86)
	at io.prestosql.sql.gen.RowExpressionCompiler.compile(RowExpressionCompiler.java:77)
	at io.prestosql.sql.gen.RowExpressionCompiler.compile(RowExpressionCompiler.java:72)
	at io.prestosql.sql.gen.PageFunctionCompiler.generateEvaluateMethod(PageFunctionCompiler.java:361)
	at io.prestosql.sql.gen.PageFunctionCompiler.definePageProjectWorkClass(PageFunctionCompiler.java:245)
	at io.prestosql.sql.gen.PageFunctionCompiler.compileProjectionInternal(PageFunctionCompiler.java:193)
	at io.prestosql.sql.gen.PageFunctionCompiler.lambda$new$0(PageFunctionCompiler.java:127)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	... 97 more

```

**Comment by sopel39** [comment]
cc @dain

**Comment by findepi** [comment]
@kongul thanks for reporting this!

> Hello we are updating Presto from version 326 to 345 and found that some of our SQL ETL's started to fail.

would you be able to bisect to narrow down the range?
eg using https://hub.docker.com/r/prestosql/presto/tags you may be able to narrow this down to single version
(this is what i did in here: https://github.com/prestosql/presto/issues/5846#issuecomment-722673124)
