### ISSUE TITLE
Flaky test TestEventListener.testKilledWhileWaitingForResources

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#5928]
https://github.com/prestosql/presto/runs/1385901561

```
2020-11-11T16:16:42.0237888Z [ERROR] Tests run: 2082, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 2,286.857 s <<< FAILURE! - in TestSuite
2020-11-11T16:16:42.0239426Z [ERROR] testKilledWhileWaitingForResources(io.prestosql.execution.TestEventListener)  Time elapsed: 0.795 s  <<< FAILURE!
2020-11-11T16:16:42.0240818Z java.util.NoSuchElementException
2020-11-11T16:16:42.0242443Z 	at com.google.common.collect.AbstractIndexedListIterator.next(AbstractIndexedListIterator.java:75)
2020-11-11T16:16:42.0244465Z 	at com.google.common.collect.Iterators.getOnlyElement(Iterators.java:301)
2020-11-11T16:16:42.0246034Z 	at com.google.common.collect.Iterables.getOnlyElement(Iterables.java:254)
2020-11-11T16:16:42.0247891Z 	at io.prestosql.execution.TestEventListener.assertFailedQuery(TestEventListener.java:243)
2020-11-11T16:16:42.0250604Z 	at io.prestosql.execution.TestEventListener.testKilledWhileWaitingForResources(TestEventListener.java:201)
2020-11-11T16:16:42.0252772Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-11-11T16:16:42.0254467Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-11-11T16:16:42.0256445Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-11-11T16:16:42.0258160Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-11-11T16:16:42.0260055Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-11-11T16:16:42.0262144Z 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
2020-11-11T16:16:42.0263908Z 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
2020-11-11T16:16:42.0265425Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2020-11-11T16:16:42.0266674Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2020-11-11T16:16:42.0268241Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-11-11T16:16:42.0270032Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-11-11T16:16:42.0271212Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-11-11T16:16:42.0274906Z 
```

**Comment by findepi** [comment]
cc @losipiuk

**Comment by findepi** [comment]
https://github.com/prestosql/presto/runs/1390098426

**Comment by losipiuk** [comment]
Fixed by https://github.com/prestosql/presto/pull/5944
