### ISSUE TITLE
 Support Hive VIEW with translate() function call

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#5975]
```
0: jdbc:hive2://localhost:10000/default> CREATE VIEW v AS SELECT translate(name, 'AN', 'xy') FROM nation WHERE nationkey < 5;
No rows affected (0.591 seconds)

0: jdbc:hive2://localhost:10000/default> SELECT * FROM v;
+------------+--+
|   v._c0    |
+------------+--+
| xLGERIx    |
| xRGEyTIyx  |
| BRxZIL     |
| CxyxDx     |
| EGYPT      |
+------------+--+
```

```
presto:default> SELECT * FROM v;
Query 20201116_154927_00006_jfdaf failed: Failed to translate Hive view 'default.v': class org.apache.calcite.sql.fun.SqlConvertFunction: TRANSLATE
io.prestosql.spi.PrestoException: Failed to translate Hive view 'default.v': class org.apache.calcite.sql.fun.SqlConvertFunction: TRANSLATE
	at io.prestosql.plugin.hive.ViewReaderUtil$HiveViewReader.decodeViewData(ViewReaderUtil.java:180)
	at io.prestosql.plugin.hive.HiveMetadata.lambda$getView$57(HiveMetadata.java:1934)
	at java.base/java.util.Optional.map(Optional.java:265)
	at io.prestosql.plugin.hive.HiveMetadata.getView(HiveMetadata.java:1928)
	at io.prestosql.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getView(ClassLoaderSafeConnectorMetadata.java:522)
	at io.prestosql.metadata.MetadataManager.getView(MetadataManager.java:1095)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1209)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:324)
	at io.prestosql.sql.tree.Table.accept(Table.java:53)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:341)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:2510)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1532)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:324)
	at io.prestosql.sql.tree.QuerySpecification.accept(QuerySpecification.java:144)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:341)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:351)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1055)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:324)
	at io.prestosql.sql.tree.Query.accept(Query.java:107)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:341)
	at io.prestosql.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:310)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:75)
	at io.prestosql.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:257)
	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:183)
	at io.prestosql.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:759)
	at io.prestosql.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:122)
	at io.prestosql.$gen.Presto_346_65_g5309ce1____20201116_154441_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.UnsupportedOperationException: class org.apache.calcite.sql.fun.SqlConvertFunction: TRANSLATE
	at org.apache.calcite.util.Util.needToImplement(Util.java:967)
	at org.apache.calcite.sql.SqlOperator.getOperandCountRange(SqlOperator.java:201)
	at org.apache.calcite.sql.SqlUtil.lambda$filterRoutinesByParameterCount$2(SqlUtil.java:574)
	at com.linkedin.coral.com.google.common.collect.Iterators$7.computeNext(Iterators.java:675)
	at com.linkedin.coral.com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.linkedin.coral.com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.linkedin.coral.com.google.common.collect.Iterators$7.computeNext(Iterators.java:673)
	at com.linkedin.coral.com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.linkedin.coral.com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.linkedin.coral.com.google.common.collect.Iterators$7.computeNext(Iterators.java:673)
	at com.linkedin.coral.com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.linkedin.coral.com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.linkedin.coral.com.google.common.collect.Iterators.addAll(Iterators.java:364)
	at com.linkedin.coral.com.google.common.collect.Lists.newArrayList(Lists.java:162)
	at org.apache.calcite.sql.SqlUtil.lookupSubjectRoutines(SqlUtil.java:505)
	at org.apache.calcite.sql.SqlUtil.lookupRoutine(SqlUtil.java:434)
	at org.apache.calcite.sql.SqlFunction.deriveType(SqlFunction.java:238)
	at org.apache.calcite.sql.SqlFunction.deriveType(SqlFunction.java:216)
	at org.apache.calcite.sql.validate.SqlValidatorImpl$DeriveTypeVisitor.visit(SqlValidatorImpl.java:5626)
	at org.apache.calcite.sql.validate.SqlValidatorImpl$DeriveTypeVisitor.visit(SqlValidatorImpl.java:5613)
	at org.apache.calcite.sql.SqlCall.accept(SqlCall.java:139)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.deriveTypeImpl(SqlValidatorImpl.java:1688)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.deriveType(SqlValidatorImpl.java:1673)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.expandSelectItem(SqlValidatorImpl.java:476)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelectList(SqlValidatorImpl.java:4104)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3392)
	at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:60)
	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1005)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:965)
	at org.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:216)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:940)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:647)
	at com.linkedin.coral.hive.hive2rel.HiveSqlToRelConverter.convertQuery(HiveSqlToRelConverter.java:58)
	at com.linkedin.coral.hive.hive2rel.HiveToRelConverter.toRel(HiveToRelConverter.java:126)
	at com.linkedin.coral.hive.hive2rel.HiveToRelConverter.convertView(HiveToRelConverter.java:108)
	at io.prestosql.plugin.hive.ViewReaderUtil$HiveViewReader.decodeViewData(ViewReaderUtil.java:161)
	... 36 more
```

**Comment by findepi** [comment]
cc @laurachenyu @phd3 @wmoustafa

**Comment by findepi** [comment]
@ebyhr posted a fix https://github.com/linkedin/coral/pull/23

Before we close this issue, I'd want to have an integration test on Presto side too.
