### ISSUE TITLE
Cassandra timeout during read query at consistency ONE or LOCAL_ONE

### ISSUE THREAD

**Issue by ChethanUK** [prestosql/presto#608]
PrestoSQL Version: 307
Cqlsh 5.0.1 | Cassandra 3.11.4 | CQL spec 3.4.4 | Native protocol v4

Basic Queries like `select * from table limit 10;` working properly..

But, When I try queries like `select count(*) from table;`
I get following error:
```
Query 20190409_080644_00010_cuncv, FAILED, 1 node
Splits: 201 total, 93 done (46.27%)
0:11 [238K rows, 232KB] [21.2K rows/s, 20.7KB/s]

Query 20190409_080644_00010_cuncv failed: Cassandra timeout during read query at consistency LOCAL_ONE (1 responses were required but only 0 replica responded)
```

**Comment by ebyhr** [comment]
This issue might be related https://github.com/prestodb/presto/issues/10021

**Comment by chethanu** [comment]
> * If the query `select count(*) from table` succeeds on cassandra without presto

No it won't.

**Comment by codekaust** [comment]
Hey @ChethanUK 
Could you solve this issue?

I am facing similar error:
```
Query 20200610_063215_00072_ggkdy failed: Cassandra timeout during read query at consistency ONE (1 responses were required but only 0 replica responded)
com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency ONE (1 responses were required but only 0 replica responded)
        at com.datastax.driver.core.exceptions.ReadTimeoutException.copy(ReadTimeoutException.java:88)
        at com.datastax.driver.core.exceptions.ReadTimeoutException.copy(ReadTimeoutException.java:25)
        at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
        at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245)
        at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:68)
        at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:51)
        at com.facebook.presto.cassandra.NativeCassandraSession.lambda$execute$8(NativeCassandraSession.java:426)
        at com.facebook.presto.cassandra.NativeCassandraSession.executeWithSession(NativeCassandraSession.java:536)
        at com.facebook.presto.cassandra.NativeCassandraSession.execute(NativeCassandraSession.java:426)
        at com.facebook.presto.cassandra.CassandraRecordCursor.<init>(CassandraRecordCursor.java:39)
        at com.facebook.presto.cassandra.CassandraRecordSet.cursor(CassandraRecordSet.java:54)
        at com.facebook.presto.spi.RecordPageSource.<init>(RecordPageSource.java:37)
        at com.facebook.presto.split.RecordPageSourceProvider.createPageSource(RecordPageSourceProvider.java:42)
        at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:56)
        at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:239)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
        at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
        at com.facebook.presto.$gen.Presto_0_220____20200610_062227_1.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency ONE (1 responses were required but only 0 replica responded)
        at com.datastax.driver.core.exceptions.ReadTimeoutException.copy(ReadTimeoutException.java:115)
        at com.datastax.driver.core.Responses$Error.asException(Responses.java:124)
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:506)
        at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1070)
        at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:993)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1280)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:890)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:564)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:505)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:419)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:391)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
        ... 1 more
Caused by: com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency ONE (1 responses were required but only 0 replica responded)
        at com.datastax.driver.core.Responses$Error$1.decode(Responses.java:62)
        at com.datastax.driver.core.Responses$Error$1.decode(Responses.java:37)
        at com.datastax.driver.core.Message$ProtocolDecoder.decode(Message.java:289)
        at com.datastax.driver.core.Message$ProtocolDecoder.decode(Message.java:269)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
        ... 20 more

```

**Comment by findepi** [comment]
@codekaust did you try setting eg 

```
cassandra.client.connect-timeout=1m
cassandra.client.read-timeout=1m
```

can you also try it out with Presto 334 release (https://prestosql.io/download.html)?

**Comment by codekaust** [comment]
> @codekaust did you try setting eg
> 
> ```
> cassandra.client.connect-timeout=1m
> cassandra.client.read-timeout=1m
> ```
> 
> can you also try it out with Presto 334 release (https://prestosql.io/download.html)?

Yes @findepi 
In-fact I set it to 15m, but instantly on running the query, it gives me the error
So do you think, that can be a solution

**Comment by findepi** [comment]
Can you share the stacktrace you are getting when running Presto 334?

**Comment by cjimti** [comment]
This might also be related, I get: `Error: Cassandra timeout during read query at consistency ONE (1 responses were required but only 0 replica responded)` on all queries after Trino has been running for a few hours. If I restart Trino this resolves. At this point I have Trino set to restart ever 4 hours until we can figure it out. I have both timeouts set to 20m but essentially all queries through Trino fail with error above after a time until a restart. 

```
  cassandra.properties: |-
    connector.name=cassandra
    cassandra.contact-points=[REDACTED]
    cassandra.native-protocol-port=9042
    cassandra.allow-drop-table=false
    cassandra.protocol-version=V4
    cassandra.consistency-level=ONE
    cassandra.username=[REDACTED]
    cassandra.password=[REDACTED]
    cassandra.client.connect-timeout=20m
    cassandra.client.read-timeout=20m
    cassandra.retry-policy=BACKOFF
    cassandra.load-policy.use-token-aware=true
    cassandra.client.so-linger=0
```
