### ISSUE TITLE
TestSyncPartitionMetadata.testConflictingMixedCasePartitionNames is flaky

### ISSUE THREAD

**Issue by kokosing** [prestosql/presto#6118]
```
2020-11-27T10:58:27.4275896Z tests               | 2020-11-27 16:43:27 INFO: FAILURE     /    io.prestosql.tests.hive.TestSyncPartitionMetadata.testConflictingMixedCasePartitionNames (Groups: smoke, hive_partitioning) took 0.4 seconds
2020-11-27T10:58:27.4372323Z tests               | 2020-11-27 16:43:27 SEVERE: Failure cause:
2020-11-27T10:58:27.4374034Z tests               | io.prestosql.tempto.query.QueryExecutionException: java.sql.SQLException: Query failed (#20201127_105827_01810_dvwkt): Error committing write to Hive
2020-11-27T10:58:27.4376454Z tests               | 	at io.prestosql.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:119)
2020-11-27T10:58:27.4379000Z tests               | 	at io.prestosql.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
2020-11-27T10:58:27.4381062Z tests               | 	at io.prestosql.tempto.query.QueryExecutor.query(QueryExecutor.java:57)
2020-11-27T10:58:27.4383266Z tests               | 	at io.prestosql.tests.hive.TestSyncPartitionMetadata.prepare(TestSyncPartitionMetadata.java:140)
2020-11-27T10:58:27.4387024Z tests               | 	at io.prestosql.tests.hive.TestSyncPartitionMetadata.testConflictingMixedCasePartitionNames(TestSyncPartitionMetadata.java:120)
2020-11-27T10:58:27.4390602Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-11-27T10:58:27.4392872Z tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-11-27T10:58:27.4395516Z tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-11-27T10:58:27.4397499Z tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-11-27T10:58:27.4399295Z tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-11-27T10:58:27.4401437Z tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-11-27T10:58:27.4402914Z tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-11-27T10:58:27.4404653Z tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-11-27T10:58:27.4406786Z tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-11-27T10:58:27.4408876Z tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-11-27T10:58:27.4411001Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-11-27T10:58:27.4413136Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-11-27T10:58:27.4414536Z tests               | 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-11-27T10:58:27.4415594Z tests               | Caused by: java.sql.SQLException: Query failed (#20201127_105827_01810_dvwkt): Error committing write to Hive
2020-11-27T10:58:27.4417630Z tests               | 	at io.prestosql.jdbc.AbstractPrestoResultSet.resultsException(AbstractPrestoResultSet.java:1777)
2020-11-27T10:58:27.4420145Z tests               | 	at io.prestosql.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:218)
2020-11-27T10:58:27.4422297Z tests               | 	at io.prestosql.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:178)
2020-11-27T10:58:27.4424751Z tests               | 	at io.prestosql.jdbc.$internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
2020-11-27T10:58:27.4427265Z tests               | 	at io.prestosql.jdbc.$internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
2020-11-27T10:58:27.4429255Z tests               | 	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
2020-11-27T10:58:27.4431374Z tests               | 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
2020-11-27T10:58:27.4433967Z tests               | 	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
2020-11-27T10:58:27.4436529Z tests               | 	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
2020-11-27T10:58:27.4438934Z tests               | 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
2020-11-27T10:58:27.4440685Z tests               | 	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
2020-11-27T10:58:27.4442242Z tests               | 	at io.prestosql.jdbc.PrestoResultSet$AsyncIterator.lambda$new$0(PrestoResultSet.java:124)
2020-11-27T10:58:27.4481135Z tests               | 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
2020-11-27T10:58:27.4482222Z tests               | 	... 3 more
2020-11-27T10:58:27.4483594Z tests               | 	Suppressed: java.lang.Exception: Query: INSERT INTO test_sync_partition_mixed_case VALUES (1, 'a', '1'), (2, 'b', '2')
2020-11-27T10:58:27.4485625Z tests               | 		at io.prestosql.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:136)
2020-11-27T10:58:27.4488454Z tests               | 		at io.prestosql.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:112)
2020-11-27T10:58:27.4490923Z tests               | 		at io.prestosql.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
2020-11-27T10:58:27.4493167Z tests               | 		at io.prestosql.tempto.query.QueryExecutor.query(QueryExecutor.java:57)
2020-11-27T10:58:27.4495548Z tests               | 		at io.prestosql.tests.hive.TestSyncPartitionMetadata.prepare(TestSyncPartitionMetadata.java:140)
2020-11-27T10:58:27.4499889Z tests               | 		at io.prestosql.tests.hive.TestSyncPartitionMetadata.testConflictingMixedCasePartitionNames(TestSyncPartitionMetadata.java:120)
2020-11-27T10:58:27.4503707Z tests               | 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-11-27T10:58:27.4506163Z tests               | 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-11-27T10:58:27.4509006Z tests               | 		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-11-27T10:58:27.4511252Z tests               | 		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-11-27T10:58:27.4513227Z tests               | 		at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-11-27T10:58:27.4515317Z tests               | 		at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-11-27T10:58:27.4516916Z tests               | 		at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-11-27T10:58:27.4518639Z tests               | 		at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-11-27T10:58:27.4520717Z tests               | 		at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-11-27T10:58:27.4522810Z tests               | 		at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-11-27T10:58:27.4523966Z tests               | 		... 3 more
2020-11-27T10:58:27.4524871Z tests               | Caused by: io.prestosql.spi.PrestoException: Error committing write to Hive
2020-11-27T10:58:27.4526547Z tests               | 	at io.prestosql.plugin.hive.orc.OrcFileWriter.commit(OrcFileWriter.java:189)
2020-11-27T10:58:27.4528386Z tests               | 	at io.prestosql.plugin.hive.HiveWriter.commit(HiveWriter.java:86)
2020-11-27T10:58:27.4530154Z tests               | 	at io.prestosql.plugin.hive.HivePageSink.doFinish(HivePageSink.java:190)
2020-11-27T10:58:27.4532677Z tests               | 	at io.prestosql.plugin.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
2020-11-27T10:58:27.4535196Z tests               | 	at io.prestosql.plugin.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:96)
2020-11-27T10:58:27.4537031Z tests               | 	at io.prestosql.plugin.hive.HivePageSink.finish(HivePageSink.java:181)
2020-11-27T10:58:27.4540147Z tests               | 	at io.prestosql.plugin.base.classloader.ClassLoaderSafeConnectorPageSink.finish(ClassLoaderSafeConnectorPageSink.java:77)
2020-11-27T10:58:27.4543508Z tests               | 	at io.prestosql.operator.TableWriterOperator.finish(TableWriterOperator.java:208)
2020-11-27T10:58:27.4545451Z tests               | 	at io.prestosql.operator.Driver.processInternal(Driver.java:397)
2020-11-27T10:58:27.4547046Z tests               | 	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
2020-11-27T10:58:27.4548491Z tests               | 	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
2020-11-27T10:58:27.4549954Z tests               | 	at io.prestosql.operator.Driver.processFor(Driver.java:276)
2020-11-27T10:58:27.4551808Z tests               | 	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
2020-11-27T10:58:27.4554495Z tests               | 	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
2020-11-27T10:58:27.4557051Z tests               | 	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
2020-11-27T10:58:27.4558459Z tests               | 	at io.prestosql.$gen.Presto_5943678____20201127_103937_2.run(Unknown Source)
2020-11-27T10:58:27.4560024Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-11-27T10:58:27.4562135Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-11-27T10:58:27.4564847Z tests               | 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-11-27T10:58:27.4567685Z tests               | Caused by: org.apache.hadoop.ipc.RemoteException: File /tmp/presto-hive/5ed82880-84f0-41d5-a814-751d4aa4a2dd/col_x=a/col_y=1/20201127_105827_01810_dvwkt_65ebcad4-8b08-4ec7-b364-09e684e68d9b could only be replicated to 0 nodes instead of minReplication (=1).  There are 1 datanode(s) running and no node(s) are excluded in this operation.
2020-11-27T10:58:27.4571437Z tests               | 	at org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.chooseTarget4NewBlock(BlockManager.java:1719)
2020-11-27T10:58:27.4575251Z tests               | 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:3508)
2020-11-27T10:58:27.4578425Z tests               | 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:694)
2020-11-27T10:58:27.4582897Z tests               | 	at org.apache.hadoop.hdfs.server.namenode.AuthorizationProviderProxyClientProtocol.addBlock(AuthorizationProviderProxyClientProtocol.java:219)
2020-11-27T10:58:27.4588794Z tests               | 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:507)
2020-11-27T10:58:27.4593981Z tests               | 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
2020-11-27T10:58:27.4597129Z tests               | 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:617)
2020-11-27T10:58:27.4598749Z tests               | 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1073)
2020-11-27T10:58:27.4599842Z tests               | 	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2281)
2020-11-27T10:58:27.4600996Z tests               | 	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2277)
2020-11-27T10:58:27.4602395Z tests               | 	at java.security.AccessController.doPrivileged(Native Method)
2020-11-27T10:58:27.4603945Z tests               | 	at javax.security.auth.Subject.doAs(Subject.java:422)
2020-11-27T10:58:27.4605766Z tests               | 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1924)
2020-11-27T10:58:27.4607547Z tests               | 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2275)
2020-11-27T10:58:27.4608322Z tests               | 
2020-11-27T10:58:27.4609337Z tests               | 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1511)
2020-11-27T10:58:27.4610743Z tests               | 	at org.apache.hadoop.ipc.Client.call(Client.java:1457)
2020-11-27T10:58:27.4611952Z tests               | 	at org.apache.hadoop.ipc.Client.call(Client.java:1367)
2020-11-27T10:58:27.4613493Z tests               | 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:228)
2020-11-27T10:58:27.4615412Z tests               | 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116)
2020-11-27T10:58:27.4616790Z tests               | 	at com.sun.proxy.$Proxy241.addBlock(Unknown Source)
2020-11-27T10:58:27.4619521Z tests               | 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.addBlock(ClientNamenodeProtocolTranslatorPB.java:513)
2020-11-27T10:58:27.4622932Z tests               | 	at jdk.internal.reflect.GeneratedMethodAccessor396.invoke(Unknown Source)
2020-11-27T10:58:27.4625557Z tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-11-27T10:58:27.4627714Z tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-11-27T10:58:27.4629822Z tests               | 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
2020-11-27T10:58:27.4632692Z tests               | 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
2020-11-27T10:58:27.4635140Z tests               | 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
2020-11-27T10:58:27.4637587Z tests               | 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
2020-11-27T10:58:27.4640142Z tests               | 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
2020-11-27T10:58:27.4641918Z tests               | 	at com.sun.proxy.$Proxy242.addBlock(Unknown Source)
2020-11-27T10:58:27.4643583Z tests               | 	at org.apache.hadoop.hdfs.DFSOutputStream.addBlock(DFSOutputStream.java:1081)
2020-11-27T10:58:27.4645833Z tests               | 	at org.apache.hadoop.hdfs.DataStreamer.locateFollowingBlock(DataStreamer.java:1865)
2020-11-27T10:58:27.4648305Z tests               | 	at org.apache.hadoop.hdfs.DataStreamer.nextBlockOutputStream(DataStreamer.java:1668)
2020-11-27T10:58:27.4650346Z tests               | 	at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:716)
2020-11-27T10:58:27.4651299Z tests               | 
```

**Comment by findepi** [comment]
dups https://github.com/prestosql/presto/issues/4936

**Comment by findepi** [comment]
https://github.com/prestosql/presto/pull/6123
