### ISSUE TITLE
Iceberg catalog: connecting to Google Cloud Storage produced error

### ISSUE THREAD

**Issue by nautilus28** [prestosql/presto#6170]
The [documentation](https://prestosql.io/docs/current/connector/iceberg.html) says that **Iceberg supports the same metastore configuration properties as the Hive connector.** However, when I provide the catalog `iceberg.properties` with

`connector.name=iceberg`
`hive.metastore.uri=thrift://hive-metastore:9083`
`hive.gcs.json-key-file-path=/gcs_keyfile.json`

I got the following error:

```
ERROR	main	io.prestosql.server.Server	Configuration errors:

1) Error: Configuration property 'hive.gcs.json-key-file-path' was not used

1 error
io.airlift.bootstrap.ApplicationConfigurationException: Configuration errors:

1) Error: Configuration property 'hive.gcs.json-key-file-path' was not used

1 error
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:239)
	at io.prestosql.plugin.iceberg.InternalIcebergConnectorFactory.createConnector(InternalIcebergConnectorFactory.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.prestosql.plugin.iceberg.IcebergConnectorFactory.create(IcebergConnectorFactory.java:42)
	at io.prestosql.connector.ConnectorManager.createConnector(ConnectorManager.java:353)
	at io.prestosql.connector.ConnectorManager.createCatalog(ConnectorManager.java:212)
	at io.prestosql.connector.ConnectorManager.createCatalog(ConnectorManager.java:204)
	at io.prestosql.connector.ConnectorManager.createCatalog(ConnectorManager.java:190)
	at io.prestosql.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:88)
	at io.prestosql.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
	at io.prestosql.server.Server.doStart(Server.java:119)
	at io.prestosql.server.Server.lambda$start$0(Server.java:73)
	at io.prestosql.$gen.Presto_347____20201201_174408_1.run(Unknown Source)
	at io.prestosql.server.Server.start(Server.java:73)
	at io.prestosql.server.PrestoServer.main(PrestoServer.java:38)
```
I am using Presto version 347.

I am not sure if this is a bug or I've done something wrong, any help or suggestions would be appreciated.

Kind regards,

**Comment by electrum** [comment]
This is a bug. Fixed by https://github.com/prestosql/presto/pull/6186

**Comment by nautilus28** [comment]
Thanks @electrum for the quick fix. Do you have idea when this could be released?

**Comment by electrum** [comment]
@nautilus28 we should be able to merge this for 348, which will be out in the next few days

**Comment by nautilus28** [comment]
Thanks @electrum, I merged the PR and made a custom build. It does fix the issue 👍
