### ISSUE TITLE
Presto JDBC fails to return TIME [TZ] with second fraction equal to or greater than .9999999995

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#6204]
```
java.time.DateTimeException: Invalid value for NanoOfSecond (valid values 0 - 999999999): 1000000000

	at java.base/java.time.temporal.ValueRange.checkValidValue(ValueRange.java:311)
	at java.base/java.time.temporal.ChronoField.checkValidValue(ChronoField.java:717)
	at java.base/java.time.LocalTime.of(LocalTime.java:342)
	at java.base/java.time.LocalDateTime.of(LocalDateTime.java:362)
	at java.base/java.time.ZonedDateTime.of(ZonedDateTime.java:339)
	at io.prestosql.jdbc.AbstractPrestoResultSet.parseTime(AbstractPrestoResultSet.java:1978)
	at io.prestosql.jdbc.AbstractPrestoResultSet.getTime(AbstractPrestoResultSet.java:333)
	at io.prestosql.jdbc.AbstractPrestoResultSet.getTime(AbstractPrestoResultSet.java:319)
	at io.prestosql.jdbc.PrestoResultSet.getTime(PrestoResultSet.java:43)
	at io.prestosql.jdbc.AbstractPrestoResultSet.getObject(AbstractPrestoResultSet.java:567)
	at io.prestosql.jdbc.PrestoResultSet.getObject(PrestoResultSet.java:43)
```

Rel https://github.com/prestosql/presto/issues/6147

**Comment by findepi** [comment]
TIME fixed in https://github.com/prestosql/presto/pull/6206
TIME WITH TIME ZONE to be fixed.
