### ISSUE TITLE
Flaky TestOAuth2WebUiAuthenticationFilter.testExpiredAccessToken

### ISSUE THREAD

**Issue by kokosing** [prestosql/presto#6233]
```
2020-12-07T16:01:56.0369011Z [ERROR] Tests run: 6832, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,074.834 s <<< FAILURE! - in TestSuite
2020-12-07T16:01:56.0378380Z [ERROR] testExpiredAccessToken(io.prestosql.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter)  Time elapsed: 5.687 s  <<< FAILURE!
2020-12-07T16:01:56.0380753Z java.lang.NullPointerException
2020-12-07T16:01:56.0391942Z 	at io.prestosql.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.lambda$testExpiredAccessToken$1(TestOAuth2WebUiAuthenticationFilter.java:205)
2020-12-07T16:01:56.0401445Z 	at io.prestosql.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.withSuccessfulAuthentication(TestOAuth2WebUiAuthenticationFilter.java:235)
2020-12-07T16:01:56.0409736Z 	at io.prestosql.server.security.oauth2.TestOAuth2WebUiAuthenticationFilter.testExpiredAccessToken(TestOAuth2WebUiAuthenticationFilter.java:204)
2020-12-07T16:01:56.0489972Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-12-07T16:01:56.0493626Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-12-07T16:01:56.0496664Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-12-07T16:01:56.0498972Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-12-07T16:01:56.0501106Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-12-07T16:01:56.0503353Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-12-07T16:01:56.0505057Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-12-07T16:01:56.0506904Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-12-07T16:01:56.0509382Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-12-07T16:01:56.0512401Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-12-07T16:01:56.0515660Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-12-07T16:01:56.0518682Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-12-07T16:01:56.0520944Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-12-07T16:01:56.0522359Z 
2020-12-07T16:01:56.0737430Z 2020-12-07T10:01:56.073-0600	INFO	Thread-72	io.airlift.bootstrap.LifeCycleManager	JVM is shutting down, cleaning up
2020-12-07T16:01:56.0739796Z 2020-12-07T10:01:56.073-0600	INFO	Thread-72	io.airlift.bootstrap.LifeCycleManager	Life cycle stopping...
2020-12-07T16:01:57.3366153Z [INFO] 
2020-12-07T16:01:57.3367016Z [INFO] Results:
2020-12-07T16:01:57.3367620Z [INFO] 
2020-12-07T16:01:57.3368443Z [ERROR] Failures: 
2020-12-07T16:01:57.3371423Z [ERROR]   TestOAuth2WebUiAuthenticationFilter.testExpiredAccessToken:204->withSuccessfulAuthentication:235->lambda$testExpiredAccessToken$1:205 NullPointer
2020-12-07T16:01:57.3379794Z [INFO] 
2020-12-07T16:01:57.3380704Z [ERROR] Tests run: 6832, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by findepi** [comment]
https://github.com/prestosql/presto/issues/6223
