### ISSUE TITLE
Hive Update failure: page doesn't have enough columns

### ISSUE THREAD

**Issue by abhishekkhanna1** [prestosql/presto#6281]
For Hive transactional tables, once the table schema is evolved by adding new columns or by renaming columns. Updates to any pre-existing/non-modified columns of the existing rows fail with the following exception:

```
create table hive.Schema3.testingTable (a int, b int) 
WITH (
	format='ORC',
	transactional=true
);

insert into hive.Schema3.testingTable values (1,100), (2,200);

ALter table hive.Schema3.testingTable ADD COLUMN column3 VARCHAR;

Update hive.Schema3.testingTable set b=1000 where a=1;
```

```
2020-12-09T01:33:41.327-0800	ERROR	SplitRunner-36-1329	io.prestosql.execution.executor.TaskExecutor	Error processing Split 20201209_093337_00109_nk3pw.1.0-0 {path=s3://test-bucket/Schema3/testingtable/delta_0000001_0000001_0000/bucket_00000, start=0, length=738, estimatedFileSize=738, hosts=[], database=Schema3, table=testingtable, forceLocalScheduling=false, partitionName=<UNPARTITIONED>, s3SelectPushdownEnabled=false} (start = 3.2522652626422E7, wall = 371 ms, cpu = 0 ms, wait = 0 ms, calls = 1): HIVE_CURSOR_ERROR: page doesn't have enough columns
io.prestosql.spi.PrestoException: page doesn't have enough columns
	at io.prestosql.plugin.hive.HivePageSource.getNextPage(HivePageSource.java:317)
	at io.prestosql.plugin.hive.HiveUpdatablePageSource.getNextPage(HiveUpdatablePageSource.java:310)
	at io.prestosql.operator.ScanFilterAndProjectOperator$ConnectorPageSourceToPages.process(ScanFilterAndProjectOperator.java:376)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils$YieldingProcess.process(WorkProcessorUtils.java:181)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:277)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:149)
	at io.prestosql.operator.Driver.processInternal(Driver.java:387)
	at io.prestosql.operator.Driver.lambda$processFor$9(Driver.java:291)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:683)
	at io.prestosql.operator.Driver.processFor(Driver.java:284)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_unknown____20201209_080621_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: page doesn't have enough columns
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
	at io.prestosql.plugin.hive.HiveUpdateProcessor.createUpdateRowBlock(HiveUpdateProcessor.java:155)
	at io.prestosql.plugin.hive.orc.OrcPageSource$UpdatedRowAdaptation.block(OrcPageSource.java:358)
	at io.prestosql.plugin.hive.orc.OrcPageSource.getNextPage(OrcPageSource.java:145)
	at io.prestosql.plugin.hive.HivePageSource.getNextPage(HivePageSource.java:268)
	... 38 more


2020-12-09T01:33:41.327-0800	ERROR	SplitRunner-37-1780	io.prestosql.execution.executor.TaskExecutor	Error processing Split 20201209_093337_00109_nk3pw.1.0-1 {path=s3://test-bucket/Schema3/testingtable/delta_0000002_0000002_0000/bucket_00000, start=0, length=717, estimatedFileSize=717, hosts=[], database=Schema3, table=testingtable, forceLocalScheduling=false, partitionName=<UNPARTITIONED>, s3SelectPushdownEnabled=false} (start = 3.2522654841856E7, wall = 369 ms, cpu = 0 ms, wait = 3 ms, calls = 1): HIVE_CURSOR_ERROR: page doesn't have enough columns
io.prestosql.spi.PrestoException: page doesn't have enough columns
	at io.prestosql.plugin.hive.HivePageSource.getNextPage(HivePageSource.java:317)
	at io.prestosql.plugin.hive.HiveUpdatablePageSource.getNextPage(HiveUpdatablePageSource.java:310)
	at io.prestosql.operator.ScanFilterAndProjectOperator$ConnectorPageSourceToPages.process(ScanFilterAndProjectOperator.java:376)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils$YieldingProcess.process(WorkProcessorUtils.java:181)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:277)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:149)
	at io.prestosql.operator.Driver.processInternal(Driver.java:387)
	at io.prestosql.operator.Driver.lambda$processFor$9(Driver.java:291)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:683)
	at io.prestosql.operator.Driver.processFor(Driver.java:284)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_unknown____20201209_080621_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: page doesn't have enough columns
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
	at io.prestosql.plugin.hive.HiveUpdateProcessor.createUpdateRowBlock(HiveUpdateProcessor.java:155)
	at io.prestosql.plugin.hive.orc.OrcPageSource$UpdatedRowAdaptation.block(OrcPageSource.java:358)
	at io.prestosql.plugin.hive.orc.OrcPageSource.getNextPage(OrcPageSource.java:145)
	at io.prestosql.plugin.hive.HivePageSource.getNextPage(HivePageSource.java:268)
	... 38 more


2020-12-09T01:33:41.331-0800	ERROR	remote-task-callback-126	io.prestosql.execution.StageStateMachine	Stage 20201209_093337_00109_nk3pw.1 failed
io.prestosql.spi.PrestoException: page doesn't have enough columns
	at io.prestosql.plugin.hive.HivePageSource.getNextPage(HivePageSource.java:317)
	at io.prestosql.plugin.hive.HiveUpdatablePageSource.getNextPage(HiveUpdatablePageSource.java:310)
	at io.prestosql.operator.ScanFilterAndProjectOperator$ConnectorPageSourceToPages.process(ScanFilterAndProjectOperator.java:376)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils$YieldingProcess.process(WorkProcessorUtils.java:181)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:277)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:149)
	at io.prestosql.operator.Driver.processInternal(Driver.java:387)
	at io.prestosql.operator.Driver.lambda$processFor$9(Driver.java:291)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:683)
	at io.prestosql.operator.Driver.processFor(Driver.java:284)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_unknown____20201209_080621_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: page doesn't have enough columns
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
	at io.prestosql.plugin.hive.HiveUpdateProcessor.createUpdateRowBlock(HiveUpdateProcessor.java:155)
	at io.prestosql.plugin.hive.orc.OrcPageSource$UpdatedRowAdaptation.block(OrcPageSource.java:358)
	at io.prestosql.plugin.hive.orc.OrcPageSource.getNextPage(OrcPageSource.java:145)
	at io.prestosql.plugin.hive.HivePageSource.getNextPage(HivePageSource.java:268)
	... 38 more


2020-12-09T01:33:41.520-0800	ERROR	transaction-finishing-12	io.prestosql.transaction.InMemoryTransactionManager	Connector threw exception on abort
java.lang.IllegalStateException: Tried to rollback buffered metastore operations after transaction has been committed/aborted
	at io.prestosql.plugin.hive.metastore.SemiTransactionalHiveMetastore.rollback(SemiTransactionalHiveMetastore.java:1159)
	at io.prestosql.plugin.hive.HiveMetadata.rollback(HiveMetadata.java:2891)
	at io.prestosql.plugin.hive.HiveConnector.rollback(HiveConnector.java:222)
	at io.prestosql.transaction.InMemoryTransactionManager$TransactionMetadata$ConnectorTransactionMetadata.abort(InMemoryTransactionManager.java:601)
	at io.prestosql.transaction.InMemoryTransactionManager$TransactionMetadata.safeAbort(InMemoryTransactionManager.java:531)
	at io.prestosql.transaction.InMemoryTransactionManager$TransactionMetadata.lambda$abortInternal$9(InMemoryTransactionManager.java:524)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
	at io.prestosql.$gen.Presto_unknown____20201209_080621_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by findepi** [comment]
@abhishekkhanna1 the UPDATE support does not exist in Presto yet
It seems you have an error in the code that is your custom patch applied on top of project's code, therefore I will close this issue.

If you re testing out this PR: https://github.com/prestosql/presto/pull/5861, please post your findings there. Thanks!

**Comment by findepi** [comment]
cc @djsstarburst

**Comment by djsstarburst** [comment]
Thanks for testing, @abhishekkhanna1!

This bug is happening because we go to some trouble to read the schema for a file from the file itself rather than the metastore.  However, in this case, immediately after ALTER TABLE but before any rows are inserted using the new schema, the file schema will of course be wrong.

I'm not sure of the best way to deal with this bug.  I'll need to consult with @electrum.

**Comment by findepi** [comment]
Followed up here: https://github.com/trinodb/trino/issues/7298
