### ISSUE TITLE
Presto can't started when I Integrated it with Ranger 2.0

### ISSUE THREAD

**Issue by felixdream** [prestosql/presto#6282]
Hi all,

when I integrate prestosql 310 with apache ranger 2.0, aflter the integration, I can't start my presto server. The server log shows like this:
```
2020-12-10T15:06:11.283+0800	INFO	main	stdout	xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
2020-12-10T15:06:11.291+0800	ERROR	main	io.prestosql.server.PrestoServer	Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
  at org.apache.ranger.authorization.presto.authorizer.RangerSystemAccessControl.<init>(RangerSystemAccessControl.java:40)
  at org.apache.ranger.authorization.presto.authorizer.RangerSystemAccessControlFactory.lambda$create$0(RangerSystemAccessControlFactory.java:45)
  while locating org.apache.ranger.authorization.presto.authorizer.RangerSystemAccessControl

1 error
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
  at org.apache.ranger.authorization.presto.authorizer.RangerSystemAccessControl.<init>(RangerSystemAccessControl.java:40)
  at org.apache.ranger.authorization.presto.authorizer.RangerSystemAccessControlFactory.lambda$create$0(RangerSystemAccessControlFactory.java:45)
  while locating org.apache.ranger.authorization.presto.authorizer.RangerSystemAccessControl

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:240)
	at org.apache.ranger.authorization.presto.authorizer.RangerSystemAccessControlFactory.create(RangerSystemAccessControlFactory.java:53)
	at io.prestosql.security.AccessControlManager.setSystemAccessControl(AccessControlManager.java:142)
	at io.prestosql.security.AccessControlManager.loadSystemAccessControl(AccessControlManager.java:122)
	at io.prestosql.server.PrestoServer.run(PrestoServer.java:138)
	at io.prestosql.server.PrestoServer.main(PrestoServer.java:70)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.apache.ranger.authorization.presto.authorizer.RangerSystemAccessControl.<init>(RangerSystemAccessControl.java:56)
	at org.apache.ranger.authorization.presto.authorizer.RangerSystemAccessControl$$FastClassByGuice$$ec9f475b.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.ranger.authorization.presto.authorizer.RangerSystemAccessControl.<init>(RangerSystemAccessControl.java:54)
	... 18 more
Caused by: java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at org.apache.ranger.plugin.service.RangerBasePlugin.copyConfigFile(RangerBasePlugin.java:196)
	at org.apache.ranger.plugin.service.RangerBasePlugin.init(RangerBasePlugin.java:225)
	at org.apache.ranger.authorization.presto.authorizer.RangerSystemAccessControl.<init>(RangerSystemAccessControl.java:84)
	... 23 more
```

In my environment, 
```
[root@cdh1 ~]# cd /opt/apps/presto/etc/
[root@cdh1 etc]# ll
total 44
-rw-r--r-- 1 root   root      27 Dec 10 15:00 access-control.properties
drwxr-xr-x 2 root   root      29 Dec  9 17:55 catalog
-rw-r--r-- 1 root   root     232 Dec 10 14:49 config.properties
lrwxrwxrwx 1 root   root      20 Dec 10 15:00 etc -> /opt/apps/presto/etc
-rw-r--r-- 1 root   root     262 Dec 10 14:47 jvm.config
-rw-r--r-- 1 root   root      19 Dec 10 15:05 log.properties
-rw-r--r-- 1 root   root      71 Dec  9 17:58 node.properties
-rwxr--r-- 1 presto presto  2065 Dec 10 15:00 ranger-policymgr-ssl.xml
-rwxr--r-- 1 presto presto 10506 Dec 10 15:00 ranger-presto-audit.xml
-rwxr--r-- 1 presto presto  2647 Dec 10 15:00 ranger-presto-security.xml
-rw-r--r-- 1 presto presto    69 Dec 10 15:00 ranger-security.xml
```

I suspend some files needed is not ready. 
Can anyone help? Thank you.

**Comment by Praveen2112** [comment]
Can you please file an issue in Apache Ranger project also ? It looks like a missing configuration that fails the RangerPlugin initialization (that's why PrestoServer is not starting). I'm closing this issue now. Feel free to join our [Slack Channel](https://prestosql.io/slack.html) or re-open this issue if it didn't help you out.
