### ISSUE TITLE
Referencing VIEW fails if session catalog & schema are not set

### ISSUE THREAD

**Issue by losipiuk** [prestosql/presto#6294]
**Repro steps.**

Startup Presto with `hive` and `tpch` catalogs.

Create nation table in hive via presto:
```
presto> create table nation as select * from tpch.sf1.nation where nationkey = 1;
```

In hive create view:
```
hive> create view nationview as select * from nation;
```

Start presto CLI without specifying default catalog (no `--catalog` arg). And run:
```
presto> select * from hive.default.nationview.
```

This fails with following exception: 
```
Query 20201210_174913_00008_8duv4 failed: line 1:93: Catalog must be specified when session catalog is not set
io.prestosql.spi.PrestoException: line 1:93: Catalog must be specified when session catalog is not set
        at io.prestosql.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
        at io.prestosql.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)
        at io.prestosql.metadata.MetadataUtil.lambda$createQualifiedObjectName$4(MetadataUtil.java:154)
        at java.base/java.util.Optional.orElseThrow(Optional.java:408)
        at io.prestosql.metadata.MetadataUtil.createQualifiedObjectName(MetadataUtil.java:153)
        at io.prestosql.sql.planner.RelationPlanner.visitTable(RelationPlanner.java:206)
        at io.prestosql.sql.planner.RelationPlanner.visitTable(RelationPlanner.java:106)
        at io.prestosql.sql.tree.Table.accept(Table.java:53)
        at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.prestosql.sql.planner.QueryPlanner.planFrom(QueryPlanner.java:494)
        at io.prestosql.sql.planner.QueryPlanner.plan(QueryPlanner.java:364)
        at io.prestosql.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:784)
        at io.prestosql.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:106)
        at io.prestosql.sql.tree.QuerySpecification.accept(QuerySpecification.java:144)
        at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.prestosql.sql.planner.QueryPlanner.planQueryBody(QueryPlanner.java:485)
        at io.prestosql.sql.planner.QueryPlanner.plan(QueryPlanner.java:174)
        at io.prestosql.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:777)
        at io.prestosql.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:106)
        at io.prestosql.sql.tree.Query.accept(Query.java:107)
        at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.prestosql.sql.planner.RelationPlanner.visitTable(RelationPlanner.java:178)
        at io.prestosql.sql.planner.RelationPlanner.visitTable(RelationPlanner.java:106)
        at io.prestosql.sql.tree.Table.accept(Table.java:53)
        at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.prestosql.sql.planner.QueryPlanner.planFrom(QueryPlanner.java:494)
        at io.prestosql.sql.planner.QueryPlanner.plan(QueryPlanner.java:364)
        at io.prestosql.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:784)
        at io.prestosql.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:106)
        at io.prestosql.sql.tree.QuerySpecification.accept(QuerySpecification.java:144)
        at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.prestosql.sql.planner.QueryPlanner.planQueryBody(QueryPlanner.java:485)
        at io.prestosql.sql.planner.QueryPlanner.plan(QueryPlanner.java:174)
        at io.prestosql.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:777)
        at io.prestosql.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:106)
        at io.prestosql.sql.tree.Query.accept(Query.java:107)
        at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.prestosql.sql.planner.LogicalPlanner.createRelationPlan(LogicalPlanner.java:669)
        at io.prestosql.sql.planner.LogicalPlanner.planStatementWithoutOutput(LogicalPlanner.java:261)
        at io.prestosql.sql.planner.LogicalPlanner.planStatement(LogicalPlanner.java:235)
        at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:200)
        at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:195)
        at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:190)
        at io.prestosql.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:449)
        at io.prestosql.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:429)
        at io.prestosql.execution.SqlQueryExecution.start(SqlQueryExecution.java:381)
        at io.prestosql.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
        at io.prestosql.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
        at io.prestosql.$gen.Presto_unknown____20201210_172832_2.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by losipiuk** [comment]
cc: @findepi @sajjoseph @martint

**Comment by losipiuk** [comment]
For Presto views we observe a similar issue. The exception is: 
```
Query 20201211_103633_00022_59qki failed: line 3:3: Schema must be specified when session schema is not set
io.prestosql.spi.PrestoException: line 3:3: Schema must be specified when session schema is not set
        at io.prestosql.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
        at io.prestosql.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)
        at io.prestosql.metadata.MetadataUtil.lambda$createQualifiedObjectName$3(MetadataUtil.java:152)
        at java.base/java.util.Optional.orElseThrow(Optional.java:408)
        at io.prestosql.metadata.MetadataUtil.createQualifiedObjectName(MetadataUtil.java:151)
        at io.prestosql.sql.planner.RelationPlanner.visitTable(RelationPlanner.java:206)
        at io.prestosql.sql.planner.RelationPlanner.visitTable(RelationPlanner.java:106)
        at io.prestosql.sql.tree.Table.accept(Table.java:53)
        at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.prestosql.sql.planner.QueryPlanner.planFrom(QueryPlanner.java:494)
        at io.prestosql.sql.planner.QueryPlanner.plan(QueryPlanner.java:364)
        at io.prestosql.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:784)
        at io.prestosql.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:106)
        at io.prestosql.sql.tree.QuerySpecification.accept(QuerySpecification.java:144)
        at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.prestosql.sql.planner.QueryPlanner.planQueryBody(QueryPlanner.java:485)
        at io.prestosql.sql.planner.QueryPlanner.plan(QueryPlanner.java:174)
        at io.prestosql.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:777)
        at io.prestosql.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:106)
        at io.prestosql.sql.tree.Query.accept(Query.java:107)
        at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.prestosql.sql.planner.RelationPlanner.visitTable(RelationPlanner.java:178)
        at io.prestosql.sql.planner.RelationPlanner.visitTable(RelationPlanner.java:106)
        at io.prestosql.sql.tree.Table.accept(Table.java:53)
        at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.prestosql.sql.planner.QueryPlanner.planFrom(QueryPlanner.java:494)
        at io.prestosql.sql.planner.QueryPlanner.plan(QueryPlanner.java:364)
        at io.prestosql.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:784)
        at io.prestosql.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:106)
```

Root cause is the same.

**Comment by losipiuk** [comment]
Followup: https://github.com/prestosql/presto/pull/6335
