### ISSUE TITLE
Flaky TestFunctionRegistry.testExactMatchBeforeCoercion

### ISSUE THREAD

**Issue by kokosing** [prestosql/presto#6423]
```
2020-12-22T12:42:44.9204499Z [ERROR] Tests run: 6863, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 957.321 s <<< FAILURE! - in TestSuite
2020-12-22T12:42:44.9206347Z [ERROR] testExactMatchBeforeCoercion(io.prestosql.metadata.TestFunctionRegistry)  Time elapsed: 0.179 s  <<< FAILURE!
2020-12-22T12:42:44.9208123Z com.google.common.base.VerifyException: Unexpected coerce result for smallint and timestamp: real
2020-12-22T12:42:44.9209426Z 	at com.google.common.base.Verify.verify(Verify.java:443)
2020-12-22T12:42:44.9211078Z 	at io.prestosql.metadata.SignatureBinder$TypeWithLiteralParametersSolver.update(SignatureBinder.java:856)
2020-12-22T12:42:44.9213183Z 	at io.prestosql.metadata.SignatureBinder.iterativeSolve(SignatureBinder.java:553)
2020-12-22T12:42:44.9215145Z 	at io.prestosql.metadata.SignatureBinder.bindVariables(SignatureBinder.java:132)
2020-12-22T12:42:44.9216864Z 	at io.prestosql.metadata.SignatureBinder.bind(SignatureBinder.java:103)
2020-12-22T12:42:44.9219014Z 	at io.prestosql.metadata.FunctionResolver.identifyApplicableFunctions(FunctionResolver.java:197)
2020-12-22T12:42:44.9221390Z 	at io.prestosql.metadata.FunctionResolver.matchFunction(FunctionResolver.java:166)
2020-12-22T12:42:44.9223521Z 	at io.prestosql.metadata.FunctionResolver.matchFunctionExact(FunctionResolver.java:156)
2020-12-22T12:42:44.9225702Z 	at io.prestosql.metadata.FunctionResolver.resolveFunction(FunctionResolver.java:121)
2020-12-22T12:42:44.9227661Z 	at io.prestosql.metadata.MetadataManager.lambda$resolveFunction$28(MetadataManager.java:1774)
2020-12-22T12:42:44.9229049Z 	at java.base/java.util.Optional.orElseGet(Optional.java:369)
2020-12-22T12:42:44.9230566Z 	at io.prestosql.metadata.MetadataManager.resolveFunction(MetadataManager.java:1774)
2020-12-22T12:42:44.9232596Z 	at io.prestosql.metadata.MetadataManager.resolveOperator(MetadataManager.java:1782)
2020-12-22T12:42:44.9235228Z 	at io.prestosql.metadata.TestFunctionRegistry.testExactMatchBeforeCoercion(TestFunctionRegistry.java:86)
2020-12-22T12:42:44.9237791Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-12-22T12:42:44.9284952Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-12-22T12:42:44.9287505Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-12-22T12:42:44.9289364Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-12-22T12:42:44.9291045Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-12-22T12:42:44.9292867Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-12-22T12:42:44.9294232Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-12-22T12:42:44.9295895Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-12-22T12:42:44.9297702Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-12-22T12:42:44.9299493Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-12-22T12:42:44.9301233Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-12-22T12:42:44.9303058Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-12-22T12:42:44.9304265Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-12-22T12:42:44.9304699Z 
2020-12-22T12:42:46.9322381Z [INFO] 
2020-12-22T12:42:46.9325016Z [INFO] Results:
2020-12-22T12:42:46.9327016Z [INFO] 
2020-12-22T12:42:46.9329962Z [ERROR] Failures: 
2020-12-22T12:42:46.9338747Z [ERROR]   TestFunctionRegistry.testExactMatchBeforeCoercion:86 » Verify Unexpected coerc...
2020-12-22T12:42:46.9341540Z [INFO] 
2020-12-22T12:42:46.9346864Z [ERROR] Tests run: 6863, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by findepi** [comment]
Would it make sense to reopen https://github.com/prestosql/presto/issues/5758 instead?

**Comment by kokosing** [comment]
Duplicate of: https://github.com/prestosql/presto/issues/5758
