### ISSUE TITLE
create hive table with timestamp literal error

### ISSUE THREAD

**Issue by tooptoop4** [prestosql/presto#6436]
```create table hive.test3.ex as select timestamp'2020-11-01 00:00:00' tthere```

```
io.prestosql.spi.PrestoException: Incorrect timestamp precision for timestamp(0); the configured precision is MILLISECONDS
	at io.prestosql.plugin.hive.HiveMetadata.validateTimestampColumns(HiveMetadata.java:2771)
	at io.prestosql.plugin.hive.HiveMetadata.getNewTableLayout(HiveMetadata.java:2490)
	at io.prestosql.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getNewTableLayout(ClassLoaderSafeConnectorMetadata.java:133)
	at io.prestosql.metadata.MetadataManager.getNewTableLayout(MetadataManager.java:799)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitCreateTableAsSelect(StatementAnalyzer.java:743)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitCreateTableAsSelect(StatementAnalyzer.java:329)
	at io.prestosql.sql.tree.CreateTableAsSelect.accept(CreateTableAsSelect.java:96)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:346)
	at io.prestosql.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:315)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:87)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:79)
	at io.prestosql.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:262)
	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:186)
	at io.prestosql.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:767)
	at io.prestosql.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:129)
	at io.prestosql.$gen.Presto_____20201224_131418_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

version 348

**Comment by findepi** [comment]
Note:
Previously, before we introduced Hive timstamp precision, the wording was different but this was not supported either:

```
presto:default> create table hive.default.ex as select timestamp'2020-11-01 00:00:00' tthere
             ->
             -> ;
Query 20201228_091733_00001_5xguv failed: Unsupported Hive type: timestamp(0)
io.prestosql.spi.PrestoException: Unsupported Hive type: timestamp(0)
	at io.prestosql.plugin.hive.util.HiveTypeTranslator.translate(HiveTypeTranslator.java:150)
	at io.prestosql.plugin.hive.HiveType.toHiveType(HiveType.java:215)
	at io.prestosql.plugin.hive.HiveMetadata.validateColumns(HiveMetadata.java:2587)
	at io.prestosql.plugin.hive.HiveMetadata.getNewTableLayout(HiveMetadata.java:2330)
	at io.prestosql.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getNewTableLayout(ClassLoaderSafeConnectorMetadata.java:130)
	at io.prestosql.metadata.MetadataManager.getNewTableLayout(MetadataManager.java:786)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitCreateTableAsSelect(StatementAnalyzer.java:655)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitCreateTableAsSelect(StatementAnalyzer.java:315)
	at io.prestosql.sql.tree.CreateTableAsSelect.accept(CreateTableAsSelect.java:96)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:332)
	at io.prestosql.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:301)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:75)
	at io.prestosql.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:246)
	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:180)
	at io.prestosql.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:746)
	at io.prestosql.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:123)
	at io.prestosql.$gen.Presto_340____20211228_091632_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by chinayangze** [comment]
when will this be resolved？？

**Comment by findepi** [comment]
https://github.com/trinodb/trino/pull/13994  would help
