### ISSUE TITLE
PrestoException: Compiler failed - for queries with nested schema having size greater than 65K

### ISSUE THREAD

**Issue by puneetjaiswal** [prestosql/presto#695]
Hi Presto Devs,

We have a few nested tables in Hive, and using presto to query those. 
We are seeing this error `PrestoException: Compiler failed` when nested schema size is greater than 65535 chars.

Here are steps to reproduce this:
1. patch HMS with - https://reviews.apache.org/r/57759/diff/1#11
2. Use Hive 2.3 or above which does not enforce 4k char limit on field length.

Create table commands in hive and presto select queries:
https://gist.github.com/puneetjaiswal/1da03307321cc1f83c491bb633c3d466

Following is the complete stacktrace, error coming from `org.objectweb.asm.ByteVector.putUTF8` Method which expects input string to be lesser than 65K in size. 
We can patch the undelying lib to accept larger string limit, that might fix this issue.

```
com.facebook.presto.spi.PrestoException: Compiler failed
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitScanFilterAndProject(LocalExecutionPlanner.java:1261)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitProject(LocalExecutionPlanner.java:1151)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitProject(LocalExecutionPlanner.java:687)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitAggregation(LocalExecutionPlanner.java:1090)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitAggregation(LocalExecutionPlanner.java:687)
	at com.facebook.presto.sql.planner.plan.AggregationNode.accept(AggregationNode.java:198)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:459)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:381)
	at com.facebook.presto.execution.SqlTaskExecutionFactory.create(SqlTaskExecutionFactory.java:76)
	at com.facebook.presto.execution.SqlTask.updateTask(SqlTask.java:380)
	at com.facebook.presto.execution.SqlTaskManager.updateTask(SqlTaskManager.java:364)
	at com.facebook.presto.server.TaskResource.createOrUpdateTask(TaskResource.java:129)
	at jdk.internal.reflect.GeneratedMethodAccessor711.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:867)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at com.facebook.presto.server.security.AuthenticationFilter.doFilter(AuthenticationFilter.java:69)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at io.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:51)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:703)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: UTF8 string too large
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2052)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3943)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3967)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4952)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4958)
	at com.facebook.presto.sql.gen.ExpressionCompiler.compileCursorProcessor(ExpressionCompiler.java:82)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitScanFilterAndProject(LocalExecutionPlanner.java:1229)
	... 74 more
Caused by: java.lang.IllegalArgumentException: UTF8 string too large
	at org.objectweb.asm.ByteVector.putUTF8(ByteVector.java:245)
	at org.objectweb.asm.SymbolTable.addConstantUtf8(SymbolTable.java:787)
	at org.objectweb.asm.SymbolTable.addConstantNameAndType(SymbolTable.java:753)
	at org.objectweb.asm.SymbolTable.addConstantDynamicOrInvokeDynamicReference(SymbolTable.java:949)
	at org.objectweb.asm.SymbolTable.addConstantInvokeDynamic(SymbolTable.java:919)
	at org.objectweb.asm.MethodWriter.visitInvokeDynamicInsn(MethodWriter.java:1083)
	at io.airlift.bytecode.instruction.InvokeInstruction$InvokeDynamicInstruction.accept(InvokeInstruction.java:403)
	at io.airlift.bytecode.expression.BytecodeExpression.accept(BytecodeExpression.java:234)
	at io.airlift.bytecode.BytecodeBlock.accept(BytecodeBlock.java:950)
	at io.airlift.bytecode.BytecodeBlock.accept(BytecodeBlock.java:950)
	at io.airlift.bytecode.expression.BytecodeExpression.accept(BytecodeExpression.java:234)
	at io.airlift.bytecode.BytecodeBlock.accept(BytecodeBlock.java:950)
	at io.airlift.bytecode.BytecodeBlock.accept(BytecodeBlock.java:950)
	at io.airlift.bytecode.BytecodeBlock.accept(BytecodeBlock.java:950)
	at io.airlift.bytecode.control.IfStatement.accept(IfStatement.java:125)
	at io.airlift.bytecode.BytecodeBlock.accept(BytecodeBlock.java:950)
	at io.airlift.bytecode.BytecodeBlock.accept(BytecodeBlock.java:950)
	at io.airlift.bytecode.BytecodeBlock.accept(BytecodeBlock.java:950)
	at io.airlift.bytecode.MethodDefinition.visit(MethodDefinition.java:250)
	at io.airlift.bytecode.MethodDefinition.visit(MethodDefinition.java:211)
	at io.airlift.bytecode.ClassDefinition.visit(ClassDefinition.java:167)
	at io.airlift.bytecode.ClassGenerator.defineClasses(ClassGenerator.java:130)
	at io.airlift.bytecode.ClassGenerator.defineClass(ClassGenerator.java:117)
	at com.facebook.presto.util.CompilerUtils.defineClass(CompilerUtils.java:63)
	at com.facebook.presto.util.CompilerUtils.defineClass(CompilerUtils.java:57)
	at com.facebook.presto.sql.gen.ExpressionCompiler.compileProcessor(ExpressionCompiler.java:166)
	at com.facebook.presto.sql.gen.ExpressionCompiler.compile(ExpressionCompiler.java:133)
	at com.facebook.presto.sql.gen.ExpressionCompiler.lambda$new$0(ExpressionCompiler.java:69)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2273)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2156)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2046)
	... 80 more
```
What is recommended way of fixing this error?

**Comment by electrum** [comment]
This looks like the same issue as #537

**Comment by puneetjaiswal** [comment]
Yes, it is. thanks.
