### ISSUE TITLE
Many test failure for TestQueuesDb

### ISSUE THREAD

**Issue by electrum** [prestosql/presto#859]
We frequently see variants of this.

```
[ERROR] tearDown(io.prestosql.execution.resourcegroups.db.TestQueuesDb)  Time elapsed: 4.838 s  <<< FAILURE!
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at io.prestosql.server.testing.TestingPrestoServer.close(TestingPrestoServer.java:323)
	at com.google.common.io.Closer.close(Closer.java:214)
	at io.prestosql.tests.DistributedQueryRunner.close(DistributedQueryRunner.java:432)
	at io.prestosql.execution.resourcegroups.db.TestQueuesDb.tearDown(TestQueuesDb.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:712)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor1956.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.airlift.bootstrap.LifeCycleManager.stop(LifeCycleManager.java:142)
	at io.prestosql.server.testing.TestingPrestoServer.close(TestingPrestoServer.java:318)
	... 18 more
Caused by: io.prestosql.spi.PrestoException: Server is shutting down
	at io.prestosql.execution.StateMachine.safeExecute(StateMachine.java:312)
	at io.prestosql.execution.StateMachine.fireStateChanged(StateMachine.java:212)
	at io.prestosql.execution.StateMachine.compareAndSet(StateMachine.java:202)
	at io.prestosql.execution.StateMachine.setIf(StateMachine.java:159)
	at io.prestosql.execution.QueryStateMachine.transitionToFailed(QueryStateMachine.java:798)
	at io.prestosql.execution.SqlQueryExecution.fail(SqlQueryExecution.java:517)
	at io.prestosql.execution.QueryTracker.stop(QueryTracker.java:125)
	at io.prestosql.execution.SqlQueryManager.stop(SqlQueryManager.java:124)
	... 23 more
Caused by: java.util.concurrent.RejectedExecutionException: Task io.prestosql.execution.StateMachine$$Lambda$1219/1347257087@6fdffe87 rejected from java.util.concurrent.ThreadPoolExecutor@1cfa47a6[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 71]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at com.google.common.util.concurrent.MoreExecutors$ListeningDecorator.execute(MoreExecutors.java:537)
	at io.prestosql.execution.StateMachine.safeExecute(StateMachine.java:308)
	... 30 more

**Comment by electrum** [comment]
We see similar failures for `TestQueues`, in the query runner `close()` method called from the try-with-resources black. This stack trace seems to indicate that a query is still running when the query runner is closed.
