### ISSUE TITLE
Add Avro as a CLI output-format choice

### ISSUE THREAD

**Issue by bruth** [prestosql/presto#861]
The use case is simply that this is another desirable format over CSV or TSV.

**Comment by electrum** [comment]
Interesting idea. Would you like to work on this yourself?

As a related enhancement, we could also support JSON.

**Comment by bruth** [comment]
I have written very little Java, but with a bit of guidance I may be able to open a PR with something. I see the [OutputPrinter](https://github.com/prestosql/presto/blob/master/presto-cli/src/main/java/io/prestosql/cli/OutputPrinter.java) interface is really basic. Is there any access to the column names and the schema information of the output table (at a minimum the types)? The Avro schema needs to be established before serializing the records.

**Comment by findepi** [comment]
@bruth just curious, what problem are you solving?
With Avro output, I guess you're going to store this data somewhere, for further processing.
Would you consider doing `CREATE TABLE t WITH (format='AVRO', location='.....') AS SELECT ...` as an alternative approach to get Avro data for a query?

**Comment by bruth** [comment]
The use case is to snapshot tables that are created and refreshed on some schedule (typically daily). Basically making copies of the *live* tables for the purpose of diffing these snapshots each day and emitting the changes as a set of events (and the change stats) for downstream consumption.

The use case is to execute a Presto query and then to write the data out to an object storage organized in a specify structure. I do already have a Hive+GCS setup that would enable an *in Presto* snapshot process using `CREATE TABLE` as you suggest.  With the `location` parameter, is it possible to specify an arbitrary GCS location? How is authentication handled in this case?

**Comment by bruth** [comment]
Even if I was constrained to the *<schema>.<table>* hierarchy (using the existing Hive+GCS setup), I could certainly work around this by include a timestamp in the table name or maintaining the relationship between these tables in a separate state store to support the downstream process.

**Comment by findepi** [comment]
@bruth 
my example was a bit too simplistic. it should be `external_location` (not `location`) and you probably need to set `hive.non-managed-table-writes-enabled`.
alternatively you can create a schema for your snapshots:
```
CREATE SCHEMA hive.snapshots WITH (location='gs://...');
```
then you'd do a snapshot as
```
CREATE TABLE hive.snapshots.daily_snapshot_yyyyMMdd AS
SELECT .... FROM hive.default...
```
> is it possible to specify an arbitrary GCS location?

Yes.
(You can even use a location on different storage, like HDFS, S3).

> How is authentication handled in this case?

There are two options:
- you already configured Presto in a way that it has access to your snapshots bucket
- you can use GCS credentials passthu if you don't want Presto to have a permanent access to the snapshots bucket. 
  Search for `hive.gcs.use-access-token` in https://prestosql.io/docs/current/connector/hive-gcs-tutorial.html and the release notes https://prestosql.io/docs/current/release/release-302.html

**Comment by bruth** [comment]
@findepi I appreciate the help. This will be a simpler solution for my use case. I will create the tables out as Avro data, so there is no need for the CLI itself to support Avro (although its an orthogonal feature).

**Comment by findepi** [comment]
I agree, this is orthogonal. Apologies, I derailed the discussion from the original issue.
@bruth, should you have any further questions, I invite you to just Slack (if you haven't yet done so) -- get an invite from https://prestosql.io/community.html

**Comment by bruth** [comment]
No apology necessary, you got to the heart of my problem. And thank you for the invite to the community Slack.

**Comment by electrum** [comment]
@bruth You would pass in the field names and types when creating the `OutputPrinter` instance in `Query.createOutputPrinter()`. That method only takes the names, so it'd be easiest to change `doRenderResults()` to pass `List<Column>` all the way down.

**Comment by electrum** [comment]
I just put up a PR which passes down the list of columns: https://github.com/prestosql/presto/pull/871

**Comment by bruth** [comment]
@findepi Since we already partially discussed snapshots.. I am going to continue it here. I can move it to Slack if you would prefer. I was able to do this:

```sql
create table gcs.snapshots."stage/cqs/demographic/1559424034" with (format = 'AVRO') as (
  select *
  from stage.cqs.demographic
  order by pat_mrn_id
);
```

And the table name `stage/cqs/demographic/1559424034` actually translated to a set of folders in GCS. Similarly, I was delighted to see the `order by` was respected when the data was written. The actual Avro files were written within that folder named liked `20190601_212110_00000_qprx2_549d110a-ebfa-4bad-af97-3903e5552fb0`. For this particular table, there are four files, which I presume are partitions with some default partition strategy or max file size? This is fine, but now I am figuring out how to compare two snapshots which translates to two folders with a set of files that are themselves sorted, but the file names provide no indication of the order they should be read (for total ordering).

I was reading about the Avro sorting capability, but I am not sure how I would apply this. The end goal is to do a single pass (hence the pre-sorting) comparison between snapshot records having the same key to detect changes in the data. It is akin to [this](https://github.com/chop-dbhi/diff-table#diff-table) (in fact I added supported for Avro files not long ago, but it expects a single file right now).

**Comment by bruth** [comment]
☝️ Although I could write the table.. reading is throwing an error. Apparent the forward slashes are problematic on reads.

```java
java.lang.RuntimeException: error initializing deserializer: io.prestosql.plugin.hive.avro.PrestoAvroSerDe
	at io.prestosql.plugin.hive.HiveUtil.initializeDeserializer(HiveUtil.java:429)
	at io.prestosql.plugin.hive.HiveUtil.getDeserializer(HiveUtil.java:385)
	at io.prestosql.plugin.hive.GenericHiveRecordCursor.<init>(GenericHiveRecordCursor.java:140)
	at io.prestosql.plugin.hive.GenericHiveRecordCursorProvider.lambda$createRecordCursor$0(GenericHiveRecordCursorProvider.java:77)
	at io.prestosql.plugin.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
	at io.prestosql.plugin.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:80)
	at io.prestosql.plugin.hive.GenericHiveRecordCursorProvider.createRecordCursor(GenericHiveRecordCursorProvider.java:71)
	at io.prestosql.plugin.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:187)
	at io.prestosql.plugin.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:95)
	at io.prestosql.spi.connector.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:44)
	at io.prestosql.split.PageSourceManager.createPageSource(PageSourceManager.java:56)
	at io.prestosql.operator.TableScanOperator.getOutput(TableScanOperator.java:239)
	at io.prestosql.operator.Driver.processInternal(Driver.java:379)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
	at io.prestosql.$gen.Presto_302_e_11____20190529_154739_1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.avro.SchemaParseException: Illegal character in: stage/cqs/demographic/1559424034
	at org.apache.avro.Schema.validateName(Schema.java:1083)
	at org.apache.avro.Schema.access$200(Schema.java:79)
	at org.apache.avro.Schema$Name.<init>(Schema.java:439)
	at org.apache.avro.Schema.createRecord(Schema.java:145)
	at org.apache.hadoop.hive.serde2.avro.TypeInfoToSchema.convert(TypeInfoToSchema.java:70)
	at org.apache.hadoop.hive.serde2.avro.AvroSerDe.getSchemaFromCols(AvroSerDe.java:170)
	at org.apache.hadoop.hive.serde2.avro.AvroSerDe.initialize(AvroSerDe.java:114)
	at io.prestosql.plugin.hive.HiveUtil.initializeDeserializer(HiveUtil.java:425)
	... 22 more
```

**Comment by dain** [comment]
In the Hive specification, the table name and location aren't really linked like that.  If you want an exact location, I believe you specify it with the a table property like this: `external_location = 's3://my-bucket/data/logs/'

**Comment by findepi** [comment]
@bruth let's continue the discussion on [Presto Slack](https://prestosql.io/community.html)
