### ISSUE TITLE
Unsafe publication in (experimental) WorkProcessorPipelineSourceOperator

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#956]
Found by Travis:
```
2019-06-10T17:50:07.421-0500 WARNING Request failed for /v1/task/20190610_225007_00000_7wuai.1.3
java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1388)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.prestosql.operator.WorkProcessorPipelineSourceOperator.getNestedOperatorStats(WorkProcessorPipelineSourceOperator.java:324)
	at java.util.Optional.map(Optional.java:215)
	at io.prestosql.operator.OperatorContext.getNestedOperatorStats(OperatorContext.java:538)
	at io.prestosql.operator.DriverContext.lambda$getOperatorStats$0(DriverContext.java:301)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.prestosql.operator.DriverContext.getOperatorStats(DriverContext.java:303)
	at io.prestosql.operator.DriverContext.getDriverStats(DriverContext.java:317)
	at io.prestosql.operator.PipelineContext.getPipelineStats(PipelineContext.java:381)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:785)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:273)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:234)
	at io.prestosql.operator.TaskContext.getTaskStats(TaskContext.java:382)
	at io.prestosql.execution.SqlTask.getTaskStats(SqlTask.java:301)
	at io.prestosql.execution.SqlTask.createTaskInfo(SqlTask.java:323)
	at io.prestosql.execution.SqlTask.getTaskInfo(SqlTask.java:212)
	at io.prestosql.execution.SqlTask.updateTask(SqlTask.java:401)
	at io.prestosql.execution.SqlTaskManager.updateTask(SqlTaskManager.java:363)
	at io.prestosql.server.TaskResource.createOrUpdateTask(TaskResource.java:129)
```

This is because `this` escapes during construction:
https://github.com/prestosql/presto/blob/b396828524d19ca103d3712d6adf13093d09045e/presto-main/src/main/java/io/prestosql/operator/WorkProcessorPipelineSourceOperator.java#L117

**Comment by findepi** [comment]
This makes the tests flaky.

**Comment by findepi** [comment]
@dain would you like to take a stab at this?

**Comment by dain** [comment]
@sopel39 is has an open PR for `WorkProcessorPipelineSourceOperator` https://github.com/prestosql/presto/pull/909

**Comment by sopel39** [comment]
There are more `this` leaks, e.g via `io.prestosql.operator.OperatorContext#setInfoSupplier`, but I think we have to live with them

**Comment by findepi** [comment]
Fixed by https://github.com/prestosql/presto/pull/969

**Comment by martint** [comment]
> There are more this leaks, e.g via io.prestosql.operator.OperatorContext#setInfoSupplier, but I think we have to live with them

If they are true leaks of “this” (i.e., “this” becomes available to other threads via that leak), there’s no living with it, we need to fix them. Otherwise, it’s a subtle bug waiting to bite us.
