### ISSUE TITLE
Hive ANALYZE does not validate partition values

### ISSUE THREAD

**Issue by electrum** [prestosql/presto#961]
Passing an empty string as the partition value (or likely any non-existent partition) will result in a verify exception:

> All computed statistics must be used

**Comment by findepi** [comment]
btw I think `All computed statistics must be used` might also be possible when a partition is dropped during ANALYZE

**Comment by electrum** [comment]
@findepi What do you mean "dropped during analyze"?

**Comment by findepi** [comment]
`ANALYZE` without `with(partitions=...)` analyzes all the partitions.
Now, if a partition is concurrently dropped by some other process, we can fail to persist analysis results (one partition missing ⇒ `All computed statistics must be used` zonk)

**Comment by electrum** [comment]
Interesting. Looking at the code, I'm not sure we need the check at all.

**Comment by realknorke** [comment]
We also ran into this issue. There is *no* concurrent schema change in our situation. But as [this issue](https://github.com/prestodb/presto/issues/13580) suggests, the problem could be the timestamp type of the partition column.

In our special case the underfs is Alluxio (between S3 and Presto) where the partitions are urlencodet  like `hour=2020-01-21%2006%3A00`

We can trigger the problem like this:
```
presto:schema> ANALYZE tablename_hourly WITH ( partitions = ARRAY[ARRAY['2020-01-21 06:00']] );

Query 20200205_095636_03786_k3xa5, FAILED, 9 nodes
Splits: 277 total, 260 done (93.86%)
0:04 [506K rows, 20MB] [122K rows/s, 4.83MB/s]

Query 20200205_095636_03786_k3xa5 failed: All computed statistics must be used
```

**Comment by findepi** [comment]
@realknorke can you try
```
ANALYZE tablename_hourly WITH ( partitions = ARRAY[ARRAY['2020-01-21 06:00']] ); -- this fails, right?
```
and
```
ANALYZE tablename_hourly WITH ( partitions = ARRAY[ARRAY['2020-01-21%2006%3A00']] );
```
?

**Comment by realknorke** [comment]
I tried this before. It fails as expected:
```
presto:s3ds> ANALYZE delivery_hourly WITH ( partitions = ARRAY[ARRAY['2020-01-21%2006%3A00']] );
Query 20200205_122830_08850_k3xa5 failed: Invalid partition value '2020-01-21%2006%3A00' for TIMESTAMP partition key: hour=2020-01-21%252006%253A00
```

**Comment by realknorke** [comment]
Stacktrace from the coordinator:

```
2020-02-05T12:32:03.034Z        ERROR   SplitRunner-60-64262    io.prestosql.execution.executor.TaskExecutor    Error processing Split 20200205_123159_08963_k3xa5.0.0-16  (start = 1.629084488365344E9, wall = 2906 ms, cpu = 0 ms, wait = 0 ms, calls = 3)
com.google.common.base.VerifyException: All computed statistics must be used
        at com.google.common.base.Verify.verify(Verify.java:124)
        at io.prestosql.plugin.hive.HiveMetadata.finishStatisticsCollection(HiveMetadata.java:1167)
        at io.prestosql.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.finishStatisticsCollection(ClassLoaderSafeConnectorMetadata.java:162)
        at io.prestosql.metadata.MetadataManager.finishStatisticsCollection(MetadataManager.java:728)
        at io.prestosql.sql.planner.LocalExecutionPlanner$Visitor.lambda$visitStatisticsWriterNode$40(LocalExecutionPlanner.java:2304)
        at io.prestosql.operator.StatisticsWriterOperator.getOutput(StatisticsWriterOperator.java:133)
        at io.prestosql.operator.Driver.processInternal(Driver.java:379)
        at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
        at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
        at io.prestosql.operator.Driver.processFor(Driver.java:276)
        at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
        at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
        at io.prestosql.$gen.Presto_328_dirty____20200131_100515_2.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)


2020-02-05T12:32:03.037Z        ERROR   remote-task-callback-30797      io.prestosql.execution.StageStateMachine        Stage 20200205_123159_08963_k3xa5.0 failed
com.google.common.base.VerifyException: All computed statistics must be used
        at com.google.common.base.Verify.verify(Verify.java:124)
        at io.prestosql.plugin.hive.HiveMetadata.finishStatisticsCollection(HiveMetadata.java:1167)
        at io.prestosql.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.finishStatisticsCollection(ClassLoaderSafeConnectorMetadata.java:162)
        at io.prestosql.metadata.MetadataManager.finishStatisticsCollection(MetadataManager.java:728)
        at io.prestosql.sql.planner.LocalExecutionPlanner$Visitor.lambda$visitStatisticsWriterNode$40(LocalExecutionPlanner.java:2304)
        at io.prestosql.operator.StatisticsWriterOperator.getOutput(StatisticsWriterOperator.java:133)
        at io.prestosql.operator.Driver.processInternal(Driver.java:379)
        at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
        at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
        at io.prestosql.operator.Driver.processFor(Driver.java:276)
        at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
        at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
        at io.prestosql.$gen.Presto_328_dirty____20200131_100515_2.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by realknorke** [comment]
I debugged into the code (v328-DIRTY!) and found the source.

short story
While identifying the partition names the partition is first casted to type TIMESTAMP (the partition column's type) and then back to string. Thus, the partition name "2020-01-21 06:00"::STRING finally is transformed to "2020-01-21 06:00:00.0"::STRING.

long story
HiveMetadata.java:1167
`verify(usedComputedStatistics == computedStatistics.size(), "All computed statistics must be used");`
failes because `usedComputedStatistics` and `computedStatistics.size()` is 1 (with key = 2020-01-20 06:00:00.0)

because
HiveMetadata:1158 (just above)
`ComputedStatistics collectedStatistics = computedStatisticsMap.get(partitionValues);`
evaluates to `null` because `partitionValues` (the loop parameter) is "2020-01-20 06:00"::STRING whereas the (only) key of the `computedStatisticsMap` is `List<String>` with member "2020-01-20 06:00:00.0".

because
HiveWriteUtils.java:272
`Object value = getField(partitionColumnTypes.get(field), partitionColumns.getBlock(field), position);` evaluates to "2020-01-20 06:00:00.0"::TIMESTAMP.

because
HiveWriteUtils.java:329
```
if (TimestampType.TIMESTAMP.equals(type)) {
            long millisUtc = type.getLong(block, position);
            return new Timestamp(millisUtc);
}
```
which finally leads to 
HiveWriteUtils.java:277
`String valueString = value.toString();`
which evaluates to a partition name with trailing seconds and milliseconds.

The problem is that the string representation of the partition columns value is not the same (like in identical) String as the partition's value in the filesystem/s3/whatever.

**Comment by tooptoop4** [comment]
@realknorke do I smell a PR in the works?

**Comment by realknorke** [comment]
Bug still present in v344…

**Comment by yashu74** [comment]
Issue Still persist & become a big blocker.. any work-around for this issue??

**Comment by damnMeddlingKid** [comment]
one possible work around to this is to give the timestamp millisecond precision. I was able to get around this by adding 0.001 to my timestamp.

**Comment by damnMeddlingKid** [comment]
I was wondering if we can avoid doing the unreliable round trip from string -> type -> string by instead using the string values that are supplied in the query. That  grouping information is in the statistics writer's aggregation descriptor. 

Does that make sense ?.
