### ISSUE TITLE
hive unknown error 16777221

### ISSUE THREAD

**Issue by zgseed** [prestosql/presto#979]
A simple statement  with hive catalog   
`SELECT * FROM  db.table1  where day= '20190613' LIMIT 10`  （field day is the partition column, and type is string）
we got an external error  with code hive-unknown-error(16777221) .
And test it with hive, it works ok. 

environment:
 presto  306
 hive 1.10-cdh
 hadoop 2.5.2-cdh

exception stack trace:
```
io.prestosql.spi.PrestoException: java.lang.reflect.InvocationTargetException
  at io.prestosql.plugin.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:194)
  at io.prestosql.plugin.hive.util.ResumableTasks.safeProcessTask(ResumableTasks.java:47)
  at io.prestosql.plugin.hive.util.ResumableTasks.access$000(ResumableTasks.java:20)
  at io.prestosql.plugin.hive.util.ResumableTasks$1.run(ResumableTasks.java:35)
  at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
  at io.prestosql.plugin.hive.HiveUtil.isSplittable(HiveUtil.java:350)
  at io.prestosql.plugin.hive.util.InternalHiveSplitFactory.createInternalHiveSplit(InternalHiveSplitFactory.java:105)
  at io.prestosql.plugin.hive.util.InternalHiveSplitFactory.createInternalHiveSplit(InternalHiveSplitFactory.java:95)
  at io.prestosql.plugin.hive.BackgroundHiveSplitLoader.lambda$createInternalHiveSplitIterator$1(BackgroundHiveSplitLoader.java:406)
  at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
  at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
  at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
  at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
  at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
  at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
  at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
  at io.prestosql.plugin.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:261)
  at io.prestosql.plugin.hive.BackgroundHiveSplitLoader.access$300(BackgroundHiveSplitLoader.java:93)
  at io.prestosql.plugin.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:187)
  ... 7 more
Caused by: java.lang.reflect.InvocationTargetException: undefined
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at io.prestosql.plugin.hive.HiveUtil.isSplittable(HiveUtil.java:347)
  ... 20 more
Caused by: java.lang.NullPointerException: undefined
  at com.hadoop.mapred.DeprecatedLzoTextInputFormat.isSplitable(DeprecatedLzoTextInputFormat.java:101)
  ... 25 more
```

**Comment by findepi** [comment]
@zgseed the stacktrace here doesn't precisely match Presto 306.
Did you replace any jars in the Presto `plugin/hive-hadoop2` folder?

**Comment by electrum** [comment]
This `NullPointerException` is confusing. Here are lines 97-101 of `DeprecatedLzoTextInputFormat`:
```java
LzoIndex index = indexes.get(file);
if (index == null) {
    throw new IOException("Index not found for " + file);
}
if (index.isEmpty()) {
```
Also, Presto doesn't use `DeprecatedLzoTextInputFormat` (it is only used for testing).

Do you have any local modifications to Presto?

**Comment by zgseed** [comment]
@findepi   @electrum sorry for that. 
I check the plugin/hive-hadoop2 folder and found a hadoop-lzo jar.  and the table's input format is com.hadoop.mapred.DeprecatedLzoTextInputFormat.  So i think some one add the jar to support this input format.

> Also, Presto doesn't use DeprecatedLzoTextInputFormat (it is only used for testing).

Does it mean presto could not read table stored using DeprecatedLzoTextInputFormat?

**Comment by electrum** [comment]
Presto has built in support for LZO (using the aircompressor library), so it should work without any additional libraries.

**Comment by findepi** [comment]
@zgseed any updates on your side?

(Let me close the issue for now. You can always comment here with any updates. We can reopen if needed.)
